#include <unknownGen.h>
#pragma push
#pragma auto_inline off
extern "C" {
void *fn_8002213C();
void *fn_80022DF8();
void fn_800F90FC(void *,void *);
void *fn_800F933C(void *,void *,void *,void *,void *);
}
class UnknownGenV800F5F54_0 {
public:
 virtual void s08();
 virtual void s0C();
 virtual void s10();
 virtual void s14();
 virtual void s18();
 virtual void s1C();
 virtual void s20();
 virtual void s24();
 virtual void s28();
 virtual void s2C();
 virtual void s30();
 virtual void s34();
 virtual void s38();
 virtual void s3C();
 virtual void s40();
 virtual void s44();
 virtual void s48();
 virtual void s4C();
 virtual void s50();
 virtual void s54();
 virtual void s58();
 virtual void s5C();
 virtual void s60();
 virtual void s64();
 virtual void s68();
 virtual void s6C();
 virtual void s70();
 virtual void s74();
 virtual void s78();
 virtual void s7C();
 virtual void s80(void *,void *,void *,void *);
};
class UnknownGenV800F5F54_1 {
public:
 virtual void s08();
 virtual void s0C();
 virtual void s10();
 virtual void s14();
 virtual void s18();
 virtual void s1C();
 virtual void s20();
 virtual void s24();
 virtual void s28();
 virtual void s2C();
 virtual void s30();
 virtual void s34();
 virtual void s38();
 virtual void s3C();
 virtual void s40();
 virtual void s44();
 virtual void s48();
 virtual void s4C();
 virtual void s50();
 virtual void s54();
 virtual void s58();
 virtual void s5C();
 virtual void s60();
 virtual void s64();
 virtual void s68();
 virtual void s6C();
 virtual void s70();
 virtual void s74();
 virtual void s78();
 virtual void s7C();
 virtual void s80();
 virtual void s84();
 virtual void s88();
 virtual void s8C();
 virtual void s90();
 virtual void s94();
 virtual void s98();
 virtual void s9C();
 virtual void sA0();
 virtual void sA4();
 virtual void sA8();
 virtual void sAC();
 virtual void sB0();
 virtual void sB4();
 virtual void sB8();
 virtual void sBC();
 virtual void sC0();
 virtual void sC4();
 virtual void sC8();
 virtual void sCC();
 virtual void sD0();
 virtual void sD4();
 virtual void sD8();
 virtual void sDC();
 virtual void sE0();
 virtual void sE4();
 virtual void sE8();
 virtual void sEC();
 virtual void sF0();
 virtual void sF4();
 virtual void sF8();
 virtual void sFC();
 virtual void s100();
 virtual void s104();
 virtual void s108();
 virtual void s10C();
 virtual void s110();
 virtual void s114();
 virtual void s118();
 virtual void s11C();
 virtual void s120();
 virtual void s124();
 virtual void s128();
 virtual void s12C();
 virtual void s130();
 virtual void s134();
 virtual void s138();
 virtual void s13C();
 virtual void s140();
 virtual void s144();
 virtual void s148();
 virtual void s14C();
 virtual void s150();
 virtual void s154();
 virtual void s158();
 virtual void s15C();
 virtual void s160();
 virtual void s164();
 virtual void s168();
 virtual void s16C();
 virtual void s170();
 virtual void s174();
 virtual void s178();
 virtual void s17C();
 virtual void s180();
 virtual void s184();
 virtual void s188();
 virtual void s18C();
 virtual void s190();
 virtual void s194();
 virtual void s198();
 virtual void s19C();
 virtual void s1A0();
 virtual void s1A4();
 virtual void s1A8();
 virtual void s1AC();
 virtual void s1B0();
 virtual void s1B4();
 virtual void s1B8();
 virtual void s1BC();
 virtual void s1C0();
 virtual void s1C4();
 virtual void s1C8();
 virtual void s1CC();
 virtual void s1D0();
 virtual void s1D4();
 virtual void s1D8();
 virtual void s1DC();
 virtual void s1E0();
 virtual void s1E4();
 virtual void s1E8();
 virtual void s1EC();
 virtual void s1F0();
 virtual void s1F4();
 virtual void s1F8();
 virtual void s1FC();
 virtual void s200();
 virtual void s204();
 virtual void s208();
 virtual void s20C();
 virtual void s210();
 virtual void s214();
 virtual void s218();
 virtual void s21C();
 virtual void s220();
 virtual void s224();
 virtual void s228();
 virtual void s22C();
 virtual void s230();
 virtual void s234();
 virtual void s238();
 virtual void s23C();
 virtual void s240();
 virtual void s244();
 virtual void s248();
 virtual void s24C();
 virtual void s250();
 virtual void s254();
 virtual void s258();
 virtual void s25C();
 virtual void s260();
 virtual void s264();
 virtual void s268();
 virtual void s26C();
 virtual void s270();
 virtual void s274();
 virtual void s278();
 virtual void s27C();
 virtual void s280();
 virtual void s284();
 virtual void s288();
 virtual void s28C();
 virtual void s290();
 virtual void s294();
 virtual void s298();
 virtual void s29C();
 virtual void s2A0();
 virtual void s2A4();
 virtual void s2A8();
 virtual void s2AC();
 virtual void s2B0();
 virtual void s2B4();
 virtual void s2B8();
 virtual void s2BC();
 virtual void s2C0();
 virtual void s2C4();
 virtual void s2C8();
 virtual void s2CC();
 virtual void s2D0();
 virtual void s2D4();
 virtual void s2D8();
 virtual void s2DC();
 virtual void s2E0();
 virtual void s2E4();
 virtual void s2E8(void *,void *,void *,void *);
};
class UnknownGenV800F5F54_2 {
public:
 virtual void s08();
 virtual void s0C();
 virtual void s10();
 virtual void s14();
 virtual void s18();
 virtual void s1C();
 virtual void s20();
 virtual void s24();
 virtual void s28();
 virtual void s2C();
 virtual void s30();
 virtual void s34();
 virtual void s38();
 virtual void s3C();
 virtual void s40();
 virtual void s44();
 virtual void s48();
 virtual void s4C();
 virtual void s50();
 virtual void s54();
 virtual void s58();
 virtual void s5C();
 virtual void s60();
 virtual void s64();
 virtual void s68();
 virtual void s6C();
 virtual void s70();
 virtual void s74();
 virtual void s78();
 virtual void s7C();
 virtual void s80(void *,void *,void *,void *);
};
class UnknownGenV800F6088_3 {
public:
 virtual void s08();
 virtual void s0C();
 virtual void s10();
 virtual void s14();
 virtual void s18();
 virtual void s1C();
 virtual void s20();
 virtual void s24();
 virtual void s28();
 virtual void s2C();
 virtual void s30();
 virtual void s34();
 virtual void s38();
 virtual void s3C();
 virtual void s40();
 virtual void s44();
 virtual void s48();
 virtual void s4C();
 virtual void s50();
 virtual void s54();
 virtual void s58();
 virtual void s5C();
 virtual void s60();
 virtual void s64();
 virtual void s68();
 virtual void s6C();
 virtual void s70();
 virtual void s74();
 virtual void s78();
 virtual void s7C();
 virtual void s80();
 virtual void s84();
 virtual void s88();
 virtual void s8C();
 virtual void s90();
 virtual void s94();
 virtual void s98();
 virtual void s9C();
 virtual void sA0();
 virtual void sA4();
 virtual void sA8();
 virtual void sAC();
 virtual void sB0();
 virtual void sB4();
 virtual void sB8();
 virtual void sBC();
 virtual void sC0();
 virtual void sC4();
 virtual void sC8();
 virtual void sCC();
 virtual void sD0(void *,void *);
};
class UnknownGenV800F6088_4 {
public:
 virtual void s08();
 virtual void s0C();
 virtual void s10();
 virtual void s14();
 virtual void s18();
 virtual void s1C();
 virtual void s20();
 virtual void s24();
 virtual void s28();
 virtual void s2C();
 virtual void s30();
 virtual void s34();
 virtual void s38();
 virtual void s3C();
 virtual void s40();
 virtual void s44();
 virtual void s48();
 virtual void s4C();
 virtual void s50();
 virtual void s54();
 virtual void s58();
 virtual void s5C();
 virtual void s60();
 virtual void s64();
 virtual void s68();
 virtual void s6C();
 virtual void s70();
 virtual void s74();
 virtual void s78();
 virtual void s7C();
 virtual void s80();
 virtual void s84();
 virtual void s88();
 virtual void s8C();
 virtual void s90();
 virtual void s94();
 virtual void s98();
 virtual void s9C();
 virtual void sA0();
 virtual void sA4();
 virtual void sA8();
 virtual void sAC();
 virtual void sB0();
 virtual void sB4();
 virtual void sB8();
 virtual void sBC();
 virtual void sC0();
 virtual void sC4();
 virtual void sC8();
 virtual void sCC();
 virtual void sD0(void *,void *);
};
class UnknownGenV800F60F8_5 {
public:
 virtual void s08();
 virtual void s0C();
 virtual void s10();
 virtual void s14();
 virtual void s18();
 virtual void s1C();
 virtual void s20();
 virtual void s24();
 virtual void s28();
 virtual void s2C();
 virtual void s30();
 virtual void s34();
 virtual void s38();
 virtual void s3C();
 virtual void s40();
 virtual void s44();
 virtual void s48();
 virtual void s4C();
 virtual void s50();
 virtual void s54();
 virtual void s58();
 virtual void s5C();
 virtual void s60();
 virtual void s64();
 virtual void s68();
 virtual void s6C();
 virtual void s70();
 virtual void s74();
 virtual void s78();
 virtual void s7C();
 virtual void s80();
 virtual void s84();
 virtual void s88();
 virtual void s8C();
 virtual void s90();
 virtual void s94();
 virtual void s98();
 virtual void s9C();
 virtual void sA0();
 virtual void sA4();
 virtual void sA8();
 virtual void sAC();
 virtual void sB0();
 virtual void sB4();
 virtual void sB8();
 virtual void sBC();
 virtual void sC0();
 virtual void sC4();
 virtual void sC8();
 virtual void sCC();
 virtual void sD0(void *,void *);
};
class UnknownGenV800F60F8_6 {
public:
 virtual void s08();
 virtual void s0C();
 virtual void s10();
 virtual void s14();
 virtual void s18();
 virtual void s1C();
 virtual void s20();
 virtual void s24();
 virtual void s28();
 virtual void s2C();
 virtual void s30();
 virtual void s34();
 virtual void s38();
 virtual void s3C();
 virtual void s40();
 virtual void s44();
 virtual void s48();
 virtual void s4C();
 virtual void s50();
 virtual void s54();
 virtual void s58();
 virtual void s5C();
 virtual void s60();
 virtual void s64();
 virtual void s68();
 virtual void s6C();
 virtual void s70();
 virtual void s74();
 virtual void s78();
 virtual void s7C();
 virtual void s80();
 virtual void s84();
 virtual void s88();
 virtual void s8C();
 virtual void s90();
 virtual void s94();
 virtual void s98();
 virtual void s9C();
 virtual void sA0();
 virtual void sA4();
 virtual void sA8();
 virtual void sAC();
 virtual void sB0();
 virtual void sB4();
 virtual void sB8();
 virtual void sBC();
 virtual void sC0();
 virtual void sC4();
 virtual void sC8();
 virtual void sCC();
 virtual void sD0(void *,void *);
};
extern "C" {
void fn_800F5F4C(void *object,int value){*reinterpret_cast<int *>(reinterpret_cast<char *>(object)+20)=value;}
void fn_800F5F54(int p0,int p1){
 void *local3;
 void *local2;
 void *local1;
 void *local0;
 *reinterpret_cast<unsigned char *>(reinterpret_cast<char *>((void *)p0)+24)=(unsigned char)(int)(void *)p1;
 fn_800F90FC(*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p0)+20),(void *)p1);
 if((unsigned char)p1){
  reinterpret_cast<UnknownGenV800F5F54_0 *>((void *)p0)->s80(*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p0)+28),*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p0)+32),*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p0)+36),*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p0)+40));
  return;
 } else {
  local3=(void *)0;
  local2=(void *)0;
  local1=(void *)640;
  local0=(void *)480;
  reinterpret_cast<UnknownGenV800F5F54_1 *>(*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p0)+20))->s2E8(&local3,&local2,&local1,&local0);
  reinterpret_cast<UnknownGenV800F5F54_2 *>((void *)p0)->s80(local3,local2,local1,local0);
  return;
 }
}
unsigned char fn_800F6028(void *object){return *reinterpret_cast<unsigned char *>(reinterpret_cast<char *>(object)+24);}
void fn_800F6030(int p0,int p1,int p2,int p3,int p4){
 *reinterpret_cast<void * *>(reinterpret_cast<char *>((void *)p0)+28)=(void *)p1;
 *reinterpret_cast<void * *>(reinterpret_cast<char *>((void *)p0)+32)=(void *)p2;
 *reinterpret_cast<void * *>(reinterpret_cast<char *>((void *)p0)+36)=(void *)p3;
 *reinterpret_cast<void * *>(reinterpret_cast<char *>((void *)p0)+40)=(void *)p4;
 fn_800F933C(*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p0)+20),(void *)p1,(void *)p2,(void *)p3,(void *)p4);
}
void *fn_800F6064(int p0,int p1,int p2,int p3,int p4){
 *reinterpret_cast<void * *>(reinterpret_cast<char *>((void *)p1)+0)=*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p0)+28);
 *reinterpret_cast<void * *>(reinterpret_cast<char *>((void *)p2)+0)=*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p0)+32);
 *reinterpret_cast<void * *>(reinterpret_cast<char *>((void *)p3)+0)=*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p0)+36);
 *reinterpret_cast<void * *>(reinterpret_cast<char *>((void *)p4)+0)=*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p0)+40);
 return (void *)p0;
}
void fn_800F6088(int p0){
 void *value0;
 void *value1;
 if((int)(int)*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p0)+20)==0){
  value0=fn_8002213C();
  reinterpret_cast<UnknownGenV800F6088_3 *>(value0)->sD0(*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p0)+12),*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p0)+16));
  return;
 } else {
  value1=fn_80022DF8();
  reinterpret_cast<UnknownGenV800F6088_4 *>(value1)->sD0(*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p0)+12),*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p0)+16));
  return;
 }
}
void fn_800F60F8(int p0){
 void *value0;
 void *value1;
 if((int)(int)*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p0)+20)==0){
  value0=fn_8002213C();
  reinterpret_cast<UnknownGenV800F60F8_5 *>(value0)->sD0(*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p0)+12),*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p0)+16));
  return;
 } else {
  value1=fn_80022DF8();
  reinterpret_cast<UnknownGenV800F60F8_6 *>(value1)->sD0(*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p0)+12),*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p0)+16));
  return;
 }
}
}
#pragma pop
