#include <unknownGen.h>
#pragma push
#pragma auto_inline off
extern "C" {
extern char lbl_8047A2F4[];
extern void *lbl_80562504;
extern void *lbl_80562B0C;
}
class UnknownGenV800C3EC8_0 {
public:
 virtual void s08();
 virtual void s0C();
 virtual void s10();
 virtual void s14();
 virtual void s18();
 virtual void s1C();
 virtual void s20();
 virtual void s24();
 virtual void s28();
 virtual void s2C();
 virtual void s30();
 virtual void s34();
 virtual void s38();
 virtual void s3C();
 virtual void s40();
 virtual void s44();
 virtual void s48();
 virtual void s4C();
 virtual void s50();
 virtual void s54();
 virtual void s58();
 virtual void s5C();
 virtual void s60();
 virtual void s64();
 virtual void s68();
 virtual void s6C();
 virtual void s70();
 virtual void s74();
 virtual void s78();
 virtual void s7C();
 virtual void s80();
 virtual void s84();
 virtual void s88();
 virtual void s8C();
 virtual void s90();
 virtual void s94();
 virtual void s98();
 virtual void s9C();
 virtual void sA0();
 virtual void sA4();
 virtual void sA8();
 virtual void sAC();
 virtual void sB0();
 virtual void sB4();
 virtual void sB8();
 virtual void sBC();
 virtual void sC0();
 virtual void sC4();
 virtual void sC8();
 virtual void sCC();
 virtual void sD0();
 virtual void sD4();
 virtual void sD8();
 virtual void sDC();
 virtual void sE0();
 virtual void sE4();
 virtual void sE8();
 virtual void sEC();
 virtual void sF0();
 virtual void sF4();
 virtual void sF8();
 virtual void sFC();
 virtual void s100();
 virtual void s104();
 virtual void s108();
 virtual void s10C();
 virtual void s110();
 virtual void s114();
 virtual void s118();
 virtual void s11C();
 virtual void s120();
 virtual void s124();
 virtual void s128();
 virtual void s12C();
 virtual void s130();
 virtual void s134();
 virtual void s138();
 virtual void s13C();
 virtual void s140();
 virtual void s144();
 virtual void s148();
 virtual void s14C();
 virtual void s150();
 virtual void s154();
 virtual void s158();
 virtual void s15C();
 virtual void s160();
 virtual void s164();
 virtual void s168();
 virtual void s16C();
 virtual void s170();
 virtual void s174();
 virtual void s178();
 virtual void s17C();
 virtual void s180();
 virtual void s184();
 virtual void s188();
 virtual void s18C();
 virtual void s190();
 virtual void s194();
 virtual void s198();
 virtual void s19C();
 virtual void s1A0();
 virtual void s1A4();
 virtual void s1A8();
 virtual void s1AC();
 virtual void s1B0();
 virtual void s1B4();
 virtual void s1B8();
 virtual void s1BC();
 virtual void s1C0();
 virtual void s1C4();
 virtual void s1C8();
 virtual void s1CC();
 virtual void s1D0();
 virtual void s1D4();
 virtual void s1D8();
 virtual void s1DC();
 virtual void s1E0();
 virtual void s1E4();
 virtual void s1E8();
 virtual void s1EC();
 virtual void s1F0();
 virtual void s1F4();
 virtual void s1F8();
 virtual void s1FC();
 virtual void s200();
 virtual void s204();
 virtual void s208();
 virtual void s20C();
 virtual void s210();
 virtual void s214();
 virtual void s218();
 virtual void s21C();
 virtual void s220();
 virtual void s224();
 virtual void s228();
 virtual void s22C();
 virtual void s230();
 virtual void s234();
 virtual void s238();
 virtual void s23C();
 virtual void s240();
 virtual void s244();
 virtual void s248();
 virtual void s24C();
 virtual void s250();
 virtual void * s254(void *);
};
class UnknownGenV800C3EC8_1 {
public:
 virtual void s08();
 virtual void s0C();
 virtual void s10();
 virtual void s14();
 virtual void s18();
 virtual void s1C();
 virtual void s20();
 virtual void s24();
 virtual void s28();
 virtual void s2C();
 virtual void s30();
 virtual void s34();
 virtual void s38();
 virtual void s3C();
 virtual void s40();
 virtual void s44();
 virtual void s48();
 virtual void s4C();
 virtual void s50();
 virtual void s54();
 virtual void s58();
 virtual void s5C();
 virtual void s60();
 virtual void s64();
 virtual void * s68(void *);
};
extern "C" {
void *fn_800C3EC0(){return lbl_80562504;}
void fn_800C3EC8(int p0,int p1){
 void *value0;
 void *value1;
 value0=reinterpret_cast<UnknownGenV800C3EC8_0 *>((void *)p1)->s254(*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p0)+16));
 *reinterpret_cast<void * *>(reinterpret_cast<char *>((void *)p0)+12)=value0;
 if(!lbl_80562B0C){
  value1=reinterpret_cast<UnknownGenV800C3EC8_1 *>((void *)p1)->s68(lbl_8047A2F4);
  lbl_80562B0C=value1;
  return;
 } else {
  return;
 }
}
}
#pragma pop
