// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801B7E14 (metaobject lbl_80564BEC, vtable lbl_804B8120), size 0x2C.
// Note: vertex: igObjectRefArrayMetaField, count from the space to the next member.
// Note: face: igObjectRefArrayMetaField, count from the space to the next member.
#ifndef META__EDGE_H
#define META__EDGE_H
#include <meta/igHeapable.h>
namespace Meta {
struct _vertex;
struct _edge : igHeapable {
 float cost;  // 0x10 igFloatMetaField
 void * vertex[2];  // 0x14 igObjectRefArrayMetaField
 void * face[2];  // 0x1C igObjectRefArrayMetaField
 _vertex *optimal;  // 0x24 igObjectRefMetaField
 unsigned char which;  // 0x28 igUnsignedCharMetaField
 unsigned char unknown29[3];
};
}
#endif
