// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801B80AC (metaobject lbl_80564C04, vtable lbl_804B8058), size 0x14.
#ifndef META__FACELIST_H
#define META__FACELIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct _faceList : igObjectList {
};
}
#endif
