// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801B845C (metaobject lbl_80564C18, vtable lbl_804B7F34), size 0x14.
#ifndef META__VERTEXLIST_H
#define META__VERTEXLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct _vertexList : igObjectList {
};
}
#endif
