// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by _vertex_register (metaobject lbl_80564C1C, vtable lbl_804B7ED8), size 0x54.
#ifndef META__VERTEX_H
#define META__VERTEX_H
#include <meta/igObject.h>
namespace Meta {
struct _edgeList;
struct _faceList;
struct igFloatList;
struct igUnsignedCharList;
struct _vertex : igObject {
 float position[3];  // 0x08 igVec3fMetaField
 float normal[3];  // 0x14 igVec3fMetaField
 float colors[4];  // 0x20 igVec4fMetaField
 igFloatList *textures;  // 0x30 igObjectRefMetaField
 igFloatList *blend_weights;  // 0x34 igObjectRefMetaField
 igUnsignedCharList *blend_indices;  // 0x38 igObjectRefMetaField
 igFloatList *que;  // 0x3C igObjectRefMetaField
 _edgeList *neighbor_edges;  // 0x40 igObjectRefMetaField
 _faceList *neighbor_faces;  // 0x44 igObjectRefMetaField
 _vertex *parent_vertex;  // 0x48 igObjectRefMetaField
 unsigned short parent_index;  // 0x4C igUnsignedShortMetaField
 unsigned short index;  // 0x4E igUnsignedShortMetaField
 unsigned short final_index;  // 0x50 igUnsignedShortMetaField
 unsigned char unknown52[2];
};
}
#endif
