// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802E76F4 (metaobject lbl_80535830, vtable lbl_804DD3C0), size 0x14.
#ifndef META_BE_H
#define META_BE_H
#include <meta/igInfoManager.h>
namespace Meta {
struct igStringRefList;
struct be : igInfoManager {
 igStringRefList *_stringRefList;  // 0x10 igObjectRefMetaField
};
}
#endif
