// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beAction2_register (metaobject lbl_8053582C, vtable lbl_804DD510), size 0x20.
#ifndef META_BEACTION2_H
#define META_BEACTION2_H
#include <meta/beBaseInfoManager.h>
namespace Meta {
struct beAction2 : beBaseInfoManager {
};
}
#endif
