// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beActionStarter_register (metaobject lbl_80535760, vtable lbl_804DD630), size 0x20.
#ifndef META_BEACTIONSTARTER_H
#define META_BEACTIONSTARTER_H
#include <meta/beBaseInfoManager.h>
namespace Meta {
struct beActionStarter : beBaseInfoManager {
};
}
#endif
