// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beAction2Info_register (metaobject lbl_805357D4, vtable lbl_804D3A1C), size 0x28.
#ifndef META_BEACTION2INFO_H
#define META_BEACTION2INFO_H
#include <meta/beBaseInfo.h>
namespace Meta {
struct beAction2DataList;
struct igAnimationDatabase;
struct igSwitch;
struct beAction2Info : beBaseInfo {
 igSwitch *_switch;  // 0x1C igObjectRefMetaField
 igAnimationDatabase *_animationDatabase;  // 0x20 igObjectRefMetaField
 beAction2DataList *_dataList;  // 0x24 igObjectRefMetaField
};
}
#endif
