// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802E6E64 (metaobject lbl_8053581C, vtable lbl_804D36AC), size 0x14.
#ifndef META_BEACTION2DATALIST_H
#define META_BEACTION2DATALIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beAction2DataList : igObjectList {
};
}
#endif
