// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802E431C (metaobject lbl_80535724, vtable lbl_804D4110), size 0x2C.
#ifndef META_BEACTIONSTARTERINFORAM_H
#define META_BEACTIONSTARTERINFORAM_H
#include <meta/beBaseInfoRam.h>
namespace Meta {
struct beActionStarterInfoRam : beBaseInfoRam {
};
}
#endif
