// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beAction2InfoRam_register (metaobject lbl_805357BC, vtable lbl_804D3BD8), size 0x3C.
#ifndef META_BEACTION2INFORAM_H
#define META_BEACTION2INFORAM_H
#include <meta/beBaseInfoRam.h>
namespace Meta {
struct beAction2InfoWork;
struct beModelCtrlNode2;
struct igActorList;
struct igAppearanceList;
struct beAction2InfoRam : beBaseInfoRam {
 beModelCtrlNode2 *_node;  // 0x2C igObjectRefMetaField
 igAppearanceList *_appearanceList;  // 0x30 igObjectRefMetaField
 igActorList *_actorList;  // 0x34 igObjectRefMetaField
 beAction2InfoWork *_work;  // 0x38 igObjectRefMetaField
};
}
#endif
