// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802E70A4 (metaobject lbl_80535820, vtable lbl_804D359C), size 0x10.
#ifndef META_BEACTION2DATA_H
#define META_BEACTION2DATA_H
#include <meta/igNamedObject.h>
namespace Meta {
struct igNamedObjectList;
struct beAction2Data : igNamedObject {
 igNamedObjectList *_comList;  // 0x0C igObjectRefMetaField
};
}
#endif
