// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802E573C (metaobject lbl_80535764, vtable lbl_804D3C48), size 0x60.
#ifndef META_BEACTION2INFOWORK_H
#define META_BEACTION2INFOWORK_H
#include <meta/igObject.h>
namespace Meta {
struct beAction2Data;
struct igBlendStateAttr;
struct igColorAttr;
struct igLightingStateAttr;
struct igTextureStateAttr;
struct beAction2InfoWork : igObject {
 beAction2Data *_comData;  // 0x08 igObjectRefMetaField
 int _comIndex;  // 0x0C igIntMetaField
 bool _isNoHokan;  // 0x10 igBoolMetaField
 bool _isMotion;  // 0x11 igBoolMetaField
 unsigned char unknown12[2];
 int _motionSt0;  // 0x14 igIntMetaField
 bool _motionIsEnd;  // 0x18 igBoolMetaField
 unsigned char unknown19[3];
 int _jointSt0;  // 0x1C igIntMetaField
 long long _jointStartTimeL;  // 0x20 igLongMetaField
 long long _jointEndTimeL;  // 0x28 igLongMetaField
 bool _jointIsEnd;  // 0x30 igBoolMetaField
 unsigned char unknown31[3];
 int _fadeSt0;  // 0x34 igIntMetaField
 float _fadeLimitValue;  // 0x38 igFloatMetaField
 float _fadeAddValue;  // 0x3C igFloatMetaField
 float _fadeValue;  // 0x40 igFloatMetaField
 int _waitSt0;  // 0x44 igIntMetaField
 int _flashSt0;  // 0x48 igIntMetaField
 bool _isFreeze;  // 0x4C igBoolMetaField
 unsigned char unknown4D[3];
 igColorAttr *_colorAttr;  // 0x50 igObjectRefMetaField
 igBlendStateAttr *_blendStateAttr;  // 0x54 igObjectRefMetaField
 igTextureStateAttr *_textureStateAttr;  // 0x58 igObjectRefMetaField
 igLightingStateAttr *_lightingStateAttr;  // 0x5C igObjectRefMetaField
};
}
#endif
