// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beAction2FADESET_register (metaobject lbl_805357F0, vtable lbl_804D3880), size 0x14.
#ifndef META_BEACTION2FADESET_H
#define META_BEACTION2FADESET_H
#include <meta/igNamedObject.h>
namespace Meta {
struct beAction2FADESET : igNamedObject {
 float _fadeTime;  // 0x0C igFloatMetaField
 float _fadeValue;  // 0x10 igFloatMetaField
};
}
#endif
