// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802E3284 (metaobject lbl_805356AC, vtable lbl_804DCDF0), size 0x2C.
#ifndef META_BEBASEINFORAM_H
#define META_BEBASEINFORAM_H
#include <meta/igObject.h>
namespace Meta {
struct beBaseInfo;
struct beBaseInfoDataList;
struct beBaseInfoManager;
struct beBaseInfoRam : igObject {
 int _ramNo;  // 0x08 igIntMetaField
 beBaseInfo *_parentInfo;  // 0x0C igObjectRefMetaField
 beBaseInfoManager *_parentManager;  // 0x10 igObjectRefMetaField
 bool _isRun;  // 0x14 igBoolMetaField
 unsigned char unknown15[3];
 int _st0;  // 0x18 igIntMetaField
 int _st1;  // 0x1C igIntMetaField
 int _st2;  // 0x20 igIntMetaField
 int _st3;  // 0x24 igIntMetaField
 beBaseInfoDataList *_dataList;  // 0x28 igObjectRefMetaField
};
}
#endif
