// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802B86E0 (metaobject lbl_80534734), size 0x18.
#ifndef META_BEBINDATAOBJECT_H
#define META_BEBINDATAOBJECT_H
#include <meta/beBaseInfoData.h>
namespace Meta {
struct beBinDataObject : beBaseInfoData {
 void *_dataBuffer;  // 0x10 igMemoryRefMetaField
 int _dataSize;  // 0x14 igIntMetaField
};
}
#endif
