// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802E2E4C (metaobject lbl_805356A0, vtable lbl_804DD840), size 0x24.
#ifndef META_BEBKCOLOR_H
#define META_BEBKCOLOR_H
#include <meta/beBaseInfoManager.h>
namespace Meta {
struct beBkColor : beBaseInfoManager {
 bool _isClear;  // 0x20 igBoolMetaField
 unsigned char unknown21[3];
};
}
#endif
