// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beCameraCtrlInfoRamShake_register (metaobject lbl_80535634, vtable lbl_804D475C), size 0x40.
#ifndef META_BECAMERACTRLINFORAMSHAKE_H
#define META_BECAMERACTRLINFORAMSHAKE_H
#include <meta/beBaseInfoData.h>
namespace Meta {
struct beCameraCtrlInfoRamShake : beBaseInfoData {
 bool _isFirst;  // 0x10 igBoolMetaField
 unsigned char unknown11[3];
 float _svEyePos[3];  // 0x14 igVec3fMetaField
 float _svIntPos[3];  // 0x20 igVec3fMetaField
 const char *_moveCode;  // 0x2C igStringMetaField
 float _value;  // 0x30 igFloatMetaField
 float _oneTime;  // 0x34 igFloatMetaField
 float _endTime;  // 0x38 igFloatMetaField
 int _movePoint;  // 0x3C igIntMetaField
};
}
#endif
