// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802E1A00 (metaobject lbl_80535604, vtable lbl_804D48C4), size 0x20.
#ifndef META_BECAMERACTRLINFO_H
#define META_BECAMERACTRLINFO_H
#include <meta/beBaseInfo.h>
namespace Meta {
struct beCameraCtrlInfo : beBaseInfo {
 void *_data;  // 0x1C igObjectRefMetaField
};
}
#endif
