// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802E1F58 (metaobject lbl_8053561C, vtable lbl_804D47CC), size 0x1C.
#ifndef META_BECAMERABOXDATA_H
#define META_BECAMERABOXDATA_H
#include <meta/igObject.h>
namespace Meta {
struct igGeometryList;
struct igSwitch;
struct igTransformList;
struct beCameraBoxData : igObject {
 igSwitch *_switch;  // 0x08 igObjectRefMetaField
 igGeometryList *_geometryList;  // 0x0C igObjectRefMetaField
 igTransformList *_transformList;  // 0x10 igObjectRefMetaField
 igTransformList *_eyePosList;  // 0x14 igObjectRefMetaField
 igTransformList *_intPosList;  // 0x18 igObjectRefMetaField
};
}
#endif
