// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beChangePosTransform_register (metaobject lbl_805355D8, vtable lbl_804DDBE0), size 0x2C.
#ifndef META_BECHANGEPOSTRANSFORM_H
#define META_BECHANGEPOSTRANSFORM_H
#include <meta/beBaseInfoManager.h>
namespace Meta {
struct beChangePosTransform : beBaseInfoManager {
 float _oldPos[3];  // 0x20 igVec3fMetaField
};
}
#endif
