// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802E10C0 (metaobject lbl_805355D4, vtable lbl_804D4954), size 0x1C.
#ifndef META_BECHANGEPOSTRANSFORMINFO_H
#define META_BECHANGEPOSTRANSFORMINFO_H
#include <meta/beBaseInfo.h>
namespace Meta {
struct beChangePosTransformInfo : beBaseInfo {
};
}
#endif
