// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802E0684 (metaobject lbl_805355BC, vtable lbl_804D4BA4), size 0x70.
#ifndef META_BECOPYTRANSFORM_H
#define META_BECOPYTRANSFORM_H
#include <meta/igTransform.h>
namespace Meta {
struct igTransform;
struct beCopyTransform : igTransform {
 igTransform *_srcTransform;  // 0x6C igObjectRefMetaField
};
}
#endif
