// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802E0B08 (metaobject lbl_805355C4, vtable lbl_804D4AD0), size 0x70.
#ifndef META_BECOPYMODELCTRL2_H
#define META_BECOPYMODELCTRL2_H
#include <meta/igTransform.h>
namespace Meta {
struct beModelCtrlNode2;
struct beCopyModelCtrl2 : igTransform {
 beModelCtrlNode2 *_srcNode;  // 0x6C igObjectRefMetaField
};
}
#endif
