// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beCri_register (metaobject lbl_80535584, vtable lbl_804DDCD4), size 0x48.
#ifndef META_BECRI_H
#define META_BECRI_H
#include <meta/igInfoManager.h>
namespace Meta {
struct beCriHandle;
struct beCriHandleList;
struct beSystem;
struct igInfoList;
struct igObjectList;
struct beCri : igInfoManager {
 beSystem *_system;  // 0x10 igObjectRefMetaField
 int _execDvdErr;  // 0x14 igIntMetaField
 long long _request;  // 0x18 igLongMetaField
 beCriHandle *_hdBGM;  // 0x20 igObjectRefMetaField
 beCriHandle *_hdENV;  // 0x24 igObjectRefMetaField
 beCriHandleList *_hdSEs;  // 0x28 igObjectRefMetaField
 igInfoList *_infoList;  // 0x2C igObjectRefMetaField
 igObjectList *_lsBinObjs;  // 0x30 igObjectRefMetaField
 int _baseVolume;  // 0x34 igIntMetaField
 int _sndfVolume;  // 0x38 igIntMetaField
 bool _pauseOnetime;  // 0x3C igBoolMetaField
 unsigned char unknown3D[3];
 int _dataType;  // 0x40 igIntMetaField
 unsigned char unknown44[4];
};
}
#endif
