// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beCriHandleList_register (metaobject lbl_805354F8, vtable lbl_804D5010), size 0x14.
#ifndef META_BECRIHANDLELIST_H
#define META_BECRIHANDLELIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beCriHandleList : igObjectList {
};
}
#endif
