// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802DF77C (metaobject lbl_8053555C, vtable lbl_804D4DE4), size 0x18.
#ifndef META_BECRIAUDIO_H
#define META_BECRIAUDIO_H
#include <meta/igObject.h>
namespace Meta {
struct beCriSndf;
struct igAdxAudio;
struct beCriAudio : igObject {
 igAdxAudio *_adxt;  // 0x08 igObjectRefMetaField
 beCriSndf *_sndf;  // 0x0C igObjectRefMetaField
 int _audioType;  // 0x10 igIntMetaField
 int _errVolume;  // 0x14 igIntMetaField
};
}
#endif
