// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802DE7A4 (metaobject lbl_805354C8, vtable lbl_804D51D0), size 0x20.
#ifndef META_BECRIVOLUME_H
#define META_BECRIVOLUME_H
#include <meta/igObject.h>
namespace Meta {
struct beCriVolume : igObject {
 int _isExec;  // 0x08 igIntMetaField
 int _max;  // 0x0C igIntMetaField
 float _current;  // 0x10 igFloatMetaField
 float _sta;  // 0x14 igFloatMetaField
 float _end;  // 0x18 igFloatMetaField
 float _unit;  // 0x1C igFloatMetaField
};
}
#endif
