// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beCriSfpData_register (metaobject lbl_805354E4, vtable lbl_804D5104), size 0x28.
#ifndef META_BECRISFPDATA_H
#define META_BECRISFPDATA_H
#include <meta/beBinDataObject.h>
namespace Meta {
struct beCriSfpData : beBinDataObject {
 int _portNo;  // 0x18 igIntMetaField
 int _tblSize;  // 0x1C igIntMetaField
 int _pcmSize;  // 0x20 igIntMetaField
 bool _isTransfer;  // 0x24 igBoolMetaField
 unsigned char unknown25[3];
};
}
#endif
