// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802DFA20 (metaobject lbl_80535570, vtable lbl_804D4D74), size 0x20.
#ifndef META_BECRISNDF_H
#define META_BECRISNDF_H
#include <meta/igObject.h>
namespace Meta {
struct beCriSndf : igObject {
 int _req;  // 0x08 igIntMetaField
 unsigned char unknown0C[4];
 long long _seq;  // 0x10 igLongMetaField
 bool _isPlaying;  // 0x18 igBoolMetaField
 unsigned char unknown19[7];
};
}
#endif
