// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beDataObjObjectList_register (metaobject lbl_80535448, vtable lbl_804D5740), size 0x10.
#ifndef META_BEDATAOBJOBJECTLIST_H
#define META_BEDATAOBJOBJECTLIST_H
#include <meta/igNamedObject.h>
namespace Meta {
struct igObjectList;
struct beDataObjObjectList : igNamedObject {
 igObjectList *_data;  // 0x0C igObjectRefMetaField
};
}
#endif
