// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802DCC38 (metaobject lbl_80535458, vtable lbl_804D5650), size 0x10.
#ifndef META_BEDATAOBJSTRING_H
#define META_BEDATAOBJSTRING_H
#include <meta/igNamedObject.h>
namespace Meta {
struct beDataObjString : igNamedObject {
 const char *_data;  // 0x0C igStringMetaField
};
}
#endif
