// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beDataObjStringList_register (metaobject lbl_80535450, vtable lbl_804D56C8), size 0x10.
#ifndef META_BEDATAOBJSTRINGLIST_H
#define META_BEDATAOBJSTRINGLIST_H
#include <meta/igNamedObject.h>
namespace Meta {
struct igStringRefList;
struct beDataObjStringList : igNamedObject {
 igStringRefList *_data;  // 0x0C igObjectRefMetaField
};
}
#endif
