// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802DD91C (metaobject lbl_80535480, vtable lbl_804D538C), size 0x14.
#ifndef META_BEDATABASELIST_H
#define META_BEDATABASELIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beDataBaseList : igObjectList {
};
}
#endif
