// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802DDD9C (metaobject lbl_80535484, vtable lbl_804D52D0), size 0x38.
#ifndef META_BEDATABASE_H
#define META_BEDATABASE_H
#include <meta/igObject.h>
namespace Meta {
struct igBoolList;
struct igCharList;
struct igFloatList;
struct igIntList;
struct igNamedObjectList;
struct igShortList;
struct beDataBase : igObject {
 igNamedObjectList *_charOffsetList;  // 0x08 igObjectRefMetaField
 igCharList *_charData;  // 0x0C igObjectRefMetaField
 igNamedObjectList *_shortOffsetList;  // 0x10 igObjectRefMetaField
 igShortList *_shortData;  // 0x14 igObjectRefMetaField
 igNamedObjectList *_intOffsetList;  // 0x18 igObjectRefMetaField
 igIntList *_intData;  // 0x1C igObjectRefMetaField
 igNamedObjectList *_floatOffsetList;  // 0x20 igObjectRefMetaField
 igFloatList *_floatData;  // 0x24 igObjectRefMetaField
 igNamedObjectList *_boolOffsetList;  // 0x28 igObjectRefMetaField
 igBoolList *_boolData;  // 0x2C igObjectRefMetaField
 igNamedObjectList *_stringOffsetList;  // 0x30 igObjectRefMetaField
 igNamedObjectList *_stringData;  // 0x34 igObjectRefMetaField
};
}
#endif
