// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beDataObjFloatList_register (metaobject lbl_80535440, vtable lbl_804D57B8), size 0x10.
#ifndef META_BEDATAOBJFLOATLIST_H
#define META_BEDATAOBJFLOATLIST_H
#include <meta/igNamedObject.h>
namespace Meta {
struct igFloatList;
struct beDataObjFloatList : igNamedObject {
 igFloatList *_data;  // 0x0C igObjectRefMetaField
};
}
#endif
