// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802DBF68 (metaobject lbl_80535438, vtable lbl_804D5938), size 0x14.
#ifndef META_BEDATAOBJLISTLIST_H
#define META_BEDATAOBJLISTLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beDataObjListList : igObjectList {
};
}
#endif
