// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802DE24C (metaobject lbl_805354B8, vtable lbl_804D5258), size 0x20.
#ifndef META_BEDBMANAGERINFO_H
#define META_BEDBMANAGERINFO_H
#include <meta/beBaseInfo.h>
namespace Meta {
struct beDataBase;
struct beDBManagerInfo : beBaseInfo {
 beDataBase *_dataBase;  // 0x1C igObjectRefMetaField
};
}
#endif
