// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beDemoKeepMes_register (metaobject lbl_80535418, vtable lbl_804D5A14), size 0x30.
#ifndef META_BEDEMOKEEPMES_H
#define META_BEDEMOKEEPMES_H
#include <meta/igObject.h>
namespace Meta {
struct beDemoKeepMes : igObject {
 int _kind;  // 0x08 igIntMetaField
 unsigned char unknown0C[4];
 long long _sendTime;  // 0x10 igLongMetaField
 const char *_groupName;  // 0x18 igStringMetaField
 const char *_infoName;  // 0x1C igStringMetaField
 int _ramNo;  // 0x20 igIntMetaField
 const char *_message;  // 0x24 igStringMetaField
 const char *_mesParam;  // 0x28 igStringMetaField
 unsigned char unknown2C[4];
};
}
#endif
