// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802DB598 (metaobject lbl_80535404, vtable lbl_804D5C68), size 0x14.
#ifndef META_BEDEMOMANAGERWORKLIST_H
#define META_BEDEMOMANAGERWORKLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beDemoManagerWorkList : igObjectList {
};
}
#endif
