// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802DA770 (metaobject lbl_80535398, vtable lbl_804DDE84), size 0x40.
#ifndef META_BEFILELISTINFOMANAGER_H
#define META_BEFILELISTINFOMANAGER_H
#include <meta/igInfoManager.h>
namespace Meta {
struct beMessenger;
struct beSystem;
struct igDirectoryList;
struct igInfoList;
struct igStringRefList;
struct igViewerSceneInfoManager;
struct beFileListInfoManager : igInfoManager {
 beSystem *_system;  // 0x10 igObjectRefMetaField
 beMessenger *_messenger;  // 0x14 igObjectRefMetaField
 igViewerSceneInfoManager *_sceneInfoManager;  // 0x18 igObjectRefMetaField
 bool _isReadOnetime;  // 0x1C igBoolMetaField
 unsigned char unknown1D[3];
 int _onetimeCount;  // 0x20 igIntMetaField
 igStringRefList *_fnames;  // 0x24 igObjectRefMetaField
 igInfoList *_infoList;  // 0x28 igObjectRefMetaField
 igDirectoryList *_dirList;  // 0x2C igObjectRefMetaField
 igInfoList *_readInfoList;  // 0x30 igObjectRefMetaField
 igInfoList *_importantInfoList;  // 0x34 igObjectRefMetaField
 int _loaded;  // 0x38 igIntMetaField
 int _proc;  // 0x3C igIntMetaField
};
}
#endif
