// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802D8BE8 (metaobject lbl_80535310, vtable lbl_804D6404), size 0x20.
#ifndef META_BEFONTINFO_H
#define META_BEFONTINFO_H
#include <meta/beBaseInfo.h>
namespace Meta {
struct beUnicodeObjList;
struct beFontInfo : beBaseInfo {
 beUnicodeObjList *_unicodeList;  // 0x1C igObjectRefMetaField
};
}
#endif
