// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802DA134 (metaobject lbl_80535384, vtable lbl_804D5F68), size 0x14.
#ifndef META_BEFONTGEOMATTRPAIRLIST_H
#define META_BEFONTGEOMATTRPAIRLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beFontGeomAttrPairList : igObjectList {
};
}
#endif
