// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802DA34C (metaobject lbl_80535388, vtable lbl_804D5EAC), size 0x14.
#ifndef META_BEFONTGEOMATTRPAIR_H
#define META_BEFONTGEOMATTRPAIR_H
#include <meta/igObject.h>
namespace Meta {
struct igGeometryAttrList;
struct beFontGeomAttrPair : igObject {
 const char *_category;  // 0x08 igStringMetaField
 const char *_panel;  // 0x0C igStringMetaField
 igGeometryAttrList *_geomAttrs;  // 0x10 igObjectRefMetaField
};
}
#endif
