// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802D983C (metaobject lbl_80535348, vtable lbl_804D609C), size 0x24.
#ifndef META_BEFONTIMAGE_H
#define META_BEFONTIMAGE_H
#include <meta/igBitmapFont.h>
namespace Meta {
struct beFontImage : igBitmapFont {
};
}
#endif
