// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beGeneraterPlayerData_register (metaobject lbl_805352CC, vtable lbl_804D67BC), size 0x18.
#ifndef META_BEGENERATERPLAYERDATA_H
#define META_BEGENERATERPLAYERDATA_H
#include <meta/igObject.h>
namespace Meta {
struct beGeneraterItemDataList;
struct beGeneraterPlayerData : igObject {
 int _geneCount;  // 0x08 igIntMetaField
 int _geneMaxCount;  // 0x0C igIntMetaField
 beGeneraterItemDataList *_itemDataList;  // 0x10 igObjectRefMetaField
 beGeneraterItemDataList *_itemLastDataList;  // 0x14 igObjectRefMetaField
};
}
#endif
