// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802D8368 (metaobject lbl_805352EC, vtable lbl_804D6540), size 0x14.
#ifndef META_BEGENERATERITEMDATAONELIST_H
#define META_BEGENERATERITEMDATAONELIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beGeneraterItemDataOneList : igObjectList {
};
}
#endif
