// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beGeneraterData_register (metaobject lbl_80535294, vtable lbl_804D695C), size 0x44.
#ifndef META_BEGENERATERDATA_H
#define META_BEGENERATERDATA_H
#include <meta/igNamedObject.h>
namespace Meta {
struct beGeneraterPlayerDataList;
struct igFloatList;
struct igVec3fList;
struct beGeneraterData : igNamedObject {
 float _pos[3];  // 0x0C igVec3fMetaField
 bool _genePosIsGlobal;  // 0x18 igBoolMetaField
 unsigned char unknown19[3];
 igVec3fList *_genePosList;  // 0x1C igObjectRefMetaField
 igFloatList *_geneRotYRadianList;  // 0x20 igObjectRefMetaField
 int _geneEnemyId;  // 0x24 igIntMetaField
 const char *_geneEnemySeq;  // 0x28 igStringMetaField
 const char *_startModeStr;  // 0x2C igStringMetaField
 float _startData;  // 0x30 igFloatMetaField
 const char *_fillModeStr;  // 0x34 igStringMetaField
 float _fillData;  // 0x38 igFloatMetaField
 const char *_callLua;  // 0x3C igStringMetaField
 beGeneraterPlayerDataList *_playerDataList;  // 0x40 igObjectRefMetaField
};
}
#endif
