// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beGeneraterItemDataOne_register (metaobject lbl_805352F0, vtable lbl_804D6484), size 0x18.
#ifndef META_BEGENERATERITEMDATAONE_H
#define META_BEGENERATERITEMDATAONE_H
#include <meta/igNamedObject.h>
namespace Meta {
struct beGeneraterItemDataOne : igNamedObject {
 int _id;  // 0x0C igIntMetaField
 int _rank;  // 0x10 igIntMetaField
 int _rate;  // 0x14 igIntMetaField
};
}
#endif
