// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802D7EFC (metaobject lbl_805352E0, vtable lbl_804D66E0), size 0x14.
#ifndef META_BEGENERATERITEMDATALIST_H
#define META_BEGENERATERITEMDATALIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beGeneraterItemDataList : igObjectList {
};
}
#endif
