// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beGenerater_register (metaobject lbl_80535304, vtable lbl_804DE17C), size 0x28.
#ifndef META_BEGENERATER_H
#define META_BEGENERATER_H
#include <meta/beBaseInfoManager.h>
namespace Meta {
struct beLua;
struct beGenerater : beBaseInfoManager {
 beLua *_luaManager;  // 0x20 igObjectRefMetaField
 bool _isPerfectDrop;  // 0x24 igBoolMetaField
 unsigned char unknown25[3];
};
}
#endif
