// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beGroupKeepList_register (metaobject lbl_80535250, vtable lbl_804D6D78), size 0x14.
#ifndef META_BEGROUPKEEPLIST_H
#define META_BEGROUPKEEPLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beGroupKeepList : igObjectList {
};
}
#endif
