// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beGroupKeep_register (metaobject lbl_80535254, vtable lbl_804D6C84), size 0x20.
#ifndef META_BEGROUPKEEP_H
#define META_BEGROUPKEEP_H
#include <meta/igGroup.h>
namespace Meta {
struct beGroupKeep : igGroup {
};
}
#endif
