// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beHitLandDelivInfoRam_register (metaobject lbl_8053521C, vtable lbl_804D6EEC), size 0x68.
#ifndef META_BEHITLANDDELIVINFORAM_H
#define META_BEHITLANDDELIVINFORAM_H
#include <meta/beBaseInfoRam.h>
namespace Meta {
struct igTransform;
struct beHitLandDelivInfoRam : beBaseInfoRam {
 igTransform *_transform;  // 0x2C igObjectRefMetaField
 int _checkFlag;  // 0x30 igIntMetaField
 float _halfWidth;  // 0x34 igFloatMetaField
 float _upRange;  // 0x38 igFloatMetaField
 float _downRange;  // 0x3C igFloatMetaField
 float _pos[3];  // 0x40 igVec3fMetaField
 float _oldPos[3];  // 0x4C igVec3fMetaField
 float _landPos[3];  // 0x58 igVec3fMetaField
 bool _landPosOK;  // 0x64 igBoolMetaField
 unsigned char unknown65[3];
};
}
#endif
