// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beHitLandResultDataList_register (metaobject lbl_8053520C, vtable lbl_804D7018), size 0x14.
#ifndef META_BEHITLANDRESULTDATALIST_H
#define META_BEHITLANDRESULTDATALIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beHitLandResultDataList : igObjectList {
};
}
#endif
