// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802D5B48 (metaobject lbl_80535210, vtable lbl_804D6F5C), size 0x58.
#ifndef META_BEHITLANDRESULTDATA_H
#define META_BEHITLANDRESULTDATA_H
#include <meta/igObject.h>
namespace Meta {
struct beHitLandResultData : igObject {
 const char *_infoName;  // 0x08 igStringMetaField
 int _ramNo;  // 0x0C igIntMetaField
 unsigned char unknown10[72];
};
}
#endif
