// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802D6180 (metaobject lbl_80535244, vtable lbl_804D6E6C), size 0x1C.
#ifndef META_BEHITLANDDELIVINFO_H
#define META_BEHITLANDDELIVINFO_H
#include <meta/beBaseInfo.h>
namespace Meta {
struct beHitLandDelivInfo : beBaseInfo {
};
}
#endif
