// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802D460C (metaobject lbl_805351A8, vtable lbl_804D7250), size 0x2C.
#ifndef META_BEHITLANDMODELINFORAM_H
#define META_BEHITLANDMODELINFORAM_H
#include <meta/beBaseInfoRam.h>
namespace Meta {
struct beHitLandModelInfoRam : beBaseInfoRam {
};
}
#endif
