// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beHitLandModelTraversal_register (metaobject lbl_805351DC, vtable lbl_804D7134), size 0x48.
#ifndef META_BEHITLANDMODELTRAVERSAL_H
#define META_BEHITLANDMODELTRAVERSAL_H
#include <meta/igIntersectTraversal.h>
namespace Meta {
struct beHitLandModelOrder;
struct beHitLandModelTraversal : igIntersectTraversal {
 beHitLandModelOrder *_order;  // 0x40 igObjectRefMetaField
 unsigned char unknown44[4];
};
}
#endif
