// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beKeyboardReceiver_register (metaobject lbl_805351A0, vtable lbl_804DE500), size 0xC.
#ifndef META_BEKEYBOARDRECEIVER_H
#define META_BEKEYBOARDRECEIVER_H
#include <meta/igEventReceiver.h>
namespace Meta {
struct igBoolList;
struct beKeyboardReceiver : igEventReceiver {
 igBoolList *_keyboard;  // 0x08 igObjectRefMetaField
};
}
#endif
