// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802D3BFC (metaobject lbl_80535168, vtable lbl_804DE618), size 0x28.
#ifndef META_BELAYERCTL_H
#define META_BELAYERCTL_H
#include <meta/beBaseInfoManager.h>
namespace Meta {
struct igSwitch;
struct beLayerCtl : beBaseInfoManager {
 bool _isOrdered;  // 0x20 igBoolMetaField
 unsigned char unknown21[3];
 igSwitch *_layerSwt;  // 0x24 igObjectRefMetaField
};
}
#endif
