// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beLayerInfoRam_register (metaobject lbl_8053514C, vtable lbl_804D75B8), size 0x2C.
#ifndef META_BELAYERINFORAM_H
#define META_BELAYERINFORAM_H
#include <meta/beBaseInfoRam.h>
namespace Meta {
struct beLayerInfoRam : beBaseInfoRam {
};
}
#endif
