// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beLayerInfo_register (metaobject lbl_80535150, vtable lbl_804D7538), size 0x20.
#ifndef META_BELAYERINFO_H
#define META_BELAYERINFO_H
#include <meta/beBaseInfo.h>
namespace Meta {
struct beLayerGroupList;
struct beLayerInfo : beBaseInfo {
 beLayerGroupList *_groups;  // 0x1C igObjectRefMetaField
};
}
#endif
