// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beLayerGroup_register (metaobject lbl_8053515C, vtable lbl_804D7388), size 0xC.
#ifndef META_BELAYERGROUP_H
#define META_BELAYERGROUP_H
#include <meta/igNamedObject.h>
namespace Meta {
struct beLayerGroup : igNamedObject {
};
}
#endif
