// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beLightCtrl_register (metaobject lbl_80535148, vtable lbl_804E1340), size 0x20.
#ifndef META_BELIGHTCTRL_H
#define META_BELIGHTCTRL_H
#include <meta/beBaseInfoManager.h>
namespace Meta {
struct beLightCtrl : beBaseInfoManager {
};
}
#endif
