// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80341618 (metaobject lbl_805366D4, vtable lbl_804E4CC0), size 0x14.
#ifndef META_BELOADINTF2COMMDLDATALIST_H
#define META_BELOADINTF2COMMDLDATALIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beLoadIntf2ComMdlDataList : igObjectList {
};
}
#endif
