// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80341830 (metaobject lbl_805366D8, vtable lbl_804E4C04), size 0x14.
#ifndef META_BELOADINTF2COMMDLDATA_H
#define META_BELOADINTF2COMMDLDATA_H
#include <meta/igObject.h>
namespace Meta {
struct beLoadIntf2ComMdlData : igObject {
 int _ramNo;  // 0x08 igIntMetaField
 const char *_openSQ;  // 0x0C igStringMetaField
 const char *_infoName;  // 0x10 igStringMetaField
};
}
#endif
