// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beLoadingNode_register (metaobject lbl_80534B94, vtable lbl_804DA0C8), size 0x80.
#ifndef META_BELOADINGNODE_H
#define META_BELOADINGNODE_H
#include <meta/beNodeAnim.h>
namespace Meta {
struct beLoadingNode : beNodeAnim {
 long long _lockTime;  // 0x70 igLongMetaField
 long long _playLimitTime;  // 0x78 igLongMetaField
};
}
#endif
