// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802D26CC (metaobject lbl_80535124, vtable lbl_804DE70C), size 0x20.
#ifndef META_BELUA_H
#define META_BELUA_H
#include <meta/igInfoManager.h>
namespace Meta {
struct beBaseInfoList;
struct beLuaState;
struct beSystem;
struct igLuaGlue;
struct beLua : igInfoManager {
 beSystem *_system;  // 0x10 igObjectRefMetaField
 beBaseInfoList *_infoList;  // 0x14 igObjectRefMetaField
 beLuaState *_luaState;  // 0x18 igObjectRefMetaField
 igLuaGlue *_luaGlue;  // 0x1C igObjectRefMetaField
};
}
#endif
