// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802D216C (metaobject lbl_80535114, vtable lbl_804D789C), size 0x14.
#ifndef META_BELUADATAOBJECTIST_H
#define META_BELUADATAOBJECTIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beLuaDataObjectist : igObjectList {
};
}
#endif
