// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802D1F48 (metaobject lbl_8053510C, vtable lbl_804D7980), size 0x10.
#ifndef META_BELUADATA_H
#define META_BELUADATA_H
#include <meta/igNamedObject.h>
namespace Meta {
struct beLuaDataObject;
struct beLuaData : igNamedObject {
 beLuaDataObject *_dataObject;  // 0x0C igObjectRefMetaField
};
}
#endif
