// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beLuaState_register (metaobject lbl_805350F8, vtable lbl_804DE7E4), size 0x18.
#ifndef META_BELUASTATE_H
#define META_BELUASTATE_H
#include <meta/igLuaState.h>
namespace Meta {
struct beLuaState : igLuaState {
 void *_lp;  // 0x14 igRawRefMetaField
};
}
#endif
