// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802D0FE8 (metaobject lbl_805350C4, vtable lbl_804D7BB0), size 0x10.
#ifndef META_BEMATCTRLDATA_H
#define META_BEMATCTRLDATA_H
#include <meta/igNamedObject.h>
namespace Meta {
struct igAABox;
struct beMatCtrlData : igNamedObject {
 igAABox *_chkBox;  // 0x0C igObjectRefMetaField
};
}
#endif
