// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beMatCtrl_register (metaobject lbl_805350D0, vtable lbl_804DE8E4), size 0x44.
// Note: _wkPlExist: igBoolArrayMetaField, count from the space to the next member.
#ifndef META_BEMATCTRL_H
#define META_BEMATCTRL_H
#include <meta/beBaseInfoManager.h>
namespace Meta {
struct beLua;
struct igIntList;
struct beMatCtrl : beBaseInfoManager {
 bool _wkPlExist[4];  // 0x20 igBoolArrayMetaField
 beLua *_lua;  // 0x24 igObjectRefMetaField
 int _wkChkMat;  // 0x28 igIntMetaField
 int _wkChkPl;  // 0x2C igIntMetaField
 int _wkChgFlagNO;  // 0x30 igIntMetaField
 bool _wkChgFlag;  // 0x34 igBoolMetaField
 unsigned char unknown35[3];
 igIntList *_wkMatOnList;  // 0x38 igObjectRefMetaField
 igIntList *_wkMatOldOnList;  // 0x3C igObjectRefMetaField
 bool _isLuaCallDisp;  // 0x40 igBoolMetaField
 unsigned char unknown41[3];
};
}
#endif
