// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802D0B58 (metaobject lbl_805350A8, vtable lbl_804D7D48), size 0x1C.
#ifndef META_BEMATCTRLSEARCH_H
#define META_BEMATCTRLSEARCH_H
#include <meta/igObject.h>
namespace Meta {
struct beMatCtrlSearchList;
struct beMatCtrlSearch : igObject {
 float _minX;  // 0x08 igFloatMetaField
 float _maxX;  // 0x0C igFloatMetaField
 int _matNO;  // 0x10 igIntMetaField
 beMatCtrlSearch *_parent;  // 0x14 igObjectRefMetaField
 beMatCtrlSearchList *_memberList;  // 0x18 igObjectRefMetaField
};
}
#endif
