// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802CD218 (metaobject lbl_80534F5C, vtable lbl_804D8908), size 0x34.
#ifndef META_BEMETERCTRLNODE_H
#define META_BEMETERCTRLNODE_H
#include <meta/igGroup.h>
namespace Meta {
struct igLongList;
struct beMeterCtrlNode : igGroup {
 bool _isMeter;  // 0x20 igBoolMetaField
 unsigned char unknown21[3];
 igLongList *_timeList;  // 0x24 igObjectRefMetaField
 float _numberOffset[3];  // 0x28 igVec3fMetaField
};
}
#endif
