// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802CEFD4 (metaobject lbl_80535014, vtable lbl_804D82AC), size 0x14.
#ifndef META_BEMESSENGERDELAYLIST_H
#define META_BEMESSENGERDELAYLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beMessengerDelayList : igObjectList {
};
}
#endif
