// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beMeterCtrl_register (metaobject lbl_80534FB8, vtable lbl_804DEB08), size 0x20.
#ifndef META_BEMETERCTRL_H
#define META_BEMETERCTRL_H
#include <meta/beBaseInfoManager.h>
namespace Meta {
struct beMeterCtrl : beBaseInfoManager {
};
}
#endif
