// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beMessengerGroupList_register (metaobject lbl_80535000, vtable lbl_804D844C), size 0x14.
#ifndef META_BEMESSENGERGROUPLIST_H
#define META_BEMESSENGERGROUPLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beMessengerGroupList : igObjectList {
};
}
#endif
