// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802CFCAC (metaobject lbl_80535068, vtable lbl_804E123C), size 0x24.
#ifndef META_BEMEMORY_H
#define META_BEMEMORY_H
#include <meta/igInfoManager.h>
namespace Meta {
struct beMessenger;
struct bePadManager;
struct beMemory : igInfoManager {
 beMessenger *_messenger;  // 0x10 igObjectRefMetaField
 bePadManager *_padManager;  // 0x14 igObjectRefMetaField
 bool _isDisp;  // 0x18 igBoolMetaField
 unsigned char unknown19[3];
 int _colorIndex;  // 0x1C igIntMetaField
 int _updateCount;  // 0x20 igIntMetaField
};
}
#endif
