// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beMessengerWorkList_register (metaobject lbl_80534FE0, vtable lbl_804D85E4), size 0x14.
#ifndef META_BEMESSENGERWORKLIST_H
#define META_BEMESSENGERWORKLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beMessengerWorkList : igObjectList {
};
}
#endif
