// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802C7228 (metaobject lbl_80534D30, vtable lbl_804DEC6C), size 0x78.
#ifndef META_BEMODELCTRLINFORIDEON4_H
#define META_BEMODELCTRLINFORIDEON4_H
#include <meta/beModelCtrlInfoRideOn.h>
namespace Meta {
struct beModelCtrlInfoRideOn4 : beModelCtrlInfoRideOn {
 float _oldPlayerPos[3];  // 0x54 igVec3fMetaField
 float _vector[3];  // 0x60 igVec3fMetaField
 float _scalar;  // 0x6C igFloatMetaField
 float _limitter;  // 0x70 igFloatMetaField
 int _isFirst;  // 0x74 igIntMetaField
};
}
#endif
