// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802CC3DC (metaobject lbl_80534F28, vtable lbl_804D8C48), size 0x10.
#ifndef META_BEMODELCTRLLABELCTRL_H
#define META_BEMODELCTRLLABELCTRL_H
#include <meta/igNamedObject.h>
namespace Meta {
struct beModelCtrlLABELCTRL : igNamedObject {
 const char *_seqName;  // 0x0C igStringMetaField
};
}
#endif
