// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802CCE38 (metaobject lbl_80534F4C), size 0x2C.
#ifndef META_BEMODELCTRL_H
#define META_BEMODELCTRL_H
#include <meta/beBaseInfoManager.h>
namespace Meta {
struct beLua;
struct beTargetObj;
struct beModelCtrl : beBaseInfoManager {
 beLua *_luaManager;  // 0x20 igObjectRefMetaField
 beTargetObj *_targetObj;  // 0x24 igObjectRefMetaField
 bool _isDebugHitBox;  // 0x28 igBoolMetaField
 unsigned char unknown29[3];
};
}
#endif
