// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802C5CE0 (metaobject lbl_80534C40), size 0x14.
#ifndef META_BEMODELCTRLSUBCOMBASE_H
#define META_BEMODELCTRLSUBCOMBASE_H
#include <meta/igObject.h>
namespace Meta {
struct beModelCtrlSubComBase : igObject {
 bool _isOneSet;  // 0x08 igBoolMetaField
 unsigned char unknown09[3];
 float _runFrame;  // 0x0C igFloatMetaField
 float _startFrame;  // 0x10 igFloatMetaField
};
}
#endif
