// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beModelCtrlSCSound_register (metaobject lbl_80534BF8, vtable lbl_804DEF48), size 0x20.
#ifndef META_BEMODELCTRLSCSOUND_H
#define META_BEMODELCTRLSCSOUND_H
#include <meta/beModelCtrlSubComBase.h>
namespace Meta {
struct beModelCtrlSCSound : beModelCtrlSubComBase {
 const char *_sndName;  // 0x14 igStringMetaField
 long long _sndHandle;  // 0x18 igLongMetaField
};
}
#endif
