// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802C6C7C (metaobject lbl_80534C64, vtable lbl_804D9D3C), size 0xEC.
#ifndef META_BEMODELCTRLINFOWORK_H
#define META_BEMODELCTRLINFOWORK_H
#include <meta/igObject.h>
namespace Meta {
struct beDataObjInt;
struct beModelCtrlData;
struct beModelCtrlInfoAI;
struct beModelCtrlInfoDataTrc;
struct beModelCtrlInfoHitBody;
struct beModelCtrlInfoRideOn;
struct beModelCtrlMoveObjectList;
struct beModelCtrlNode2;
struct beModelCtrlSubCom;
struct igAABox;
struct igFloatList;
struct igGroup;
struct igIntList;
struct igStringRefList;
struct beModelCtrlInfoWork : igObject {
 beDataObjInt *_mHp;  // 0x08 igObjectRefMetaField
 beDataObjInt *_hp;  // 0x0C igObjectRefMetaField
 int _recNo;  // 0x10 igIntMetaField
 const char *_seqCodeName;  // 0x14 igStringMetaField
 beModelCtrlData *_comData;  // 0x18 igObjectRefMetaField
 int _comIndex;  // 0x1C igIntMetaField
 int _comLabelCount;  // 0x20 igIntMetaField
 igStringRefList *_labelSeqList;  // 0x24 igObjectRefMetaField
 igStringRefList *_labelNameList;  // 0x28 igObjectRefMetaField
 igIntList *_labelOffsetList;  // 0x2C igObjectRefMetaField
 const char *_luaBHit;  // 0x30 igStringMetaField
 const char *_luaWHit;  // 0x34 igStringMetaField
 const char *_luaFHit;  // 0x38 igStringMetaField
 int _ctrlSt0;  // 0x3C igIntMetaField
 int _ctrlSt1;  // 0x40 igIntMetaField
 bool _isOnCtrl;  // 0x44 igBoolMetaField
 bool _isOnFreeze;  // 0x45 igBoolMetaField
 unsigned char unknown46[2];
 igFloatList *_pdMoveDataList;  // 0x48 igObjectRefMetaField
 const char *_wCheckName;  // 0x4C igStringMetaField
 beModelCtrlInfoAI *_aI;  // 0x50 igObjectRefMetaField
 float _aIHOffsetY;  // 0x54 igFloatMetaField
 const char *_targetMode;  // 0x58 igStringMetaField
 const char *_targetKind;  // 0x5C igStringMetaField
 const char *_targetSpc1;  // 0x60 igStringMetaField
 float _targetPos[3];  // 0x64 igVec3fMetaField
 bool _keyInput;  // 0x70 igBoolMetaField
 unsigned char unknown71[3];
 const char *_keyEventName;  // 0x74 igStringMetaField
 bool _isHitCheck;  // 0x78 igBoolMetaField
 unsigned char unknown79[3];
 float _mutekiCount;  // 0x7C igFloatMetaField
 float _targetDirection[3];  // 0x80 igVec3fMetaField
 float _directionLimiter[3];  // 0x8C igVec3fMetaField
 float _direction[3];  // 0x98 igVec3fMetaField
 float _svLODHighRange;  // 0xA4 igFloatMetaField
 bool _isPosLock;  // 0xA8 igBoolMetaField
 unsigned char unknownA9[3];
 beModelCtrlNode2 *_posLockNode;  // 0xAC igObjectRefMetaField
 beModelCtrlInfoDataTrc *_posLockTrc;  // 0xB0 igObjectRefMetaField
 const char *_posLockModelName;  // 0xB4 igStringMetaField
 const char *_posLockBoneName;  // 0xB8 igStringMetaField
 float _posLockOffset[3];  // 0xBC igVec3fMetaField
 beModelCtrlMoveObjectList *_moveObjectList;  // 0xC8 igObjectRefMetaField
 beModelCtrlInfoRideOn *_rideOnData;  // 0xCC igObjectRefMetaField
 igGroup *_debugHitBoxNode;  // 0xD0 igObjectRefMetaField
 beModelCtrlInfoHitBody *_hitBody;  // 0xD4 igObjectRefMetaField
 bool _isWallCheck;  // 0xD8 igBoolMetaField
 bool _isFloorCheck;  // 0xD9 igBoolMetaField
 bool _isFallCheck;  // 0xDA igBoolMetaField
 unsigned char unknownDB[1];
 const char *_hitParentName;  // 0xDC igStringMetaField
 int _hitParentRamNo;  // 0xE0 igIntMetaField
 beModelCtrlSubCom *_subCommand;  // 0xE4 igObjectRefMetaField
 igAABox *_baseAABox;  // 0xE8 igObjectRefMetaField
};
}
#endif
