// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beModelCtrlInfoRideOn_register (metaobject lbl_80534D74, vtable lbl_804D9CC8), size 0x54.
#ifndef META_BEMODELCTRLINFORIDEON_H
#define META_BEMODELCTRLINFORIDEON_H
#include <meta/igObject.h>
namespace Meta {
struct beModelCtrlNode2;
struct beModelCtrlInfoRideOn : igObject {
 const char *_modelName;  // 0x08 igStringMetaField
 int _modelRamNo;  // 0x0C igIntMetaField
 beModelCtrlNode2 *_modelNode;  // 0x10 igObjectRefMetaField
 float _oldMatrix[16];  // 0x14 igMatrix44fMetaField
};
}
#endif
