// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beModelCtrlMoveObjectList_register (metaobject lbl_80534DC0, vtable lbl_804D9B0C), size 0x14.
#ifndef META_BEMODELCTRLMOVEOBJECTLIST_H
#define META_BEMODELCTRLMOVEOBJECTLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beModelCtrlMoveObjectList : igObjectList {
};
}
#endif
