// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802C53E8 (metaobject lbl_80534BF0, vtable lbl_804D9EFC), size 0xC.
#ifndef META_BEMODELCTRLSUBCOM_H
#define META_BEMODELCTRLSUBCOM_H
#include <meta/igObject.h>
namespace Meta {
struct igObjectList;
struct beModelCtrlSubCom : igObject {
 igObjectList *_comList;  // 0x08 igObjectRefMetaField
};
}
#endif
