// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beModelCtrlInfoRideOn3_register (metaobject lbl_80534D4C, vtable lbl_804DECE8), size 0x70.
#ifndef META_BEMODELCTRLINFORIDEON3_H
#define META_BEMODELCTRLINFORIDEON3_H
#include <meta/beModelCtrlInfoRideOn.h>
namespace Meta {
struct beModelCtrlInfoRideOn3 : beModelCtrlInfoRideOn {
 float _worldPosition[3];  // 0x54 igVec3fMetaField
 float _minSpeed;  // 0x60 igFloatMetaField
 float _maxSpeed;  // 0x64 igFloatMetaField
 float _minKyori;  // 0x68 igFloatMetaField
 float _maxKyori;  // 0x6C igFloatMetaField
};
}
#endif
