// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802CC7E4 (metaobject lbl_80534F34, vtable lbl_804D8B58), size 0x10.
#ifndef META_BEMODELCTRLLUACALL_H
#define META_BEMODELCTRLLUACALL_H
#include <meta/igNamedObject.h>
namespace Meta {
struct beModelCtrlLUACALL : igNamedObject {
 const char *_modeName;  // 0x0C igStringMetaField
};
}
#endif
