// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beMovieInfo_register (metaobject lbl_80534BCC, vtable lbl_804DA004), size 0x1C.
#ifndef META_BEMOVIEINFO_H
#define META_BEMOVIEINFO_H
#include <meta/beBaseInfo.h>
namespace Meta {
struct beMovieInfo : beBaseInfo {
};
}
#endif
