// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802CB270 (metaobject lbl_80534ED4, vtable lbl_804D9080), size 0xC.
#ifndef META_BEMODELCTRLWCHECK_H
#define META_BEMODELCTRLWCHECK_H
#include <meta/igNamedObject.h>
namespace Meta {
struct beModelCtrlWCHECK : igNamedObject {
};
}
#endif
