// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802CC9E0 (metaobject lbl_80534F3C, vtable lbl_804D8A74), size 0x14.
#ifndef META_BEMODELCTRLDATALIST_H
#define META_BEMODELCTRLDATALIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beModelCtrlDataList : igObjectList {
};
}
#endif
