// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beModelCtrlInfoDataAIH_register (metaobject lbl_80534E38, vtable lbl_804D9628), size 0x2C.
#ifndef META_BEMODELCTRLINFODATAAIH_H
#define META_BEMODELCTRLINFODATAAIH_H
#include <meta/beBaseInfoData.h>
namespace Meta {
struct beModelCtrlInfoDataAIH : beBaseInfoData {
 bool _isXHoming;  // 0x10 igBoolMetaField
 bool _isYHoming;  // 0x11 igBoolMetaField
 unsigned char unknown12[2];
 float _firstFrame;  // 0x14 igFloatMetaField
 float _secondFrame;  // 0x18 igFloatMetaField
 float _areaSquare;  // 0x1C igFloatMetaField
 float _limitRotX;  // 0x20 igFloatMetaField
 float _limitRotY;  // 0x24 igFloatMetaField
 int _limitCount;  // 0x28 igIntMetaField
};
}
#endif
