// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802C78C8 (metaobject lbl_80534D68, vtable lbl_804DED64), size 0x60.
#ifndef META_BEMODELCTRLINFORIDEON2_H
#define META_BEMODELCTRLINFORIDEON2_H
#include <meta/beModelCtrlInfoRideOn.h>
namespace Meta {
struct beModelCtrlInfoRideOn2 : beModelCtrlInfoRideOn {
 float _vector[3];  // 0x54 igVec3fMetaField
};
}
#endif
