// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802C8BD4 (metaobject lbl_80534DF0, vtable lbl_804D98B0), size 0x20.
#ifndef META_BEMODELCTRLINFO_H
#define META_BEMODELCTRLINFO_H
#include <meta/beBaseInfo.h>
namespace Meta {
struct beModelCtrlInfo : beBaseInfo {
 const char *_kindString;  // 0x1C igStringMetaField
};
}
#endif
