// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802CBEC0 (metaobject lbl_80534F1C, vtable lbl_804D8DB0), size 0xC.
#ifndef META_BEMODELCTRLCTRL_H
#define META_BEMODELCTRLCTRL_H
#include <meta/igNamedObject.h>
namespace Meta {
struct beModelCtrlCTRL : igNamedObject {
};
}
#endif
