// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802CA2A8 (metaobject lbl_80534E6C, vtable lbl_804D94BC), size 0x14.
#ifndef META_BEMODELCTRLAIMAPLIST_H
#define META_BEMODELCTRLAIMAPLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beModelCtrlAIMapList : igObjectList {
};
}
#endif
