// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beModelCtrlInfoList_register (metaobject lbl_80534DEC, vtable lbl_804D9974), size 0x14.
#ifndef META_BEMODELCTRLINFOLIST_H
#define META_BEMODELCTRLINFOLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beModelCtrlInfoList : igObjectList {
};
}
#endif
