// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802CB40C (metaobject lbl_80534ED8, vtable lbl_804D9008), size 0x14.
#ifndef META_BEMODELCTRLPDMOVE_H
#define META_BEMODELCTRLPDMOVE_H
#include <meta/igNamedObject.h>
namespace Meta {
struct beModelCtrlPDMOVE : igNamedObject {
 float _value;  // 0x0C igFloatMetaField
 float _frame;  // 0x10 igFloatMetaField
};
}
#endif
