// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beModelCtrlLABEL_register (metaobject lbl_80534F30, vtable lbl_804D8BD0), size 0xC.
#ifndef META_BEMODELCTRLLABEL_H
#define META_BEMODELCTRLLABEL_H
#include <meta/igNamedObject.h>
namespace Meta {
struct beModelCtrlLABEL : igNamedObject {
};
}
#endif
