// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beModelCtrlInfoRamData_register (metaobject lbl_80534DF8, vtable lbl_804D9828), size 0x18.
#ifndef META_BEMODELCTRLINFORAMDATA_H
#define META_BEMODELCTRLINFORAMDATA_H
#include <meta/beBaseInfoData.h>
namespace Meta {
struct beModelCtrlInfoWork;
struct beModelCtrlNode2;
struct beModelCtrlInfoRamData : beBaseInfoData {
 beModelCtrlNode2 *_node;  // 0x10 igObjectRefMetaField
 beModelCtrlInfoWork *_work;  // 0x14 igObjectRefMetaField
};
}
#endif
