// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802CAC8C (metaobject lbl_80534EB0, vtable lbl_804D91E8), size 0x30.
#ifndef META_BEMODELCTRLHITBOX_H
#define META_BEMODELCTRLHITBOX_H
#include <meta/igNamedObject.h>
namespace Meta {
struct beModelCtrlHITBOX : igNamedObject {
 int _kind;  // 0x0C igIntMetaField
 float _start;  // 0x10 igFloatMetaField
 float _length;  // 0x14 igFloatMetaField
 float _offset[3];  // 0x18 igVec3fMetaField
 float _boxSize[3];  // 0x24 igVec3fMetaField
};
}
#endif
