// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802CC05C (metaobject lbl_80534F20, vtable lbl_804D8D38), size 0xC.
#ifndef META_BEMODELCTRLJUMP_H
#define META_BEMODELCTRLJUMP_H
#include <meta/igNamedObject.h>
namespace Meta {
struct beModelCtrlJUMP : igNamedObject {
};
}
#endif
