// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWStatusTitle03_register (metaobject lbl_80535D50, vtable lbl_804EC524), size 0x50.
#ifndef META_BENDMWSTATUSTITLE03_H
#define META_BENDMWSTATUSTITLE03_H
#include <meta/beNDMWWindowTitle.h>
namespace Meta {
struct beNDMWStatusTitle03 : beNDMWWindowTitle {
};
}
#endif
