// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8033D874 (metaobject lbl_8053644C, vtable lbl_804E5A8C), size 0x14.
#ifndef META_BENDMWLOADINTF2DEGISTATECTRL_H
#define META_BENDMWLOADINTF2DEGISTATECTRL_H
#include <meta/beBaseInfoData.h>
namespace Meta {
struct beNDMWLoadIntf2DegiStateList;
struct beNDMWLoadIntf2DegiStateCtrl : beBaseInfoData {
 beNDMWLoadIntf2DegiStateList *_statDataList;  // 0x10 igObjectRefMetaField
};
}
#endif
