// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80340B34 (metaobject lbl_80536634, vtable lbl_804E4E9C), size 0x4C.
// Note: _dmNameUni: igUnsignedShortArrayMetaField, count from the space to the next member.
#ifndef META_BENDMWDEGIDATA_H
#define META_BENDMWDEGIDATA_H
#include <meta/igObject.h>
namespace Meta {
struct igInsightCore;
struct beNDMWDegiData : igObject {
 unsigned short _dmNameUni[10];  // 0x08 igUnsignedShortArrayMetaField
 void *_data;  // 0x1C igMemoryRefMetaField
 igInsightCore *_insight;  // 0x20 igObjectRefMetaField
 int _dataSize;  // 0x24 igIntMetaField
 bool _isUse;  // 0x28 igBoolMetaField
 unsigned char unknown29[3];
 int _id;  // 0x2C igIntMetaField
 const char *_dmkind;  // 0x30 igStringMetaField
 const char *_dmName;  // 0x34 igStringMetaField
 int _lv;  // 0x38 igIntMetaField
 int _hp;  // 0x3C igIntMetaField
 int _maxHp;  // 0x40 igIntMetaField
 int _mp;  // 0x44 igIntMetaField
 int _maxMp;  // 0x48 igIntMetaField
};
}
#endif
