// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWStatusTitle01_register (metaobject lbl_80535D58, vtable lbl_804EC634), size 0x50.
#ifndef META_BENDMWSTATUSTITLE01_H
#define META_BENDMWSTATUSTITLE01_H
#include <meta/beNDMWWindowTitle.h>
namespace Meta {
struct beNDMWStatusTitle01 : beNDMWWindowTitle {
};
}
#endif
