// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWShopCtrlDiskSell_register (metaobject lbl_80535E14, vtable lbl_804ECBBC), size 0x68.
#ifndef META_BENDMWSHOPCTRLDISKSELL_H
#define META_BENDMWSHOPCTRLDISKSELL_H
#include <meta/beNDMWWindowCtrl.h>
namespace Meta {
struct igIntList;
struct beNDMWShopCtrlDiskSell : beNDMWWindowCtrl {
 igIntList *_diskIdList;  // 0x54 igObjectRefMetaField
 int _cursor;  // 0x58 igIntMetaField
 int _maxSell;  // 0x5C igIntMetaField
 int _kazu;  // 0x60 igIntMetaField
 int _tanka;  // 0x64 igIntMetaField
};
}
#endif
