// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWStatusSelectE0_register (metaobject lbl_80535D94, vtable lbl_804EC224), size 0x70.
#ifndef META_BENDMWSTATUSSELECTE0_H
#define META_BENDMWSTATUSSELECTE0_H
#include <meta/beNDMWWindowSelect.h>
namespace Meta {
struct beNDMWStatusSelectE0 : beNDMWWindowSelect {
};
}
#endif
