// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWWindow_register (metaobject lbl_80535C80), size 0x50.
#ifndef META_BENDMWWINDOW_H
#define META_BENDMWWINDOW_H
#include <meta/igObject.h>
namespace Meta {
struct beMessenger;
struct beNDMWWindowList;
struct bePadManager;
struct igInsightCore;
struct igIntList;
struct igStringRefList;
struct beNDMWWindow : igObject {
 igInsightCore *_insight;  // 0x08 igObjectRefMetaField
 beMessenger *_messenger;  // 0x0C igObjectRefMetaField
 bePadManager *_padManager;  // 0x10 igObjectRefMetaField
 int _playerNo;  // 0x14 igIntMetaField
 bool _isRun;  // 0x18 igBoolMetaField
 unsigned char unknown19[3];
 int _st0;  // 0x1C igIntMetaField
 int _st1;  // 0x20 igIntMetaField
 int _st2;  // 0x24 igIntMetaField
 int _st3;  // 0x28 igIntMetaField
 int _entCode;  // 0x2C igIntMetaField
 int _retCode;  // 0x30 igIntMetaField
 beNDMWWindowList *_subWindow;  // 0x34 igObjectRefMetaField
 beNDMWWindow *_mother;  // 0x38 igObjectRefMetaField
 igStringRefList *_textCloseTypeList;  // 0x3C igObjectRefMetaField
 igStringRefList *_textCloseNameList;  // 0x40 igObjectRefMetaField
 igStringRefList *_modelCloseInfoNameList;  // 0x44 igObjectRefMetaField
 igIntList *_modelCloseRamNoList;  // 0x48 igObjectRefMetaField
 igStringRefList *_modelCloseSeqNameList;  // 0x4C igObjectRefMetaField
};
}
#endif
