// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWStatusCtrlDisk_register (metaobject lbl_80535F04, vtable lbl_804EBA84), size 0x6C.
#ifndef META_BENDMWSTATUSCTRLDISK_H
#define META_BENDMWSTATUSCTRLDISK_H
#include <meta/beNDMWWindowCtrl.h>
namespace Meta {
struct beNDMWItemBaseList;
struct beNDMWItemDisk;
struct igIntList;
struct beNDMWStatusCtrlDisk : beNDMWWindowCtrl {
 int _cursor;  // 0x54 igIntMetaField
 igIntList *_playerNoList;  // 0x58 igObjectRefMetaField
 int _receipt;  // 0x5C igIntMetaField
 beNDMWItemBaseList *_diskList;  // 0x60 igObjectRefMetaField
 beNDMWItemDisk *_sendDisk;  // 0x64 igObjectRefMetaField
 int _sendMax;  // 0x68 igIntMetaField
};
}
#endif
