// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWMdlEBullet_register (metaobject lbl_80536234, vtable lbl_804E74CC), size 0x2C.
#ifndef META_BENDMWMDLEBULLET_H
#define META_BENDMWMDLEBULLET_H
#include <meta/beModelCtrl.h>
namespace Meta {
struct beNDMWMdlEBullet : beModelCtrl {
};
}
#endif
