// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWLoadIntf2MakeChr_register (metaobject lbl_805364A0, vtable lbl_804E5874), size 0x3C.
// Note: _degiName: igCharArrayMetaField, count from the space to the next member.
#ifndef META_BENDMWLOADINTF2MAKECHR_H
#define META_BENDMWLOADINTF2MAKECHR_H
#include <meta/beBaseInfoData.h>
namespace Meta {
struct beNDMWLoadIntf2MakeChr : beBaseInfoData {
 char _degiName[32];  // 0x10 igCharArrayMetaField
 int _chaSelDegi;  // 0x30 igIntMetaField
 int _nameCur;  // 0x34 igIntMetaField
 int _mojiSelPoint;  // 0x38 igIntMetaField
};
}
#endif
