// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80342F10 (metaobject lbl_80536748, vtable lbl_804EE41C), size 0x18.
#ifndef META_BENDMWITEMYELLOWARMOR_H
#define META_BENDMWITEMYELLOWARMOR_H
#include <meta/beNDMWItemRevisionBase.h>
namespace Meta {
struct beNDMWItemYellowArmor : beNDMWItemRevisionBase {
};
}
#endif
