// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWStatusSelect00_register (metaobject lbl_80535D9C, vtable lbl_804EC334), size 0x70.
#ifndef META_BENDMWSTATUSSELECT00_H
#define META_BENDMWSTATUSSELECT00_H
#include <meta/beNDMWWindowSelect.h>
namespace Meta {
struct beNDMWStatusSelect00 : beNDMWWindowSelect {
};
}
#endif
