// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWShopSelectA0_register (metaobject lbl_80535D68, vtable lbl_804ED484), size 0x70.
#ifndef META_BENDMWSHOPSELECTA0_H
#define META_BENDMWSHOPSELECTA0_H
#include <meta/beNDMWWindowSelect.h>
namespace Meta {
struct beNDMWShopSelectA0 : beNDMWWindowSelect {
};
}
#endif
