// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80333D3C (metaobject lbl_80535F9C), size 0x60.
#ifndef META_BENDMWLISTCTRL_H
#define META_BENDMWLISTCTRL_H
#include <meta/beNDMWWindowCtrl.h>
namespace Meta {
struct beNDMWListCtrl : beNDMWWindowCtrl {
 int _nowPage;  // 0x54 igIntMetaField
 int _maxPage;  // 0x58 igIntMetaField
 int _cursor;  // 0x5C igIntMetaField
};
}
#endif
