// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWMcSlotList_register (metaobject lbl_805365E8, vtable lbl_804E53F0), size 0x14.
#ifndef META_BENDMWMCSLOTLIST_H
#define META_BENDMWMCSLOTLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beNDMWMcSlotList : igObjectList {
};
}
#endif
