// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWPanelWazaInfoWork_register (metaobject lbl_805360A4, vtable lbl_804E61B4), size 0x30.
#ifndef META_BENDMWPANELWAZAINFOWORK_H
#define META_BENDMWPANELWAZAINFOWORK_H
#include <meta/igObject.h>
namespace Meta {
struct beNDMWMdlPlayerInfoWork;
struct beNDMWPanelObjectItem;
struct beNDMWPanelObjectStat;
struct beNDMWPanelObjectWaza;
struct igIntList;
struct igStringRefList;
struct beNDMWPanelWazaInfoWork : igObject {
 int _page;  // 0x08 igIntMetaField
 bool _isWindowGenerate;  // 0x0C igBoolMetaField
 bool _isCursorGenerate;  // 0x0D igBoolMetaField
 unsigned char unknown0E[2];
 beNDMWPanelObjectWaza *_panelWaza;  // 0x10 igObjectRefMetaField
 beNDMWPanelObjectItem *_panelItem;  // 0x14 igObjectRefMetaField
 beNDMWPanelObjectStat *_panelStat;  // 0x18 igObjectRefMetaField
 bool _retIsFire;  // 0x1C igBoolMetaField
 unsigned char unknown1D[3];
 const char *_retWazaLabel;  // 0x20 igStringMetaField
 beNDMWMdlPlayerInfoWork *_playerWork;  // 0x24 igObjectRefMetaField
 igStringRefList *_textSetList;  // 0x28 igObjectRefMetaField
 igIntList *_textColorList;  // 0x2C igObjectRefMetaField
};
}
#endif
