// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWShopTitle00_register (metaobject lbl_80535D48, vtable lbl_804EDA38), size 0x50.
#ifndef META_BENDMWSHOPTITLE00_H
#define META_BENDMWSHOPTITLE00_H
#include <meta/beNDMWWindowTitle.h>
namespace Meta {
struct beNDMWShopTitle00 : beNDMWWindowTitle {
};
}
#endif
