// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8033E350 (metaobject lbl_805364B8, vtable lbl_804E57F4), size 0x34.
#ifndef META_BENDMWLOADINTF2CTRLDATA_H
#define META_BENDMWLOADINTF2CTRLDATA_H
#include <meta/beBaseInfoData.h>
namespace Meta {
struct beNDMWLoadIntf2CtrlData : beBaseInfoData {
 bool _isRun;  // 0x10 igBoolMetaField
 bool _isRdy;  // 0x11 igBoolMetaField
 bool _isEntry;  // 0x12 igBoolMetaField
 bool _isCtrl;  // 0x13 igBoolMetaField
 bool _isCansel;  // 0x14 igBoolMetaField
 bool _isMesWin;  // 0x15 igBoolMetaField
 bool _isSystem;  // 0x16 igBoolMetaField
 bool _isNoSelMdl;  // 0x17 igBoolMetaField
 int _newLoadSel;  // 0x18 igIntMetaField
 bool _isNewMake;  // 0x1C igBoolMetaField
 bool _isRdyCancel;  // 0x1D igBoolMetaField
 unsigned char unknown1E[2];
 int _oldPadData;  // 0x20 igIntMetaField
 int _st0;  // 0x24 igIntMetaField
 int _st1;  // 0x28 igIntMetaField
 int _st2;  // 0x2C igIntMetaField
 int _st3;  // 0x30 igIntMetaField
};
}
#endif
