// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWStatusInfo_register (metaobject lbl_80535DBC, vtable lbl_804E69FC), size 0x1C.
#ifndef META_BENDMWSTATUSINFO_H
#define META_BENDMWSTATUSINFO_H
#include <meta/beBaseInfo.h>
namespace Meta {
struct beNDMWStatusInfo : beBaseInfo {
};
}
#endif
