// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWShopSelect11_register (metaobject lbl_80535D74, vtable lbl_804ED61C), size 0x70.
#ifndef META_BENDMWSHOPSELECT11_H
#define META_BENDMWSHOPSELECT11_H
#include <meta/beNDMWWindowSelect.h>
namespace Meta {
struct beNDMWShopSelect11 : beNDMWWindowSelect {
};
}
#endif
