// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8032A174 (metaobject lbl_80535D90, vtable lbl_804EC19C), size 0x70.
#ifndef META_BENDMWSTATUSSELECTE1_H
#define META_BENDMWSTATUSSELECTE1_H
#include <meta/beNDMWWindowSelect.h>
namespace Meta {
struct beNDMWStatusSelectE1 : beNDMWWindowSelect {
};
}
#endif
