// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWStatusInfoWork_register (metaobject lbl_80535DC8, vtable lbl_804E68FC), size 0x24.
#ifndef META_BENDMWSTATUSINFOWORK_H
#define META_BENDMWSTATUSINFOWORK_H
#include <meta/igObject.h>
namespace Meta {
struct beNDMWItemBaseList;
struct igIntList;
struct beNDMWStatusInfoWork : igObject {
 igIntList *_parameter;  // 0x08 igObjectRefMetaField
 igIntList *_preview;  // 0x0C igObjectRefMetaField
 beNDMWItemBaseList *_weaponSalesList;  // 0x10 igObjectRefMetaField
 beNDMWItemBaseList *_armorSalesList;  // 0x14 igObjectRefMetaField
 beNDMWItemBaseList *_chipSalesList;  // 0x18 igObjectRefMetaField
 beNDMWItemBaseList *_junkSalesList;  // 0x1C igObjectRefMetaField
 int _junkGift;  // 0x20 igIntMetaField
};
}
#endif
