// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80339814 (metaobject lbl_805361BC), size 0x114.
#ifndef META_BENDMWMDLPEBASEINFOWORK_H
#define META_BENDMWMDLPEBASEINFOWORK_H
#include <meta/beModelCtrlInfoWork.h>
namespace Meta {
struct beMessenger;
struct igBoolList;
struct igIntList;
struct beNDMWMdlPEBaseInfoWork : beModelCtrlInfoWork {
 bool _isPlayer;  // 0xEC igBoolMetaField
 unsigned char unknownED[3];
 igIntList *_dispRamNoList;  // 0xF0 igObjectRefMetaField
 igIntList *_dispPosNoList;  // 0xF4 igObjectRefMetaField
 igIntList *_timerList;  // 0xF8 igObjectRefMetaField
 igBoolList *_isFirstList;  // 0xFC igObjectRefMetaField
 int _poisonDamage;  // 0x100 igIntMetaField
 int _poisonEndurance;  // 0x104 igIntMetaField
 igIntList *_downDataList;  // 0x108 igObjectRefMetaField
 igIntList *_upDataList;  // 0x10C igObjectRefMetaField
 beMessenger *_messenger;  // 0x110 igObjectRefMetaField
};
}
#endif
