// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80343ECC (metaobject lbl_80536794, vtable lbl_804E46DC), size 0x14.
#ifndef META_BENDMWSHINKAOBJECTLIST_H
#define META_BENDMWSHINKAOBJECTLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beNDMWShinkaObjectList : igObjectList {
};
}
#endif
