// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWStatusCtrlD0_register (metaobject lbl_80535F70, vtable lbl_804EBC18), size 0x74.
#ifndef META_BENDMWSTATUSCTRLD0_H
#define META_BENDMWSTATUSCTRLD0_H
#include <meta/beNDMWListCtrl.h>
namespace Meta {
struct igBoolList;
struct igIntList;
struct beNDMWStatusCtrlD0 : beNDMWListCtrl {
 bool _isBankFolder;  // 0x60 igBoolMetaField
 unsigned char unknown61[3];
 igIntList *_kindList;  // 0x64 igObjectRefMetaField
 int _isAbType;  // 0x68 igIntMetaField
 bool _isEquipDisable;  // 0x6C igBoolMetaField
 bool _isUnknownEnable;  // 0x6D igBoolMetaField
 bool _isUnknownDisable;  // 0x6E igBoolMetaField
 bool _isAutoClose;  // 0x6F igBoolMetaField
 igBoolList *_decideList;  // 0x70 igObjectRefMetaField
};
}
#endif
