// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80336A94 (metaobject lbl_8053609C, vtable lbl_804E622C), size 0x30.
#ifndef META_BENDMWPANELWAZAINFORAM_H
#define META_BENDMWPANELWAZAINFORAM_H
#include <meta/beBaseInfoRam.h>
namespace Meta {
struct beNDMWPanelWazaInfoWork;
struct beNDMWPanelWazaInfoRam : beBaseInfoRam {
 beNDMWPanelWazaInfoWork *_work;  // 0x2C igObjectRefMetaField
};
}
#endif
