// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWLoadIntf2DegiStateList_register (metaobject lbl_80536458, vtable lbl_804E59A0), size 0x14.
#ifndef META_BENDMWLOADINTF2DEGISTATELIST_H
#define META_BENDMWLOADINTF2DEGISTATELIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beNDMWLoadIntf2DegiStateList : igObjectList {
};
}
#endif
