// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80335ED8 (metaobject lbl_80536064, vtable lbl_804E63C4), size 0x1C.
#ifndef META_BENDMWSAVECTRLINFO_H
#define META_BENDMWSAVECTRLINFO_H
#include <meta/beBaseInfo.h>
namespace Meta {
struct beNDMWSaveCtrlInfo : beBaseInfo {
};
}
#endif
