// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWShopCtrlSell_register (metaobject lbl_80535E34, vtable lbl_804ECCD8), size 0x54.
#ifndef META_BENDMWSHOPCTRLSELL_H
#define META_BENDMWSHOPCTRLSELL_H
#include <meta/beNDMWWindowCtrl.h>
namespace Meta {
struct beNDMWShopCtrlSell : beNDMWWindowCtrl {
};
}
#endif
