// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWShopDevice_register (metaobject lbl_80535DF8, vtable lbl_804EC9FC), size 0x64.
#ifndef META_BENDMWSHOPDEVICE_H
#define META_BENDMWSHOPDEVICE_H
#include <meta/beNDMWListCtrl.h>
namespace Meta {
struct beNDMWItemBaseList;
struct beNDMWShopDevice : beNDMWListCtrl {
 beNDMWItemBaseList *_salesList;  // 0x60 igObjectRefMetaField
};
}
#endif
