// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWTitle2_register (metaobject lbl_80535D2C, vtable lbl_804EA898), size 0x34.
#ifndef META_BENDMWTITLE2_H
#define META_BENDMWTITLE2_H
#include <meta/beBaseInfoManager.h>
namespace Meta {
struct beNDMWMcUtilCtrl;
struct bePadManager;
struct beNDMWTitle2 : beBaseInfoManager {
 bePadManager *_padManager;  // 0x20 igObjectRefMetaField
 beNDMWMcUtilCtrl *_mcUtilCtrl;  // 0x24 igObjectRefMetaField
 bool _isMakeFileOK;  // 0x28 igBoolMetaField
 unsigned char unknown29[3];
 int _select;  // 0x2C igIntMetaField
 unsigned char unknown30[4];
};
}
#endif
