// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWStatusTitle00_register (metaobject lbl_80535D5C, vtable lbl_804EC6BC), size 0x50.
#ifndef META_BENDMWSTATUSTITLE00_H
#define META_BENDMWSTATUSTITLE00_H
#include <meta/beNDMWWindowTitle.h>
namespace Meta {
struct beNDMWStatusTitle00 : beNDMWWindowTitle {
};
}
#endif
