// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWSaveIntfComMdlCtrl_register (metaobject lbl_80535FE0, vtable lbl_804E6664), size 0x28.
#ifndef META_BENDMWSAVEINTFCOMMDLCTRL_H
#define META_BENDMWSAVEINTFCOMMDLCTRL_H
#include <meta/beBaseInfoData.h>
namespace Meta {
struct beMessenger;
struct beSaveIntfComMdlDataList;
struct beNDMWSaveIntfComMdlCtrl : beBaseInfoData {
 beMessenger *_messenger;  // 0x10 igObjectRefMetaField
 beSaveIntfComMdlDataList *_openDataList;  // 0x14 igObjectRefMetaField
 beSaveIntfComMdlDataList *_closeDataList;  // 0x18 igObjectRefMetaField
 float _pos[3];  // 0x1C igVec3fMetaField
};
}
#endif
