// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8033C004 (metaobject lbl_80536258, vtable lbl_804EE6B0), size 0x5C.
#ifndef META_BENDMWLOGO_H
#define META_BENDMWLOGO_H
#include <meta/beBaseInfoManager.h>
namespace Meta {
struct beNDMWMcUtilCtrl;
struct bePadManager;
struct beSystem;
struct beNDMWLogo : beBaseInfoManager {
 beSystem *_system;  // 0x20 igObjectRefMetaField
 bePadManager *_padManager;  // 0x24 igObjectRefMetaField
 beNDMWMcUtilCtrl *_mcUtilCtrl;  // 0x28 igObjectRefMetaField
 int _connect;  // 0x2C igIntMetaField
 bool _reCheck;  // 0x30 igBoolMetaField
 unsigned char unknown31[3];
 int _retryCount;  // 0x34 igIntMetaField
 bool _isUseSave;  // 0x38 igBoolMetaField
 bool _isMtap;  // 0x39 igBoolMetaField
 unsigned char unknown3A[2];
 int _select;  // 0x3C igIntMetaField
 int _errTarget;  // 0x40 igIntMetaField
 int _errType;  // 0x44 igIntMetaField
 unsigned char unknown48[20];
};
}
#endif
