// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80332AF0 (metaobject lbl_80535F34, vtable lbl_804EBDA8), size 0x7C.
#ifndef META_BENDMWSTATUSMAINSLOT_H
#define META_BENDMWSTATUSMAINSLOT_H
#include <meta/beNDMWStatusCtrlBaseEquip.h>
namespace Meta {
struct beNDMWStatusMainSlot : beNDMWStatusCtrlBaseEquip {
};
}
#endif
