// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80326EFC (metaobject lbl_80535D40, vtable lbl_804ED928), size 0x50.
#ifndef META_BENDMWSHOPTITLE03_H
#define META_BENDMWSHOPTITLE03_H
#include <meta/beNDMWWindowTitle.h>
namespace Meta {
struct beNDMWShopTitle03 : beNDMWWindowTitle {
};
}
#endif
