// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8033FC7C (metaobject lbl_805365EC, vtable lbl_804E52D8), size 0x1C.
#ifndef META_BENDMWMCSLOTXBOX_H
#define META_BENDMWMCSLOTXBOX_H
#include <meta/beNDMWMcSlot.h>
namespace Meta {
struct beNDMWMcSlotXbox : beNDMWMcSlot {
 const char *_mName;  // 0x18 igStringMetaField
};
}
#endif
