// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8033F664 (metaobject lbl_805365A8, vtable lbl_804E5588), size 0x14.
#ifndef META_BENDMWLOADSAVEPLWORKLIST_H
#define META_BENDMWLOADSAVEPLWORKLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beNDMWLoadSavePlWorkList : igObjectList {
};
}
#endif
