// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8032628C (metaobject lbl_80535CD0, vtable lbl_804E6B64), size 0x38.
#ifndef META_BENDMWTITLE2OPTION_H
#define META_BENDMWTITLE2OPTION_H
#include <meta/beBaseInfoData.h>
namespace Meta {
struct beMessenger;
struct beNDMWTitle2Option : beBaseInfoData {
 beMessenger *_messenger;  // 0x10 igObjectRefMetaField
 int _selLang;  // 0x14 igIntMetaField
 int _ctrlPos;  // 0x18 igIntMetaField
 bool _isOK;  // 0x1C igBoolMetaField
 unsigned char unknown1D[3];
 int _comConf;  // 0x20 igIntMetaField
 int _lightConf;  // 0x24 igIntMetaField
 int _oldCountry;  // 0x28 igIntMetaField
 int _dispComConf;  // 0x2C igIntMetaField
 int _dispLightConf;  // 0x30 igIntMetaField
 int _dispCountryConf;  // 0x34 igIntMetaField
};
}
#endif
