// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8032F938 (metaobject lbl_80535EA8, vtable lbl_804ECE6C), size 0x64.
#ifndef META_BENDMWSHOPCTRLEVOLVE_H
#define META_BENDMWSHOPCTRLEVOLVE_H
#include <meta/beNDMWListCtrl.h>
namespace Meta {
struct beNDMWShinkaCtrl;
struct beNDMWShopCtrlEvolve : beNDMWListCtrl {
 beNDMWShinkaCtrl *_shinkaCtrl;  // 0x60 igObjectRefMetaField
};
}
#endif
