// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWShopTitle01_register (metaobject lbl_80535D44, vtable lbl_804ED9B0), size 0x50.
#ifndef META_BENDMWSHOPTITLE01_H
#define META_BENDMWSHOPTITLE01_H
#include <meta/beNDMWWindowTitle.h>
namespace Meta {
struct beNDMWShopTitle01 : beNDMWWindowTitle {
};
}
#endif
