// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80333F14 (metaobject lbl_80535FAC), size 0x54.
#ifndef META_BENDMWWINDOWCTRL_H
#define META_BENDMWWINDOWCTRL_H
#include <meta/beNDMWWindow.h>
namespace Meta {
struct beNDMWWindowCtrl : beNDMWWindow {
 int _nowProcKazu;  // 0x50 igIntMetaField
};
}
#endif
