// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8034067C (metaobject lbl_80536620, vtable lbl_804E5034), size 0x14.
#ifndef META_BENDMWLOADSLOTPLAYER_H
#define META_BENDMWLOADSLOTPLAYER_H
#include <meta/igObject.h>
namespace Meta {
struct beNDMWDegiDataList;
struct igIntList;
struct beNDMWLoadSlotPlayer : igObject {
 int _connectNO;  // 0x08 igIntMetaField
 beNDMWDegiDataList *_saveDataList;  // 0x0C igObjectRefMetaField
 igIntList *_accessPlList;  // 0x10 igObjectRefMetaField
};
}
#endif
