// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWStatusPowerSocket_register (metaobject lbl_80535F38, vtable lbl_804EBE7C), size 0x7C.
#ifndef META_BENDMWSTATUSPOWERSOCKET_H
#define META_BENDMWSTATUSPOWERSOCKET_H
#include <meta/beNDMWStatusCtrlBaseEquip.h>
namespace Meta {
struct beNDMWStatusPowerSocket : beNDMWStatusCtrlBaseEquip {
};
}
#endif
