// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80334D5C (metaobject lbl_80535FDC, vtable lbl_804E66EC), size 0x1C.
#ifndef META_BENDMWSAVEINTFINFO_H
#define META_BENDMWSAVEINTFINFO_H
#include <meta/beBaseInfo.h>
namespace Meta {
struct beNDMWSaveIntfInfo : beBaseInfo {
};
}
#endif
