// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWShopCtrl00_register (metaobject lbl_80535EBC, vtable lbl_804ED31C), size 0x54.
#ifndef META_BENDMWSHOPCTRL00_H
#define META_BENDMWSHOPCTRL00_H
#include <meta/beNDMWWindowCtrl.h>
namespace Meta {
struct beNDMWShopCtrl00 : beNDMWWindowCtrl {
};
}
#endif
