// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80344774 (metaobject lbl_805367F0, vtable lbl_804EB2C4), size 0x4C.
#ifndef META_BENDMWGAMERAM_H
#define META_BENDMWGAMERAM_H
#include <meta/beBaseInfoManager.h>
namespace Meta {
struct beDataBase;
struct beDataObjList;
struct beDataObjListList;
struct beNDMWGameRam : beBaseInfoManager {
 beDataBase *_dBShinka;  // 0x20 igObjectRefMetaField
 beDataBase *_dBPcTech;  // 0x24 igObjectRefMetaField
 beDataBase *_dBWeapon;  // 0x28 igObjectRefMetaField
 beDataBase *_dBArmor1;  // 0x2C igObjectRefMetaField
 beDataBase *_dBArmor2;  // 0x30 igObjectRefMetaField
 beDataBase *_dBAbChip;  // 0x34 igObjectRefMetaField
 beDataBase *_dBEnemy;  // 0x38 igObjectRefMetaField
 beDataBase *_dBEneatk;  // 0x3C igObjectRefMetaField
 beDataObjList *_commonDataList;  // 0x40 igObjectRefMetaField
 beDataObjListList *_playerDataListList;  // 0x44 igObjectRefMetaField
 bool _isDispFightData;  // 0x48 igBoolMetaField
 unsigned char unknown49[3];
};
}
#endif
