// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWLoadIntf2TextOrder_register (metaobject lbl_805366E8, vtable lbl_804E4B94), size 0x18.
#ifndef META_BENDMWLOADINTF2TEXTORDER_H
#define META_BENDMWLOADINTF2TEXTORDER_H
#include <meta/beBaseInfoData.h>
namespace Meta {
struct beLua;
struct beMessenger;
struct beNDMWLoadIntf2TextOrder : beBaseInfoData {
 beMessenger *_messenger;  // 0x10 igObjectRefMetaField
 beLua *_lua;  // 0x14 igObjectRefMetaField
};
}
#endif
