// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWItemRevisionBase_register (metaobject lbl_8053675C), size 0x18.
#ifndef META_BENDMWITEMREVISIONBASE_H
#define META_BENDMWITEMREVISIONBASE_H
#include <meta/beNDMWItemBase.h>
namespace Meta {
struct beNDMWItemRevisionBase : beNDMWItemBase {
 int _revision;  // 0x14 igIntMetaField
};
}
#endif
