// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWAfsSetup_register (metaobject lbl_8053684C, vtable lbl_804E7024), size 0x28.
#ifndef META_BENDMWAFSSETUP_H
#define META_BENDMWAFSSETUP_H
#include <meta/igInfoManager.h>
namespace Meta {
struct igBoxComponent;
struct igGuiComponent;
struct igInfoList;
struct beNDMWAfsSetup : igInfoManager {
 igInfoList *_infoList;  // 0x10 igObjectRefMetaField
 igBoxComponent *_customMenu;  // 0x14 igObjectRefMetaField
 igBoxComponent *_subMenu;  // 0x18 igObjectRefMetaField
 igGuiComponent *_subMenuHolder;  // 0x1C igObjectRefMetaField
 unsigned char unknown20[8];
};
}
#endif
