// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWLoadSavePlWork_register (metaobject lbl_805365AC, vtable lbl_804E54CC), size 0x34.
#ifndef META_BENDMWLOADSAVEPLWORK_H
#define META_BENDMWLOADSAVEPLWORK_H
#include <meta/igObject.h>
namespace Meta {
struct beNDMWLoadSlotPlayer;
struct beNDMWLoadSavePlWork : igObject {
 int _sysCount0;  // 0x08 igIntMetaField
 bool _isEntry;  // 0x0C igBoolMetaField
 bool _isRdy;  // 0x0D igBoolMetaField
 bool _isClose;  // 0x0E igBoolMetaField
 bool _isCtrl;  // 0x0F igBoolMetaField
 bool _isCutConnect;  // 0x10 igBoolMetaField
 unsigned char unknown11[3];
 int _utilReturn;  // 0x14 igIntMetaField
 int _utilNext;  // 0x18 igIntMetaField
 bool _isHaveSaveData;  // 0x1C igBoolMetaField
 unsigned char unknown1D[3];
 beNDMWLoadSlotPlayer *_haveSaveData;  // 0x20 igObjectRefMetaField
 int _sysStat0;  // 0x24 igIntMetaField
 int _sysStat1;  // 0x28 igIntMetaField
 int _sysStat2;  // 0x2C igIntMetaField
 int _sysStat3;  // 0x30 igIntMetaField
};
}
#endif
