// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWStatus_register (metaobject lbl_80535FB8, vtable lbl_804E80EC), size 0x2C.
#ifndef META_BENDMWSTATUS_H
#define META_BENDMWSTATUS_H
#include <meta/beBaseInfoManager.h>
namespace Meta {
struct beNDMWWindow;
struct beNDMWStatus : beBaseInfoManager {
 beNDMWWindow *_windowPro;  // 0x20 igObjectRefMetaField
 int _whoGenerate;  // 0x24 igIntMetaField
 int _subWndNo;  // 0x28 igIntMetaField
};
}
#endif
