// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8032AE7C (metaobject lbl_80535DC0, vtable lbl_804E6974), size 0x30.
#ifndef META_BENDMWSTATUSINFORAM_H
#define META_BENDMWSTATUSINFORAM_H
#include <meta/beBaseInfoRam.h>
namespace Meta {
struct beNDMWStatusInfoWork;
struct beNDMWStatusInfoRam : beBaseInfoRam {
 beNDMWStatusInfoWork *_work;  // 0x2C igObjectRefMetaField
};
}
#endif
