// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80330F68 (metaobject lbl_80535EE8, vtable lbl_804EB97C), size 0x64.
#ifndef META_BENDMWSTATUSCTRLSENDBIT_H
#define META_BENDMWSTATUSCTRLSENDBIT_H
#include <meta/beNDMWWindowCtrl.h>
namespace Meta {
struct igIntList;
struct beNDMWStatusCtrlSendBit : beNDMWWindowCtrl {
 int _editBit;  // 0x54 igIntMetaField
 int _editMax;  // 0x58 igIntMetaField
 igIntList *_playerNoList;  // 0x5C igObjectRefMetaField
 int _receipt;  // 0x60 igIntMetaField
};
}
#endif
