// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWItemRevisionPocketBase_register (metaobject lbl_80536754), size 0x1C.
#ifndef META_BENDMWITEMREVISIONPOCKETBASE_H
#define META_BENDMWITEMREVISIONPOCKETBASE_H
#include <meta/beNDMWItemRevisionBase.h>
namespace Meta {
struct beNDMWItemRevisionPocketBase : beNDMWItemRevisionBase {
 int _pocket;  // 0x18 igIntMetaField
};
}
#endif
