// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80339C14 (metaobject lbl_805361E8, vtable lbl_804E7B24), size 0x2C.
#ifndef META_BENDMWMDLPBULLET_H
#define META_BENDMWMDLPBULLET_H
#include <meta/beModelCtrl.h>
namespace Meta {
struct beNDMWMdlPBullet : beModelCtrl {
};
}
#endif
