// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWLoadCtrl2CtrlData_register (metaobject lbl_805366F8, vtable lbl_804E4B14), size 0x24.
#ifndef META_BENDMWLOADCTRL2CTRLDATA_H
#define META_BENDMWLOADCTRL2CTRLDATA_H
#include <meta/beBaseInfoData.h>
namespace Meta {
struct beNDMWLoadCtrl2CtrlData : beBaseInfoData {
 bool _isTitle;  // 0x10 igBoolMetaField
 unsigned char unknown11[3];
 int _st0;  // 0x14 igIntMetaField
 int _st1;  // 0x18 igIntMetaField
 int _st2;  // 0x1C igIntMetaField
 int _st3;  // 0x20 igIntMetaField
};
}
#endif
