// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80329E9C (metaobject lbl_80535D88, vtable lbl_804ED83C), size 0x74.
#ifndef META_BENDMWSHOPSELECT00_H
#define META_BENDMWSHOPSELECT00_H
#include <meta/beNDMWWindowSelect.h>
namespace Meta {
struct beNDMWShopSelect00 : beNDMWWindowSelect {
 const char *_panelName;  // 0x70 igStringMetaField
};
}
#endif
