// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWMdlPlayer2_register (metaobject lbl_80536158, vtable lbl_804E7F3C), size 0x30.
#ifndef META_BENDMWMDLPLAYER2_H
#define META_BENDMWMDLPLAYER2_H
#include <meta/beModelCtrl.h>
namespace Meta {
struct bePadManager;
struct beNDMWMdlPlayer2 : beModelCtrl {
 bePadManager *_padManager;  // 0x2C igObjectRefMetaField
};
}
#endif
