// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWStatusCtrlSkill_register (metaobject lbl_80535ED8, vtable lbl_804EB8EC), size 0x6C.
#ifndef META_BENDMWSTATUSCTRLSKILL_H
#define META_BENDMWSTATUSCTRLSKILL_H
#include <meta/beNDMWListCtrl.h>
namespace Meta {
struct beNDMWShinkaCtrl;
struct igIntList;
struct beNDMWStatusCtrlSkill : beNDMWListCtrl {
 int _skillMenu;  // 0x60 igIntMetaField
 beNDMWShinkaCtrl *_shinkaCtrl;  // 0x64 igObjectRefMetaField
 igIntList *_skillList;  // 0x68 igObjectRefMetaField
};
}
#endif
