// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWSaveIntf_register (metaobject lbl_80536054, vtable lbl_804EB658), size 0x2C.
#ifndef META_BENDMWSAVEINTF_H
#define META_BENDMWSAVEINTF_H
#include <meta/beBaseInfoManager.h>
namespace Meta {
struct bePadManager;
struct beSystem;
struct beNDMWSaveIntf : beBaseInfoManager {
 beSystem *_system;  // 0x20 igObjectRefMetaField
 bePadManager *_padManager;  // 0x24 igObjectRefMetaField
 int _kindHard;  // 0x28 igIntMetaField
};
}
#endif
