// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWShopSelect03_register (metaobject lbl_80535D78, vtable lbl_804ED6A4), size 0x70.
#ifndef META_BENDMWSHOPSELECT03_H
#define META_BENDMWSHOPSELECT03_H
#include <meta/beNDMWWindowSelect.h>
namespace Meta {
struct beNDMWShopSelect03 : beNDMWWindowSelect {
};
}
#endif
