// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWMdlPlayer_register (metaobject lbl_80536178, vtable lbl_804E7DAC), size 0x38.
#ifndef META_BENDMWMDLPLAYER_H
#define META_BENDMWMDLPLAYER_H
#include <meta/beNDMWMdlPEBase.h>
namespace Meta {
struct beNDMWGameRam;
struct bePadManager;
struct igViewerSceneInfoManager;
struct beNDMWMdlPlayer : beNDMWMdlPEBase {
 igViewerSceneInfoManager *_viewerSIManager;  // 0x2C igObjectRefMetaField
 bePadManager *_padManager;  // 0x30 igObjectRefMetaField
 beNDMWGameRam *_gameRam;  // 0x34 igObjectRefMetaField
};
}
#endif
