// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8032900C (metaobject lbl_80535D6C, vtable lbl_804ED50C), size 0x70.
#ifndef META_BENDMWSHOPSELECT52_H
#define META_BENDMWSHOPSELECT52_H
#include <meta/beNDMWWindowSelect.h>
namespace Meta {
struct beNDMWShopSelect52 : beNDMWWindowSelect {
};
}
#endif
