// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80329934 (metaobject lbl_80535D7C, vtable lbl_804ED72C), size 0x74.
#ifndef META_BENDMWSHOPSELECT02_H
#define META_BENDMWSHOPSELECT02_H
#include <meta/beNDMWWindowSelect.h>
namespace Meta {
struct igIntList;
struct beNDMWShopSelect02 : beNDMWWindowSelect {
 igIntList *_playerNoList;  // 0x70 igObjectRefMetaField
};
}
#endif
