// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWPanelObjectWaza_register (metaobject lbl_805360F8, vtable lbl_804E73AC), size 0x44.
#ifndef META_BENDMWPANELOBJECTWAZA_H
#define META_BENDMWPANELOBJECTWAZA_H
#include <meta/beNDMWPanelObject.h>
namespace Meta {
struct igIntList;
struct igObjectList;
struct beNDMWPanelObjectWaza : beNDMWPanelObject {
 igObjectList *_listFolder;  // 0x3C igObjectRefMetaField
 igIntList *_listColor;  // 0x40 igObjectRefMetaField
};
}
#endif
