// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWStatusTitle02_register (metaobject lbl_80535D54, vtable lbl_804EC5AC), size 0x50.
#ifndef META_BENDMWSTATUSTITLE02_H
#define META_BENDMWSTATUSTITLE02_H
#include <meta/beNDMWWindowTitle.h>
namespace Meta {
struct beNDMWStatusTitle02 : beNDMWWindowTitle {
};
}
#endif
