// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWStatusSubSlot_register (metaobject lbl_80535F30, vtable lbl_804EBCD4), size 0x7C.
#ifndef META_BENDMWSTATUSSUBSLOT_H
#define META_BENDMWSTATUSSUBSLOT_H
#include <meta/beNDMWStatusCtrlBaseEquip.h>
namespace Meta {
struct beNDMWStatusSubSlot : beNDMWStatusCtrlBaseEquip {
};
}
#endif
