// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWLogoCtrlData_register (metaobject lbl_8053623C, vtable lbl_804E5E1C), size 0x20.
#ifndef META_BENDMWLOGOCTRLDATA_H
#define META_BENDMWLOGOCTRLDATA_H
#include <meta/beBaseInfoData.h>
namespace Meta {
struct beNDMWLogoCtrlData : beBaseInfoData {
 int _st0;  // 0x10 igIntMetaField
 int _st1;  // 0x14 igIntMetaField
 int _st2;  // 0x18 igIntMetaField
 int _st3;  // 0x1C igIntMetaField
};
}
#endif
