// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8033F3A4 (metaobject lbl_80536560, vtable lbl_804E5664), size 0x40.
#ifndef META_BENDMWMCUTILCTRL_H
#define META_BENDMWMCUTILCTRL_H
#include <meta/igObject.h>
namespace Meta {
struct beMessenger;
struct beNDMWMcSlotList;
struct beSaveDataDeliver;
struct beNDMWMcUtilCtrl : igObject {
 beMessenger *_messenger;  // 0x08 igObjectRefMetaField
 bool _isUseUtil;  // 0x0C igBoolMetaField
 bool _isRdy;  // 0x0D igBoolMetaField
 bool _isRun;  // 0x0E igBoolMetaField
 bool _isMtap;  // 0x0F igBoolMetaField
 bool _isFormatRun;  // 0x10 igBoolMetaField
 unsigned char unknown11[3];
 int _tgCon;  // 0x14 igIntMetaField
 int _usePlNo;  // 0x18 igIntMetaField
 int _kind;  // 0x1C igIntMetaField
 int _result;  // 0x20 igIntMetaField
 bool _isResult;  // 0x24 igBoolMetaField
 unsigned char unknown25[3];
 beSaveDataDeliver *_svData;  // 0x28 igObjectRefMetaField
 beNDMWMcSlotList *_slot;  // 0x2C igObjectRefMetaField
 int _st0;  // 0x30 igIntMetaField
 int _st1;  // 0x34 igIntMetaField
 int _st2;  // 0x38 igIntMetaField
 int _st3;  // 0x3C igIntMetaField
};
}
#endif
