// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8032A5EC (metaobject lbl_80535D98, vtable lbl_804EC2AC), size 0x70.
#ifndef META_BENDMWSTATUSSELECT01_H
#define META_BENDMWSTATUSSELECT01_H
#include <meta/beNDMWWindowSelect.h>
namespace Meta {
struct beNDMWStatusSelect01 : beNDMWWindowSelect {
};
}
#endif
