// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80342B58 (metaobject lbl_8053673C, vtable lbl_804EE2E8), size 0x18.
#ifndef META_BENDMWITEMDISK_H
#define META_BENDMWITEMDISK_H
#include <meta/beNDMWItemBase.h>
namespace Meta {
struct beNDMWItemDisk : beNDMWItemBase {
 int _kazu;  // 0x14 igIntMetaField
};
}
#endif
