// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWMdlEnemy_register (metaobject lbl_80536228, vtable lbl_804E7818), size 0x2C.
#ifndef META_BENDMWMDLENEMY_H
#define META_BENDMWMDLENEMY_H
#include <meta/beNDMWMdlPEBase.h>
namespace Meta {
struct beNDMWMdlEnemy : beNDMWMdlPEBase {
};
}
#endif
