// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWMdlMapBase_register (metaobject lbl_805361F4, vtable lbl_804EE804), size 0x2C.
#ifndef META_BENDMWMDLMAPBASE_H
#define META_BENDMWMDLMAPBASE_H
#include <meta/beModelCtrl.h>
namespace Meta {
struct beNDMWMdlMapBase : beModelCtrl {
};
}
#endif
