// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWStageCtl_register (metaobject lbl_80535FD4, vtable lbl_804E6EA0), size 0x28.
#ifndef META_BENDMWSTAGECTL_H
#define META_BENDMWSTAGECTL_H
#include <meta/beBaseInfoManager.h>
namespace Meta {
struct beNDMWStageCtl : beBaseInfoManager {
 long long _resetTrgTime;  // 0x20 igLongMetaField
};
}
#endif
