// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8032D6C8 (metaobject lbl_80535E38, vtable lbl_804ECD5C), size 0x5C.
#ifndef META_BENDMWSHOPCTRLEDITBIT_H
#define META_BENDMWSHOPCTRLEDITBIT_H
#include <meta/beNDMWWindowCtrl.h>
namespace Meta {
struct beNDMWShopCtrlEditBit : beNDMWWindowCtrl {
 int _editBit;  // 0x54 igIntMetaField
 int _editMax;  // 0x58 igIntMetaField
};
}
#endif
