// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWShopCtrl40_register (metaobject lbl_80535E98, vtable lbl_804ED190), size 0x58.
#ifndef META_BENDMWSHOPCTRL40_H
#define META_BENDMWSHOPCTRL40_H
#include <meta/beNDMWWindowCtrl.h>
namespace Meta {
struct beNDMWShopCtrl40 : beNDMWWindowCtrl {
 int _selectCursor;  // 0x54 igIntMetaField
};
}
#endif
