// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWStatusCtrlBaseEquip_register (metaobject lbl_80535F3C), size 0x7C.
#ifndef META_BENDMWSTATUSCTRLBASEEQUIP_H
#define META_BENDMWSTATUSCTRLBASEEQUIP_H
#include <meta/beNDMWWindowCtrl.h>
namespace Meta {
struct beDataObjList;
struct beNDMWItemBaseList;
struct beNDMWStatusCtrlBaseEquip : beNDMWWindowCtrl {
 int _kindListPos;  // 0x54 igIntMetaField
 int _kindListMax;  // 0x58 igIntMetaField
 int _pocketPos;  // 0x5C igIntMetaField
 beDataObjList *_playerList;  // 0x60 igObjectRefMetaField
 beNDMWItemBaseList *_powerSocket;  // 0x64 igObjectRefMetaField
 beNDMWItemBaseList *_mainSlot;  // 0x68 igObjectRefMetaField
 beNDMWItemBaseList *_subSlot;  // 0x6C igObjectRefMetaField
 beNDMWItemBaseList *_wpuPocket;  // 0x70 igObjectRefMetaField
 beNDMWItemBaseList *_apuPocket;  // 0x74 igObjectRefMetaField
 beNDMWItemBaseList *_deviceFolder;  // 0x78 igObjectRefMetaField
};
}
#endif
