// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWStatusCtrl00_register (metaobject lbl_80535F94, vtable lbl_804EC074), size 0x58.
#ifndef META_BENDMWSTATUSCTRL00_H
#define META_BENDMWSTATUSCTRL00_H
#include <meta/beNDMWWindowCtrl.h>
namespace Meta {
struct beNDMWStatusCtrl00 : beNDMWWindowCtrl {
 int _statusMenu;  // 0x54 igIntMetaField
};
}
#endif
