// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWShopCtrlXdataChip_register (metaobject lbl_80535E00, vtable lbl_804ECA94), size 0x64.
#ifndef META_BENDMWSHOPCTRLXDATACHIP_H
#define META_BENDMWSHOPCTRLXDATACHIP_H
#include <meta/beNDMWListCtrl.h>
namespace Meta {
struct beNDMWItemBaseList;
struct beNDMWShopCtrlXdataChip : beNDMWListCtrl {
 beNDMWItemBaseList *_itemBaseList;  // 0x60 igObjectRefMetaField
};
}
#endif
