// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80342754 (metaobject lbl_80536730, vtable lbl_804EE1D8), size 0x14.
#ifndef META_BENDMWITEMIMPORTANT_H
#define META_BENDMWITEMIMPORTANT_H
#include <meta/beNDMWItemBase.h>
namespace Meta {
struct beNDMWItemImportant : beNDMWItemBase {
};
}
#endif
