// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8033FEA8 (metaobject lbl_805365F4, vtable lbl_804E5260), size 0x20.
#ifndef META_BENDMWMCSLOTGC_H
#define META_BENDMWMCSLOTGC_H
#include <meta/beNDMWMcSlot.h>
namespace Meta {
struct beNDMWMcSlotGC : beNDMWMcSlot {
 int _fileKaz;  // 0x18 igIntMetaField
 int _detail;  // 0x1C igIntMetaField
};
}
#endif
