// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80325AB0 (metaobject lbl_80535C78, vtable lbl_804E6CB0), size 0x14.
#ifndef META_BENDMWWINDOWLIST_H
#define META_BENDMWWINDOWLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beNDMWWindowList : igObjectList {
};
}
#endif
