// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNDMWLoadIntf2DataSelIntf_register (metaobject lbl_805363E8, vtable lbl_804E5B0C), size 0x5C.
#ifndef META_BENDMWLOADINTF2DATASELINTF_H
#define META_BENDMWLOADINTF2DATASELINTF_H
#include <meta/beBaseInfoData.h>
namespace Meta {
struct beNDMWLoadCtrl2CommonIntf;
struct beNDMWLoadIntf2ComMdlCtrl;
struct beNDMWLoadIntf2DegiStateCtrl;
struct beNDMWLoadIntf2MesWin;
struct beNDMWLoadIntf2TextOrder;
struct bePadManager;
struct beNDMWLoadIntf2DataSelIntf : beBaseInfoData {
 int _mcSelPoint;  // 0x10 igIntMetaField
 int _svDataSelPoint;  // 0x14 igIntMetaField
 bePadManager *_padManager;  // 0x18 igObjectRefMetaField
 beNDMWLoadIntf2ComMdlCtrl *_comMdlCtrl;  // 0x1C igObjectRefMetaField
 beNDMWLoadIntf2TextOrder *_textOrder;  // 0x20 igObjectRefMetaField
 beNDMWLoadCtrl2CommonIntf *_commonIntf;  // 0x24 igObjectRefMetaField
 beNDMWLoadIntf2MesWin *_mesWin;  // 0x28 igObjectRefMetaField
 beNDMWLoadIntf2DegiStateCtrl *_statDisp;  // 0x2C igObjectRefMetaField
 bool _isSaveArea;  // 0x30 igBoolMetaField
 bool _isUpStatWin;  // 0x31 igBoolMetaField
 bool _isDownStatWin;  // 0x32 igBoolMetaField
 bool _isSlotWin;  // 0x33 igBoolMetaField
 bool _isSelCur;  // 0x34 igBoolMetaField
 unsigned char unknown35[3];
 int _kind;  // 0x38 igIntMetaField
 int _plNo;  // 0x3C igIntMetaField
 int _mesKind;  // 0x40 igIntMetaField
 int _result;  // 0x44 igIntMetaField
 bool _isEnd;  // 0x48 igBoolMetaField
 bool _isCancel;  // 0x49 igBoolMetaField
 unsigned char unknown4A[2];
 int _st0;  // 0x4C igIntMetaField
 int _st1;  // 0x50 igIntMetaField
 int _st2;  // 0x54 igIntMetaField
 int _st3;  // 0x58 igIntMetaField
};
}
#endif
