// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8032CF90 (metaobject lbl_80535E2C, vtable lbl_804ECC48), size 0x64.
#ifndef META_BENDMWSHOPCTRLDEVICESELL_H
#define META_BENDMWSHOPCTRLDEVICESELL_H
#include <meta/beNDMWListCtrl.h>
namespace Meta {
struct igBoolList;
struct beNDMWShopCtrlDeviceSell : beNDMWListCtrl {
 igBoolList *_decideList;  // 0x60 igObjectRefMetaField
};
}
#endif
