// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802C382C (metaobject lbl_80534B74, vtable lbl_804DA478), size 0x14.
#ifndef META_BENUMVERINSIDEDATALIST_H
#define META_BENUMVERINSIDEDATALIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beNumVerInsideDataList : igObjectList {
};
}
#endif
