// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802C2DA0 (metaobject lbl_80534B38, vtable lbl_804DA764), size 0x14.
#ifndef META_BENUMBERCTRLINFOWORK_H
#define META_BENUMBERCTRLINFOWORK_H
#include <meta/igObject.h>
namespace Meta {
struct beNumberCtrlInfoWork : igObject {
 int _dispNum;  // 0x08 igIntMetaField
 int _realNum;  // 0x0C igIntMetaField
 int _changeNum;  // 0x10 igIntMetaField
};
}
#endif
