// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802C3E10 (metaobject lbl_80534B88, vtable lbl_804DA21C), size 0x1C.
#ifndef META_BENUMBERCTRLINFO_H
#define META_BENUMBERCTRLINFO_H
#include <meta/beBaseInfo.h>
namespace Meta {
struct beNumberCtrlInfo : beBaseInfo {
};
}
#endif
