// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802C313C (metaobject lbl_80534B48, vtable lbl_804DA6F4), size 0x44.
#ifndef META_BENUMBERCTRLINFORAM_H
#define META_BENUMBERCTRLINFORAM_H
#include <meta/beBaseInfoRam.h>
namespace Meta {
struct beNumVerDataList;
struct beNumberCtrlInfoWork;
struct igGeometry;
struct beNumberCtrlInfoRam : beBaseInfoRam {
 igGeometry *_geometry;  // 0x2C igObjectRefMetaField
 float _offsetNext;  // 0x30 igFloatMetaField
 int _maxValue;  // 0x34 igIntMetaField
 int _mode;  // 0x38 igIntMetaField
 beNumVerDataList *_numList;  // 0x3C igObjectRefMetaField
 beNumberCtrlInfoWork *_work;  // 0x40 igObjectRefMetaField
};
}
#endif
