// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beNumberCtrlInfoList_register (metaobject lbl_80534B84, vtable lbl_804DA2E0), size 0x14.
#ifndef META_BENUMBERCTRLINFOLIST_H
#define META_BENUMBERCTRLINFOLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beNumberCtrlInfoList : igObjectList {
};
}
#endif
