// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802C20A8 (metaobject lbl_80534AA8, vtable lbl_804DF2B0), size 0x20.
#ifndef META_BEPARTICLECTRL2_H
#define META_BEPARTICLECTRL2_H
#include <meta/beBaseInfoManager.h>
namespace Meta {
struct beParticleCtrl2 : beBaseInfoManager {
};
}
#endif
