// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by bePadManager_register (metaobject lbl_80534AAC, vtable lbl_804DF18C), size 0x20.
#ifndef META_BEPADMANAGER_H
#define META_BEPADMANAGER_H
#include <meta/igInfoManager.h>
namespace Meta {
struct beKeyboardReceiver;
struct bePadDataList;
struct beSystem;
struct bePadManager : igInfoManager {
 beSystem *_system;  // 0x10 igObjectRefMetaField
 bePadDataList *_padList;  // 0x14 igObjectRefMetaField
 beKeyboardReceiver *_kbReceiver;  // 0x18 igObjectRefMetaField
 bool _is1pAllDevice;  // 0x1C igBoolMetaField
 bool _isPadDisable;  // 0x1D igBoolMetaField
 unsigned char unknown1E[2];
};
}
#endif
