// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802C1974 (metaobject lbl_80534A84, vtable lbl_804DAA14), size 0x18.
#ifndef META_BEPARTICLECTRL2INFOWORK_H
#define META_BEPARTICLECTRL2INFOWORK_H
#include <meta/igObject.h>
namespace Meta {
struct beModelCtrlNode2;
struct beParticleCtrl2InfoWork : igObject {
 beModelCtrlNode2 *_positionLockNode;  // 0x08 igObjectRefMetaField
 float _positionLockOffset[3];  // 0x0C igVec3fMetaField
};
}
#endif
