// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by bePlaySE_register (metaobject lbl_80534788, vtable lbl_804DBA4C), size 0x18.
#ifndef META_BEPLAYSE_H
#define META_BEPLAYSE_H
#include <meta/igObject.h>
namespace Meta {
struct bePlaySE : igObject {
 int _id;  // 0x08 igIntMetaField
 unsigned char unknown0C[4];
 long long _time;  // 0x10 igLongMetaField
};
}
#endif
