// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802B93C8 (metaobject lbl_80534784, vtable lbl_804DBB08), size 0x14.
#ifndef META_BEPLAYSELIST_H
#define META_BEPLAYSELIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct bePlaySEList : igObjectList {
};
}
#endif
