// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802C12A0 (metaobject lbl_80534A6C, vtable lbl_804DF3EC), size 0x24.
#ifndef META_BEPOINT01_H
#define META_BEPOINT01_H
#include <meta/beBaseInfoManager.h>
namespace Meta {
struct bePoint01 : beBaseInfoManager {
 int _pointNo;  // 0x20 igIntMetaField
};
}
#endif
