// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802C0B64 (metaobject lbl_80534A50, vtable lbl_804DABA4), size 0x24.
#ifndef META_BERESETNODE_H
#define META_BERESETNODE_H
#include <meta/igGroup.h>
namespace Meta {
struct beResetNode : igGroup {
 bool _isResetTime;  // 0x20 igBoolMetaField
 bool _isResetRotAndScale;  // 0x21 igBoolMetaField
 unsigned char unknown22[2];
};
}
#endif
