// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beSaveUtilInfo_register (metaobject lbl_80534828, vtable lbl_804DB374), size 0x1C.
#ifndef META_BESAVEUTILINFO_H
#define META_BESAVEUTILINFO_H
#include <meta/beBaseInfo.h>
namespace Meta {
struct beSaveUtilInfo : beBaseInfo {
};
}
#endif
