// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beSaveDataDeliver_register (metaobject lbl_805349F8, vtable lbl_804DACBC), size 0x10.
#ifndef META_BESAVEDATADELIVER_H
#define META_BESAVEDATADELIVER_H
#include <meta/igObject.h>
namespace Meta {
struct beSaveDataDeliver : igObject {
 void *_data;  // 0x08 igMemoryRefMetaField
 int _size;  // 0x0C igIntMetaField
};
}
#endif
