// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802BF3C4 (metaobject lbl_8053496C), size 0xD4.
#ifndef META_BESAVEAPI_H
#define META_BESAVEAPI_H
#include <meta/igObject.h>
namespace Meta {
struct beSaveMemoryObj;
struct beSaveApi : igObject {
 int _dummyCount;  // 0x08 igIntMetaField
 int _orderType;  // 0x0C igIntMetaField
 bool _isConAllChk;  // 0x10 igBoolMetaField
 unsigned char unknown11[3];
 int _connect;  // 0x14 igIntMetaField
 int _result;  // 0x18 igIntMetaField
 bool _isEnd;  // 0x1C igBoolMetaField
 unsigned char unknown1D[3];
 int _st0;  // 0x20 igIntMetaField
 int _st1;  // 0x24 igIntMetaField
 int _st2;  // 0x28 igIntMetaField
 int _st3;  // 0x2C igIntMetaField
 beSaveMemoryObj *_imageWork;  // 0x30 igObjectRefMetaField
 beSaveMemoryObj *_mountWork;  // 0x34 igObjectRefMetaField
 beSaveMemoryObj *_iconWork;  // 0x38 igObjectRefMetaField
 unsigned char unknown3C[152];
};
}
#endif
