// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802BBAA4 (metaobject lbl_8053481C, vtable lbl_804DB3F4), size 0x34.
#ifndef META_BESAVEUTILINFORAM_H
#define META_BESAVEUTILINFORAM_H
#include <meta/beBaseInfoRam.h>
namespace Meta {
struct beSvDeliver;
struct beSaveUtilInfoRam : beBaseInfoRam {
 bool _isRdy;  // 0x2C igBoolMetaField
 unsigned char unknown2D[3];
 beSvDeliver *_deliver;  // 0x30 igObjectRefMetaField
};
}
#endif
