// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beSeData_register (metaobject lbl_80534808, vtable lbl_804DB46C), size 0x14.
#ifndef META_BESEDATA_H
#define META_BESEDATA_H
#include <meta/igNamedObject.h>
namespace Meta {
struct beSeData : igNamedObject {
 const char *_sound;  // 0x0C igStringMetaField
 short _delay;  // 0x10 igShortMetaField
 unsigned char unknown12[2];
};
}
#endif
