// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beSelectCtrlInfoRamData_register (metaobject lbl_805347B8, vtable lbl_804DB794), size 0x20.
#ifndef META_BESELECTCTRLINFORAMDATA_H
#define META_BESELECTCTRLINFORAMDATA_H
#include <meta/beBaseInfoData.h>
namespace Meta {
struct beSelectCtrlInfoWork;
struct beSelectCtrlInfoRamData : beBaseInfoData {
 bool _isTateSelect;  // 0x10 igBoolMetaField
 unsigned char unknown11[3];
 int _maxSelect;  // 0x14 igIntMetaField
 int _selectNo;  // 0x18 igIntMetaField
 beSelectCtrlInfoWork *_work;  // 0x1C igObjectRefMetaField
};
}
#endif
