// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beShadow01Info_register (metaobject lbl_80534798, vtable lbl_804DB8AC), size 0x28.
#ifndef META_BESHADOW01INFO_H
#define META_BESHADOW01INFO_H
#include <meta/beBaseInfo.h>
namespace Meta {
struct igNode;
struct igProjectiveShadowShader;
struct beShadow01Info : beBaseInfo {
 igNode *_receiverNode;  // 0x1C igObjectRefMetaField
 igNode *_casterNode;  // 0x20 igObjectRefMetaField
 igProjectiveShadowShader *_projShadowShader;  // 0x24 igObjectRefMetaField
};
}
#endif
