// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beShadow01_register (metaobject lbl_805347A8, vtable lbl_804DF760), size 0x30.
#ifndef META_BESHADOW01_H
#define META_BESHADOW01_H
#include <meta/beBaseInfoManager.h>
namespace Meta {
struct beShadow01InfoList;
struct beShadow01 : beBaseInfoManager {
 beShadow01InfoList *_svInfoList;  // 0x20 igObjectRefMetaField
 float _savePos[3];  // 0x24 igVec3fMetaField
};
}
#endif
