// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beShadow01InfoList_register (metaobject lbl_80534794, vtable lbl_804DB970), size 0x14.
#ifndef META_BESHADOW01INFOLIST_H
#define META_BESHADOW01INFOLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beShadow01InfoList : igObjectList {
};
}
#endif
