// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beSoundInfo_register (metaobject lbl_80534740, vtable lbl_804DBCD8), size 0x28.
#ifndef META_BESOUNDINFO_H
#define META_BESOUNDINFO_H
#include <meta/beBaseInfo.h>
namespace Meta {
struct igNamedObjectList;
struct beSoundInfo : beBaseInfo {
 igNamedObjectList *_fnameList;  // 0x1C igObjectRefMetaField
 const char *_dataType;  // 0x20 igStringMetaField
 short _baseVolume;  // 0x24 igShortMetaField
 short _sndfVolume;  // 0x26 igShortMetaField
};
}
#endif
