// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beSound_register (metaobject lbl_80534774, vtable lbl_804DF8DC), size 0x2C.
#ifndef META_BESOUND_H
#define META_BESOUND_H
#include <meta/beBaseInfoManager.h>
namespace Meta {
struct beCri;
struct bePlaySEList;
struct beSound : beBaseInfoManager {
 beCri *_cri;  // 0x20 igObjectRefMetaField
 const char *_currentBGM;  // 0x24 igStringMetaField
 bePlaySEList *_playSEs;  // 0x28 igObjectRefMetaField
};
}
#endif
