// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802B8CAC (metaobject lbl_80534754, vtable lbl_804DBBF4), size 0x20.
#ifndef META_BESOUNDDATA_H
#define META_BESOUNDDATA_H
#include <meta/beBaseInfoData.h>
namespace Meta {
struct beSoundData : beBaseInfoData {
 short _type;  // 0x10 igShortMetaField
 short _fnameIdx;  // 0x12 igShortMetaField
 int _memoryIdx;  // 0x14 igIntMetaField
 short _channel;  // 0x18 igShortMetaField
 short _volume;  // 0x1A igShortMetaField
 short _priority;  // 0x1C igShortMetaField
 unsigned char unknown1E[2];
};
}
#endif
