// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802B85E0 (metaobject lbl_80534730, vtable lbl_804DBD68), size 0x1C.
#ifndef META_BESTATICINFO_H
#define META_BESTATICINFO_H
#include <meta/beBaseInfo.h>
namespace Meta {
struct beStaticInfo : beBaseInfo {
};
}
#endif
