// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beSvFileFindApi_register (metaobject lbl_8053495C, vtable lbl_804E0E94), size 0xD4.
#ifndef META_BESVFILEFINDAPI_H
#define META_BESVFILEFINDAPI_H
#include <meta/beSaveApi.h>
namespace Meta {
struct beSvFileFindApi : beSaveApi {
};
}
#endif
