// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beSvSlotGC_register (metaobject lbl_805349C0, vtable lbl_804DADC0), size 0x18.
#ifndef META_BESVSLOTGC_H
#define META_BESVSLOTGC_H
#include <meta/beSvSlotData.h>
namespace Meta {
struct beSvSlotGC : beSvSlotData {
};
}
#endif
