// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802BF1A8 (metaobject lbl_80534960, vtable lbl_804E0F1C), size 0xE0.
#ifndef META_BESVFILEMAKEAPI_H
#define META_BESVFILEMAKEAPI_H
#include <meta/beSaveApi.h>
namespace Meta {
struct beSaveMemoryObj;
struct beSvPlatBaseData;
struct beSvFileMakeApi : beSaveApi {
 beSvPlatBaseData *_earlyGamedata;  // 0xD4 igObjectRefMetaField
 beSaveMemoryObj *_saveWork;  // 0xD8 igObjectRefMetaField
 unsigned char unknownDC[4];
};
}
#endif
