// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beSvSlotDataList_register (metaobject lbl_805349B8, vtable lbl_804DAF50), size 0x14.
#ifndef META_BESVSLOTDATALIST_H
#define META_BESVSLOTDATALIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beSvSlotDataList : igObjectList {
};
}
#endif
