// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802BE6B4 (metaobject lbl_8053493C, vtable lbl_804E0CFC), size 0xEC.
#ifndef META_BESVREADMEDIAAPI_H
#define META_BESVREADMEDIAAPI_H
#include <meta/beSaveApi.h>
namespace Meta {
struct beSaveDataDeliver;
struct beSvPlatBaseData;
struct igObjectList;
struct beSvReadMediaApi : beSaveApi {
 beSaveDataDeliver *_gameData;  // 0xD4 igObjectRefMetaField
 beSvPlatBaseData *_outputGamedata;  // 0xD8 igObjectRefMetaField
 int _oneSvDataSize;  // 0xDC igIntMetaField
 beSaveDataDeliver *_lodeData;  // 0xE0 igObjectRefMetaField
 igObjectList *_loadWorkList;  // 0xE4 igObjectRefMetaField
 unsigned char unknownE8[4];
};
}
#endif
