// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beSvUseCheckApi_register (metaobject lbl_80534954, vtable lbl_804E0D84), size 0xD4.
#ifndef META_BESVUSECHECKAPI_H
#define META_BESVUSECHECKAPI_H
#include <meta/beSaveApi.h>
namespace Meta {
struct beSvUseCheckApi : beSaveApi {
};
}
#endif
