// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802BCC28 (metaobject lbl_80534864, vtable lbl_804DB130), size 0xD8.
// Note: _bgColor0: igShortArrayMetaField, count from the space to the next member.
// Note: _bgColor1: igShortArrayMetaField, count from the space to the next member.
// Note: _bgColor2: igShortArrayMetaField, count from the space to the next member.
// Note: _bgColor3: igShortArrayMetaField, count from the space to the next member.
// Note: _lightDir0: igFloatArrayMetaField, count from the space to the next member.
// Note: _lightDir1: igFloatArrayMetaField, count from the space to the next member.
// Note: _lightDir2: igFloatArrayMetaField, count from the space to the next member.
// Note: _lightColor0: igFloatArrayMetaField, count from the space to the next member.
// Note: _lightColor1: igFloatArrayMetaField, count from the space to the next member.
// Note: _lightColor2: igFloatArrayMetaField, count from the space to the next member.
// Note: _ambient: igFloatArrayMetaField, count from the space to the next member.
// Note: _dataOffSet: igIntArrayMetaField, count from the space to the next member.
#ifndef META_BESVPLATDATAPS2_H
#define META_BESVPLATDATAPS2_H
#include <meta/beSvPlatBaseData.h>
namespace Meta {
struct igObjectList;
struct beSvPlatDataPS2 : beSvPlatBaseData {
 const char *_dirName;  // 0x18 igStringMetaField
 const char *_title;  // 0x1C igStringMetaField
 unsigned short _offsLF;  // 0x20 igUnsignedShortMetaField
 unsigned char unknown22[2];
 unsigned int _transRate;  // 0x24 igUnsignedIntMetaField
 short _bgColor0[4];  // 0x28 igShortArrayMetaField
 short _bgColor1[4];  // 0x30 igShortArrayMetaField
 short _bgColor2[4];  // 0x38 igShortArrayMetaField
 short _bgColor3[4];  // 0x40 igShortArrayMetaField
 float _lightDir0[4];  // 0x48 igFloatArrayMetaField
 float _lightDir1[4];  // 0x58 igFloatArrayMetaField
 float _lightDir2[4];  // 0x68 igFloatArrayMetaField
 float _lightColor0[4];  // 0x78 igFloatArrayMetaField
 float _lightColor1[4];  // 0x88 igFloatArrayMetaField
 float _lightColor2[4];  // 0x98 igFloatArrayMetaField
 float _ambient[4];  // 0xA8 igFloatArrayMetaField
 const char *_fnameIcon0;  // 0xB8 igStringMetaField
 const char *_fnameIcon1;  // 0xBC igStringMetaField
 const char *_fnameIcon2;  // 0xC0 igStringMetaField
 int _dataOffSet[2];  // 0xC4 igIntArrayMetaField
 unsigned int _saveDataSize;  // 0xCC igUnsignedIntMetaField
 int _iconCount;  // 0xD0 igIntMetaField
 igObjectList *_image;  // 0xD4 igObjectRefMetaField
};
}
#endif
