// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beSvWriteMediaApi_register (metaobject lbl_80534930, vtable lbl_804E0C74), size 0xE0.
#ifndef META_BESVWRITEMEDIAAPI_H
#define META_BESVWRITEMEDIAAPI_H
#include <meta/beSaveApi.h>
namespace Meta {
struct beSaveMemoryObj;
struct beSvPlatBaseData;
struct beSvWriteMediaApi : beSaveApi {
 beSvPlatBaseData *_nowGamedata;  // 0xD4 igObjectRefMetaField
 beSaveMemoryObj *_saveWork;  // 0xD8 igObjectRefMetaField
 unsigned char unknownDC[4];
};
}
#endif
