// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802BC590 (metaobject lbl_80534840, vtable lbl_804DB218), size 0x2C.
// Note: _dataOffSet: igIntArrayMetaField, count from the space to the next member.
#ifndef META_BESVPLATDATAXBOX_H
#define META_BESVPLATDATAXBOX_H
#include <meta/beSvPlatBaseData.h>
namespace Meta {
struct beXboxImage24k;
struct beSvPlatDataXbox : beSvPlatBaseData {
 int _dataOffSet[2];  // 0x18 igIntArrayMetaField
 int _imageSize;  // 0x20 igIntMetaField
 beXboxImage24k *_image;  // 0x24 igObjectRefMetaField
 unsigned int _saveDataSize;  // 0x28 igUnsignedIntMetaField
};
}
#endif
