// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802BF680 (metaobject lbl_805349A4, vtable lbl_804DB2EC), size 0x18.
#ifndef META_BESVPLATBASEDATA_H
#define META_BESVPLATBASEDATA_H
#include <meta/igObject.h>
namespace Meta {
struct beSvSlotDataList;
struct beSvPlatBaseData : igObject {
 int _connectMax;  // 0x08 igIntMetaField
 beSvSlotDataList *_slotList;  // 0x0C igObjectRefMetaField
 unsigned int _dataSize;  // 0x10 igUnsignedIntMetaField
 unsigned int _memNeed;  // 0x14 igUnsignedIntMetaField
};
}
#endif
