// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beSvSlotPS2_register (metaobject lbl_805349BC, vtable lbl_804DAE38), size 0x18.
#ifndef META_BESVSLOTPS2_H
#define META_BESVSLOTPS2_H
#include <meta/beSvSlotData.h>
namespace Meta {
struct beSvSlotPS2 : beSvSlotData {
};
}
#endif
