// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802C073C (metaobject lbl_80534A04, vtable lbl_804DAC4C), size 0x44.
#ifndef META_BESVDELIVER_H
#define META_BESVDELIVER_H
#include <meta/igObject.h>
namespace Meta {
struct beSaveDataDeliver;
struct beSvPlatBaseData;
struct igIntList;
struct beSvDeliver : igObject {
 beSaveDataDeliver *_gameData;  // 0x08 igObjectRefMetaField
 igIntList *_actConnect;  // 0x0C igObjectRefMetaField
 int _targetConnect;  // 0x10 igIntMetaField
 int _saveVer;  // 0x14 igIntMetaField
 int _result;  // 0x18 igIntMetaField
 int _operate;  // 0x1C igIntMetaField
 int _memCapa;  // 0x20 igIntMetaField
 int _fileCapa;  // 0x24 igIntMetaField
 signed char _useMtap;  // 0x28 igCharMetaField
 signed char _chgUseMtap;  // 0x29 igCharMetaField
 bool _isMemCapaOK;  // 0x2A igBoolMetaField
 bool _isfileCapaOK;  // 0x2B igBoolMetaField
 bool _isEndOperat;  // 0x2C igBoolMetaField
 unsigned char unknown2D[3];
 igIntList *_freeSizeList;  // 0x30 igObjectRefMetaField
 igIntList *_freeFileList;  // 0x34 igObjectRefMetaField
 igIntList *_formatList;  // 0x38 igObjectRefMetaField
 igIntList *_totalSizeList;  // 0x3C igObjectRefMetaField
 beSvPlatBaseData *_platformData;  // 0x40 igObjectRefMetaField
};
}
#endif
