// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beSvEndApi_register (metaobject lbl_80534910, vtable lbl_804E0ADC), size 0xD4.
#ifndef META_BESVENDAPI_H
#define META_BESVENDAPI_H
#include <meta/beSaveApi.h>
namespace Meta {
struct beSvEndApi : beSaveApi {
};
}
#endif
