// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beSvConnectCheck_register (metaobject lbl_8053490C, vtable lbl_804E0A54), size 0xF4.
#ifndef META_BESVCONNECTCHECK_H
#define META_BESVCONNECTCHECK_H
#include <meta/beSaveApi.h>
namespace Meta {
struct beSvConnectCheck : beSaveApi {
 unsigned char unknownD4[32];
};
}
#endif
