// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802BEC88 (metaobject lbl_80534958, vtable lbl_804E0E0C), size 0xD4.
#ifndef META_BESVFORMATAPI_H
#define META_BESVFORMATAPI_H
#include <meta/beSaveApi.h>
namespace Meta {
struct beSvFormatApi : beSaveApi {
};
}
#endif
