// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beSwitchCtrl_register (metaobject lbl_80534720, vtable lbl_804DF9F8), size 0x20.
#ifndef META_BESWITCHCTRL_H
#define META_BESWITCHCTRL_H
#include <meta/beBaseInfoManager.h>
namespace Meta {
struct beSwitchCtrl : beBaseInfoManager {
};
}
#endif
