// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beTextureCtrlAttr_register (metaobject lbl_80534670, vtable lbl_804DBF60), size 0x10.
#ifndef META_BETEXTURECTRLATTR_H
#define META_BETEXTURECTRLATTR_H
#include <meta/igNamedObject.h>
namespace Meta {
struct igAttrSet;
struct beTextureCtrlAttr : igNamedObject {
 igAttrSet *_attrSet;  // 0x0C igObjectRefMetaField
};
}
#endif
