// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802B5DB8 (metaobject lbl_8053464C, vtable lbl_804DC188), size 0x20.
#ifndef META_BETIMERDATA_H
#define META_BETIMERDATA_H
#include <meta/igObject.h>
namespace Meta {
struct beTimerData : igObject {
 long long _startTime;  // 0x08 igLongMetaField
 const char *_resetCondition;  // 0x10 igStringMetaField
 const char *_callLuaFile;  // 0x14 igStringMetaField
 long long _downTimer;  // 0x18 igLongMetaField
};
}
#endif
