// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beTimerDataList_register (metaobject lbl_80534648, vtable lbl_804DC244), size 0x14.
#ifndef META_BETIMERDATALIST_H
#define META_BETIMERDATALIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beTimerDataList : igObjectList {
};
}
#endif
