// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802D9334 (metaobject lbl_8053533C, vtable lbl_804DDF38), size 0x10.
#ifndef META_BEUNICODEOBJ_H
#define META_BEUNICODEOBJ_H
#include <meta/igNamedObject.h>
namespace Meta {
struct beUnicodeObj : igNamedObject {
 void *_buffer;  // 0x0C igMemoryRefMetaField
};
}
#endif
