// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802B4394 (metaobject lbl_8053457C, vtable lbl_804DC704), size 0xB8.
#ifndef META_BEWATERPLAININFORAM_H
#define META_BEWATERPLAININFORAM_H
#include <meta/beBaseInfoRam.h>
namespace Meta {
struct beWaterMove;
struct igFloatList;
struct igFloatListList;
struct igIntList;
struct igVertexArray;
struct beWaterPlainInfoRam : beBaseInfoRam {
 float _dampeningCoefficient;  // 0x2C igFloatMetaField
 float _A;  // 0x30 igFloatMetaField
 float _B;  // 0x34 igFloatMetaField
 float _waveSpeed;  // 0x38 igFloatMetaField
 float _shallmin;  // 0x3C igFloatMetaField
 float _shallmax;  // 0x40 igFloatMetaField
 float _shalldamp;  // 0x44 igFloatMetaField
 float _deepmin;  // 0x48 igFloatMetaField
 float _deepmax;  // 0x4C igFloatMetaField
 float _deepdamp;  // 0x50 igFloatMetaField
 igVertexArray *_vertexArray;  // 0x54 igObjectRefMetaField
 igFloatList *_dampeningGrid;  // 0x58 igObjectRefMetaField
 igIntList *_dplist2VertexNO;  // 0x5C igObjectRefMetaField
 unsigned int _mapWidth;  // 0x60 igUnsignedIntMetaField
 unsigned int _mapHeight;  // 0x64 igUnsignedIntMetaField
 float _pos[3];  // 0x68 igVec3fMetaField
 float _areaMax[3];  // 0x74 igVec3fMetaField
 float _areaMin[3];  // 0x80 igVec3fMetaField
 float _xsize;  // 0x8C igFloatMetaField
 float _zsize;  // 0x90 igFloatMetaField
 float _cellSize;  // 0x94 igFloatMetaField
 igFloatListList *_gridLists;  // 0x98 igObjectRefMetaField
 float _maxY;  // 0x9C igFloatMetaField
 float _minY;  // 0xA0 igFloatMetaField
 float _defaultY;  // 0xA4 igFloatMetaField
 long long _updateTime;  // 0xA8 igLongMetaField
 beWaterMove *_waterMove;  // 0xB0 igObjectRefMetaField
 unsigned char unknownB4[4];
};
}
#endif
