// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802B4AB0 (metaobject lbl_80534608, vtable lbl_804DC4F4), size 0x18.
#ifndef META_BEWATERMOVEDATA_H
#define META_BEWATERMOVEDATA_H
#include <meta/igObject.h>
namespace Meta {
struct igVec3fList;
struct beWaterMoveData : igObject {
 long long _time;  // 0x08 igLongMetaField
 float _power;  // 0x10 igFloatMetaField
 igVec3fList *_posList;  // 0x14 igObjectRefMetaField
};
}
#endif
