// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beWeaponAttachData_register (metaobject lbl_80534568, vtable lbl_804DC960), size 0x10.
#ifndef META_BEWEAPONATTACHDATA_H
#define META_BEWEAPONATTACHDATA_H
#include <meta/igObject.h>
namespace Meta {
struct igAppearanceListList;
struct igModelViewMatrixBoneSelectList;
struct beWeaponAttachData : igObject {
 igModelViewMatrixBoneSelectList *_boneSelectList;  // 0x08 igObjectRefMetaField
 igAppearanceListList *_appearanceListList;  // 0x0C igObjectRefMetaField
};
}
#endif
