// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beWeaponSeqDataList_register (metaobject lbl_8053454C, vtable lbl_804DCBBC), size 0x14.
#ifndef META_BEWEAPONSEQDATALIST_H
#define META_BEWEAPONSEQDATALIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beWeaponSeqDataList : igObjectList {
};
}
#endif
