// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802B3A48 (metaobject lbl_80534564, vtable lbl_804DCA1C), size 0x14.
#ifndef META_BEWEAPONATTACHDATALIST_H
#define META_BEWEAPONATTACHDATALIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct beWeaponAttachDataList : igObjectList {
};
}
#endif
