// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by beWeaponInfoRam_register (metaobject lbl_80534538, vtable lbl_804DCD94), size 0x2C.
#ifndef META_BEWEAPONINFORAM_H
#define META_BEWEAPONINFORAM_H
#include <meta/beBaseInfoRam.h>
namespace Meta {
struct beWeaponInfoRam : beBaseInfoRam {
};
}
#endif
