// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802B325C (metaobject lbl_80534550, vtable lbl_804DCB00), size 0x10.
#ifndef META_BEWEAPONSEQDATA_H
#define META_BEWEAPONSEQDATA_H
#include <meta/igNamedObject.h>
namespace Meta {
struct beWeaponSeqData : igNamedObject {
 const char *_label;  // 0x0C igStringMetaField
};
}
#endif
