// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802B2DA0 (metaobject lbl_8053453C, vtable lbl_804DCCB0), size 0x28.
#ifndef META_BEWEAPONINFO_H
#define META_BEWEAPONINFO_H
#include <meta/beBaseInfo.h>
namespace Meta {
struct beWeaponSeqDataList;
struct igNamedObjectList;
struct igNodeList;
struct beWeaponInfo : beBaseInfo {
 igNodeList *_nodeList;  // 0x1C igObjectRefMetaField
 igNamedObjectList *_boneNameList;  // 0x20 igObjectRefMetaField
 beWeaponSeqDataList *_seqDataList;  // 0x24 igObjectRefMetaField
};
}
#endif
