// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8012287C (metaobject lbl_80563A34, vtable lbl_8049A32C), size 0x20.
#ifndef META_IGAABOX_H
#define META_IGAABOX_H
#include <meta/igVolume.h>
namespace Meta {
struct igAABox : igVolume {
 float _min[3];  // 0x08 igVec3fMetaField
 float _max[3];  // 0x14 igVec3fMetaField
};
}
#endif
