// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igAABoxList_register (metaobject lbl_80563A30, vtable lbl_8049A388), size 0x14.
#ifndef META_IGAABOXLIST_H
#define META_IGAABOXLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igAABoxList : igObjectList {
};
}
#endif
