// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801105D4 (metaobject lbl_805636AC, vtable lbl_80496284), size 0x18.
#ifndef META_IGACTIVECOMPONENTSOBSERVER_H
#define META_IGACTIVECOMPONENTSOBSERVER_H
#include <meta/igView.h>
namespace Meta {
struct igGuiComponent;
struct igActiveComponentsObserver : igView {
 igGuiComponent *_oldComponentUnderMouse;  // 0x0C igObjectRefMetaField
 igGuiComponent *_oldFocusedComponent;  // 0x10 igObjectRefMetaField
 igGuiComponent *_oldPushedComponent;  // 0x14 igObjectRefMetaField
};
}
#endif
