// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igActorInfo_register (metaobject lbl_80565584, vtable lbl_804B58AC), size 0x28.
#ifndef META_IGACTORINFO_H
#define META_IGACTORINFO_H
#include <meta/igInfo.h>
namespace Meta {
struct igActor;
struct igActorList;
struct igAnimationCombinerList;
struct igAnimationDatabase;
struct igAppearanceList;
struct igActorInfo : igInfo {
 igActor *_actor;  // 0x14 igObjectRefMetaField
 igActorList *_actorList;  // 0x18 igObjectRefMetaField
 igAnimationDatabase *_animationDatabase;  // 0x1C igObjectRefMetaField
 igAnimationCombinerList *_combinerList;  // 0x20 igObjectRefMetaField
 igAppearanceList *_appearanceList;  // 0x24 igObjectRefMetaField
};
}
#endif
