// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80115AA4 (metaobject lbl_805638AC), size 0x8.
#ifndef META_IGACTION_H
#define META_IGACTION_H
#include <meta/igObject.h>
namespace Meta {
struct igAction : igObject {
};
}
#endif
