// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igAdx_register (metaobject lbl_80534350, vtable lbl_804CD7E0), size 0x8.
#ifndef META_IGADX_H
#define META_IGADX_H
#include <meta/igObject.h>
namespace Meta {
struct igAdx : igObject {
};
}
#endif
