// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802AAAB8 (metaobject lbl_80534354, vtable lbl_804CE588), size 0x14.
#ifndef META_IGADXAFSFILELIST_H
#define META_IGADXAFSFILELIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igAdxAfsFileList : igObjectList {
};
}
#endif
