// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igAdxFile_register (metaobject lbl_80534370, vtable lbl_804CD89C), size 0x68.
#ifndef META_IGADXFILE_H
#define META_IGADXFILE_H
#include <meta/igFile.h>
namespace Meta {
struct igAdxFile : igFile {
 bool _bIsOpen;  // 0x2C igBoolMetaField
 unsigned char unknown2D[3];
 void *_pBuffer;  // 0x30 igRawRefMetaField
 void *_pBufferPtr;  // 0x34 igRawRefMetaField
 void *_pTmpBuffer;  // 0x38 igRawRefMetaField
 bool _bUseAsync;  // 0x3C igBoolMetaField
 bool _bUseAlchemyAsync;  // 0x3D igBoolMetaField
 bool _bUseBuffer;  // 0x3E igBoolMetaField
 bool _bBufferFilled;  // 0x3F igBoolMetaField
 int _iBufferSize;  // 0x40 igIntMetaField
 int _iBufferPos;  // 0x44 igIntMetaField
 int _iSeekPosition;  // 0x48 igIntMetaField
 int _iFileSize;  // 0x4C igIntMetaField
 int _iSectorSize;  // 0x50 igIntMetaField
 unsigned char unknown54[4];
 unsigned long long _lSleepTime;  // 0x58 igUnsignedLongMetaField
 unsigned char unknown60[8];
};
}
#endif
