// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igAliasMemoryPool_register (metaobject lbl_80561E5C), size 0xB8.
#ifndef META_IGALIASMEMORYPOOL_H
#define META_IGALIASMEMORYPOOL_H
#include <meta/igMemoryPool.h>
namespace Meta {
struct igEventTracker;
struct igMemoryPool;
struct igSemaphore;
struct igAliasMemoryPool : igMemoryPool {
 bool _isActive;  // 0x70 igBoolMetaField
 bool _isReassignable;  // 0x71 igBoolMetaField
 unsigned char unknown72[2];
 igSemaphore *_allocationLock;  // 0x74 igObjectRefMetaField
 int _poolIndex;  // 0x78 igIntMetaField
 unsigned char unknown7C[4];
 unsigned long long _allocedBytes;  // 0x80 igUnsignedLongMetaField
 int _nAllocs;  // 0x88 igIntMetaField
 int _nFrees;  // 0x8C igIntMetaField
 unsigned long long _maxSize;  // 0x90 igUnsignedLongMetaField
 igEventTracker *_eventTracker;  // 0x98 igObjectRefMetaField
 unsigned char unknown9C[4];
 unsigned long long _allocedBytesHigh;  // 0xA0 igUnsignedLongMetaField
 int _netAllocsHigh;  // 0xA8 igIntMetaField
 unsigned int _elementSize;  // 0xAC igUnsignedIntMetaField
 unsigned short _alignment;  // 0xB0 igUnsignedShortMetaField
 unsigned char unknownB2[2];
 igMemoryPool *_aliasedMemoryPool;  // 0xB4 igObjectRefMetaField
};
}
#endif
