// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igAlphaFunctionAttr_register (metaobject lbl_80562A7C, vtable lbl_8047D67C), size 0x14.
#ifndef META_IGALPHAFUNCTIONATTR_H
#define META_IGALPHAFUNCTIONATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igAlphaFunctionAttr : igVisualAttribute {
 int _func;  // 0x0C igEnumMetaField
 float _refValue;  // 0x10 igFloatMetaField
};
}
#endif
