// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80131350 (metaobject lbl_80563B00, vtable lbl_804A2EAC), size 0xC.
#ifndef META_IGALLNODESTATISTICS_H
#define META_IGALLNODESTATISTICS_H
#include <meta/igObject.h>
namespace Meta {
struct igGenericNodeStatisticsList;
struct igAllNodeStatistics : igObject {
 igGenericNodeStatisticsList *_nodeStatisticsList;  // 0x08 igObjectRefMetaField
};
}
#endif
