// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igAnimationCombinerList_register (metaobject lbl_805654B0, vtable lbl_804B6008), size 0x14.
#ifndef META_IGANIMATIONCOMBINERLIST_H
#define META_IGANIMATIONCOMBINERLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igAnimationCombinerList : igObjectList {
};
}
#endif
