// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igAnimationCombinerBoneInfoListList_register (metaobject lbl_80565484, vtable lbl_804B61F4), size 0x14.
#ifndef META_IGANIMATIONCOMBINERBONEINFOLISTLIST_H
#define META_IGANIMATIONCOMBINERBONEINFOLISTLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igAnimationCombinerBoneInfoListList : igObjectList {
};
}
#endif
