// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igAnimationCombinerBoneInfoPool_register (metaobject lbl_80565480, vtable lbl_804B62BC), size 0x20.
#ifndef META_IGANIMATIONCOMBINERBONEINFOPOOL_H
#define META_IGANIMATIONCOMBINERBONEINFOPOOL_H
#include <meta/igObjectPool.h>
namespace Meta {
struct igAnimationCombinerBoneInfoPool : igObjectPool {
};
}
#endif
