// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801CA744 (metaobject lbl_8056544C, vtable lbl_804B64A8), size 0x14.
#ifndef META_IGANIMATIONMODIFIERLIST_H
#define META_IGANIMATIONMODIFIERLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igAnimationModifierList : igObjectList {
};
}
#endif
