// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igAnimationTransitionDefinitionList_register (metaobject lbl_80565534, vtable lbl_804B5CD8), size 0x14.
#ifndef META_IGANIMATIONTRANSITIONDEFINITIONLIST_H
#define META_IGANIMATIONTRANSITIONDEFINITIONLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igAnimationTransitionDefinitionList : igObjectList {
};
}
#endif
