// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801CB68C (metaobject lbl_8056548C, vtable lbl_804B60D0), size 0x3C.
#ifndef META_IGANIMATIONCOMBINERBONEINFO_H
#define META_IGANIMATIONCOMBINERBONEINFO_H
#include <meta/igObject.h>
namespace Meta {
struct igAnimationState;
struct igTransformSource;
struct igAnimationCombinerBoneInfo : igObject {
 int _lastKeyframe;  // 0x08 igIntMetaField
 igAnimationState *_animationState;  // 0x0C igObjectRefMetaField
 igTransformSource *_transformSource;  // 0x10 igObjectRefMetaField
 float _constantQuaternion[4];  // 0x14 igVec4fMetaField
 float _constantTranslation[3];  // 0x24 igVec3fMetaField
 int _priority;  // 0x30 igIntMetaField
 bool _useAnimationTranslation;  // 0x34 igBoolMetaField
 unsigned char unknown35[3];
 int _reflect;  // 0x38 igIntMetaField
};
}
#endif
