// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igAnimation_register (metaobject lbl_80565510, vtable lbl_804B76E0), size 0x40.
#ifndef META_IGANIMATION_H
#define META_IGANIMATION_H
#include <meta/igNamedObject.h>
namespace Meta {
struct igAnimationBindingList;
struct igAnimationTrackList;
struct igAnimationTransitionDefinitionList;
struct igBitMask;
struct igAnimation : igNamedObject {
 int _priority;  // 0x0C igIntMetaField
 igAnimationBindingList *_bindingList;  // 0x10 igObjectRefMetaField
 igAnimationTrackList *_trackList;  // 0x14 igObjectRefMetaField
 igAnimationTransitionDefinitionList *_transitionList;  // 0x18 igObjectRefMetaField
 unsigned char unknown1C[4];
 long long _keyFrameTimeOffset;  // 0x20 igLongMetaField
 long long _startTime;  // 0x28 igLongMetaField
 long long _duration;  // 0x30 igLongMetaField
 igBitMask *_useAnimationTransBoolArray;  // 0x38 igObjectRefMetaField
 unsigned char unknown3C[4];
};
}
#endif
