// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igAnimationBindingList_register (metaobject lbl_805654F0, vtable lbl_804B5EC4), size 0x14.
#ifndef META_IGANIMATIONBINDINGLIST_H
#define META_IGANIMATIONBINDINGLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igAnimationBindingList : igObjectList {
};
}
#endif
