// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igAnimationTransitionDefinition_register (metaobject lbl_80565538, vtable lbl_804B5C7C), size 0x14.
#ifndef META_IGANIMATIONTRANSITIONDEFINITION_H
#define META_IGANIMATIONTRANSITIONDEFINITION_H
#include <meta/igObject.h>
namespace Meta {
struct igAnimation;
struct igAnimationTransitionParams;
struct igAnimationTransitionPointList;
struct igAnimationTransitionDefinition : igObject {
 igAnimation *_baseAnimation;  // 0x08 igObjectRefMetaField
 igAnimationTransitionPointList *_transitionPointList;  // 0x0C igObjectRefMetaField
 igAnimationTransitionParams *_params;  // 0x10 igObjectRefMetaField
};
}
#endif
