// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igAnimationTrackList_register (metaobject lbl_8056556C, vtable lbl_804B5A34), size 0x14.
#ifndef META_IGANIMATIONTRACKLIST_H
#define META_IGANIMATIONTRACKLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igAnimationTrackList : igObjectList {
};
}
#endif
