// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801CCE78 (metaobject lbl_80565548, vtable lbl_804B5BB4), size 0x14.
#ifndef META_IGANIMATIONTRANSITIONPOINTLIST_H
#define META_IGANIMATIONTRANSITIONPOINTLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igAnimationTransitionPointList : igObjectList {
};
}
#endif
