// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801CC214 (metaobject lbl_805654F4, vtable lbl_804B5E68), size 0x1C.
#ifndef META_IGANIMATIONBINDING_H
#define META_IGANIMATIONBINDING_H
#include <meta/igObject.h>
namespace Meta {
struct igAnimationHierarchy;
struct igBitMask;
struct igIntList;
struct igAnimationBinding : igObject {
 igAnimationHierarchy *_hierarchy;  // 0x08 igObjectRefMetaField
 void *_boneTrackIdxArray;  // 0x0C igMemoryRefMetaField
 int _bindCount;  // 0x10 igIntMetaField
 igIntList *_chainSwapList;  // 0x14 igObjectRefMetaField
 igBitMask *_reflectTrack;  // 0x18 igObjectRefMetaField
};
}
#endif
