// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801C95D8 (metaobject lbl_805653A8, vtable lbl_804B675C), size 0x20.
#ifndef META_IGANIMATIONSTATEPOOL_H
#define META_IGANIMATIONSTATEPOOL_H
#include <meta/igObjectPool.h>
namespace Meta {
struct igAnimationStatePool : igObjectPool {
};
}
#endif
