// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igAnimationSystem_register (metaobject lbl_805653A0), size 0x10.
#ifndef META_IGANIMATIONSYSTEM_H
#define META_IGANIMATIONSYSTEM_H
#include <meta/igNamedObject.h>
namespace Meta {
struct igAnimationHierarchy;
struct igAnimationSystem : igNamedObject {
 igAnimationHierarchy *_animHierarchy;  // 0x0C igObjectRefMetaField
};
}
#endif
