// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801C9F34 (metaobject lbl_8056542C, vtable lbl_804B5608), size 0x18.
#ifndef META_IGANIMATIONINFO_H
#define META_IGANIMATIONINFO_H
#include <meta/igInfo.h>
namespace Meta {
struct igAnimationTokenList;
struct igAnimationInfo : igInfo {
 igAnimationTokenList *_data;  // 0x14 igObjectRefMetaField
};
}
#endif
