// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igAnimationCombiner_register (metaobject lbl_805654B4, vtable lbl_804B56D0), size 0x60.
#ifndef META_IGANIMATIONCOMBINER_H
#define META_IGANIMATIONCOMBINER_H
#include <meta/igAnimationSystem.h>
namespace Meta {
struct igAnimationCombinerBoneInfoListList;
struct igAnimationStateList;
struct igIntList;
struct igAnimationCombiner : igAnimationSystem {
 long long _animationStateTime;  // 0x10 igLongMetaField
 long long _lastCleanStatesTime;  // 0x18 igLongMetaField
 long long _cleanStatesTimeThreshold;  // 0x20 igLongMetaField
 long long _cleanStatesTransitionMargin;  // 0x28 igLongMetaField
 igAnimationCombinerBoneInfoListList *_boneInfoListList;  // 0x30 igObjectRefMetaField
 igIntList *_boneInfoListBase;  // 0x34 igObjectRefMetaField
 igAnimationStateList *_animationStateList;  // 0x38 igObjectRefMetaField
 void *_resultQuaternionArray;  // 0x3C igMemoryRefMetaField
 void *_animationCacheMatrixArray;  // 0x40 igMemoryRefMetaField
 unsigned char unknown44[4];
 long long _cacheTime;  // 0x48 igLongMetaField
 bool _cacheValid;  // 0x50 igBoolMetaField
 bool _hierarchyUpdated;  // 0x51 igBoolMetaField
 unsigned char unknown52[2];
 void *_boneMatrixArray;  // 0x54 igMemoryRefMetaField
 void *_blendMatrixArray;  // 0x58 igMemoryRefMetaField
 unsigned char unknown5C[4];
};
}
#endif
