// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802B3F00 (metaobject lbl_80534574, vtable lbl_804DC884), size 0x14.
#ifndef META_IGAPPEARANCELISTLIST_H
#define META_IGAPPEARANCELISTLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igAppearanceListList : igObjectList {
};
}
#endif
