// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igAppearance_register (metaobject lbl_80565388, vtable lbl_804B6824), size 0x20.
#ifndef META_IGAPPEARANCE_H
#define META_IGAPPEARANCE_H
#include <meta/igNamedObject.h>
namespace Meta {
struct igModelViewMatrixBoneSelectList;
struct igNodeList;
struct igSkin;
struct igSkinList;
struct igStringObjList;
struct igAppearance : igNamedObject {
 igSkin *_skin;  // 0x0C igObjectRefMetaField
 igSkinList *_attachedSkins;  // 0x10 igObjectRefMetaField
 igModelViewMatrixBoneSelectList *_attachedGraphs;  // 0x14 igObjectRefMetaField
 igStringObjList *_segmentOverrideNameList;  // 0x18 igObjectRefMetaField
 igNodeList *_segmentOverrideGraphList;  // 0x1C igObjectRefMetaField
};
}
#endif
