// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80152C44 (metaobject lbl_8056456C, vtable lbl_804A86D0), size 0x28.
#ifndef META_IGATTREDITFORLIGHTSTATESET_H
#define META_IGATTREDITFORLIGHTSTATESET_H
#include <meta/igAttrEditForNode.h>
namespace Meta {
struct igAttrEditForLightStateSet : igAttrEditForNode {
};
}
#endif
