// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801C84E4 (metaobject lbl_8056534C, vtable lbl_804B6AD0), size 0x14.
#ifndef META_IGATTRSTACKLIST_H
#define META_IGATTRSTACKLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igAttrStackList : igObjectList {
};
}
#endif
