// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igAttrEditForNode_register (metaobject lbl_8056458C), size 0x28.
#ifndef META_IGATTREDITFORNODE_H
#define META_IGATTREDITFORNODE_H
#include <meta/igAttrEdit.h>
namespace Meta {
struct igAttrEditForNode : igAttrEdit {
};
}
#endif
