// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igAttrStack_register (metaobject lbl_80565350, vtable lbl_804B6A10), size 0x34.
#ifndef META_IGATTRSTACK_H
#define META_IGATTRSTACK_H
#include <meta/igNonRefCountedObjectStack.h>
namespace Meta {
struct igAttr;
struct igRenderPackage;
struct igAttrStack : igNonRefCountedObjectStack {
 igAttr *_default;  // 0x14 igObjectRefMetaField
 int _cachedOverride;  // 0x18 igIntMetaField
 void *_popProc;  // 0x1C igRawRefMetaField
 bool _hasChangedFromLastIncrementalFlush;  // 0x20 igBoolMetaField
 unsigned char unknown21[3];
 igAttr *_lastIncrementalFlushedAttr;  // 0x24 igObjectRefMetaField
 bool _hasChangedFromRoot;  // 0x28 igBoolMetaField
 unsigned char unknown29[3];
 igAttr *_lastFlushedAttr;  // 0x2C igObjectRefMetaField
 igRenderPackage *_cachedRenderPackage;  // 0x30 igObjectRefMetaField
};
}
#endif
