// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800BB228 (metaobject lbl_80562A58), size 0x8.
#ifndef META_IGATTRDEFAULTMANAGER_H
#define META_IGATTRDEFAULTMANAGER_H
#include <meta/igObject.h>
namespace Meta {
struct igAttrDefaultManager : igObject {
};
}
#endif
