// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800C7034 (metaobject lbl_80562B24), size 0xC.
#ifndef META_IGAUDIOCONTEXT_H
#define META_IGAUDIOCONTEXT_H
#include <meta/igObject.h>
namespace Meta {
struct igAudioContext : igObject {
 bool _immediateMode;  // 0x08 igBoolMetaField
 unsigned char unknown09[3];
};
}
#endif
