// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igBase_register (metaobject lbl_8056455C), size 0x20.
#ifndef META_IGBASE_H
#define META_IGBASE_H
#include <meta/igInterfaced.h>
namespace Meta {
struct igBase : igInterfaced {
};
}
#endif
