// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igBellFilterFun_register (metaobject lbl_805642C4, vtable lbl_804A8DE8), size 0x10.
#ifndef META_IGBELLFILTERFUN_H
#define META_IGBELLFILTERFUN_H
#include <meta/igSerialFilterFun.h>
namespace Meta {
struct igBellFilterFun : igSerialFilterFun {
};
}
#endif
