// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801C7448 (metaobject lbl_805652CC, vtable lbl_804B6CF4), size 0x18.
#ifndef META_IGBITMASK_H
#define META_IGBITMASK_H
#include <meta/igUnsignedIntList.h>
namespace Meta {
struct igBitMask : igUnsignedIntList {
 unsigned int _bitCount;  // 0x14 igUnsignedIntMetaField
};
}
#endif
