// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igBillboardProcessor_register (metaobject lbl_805652D8, vtable lbl_804B5434), size 0x28.
#ifndef META_IGBILLBOARDPROCESSOR_H
#define META_IGBILLBOARDPROCESSOR_H
#include <meta/igShaderProcessor.h>
namespace Meta {
struct igModelViewMatrixAttr;
struct igBillboardProcessor : igShaderProcessor {
 int _mode;  // 0x08 igEnumMetaField
 float _axis[3];  // 0x0C igVec3fMetaField
 float _origin[3];  // 0x18 igVec3fMetaField
 igModelViewMatrixAttr *_modelViewMatrix;  // 0x24 igObjectRefMetaField
};
}
#endif
