// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801C7A68 (metaobject lbl_805652EC, vtable lbl_804B6C60), size 0x40.
#ifndef META_IGBILLBOARD_H
#define META_IGBILLBOARD_H
#include <meta/igGroup.h>
namespace Meta {
struct igModelViewMatrixAttr;
struct igBillboard : igGroup {
 int _mode;  // 0x20 igIntMetaField
 float _axis[3];  // 0x24 igVec3fMetaField
 float _origin[3];  // 0x30 igVec3fMetaField
 igModelViewMatrixAttr *_mvm;  // 0x3C igObjectRefMetaField
};
}
#endif
