// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igBlendStateAttr_register (metaobject lbl_805629D8, vtable lbl_8047D2AC), size 0x10.
#ifndef META_IGBLENDSTATEATTR_H
#define META_IGBLENDSTATEATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igBlendStateAttr : igVisualAttribute {
 bool _enabled;  // 0x0C igBoolMetaField
 unsigned char unknown0D[3];
};
}
#endif
