// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igBlendListRecordList_register (metaobject lbl_805650AC, vtable lbl_804B7120), size 0x14.
#ifndef META_IGBLENDLISTRECORDLIST_H
#define META_IGBLENDLISTRECORDLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igBlendListRecordList : igObjectList {
};
}
#endif
