// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800B9AEC (metaobject lbl_805629C8, vtable lbl_8047D1AC), size 0x10.
#ifndef META_IGBLENDINGCORRECTIONSTATEATTR_H
#define META_IGBLENDINGCORRECTIONSTATEATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igBlendingCorrectionStateAttr : igVisualAttribute {
 bool _state;  // 0x0C igBoolMetaField
 unsigned char unknown0D[3];
};
}
#endif
