// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igBlendMatrixPaletteAttrList_register (metaobject lbl_805629E0, vtable lbl_8047DB50), size 0x14.
#ifndef META_IGBLENDMATRIXPALETTEATTRLIST_H
#define META_IGBLENDMATRIXPALETTEATTRLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igBlendMatrixPaletteAttrList : igObjectList {
};
}
#endif
