// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igBlendingControlStateAttr_register (metaobject lbl_805629D0, vtable lbl_8047D22C), size 0x10.
#ifndef META_IGBLENDINGCONTROLSTATEATTR_H
#define META_IGBLENDINGCONTROLSTATEATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igBlendingControlStateAttr : igVisualAttribute {
 bool _state;  // 0x0C igBoolMetaField
 unsigned char unknown0D[3];
};
}
#endif
