// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800BA28C (metaobject lbl_805629E4, vtable lbl_8047D330), size 0x1C.
#ifndef META_IGBLENDMATRIXPALETTEATTR_H
#define META_IGBLENDMATRIXPALETTEATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igBlendMatrixPaletteAttr : igVisualAttribute {
 void *_matrixCache;  // 0x0C igMemoryRefMetaField
 void *_matrixIndices;  // 0x10 igMemoryRefMetaField
 unsigned int _currentMatrixCount;  // 0x14 igUnsignedIntMetaField
 unsigned int _capacity;  // 0x18 igUnsignedIntMetaField
};
}
#endif
