// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igBoxModel_register (metaobject lbl_80563830, vtable lbl_80497DC0), size 0x28.
#ifndef META_IGBOXMODEL_H
#define META_IGBOXMODEL_H
#include <meta/igGuiComponentModel.h>
namespace Meta {
struct igGuiComponentList;
struct igBoxModel : igGuiComponentModel {
 igGuiComponentList *_children;  // 0x24 igObjectRefMetaField
};
}
#endif
