// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igBoolObject_register (metaobject lbl_80565B2C, vtable lbl_804BB794), size 0xC.
#ifndef META_IGBOOLOBJECT_H
#define META_IGBOOLOBJECT_H
#include <meta/igObject.h>
namespace Meta {
struct igBoolObject : igObject {
 bool _value;  // 0x08 igBoolMetaField
 unsigned char unknown09[3];
};
}
#endif
