// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80038AAC (metaobject lbl_80561E50, vtable lbl_80473260), size 0x38.
#ifndef META_IGBOOLARRAYMETAFIELD_H
#define META_IGBOOLARRAYMETAFIELD_H
#include <meta/igBoolMetaField.h>
namespace Meta {
struct igBoolArrayMetaField : igBoolMetaField {
 int _num;  // 0x34 igIntMetaField
};
}
#endif
