// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igBoxAspect_register (metaobject lbl_8056381C, vtable lbl_804968F8), size 0x34.
#ifndef META_IGBOXASPECT_H
#define META_IGBOXASPECT_H
#include <meta/igGuiComponentAspect.h>
#include <meta/enums.h>
namespace Meta {
struct igChildSizeObserverList;
struct igNonRefCountedTransformList;
struct igBoxAspect : igGuiComponentAspect {
 ORIENTATION::Value _orientation;  // 0x28 igEnumMetaField
 igChildSizeObserverList *_childSizeObserverList;  // 0x2C igObjectRefMetaField
 igNonRefCountedTransformList *_transformList;  // 0x30 igObjectRefMetaField
};
}
#endif
