// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80036D38 (metaobject lbl_80561DD8, vtable lbl_804743C0), size 0x14.
#ifndef META_IGBOOLLIST_H
#define META_IGBOOLLIST_H
#include <meta/igDataList.h>
namespace Meta {
struct igBoolList : igDataList {
};
}
#endif
