// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igBoolMetaField_register (metaobject lbl_80561E48), size 0x34.
#ifndef META_IGBOOLMETAFIELD_H
#define META_IGBOOLMETAFIELD_H
#include <meta/igMetaField.h>
namespace Meta {
struct igBoolMetaField : igMetaField {
};
}
#endif
