// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8014A094 (metaobject lbl_805642C0, vtable lbl_804A8E4C), size 0x10.
#ifndef META_IGBSPLINEFILTERFUN_H
#define META_IGBSPLINEFILTERFUN_H
#include <meta/igSerialFilterFun.h>
namespace Meta {
struct igBSplineFilterFun : igSerialFilterFun {
};
}
#endif
