// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igCamera_register (metaobject lbl_8056520C, vtable lbl_804B6F0C), size 0x38.
#ifndef META_IGCAMERA_H
#define META_IGCAMERA_H
#include <meta/igNode.h>
#include <meta/enums.h>
namespace Meta {
struct igCamera : igNode {
 CameraType::Value _cameraType;  // 0x1C igEnumMetaField
 bool _deadfield1;  // 0x20 igBoolMetaField
 unsigned char unknown21[3];
 float _deadfield2;  // 0x24 igFloatMetaField
 float _deadfield3;  // 0x28 igFloatMetaField
 float _horizontalFieldOfView;  // 0x2C igFloatMetaField
 float _nearPlane;  // 0x30 igFloatMetaField
 float _farPlane;  // 0x34 igFloatMetaField
};
}
#endif
