// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8003826C (metaobject lbl_80561E30, vtable lbl_80473164), size 0x14.
#ifndef META_IGCALLSTACKTRACER_H
#define META_IGCALLSTACKTRACER_H
#include <meta/igUnsignedIntListNoClean.h>
namespace Meta {
struct igCallStackTracer : igUnsignedIntListNoClean {
};
}
#endif
