// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801C5264 (metaobject lbl_805651A8, vtable lbl_804B51E4), size 0x2C.
#ifndef META_IGCARTOONSHADERPROCESSOR_H
#define META_IGCARTOONSHADERPROCESSOR_H
#include <meta/igShaderProcessor.h>
namespace Meta {
struct igLightAttr;
struct igTextureAttr;
struct igTextureMatrixAttr;
struct igCartoonShaderProcessor : igShaderProcessor {
 igTextureMatrixAttr *_cartoonTextureMatrix;  // 0x08 igObjectRefMetaField
 igTextureAttr *_cartoonTexture;  // 0x0C igObjectRefMetaField
 float _lightDirection[3];  // 0x10 igVec3fMetaField
 igLightAttr *_light;  // 0x1C igObjectRefMetaField
 float _eyeDirection[3];  // 0x20 igVec3fMetaField
};
}
#endif
