// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igCallStackTable_register (metaobject lbl_80561E34, vtable lbl_804731E0), size 0x18.
#ifndef META_IGCALLSTACKTABLE_H
#define META_IGCALLSTACKTABLE_H
#include <meta/igObject.h>
namespace Meta {
struct igIntListNoClean;
struct igUnsignedIntListNoClean;
struct igCallStackTable : igObject {
 int _capacity;  // 0x08 igIntMetaField
 int _hashCapacity;  // 0x0C igIntMetaField
 igUnsignedIntListNoClean *_callStacks;  // 0x10 igObjectRefMetaField
 igIntListNoClean *_hashIndex;  // 0x14 igObjectRefMetaField
};
}
#endif
