// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801526C8 (metaobject lbl_80564558), size 0x20.
#ifndef META_IGCACHEDINSTANCELOCK_H
#define META_IGCACHEDINSTANCELOCK_H
#include <meta/igInstanceLock.h>
namespace Meta {
struct igCachedInstanceLock : igInstanceLock {
};
}
#endif
