// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igCapabilityManager_register (metaobject lbl_805630B8), size 0x8.
#ifndef META_IGCAPABILITYMANAGER_H
#define META_IGCAPABILITYMANAGER_H
#include <meta/igObject.h>
namespace Meta {
struct igCapabilityManager : igObject {
};
}
#endif
