// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igCBBoxList_register (metaobject lbl_80563D7C, vtable lbl_804AA48C), size 0x14.
#ifndef META_IGCBBOXLIST_H
#define META_IGCBBOXLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igCBBoxList : igObjectList {
};
}
#endif
