// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igChildEdit_register (metaobject lbl_80564530), size 0x28.
#ifndef META_IGCHILDEDIT_H
#define META_IGCHILDEDIT_H
#include <meta/igChildContainer.h>
namespace Meta {
struct igChildEdit : igChildContainer {
 void *_container;  // 0x20 igObjectRefMetaField
 void *_child;  // 0x24 igObjectRefMetaField
};
}
#endif
