// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igChildSizeObserverList_register (metaobject lbl_8056380C, vtable lbl_80496F94), size 0x14.
#ifndef META_IGCHILDSIZEOBSERVERLIST_H
#define META_IGCHILDSIZEOBSERVERLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igChildSizeObserverList : igObjectList {
};
}
#endif
