// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80151CBC (metaobject lbl_80564524, vtable lbl_804A82BC), size 0x28.
#ifndef META_IGCHILDEDITFORNODE_H
#define META_IGCHILDEDITFORNODE_H
#include <meta/igChildEdit.h>
namespace Meta {
struct igChildEditForNode : igChildEdit {
};
}
#endif
