// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800B9688 (metaobject lbl_805629A0, vtable lbl_8047D0A8), size 0x10.
#ifndef META_IGCLIPPINGSTATEATTR_H
#define META_IGCLIPPINGSTATEATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igClippingStateAttr : igVisualAttribute {
 bool _enabled;  // 0x0C igBoolMetaField
 unsigned char unknown0D[3];
};
}
#endif
