// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igClut_register (metaobject lbl_80563098, vtable lbl_80492A68), size 0x20.
#ifndef META_IGCLUT_H
#define META_IGCLUT_H
#include <meta/igObject.h>
namespace Meta {
struct igClut : igObject {
 unsigned char unknown08[24];
};
}
#endif
