// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8014F654 (metaobject lbl_805644A0, vtable lbl_804A7800), size 0x34.
#ifndef META_IGCOMBINETRANSFORMS_H
#define META_IGCOMBINETRANSFORMS_H
#include <meta/igOptVisitObject.h>
namespace Meta {
struct igCombineTransforms : igOptVisitObject {
 const char *_transformString;  // 0x2C igStringMetaField
 float _shearAmount;  // 0x30 igFloatMetaField
};
}
#endif
