// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801C353C (metaobject lbl_8056506C, vtable lbl_804B5040), size 0x5C.
#ifndef META_IGCOMPILEDGRAPH_H
#define META_IGCOMPILEDGRAPH_H
#include <meta/igGroup.h>
namespace Meta {
struct igAttrList;
struct igBlendListRecordList;
struct igCompiledTransformList;
struct igEnvironmentMapShader2List;
struct igIntList;
struct igMatrixOptStateAttr;
struct igModelViewMatrixAttrList;
struct igNonRefCountedAttrList;
struct igCompiledGraph : igGroup {
 igNonRefCountedAttrList *_compiledList;  // 0x20 igObjectRefMetaField
 igIntList *_srcMvmAttrIdx;  // 0x24 igObjectRefMetaField
 igNonRefCountedAttrList *_destMvmAttrPtr;  // 0x28 igObjectRefMetaField
 igNonRefCountedAttrList *_instMvmAttrPtr;  // 0x2C igObjectRefMetaField
 igBlendListRecordList *_bRecList;  // 0x30 igObjectRefMetaField
 int _priorStateUsage;  // 0x34 igEnumMetaField
 igNonRefCountedAttrList *_destRestoreAttrPtr;  // 0x38 igObjectRefMetaField
 igNonRefCountedAttrList *_restoreAttrs;  // 0x3C igObjectRefMetaField
 igAttrList *_dupDefaultAttrs;  // 0x40 igObjectRefMetaField
 igModelViewMatrixAttrList *_mvmList;  // 0x44 igObjectRefMetaField
 igCompiledTransformList *_xformInfoList;  // 0x48 igObjectRefMetaField
 int _moCount;  // 0x4C igIntMetaField
 int _lastCompileResult;  // 0x50 igEnumMetaField
 igMatrixOptStateAttr *_matOptStateAttr;  // 0x54 igObjectRefMetaField
 igEnvironmentMapShader2List *_environmentShader2List;  // 0x58 igObjectRefMetaField
};
}
#endif
