// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801305C4 (metaobject lbl_80563ABC, vtable lbl_804AAD84), size 0x14.
#ifndef META_IGCOMPOUNDLIST_H
#define META_IGCOMPOUNDLIST_H
#include <meta/igObject.h>
namespace Meta {
struct igCompoundList : igObject {
 int _count;  // 0x08 igIntMetaField
 int _capacity;  // 0x0C igIntMetaField
 void *_data;  // 0x10 igMemoryRefMetaField
};
}
#endif
