// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igCompressedAnimationSequenceQS_register (metaobject lbl_80565030, vtable lbl_804B4F7C), size 0x40.
// Note: _interpolationMethod: igUnsignedCharArrayMetaField, count from the space to the next member.
#ifndef META_IGCOMPRESSEDANIMATIONSEQUENCEQS_H
#define META_IGCOMPRESSEDANIMATIONSEQUENCEQS_H
#include <meta/igAnimationSequence.h>
namespace Meta {
struct igUnsignedShortList;
struct igCompressedAnimationSequenceQS : igAnimationSequence {
 igUnsignedShortList *_compressedTranslationList;  // 0x08 igObjectRefMetaField
 igUnsignedShortList *_compressedQuaternionList;  // 0x0C igObjectRefMetaField
 igUnsignedShortList *_compressedTimeList;  // 0x10 igObjectRefMetaField
 float _translationBase;  // 0x14 igFloatMetaField
 float _translationRangeOverMaxUShort;  // 0x18 igFloatMetaField
 float _quaternionBase;  // 0x1C igFloatMetaField
 float _quaternionRangeOverMaxUShort;  // 0x20 igFloatMetaField
 unsigned char unknown24[4];
 unsigned long long _animationDuration;  // 0x28 igUnsignedLongMetaField
 int _playMode;  // 0x30 igEnumMetaField
 int _lastTime;  // 0x34 igIntMetaField
 unsigned char _channels;  // 0x38 igUnsignedCharMetaField
 unsigned char _interpolationMethod[7];  // 0x39 igUnsignedCharArrayMetaField
};
}
#endif
