// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igCollapseNodeForAttrSet_register (metaobject lbl_805644BC, vtable lbl_804A7AF8), size 0x2C.
#ifndef META_IGCOLLAPSENODEFORATTRSET_H
#define META_IGCOLLAPSENODEFORATTRSET_H
#include <meta/igCollapseNode.h>
namespace Meta {
struct igCollapseNodeForAttrSet : igCollapseNode {
};
}
#endif
