// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80037798 (metaobject lbl_80561E00), size 0x14.
#ifndef META_IGCONTEXT_H
#define META_IGCONTEXT_H
#include <meta/igObject.h>
namespace Meta {
struct igContextExtInfoList;
struct igContextExtList;
struct igContext : igObject {
 igContextExtInfoList *_pExtList;  // 0x08 igObjectRefMetaField
 int _iNumExts;  // 0x0C igIntMetaField
 igContextExtList *_pExtInstances;  // 0x10 igObjectRefMetaField
};
}
#endif
