// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801509E8 (metaobject lbl_805644D0, vtable lbl_804A7DF0), size 0x2C.
#ifndef META_IGCOLLAPSENODEFORUSERINFO_H
#define META_IGCOLLAPSENODEFORUSERINFO_H
#include <meta/igCollapseNode.h>
namespace Meta {
struct igCollapseNodeForUserInfo : igCollapseNode {
};
}
#endif
