// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igCopyRenderDestinationAttr_register (metaobject lbl_80562948, vtable lbl_8047CEA0), size 0x34.
#ifndef META_IGCOPYRENDERDESTINATIONATTR_H
#define META_IGCOPYRENDERDESTINATIONATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igImage;
struct igRenderDestinationAttr;
struct igTextureAttr;
struct igCopyRenderDestinationAttr : igVisualAttribute {
 int _copyType;  // 0x0C igEnumMetaField
 igRenderDestinationAttr *_pRDAttr;  // 0x10 igObjectRefMetaField
 igImage *_pImage;  // 0x14 igObjectRefMetaField
 igTextureAttr *_pTextureAttr;  // 0x18 igObjectRefMetaField
 int _sourceX;  // 0x1C igIntMetaField
 int _sourceY;  // 0x20 igIntMetaField
 int _destinationX;  // 0x24 igIntMetaField
 int _destinationY;  // 0x28 igIntMetaField
 int _sizeW;  // 0x2C igIntMetaField
 int _sizeH;  // 0x30 igIntMetaField
};
}
#endif
