// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8028D61C (metaobject lbl_8056610C, vtable lbl_804CCDD4), size 0x10.
#ifndef META_IGCOLLISIONGRIDHELPER_H
#define META_IGCOLLISIONGRIDHELPER_H
#include <meta/igObject.h>
namespace Meta {
struct igCollisionGrid;
struct igMetaObject;
struct igCollisionGridHelper : igObject {
 igCollisionGrid *_grid;  // 0x08 igObjectRefMetaField
 igMetaObject *_staticGroupType;  // 0x0C igObjectRefMetaField
};
}
#endif
