// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igCompareAttr_register (metaobject lbl_80564490, vtable lbl_804A776C), size 0x2C.
#ifndef META_IGCOMPAREATTR_H
#define META_IGCOMPAREATTR_H
#include <meta/igItemBase.h>
namespace Meta {
struct igAttr;
struct igCompareAttr : igItemBase {
 igAttr *_attributeOne;  // 0x20 igObjectRefMetaField
 igAttr *_attributeTwo;  // 0x24 igObjectRefMetaField
 bool _compare;  // 0x28 igBoolMetaField
 unsigned char unknown29[3];
};
}
#endif
