// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igCollapseHierarchy_register (metaobject lbl_805644F4, vtable lbl_804A80E8), size 0x30.
#ifndef META_IGCOLLAPSEHIERARCHY_H
#define META_IGCOLLAPSEHIERARCHY_H
#include <meta/igOptBase.h>
namespace Meta {
struct igMetaObject;
struct igCollapseHierarchy : igOptBase {
 const char *_traversalName;  // 0x28 igStringMetaField
 igMetaObject *_nodeType;  // 0x2C igObjectRefMetaField
};
}
#endif
