// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igCollisionCellList_register (metaobject lbl_80566158, vtable lbl_804CCD0C), size 0x14.
#ifndef META_IGCOLLISIONCELLLIST_H
#define META_IGCOLLISIONCELLLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igCollisionCellList : igObjectList {
};
}
#endif
