// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igCollapseNodeForTransform_register (metaobject lbl_805644D8, vtable lbl_804A7F20), size 0x2C.
#ifndef META_IGCOLLAPSENODEFORTRANSFORM_H
#define META_IGCOLLAPSENODEFORTRANSFORM_H
#include <meta/igCollapseNode.h>
namespace Meta {
struct igCollapseNodeForTransform : igCollapseNode {
};
}
#endif
