// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8028D3D4 (metaobject lbl_805660E8, vtable lbl_804CCE30), size 0x60.
#ifndef META_IGCOLLISIONGROUP_H
#define META_IGCOLLISIONGROUP_H
#include <meta/igGroup.h>
namespace Meta {
struct igTransform;
struct igCollisionGroup : igGroup {
 igTransform *_transform;  // 0x20 igObjectRefMetaField
 float _position[3];  // 0x24 igVec3fMetaField
 float _lastPosition[3];  // 0x30 igVec3fMetaField
 float _collisionPosition[3];  // 0x3C igVec3fMetaField
 float _direction[3];  // 0x48 igVec3fMetaField
 float _radius;  // 0x54 igFloatMetaField
 float _time;  // 0x58 igFloatMetaField
 int _collisionCells;  // 0x5C igIntMetaField
};
}
#endif
