// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igCollapseNode_register (metaobject lbl_805644E0), size 0x2C.
#ifndef META_IGCOLLAPSENODE_H
#define META_IGCOLLAPSENODE_H
#include <meta/igItemBase.h>
namespace Meta {
struct igNode;
struct igCollapseNode : igItemBase {
 igNode *_node;  // 0x20 igObjectRefMetaField
 igNode *_replaceNode;  // 0x24 igObjectRefMetaField
 int _collapse;  // 0x28 igEnumMetaField
};
}
#endif
