// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igCompiledTransformList_register (metaobject lbl_805650F0, vtable lbl_804B6FFC), size 0x14.
#ifndef META_IGCOMPILEDTRANSFORMLIST_H
#define META_IGCOMPILEDTRANSFORMLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igCompiledTransformList : igObjectList {
};
}
#endif
