// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8014DF80 (metaobject lbl_8056441C, vtable lbl_804A736C), size 0x34.
#ifndef META_IGCONVERTTRANSFORMSTOCOMPRESSEDSEQUENCESQS_H
#define META_IGCONVERTTRANSFORMSTOCOMPRESSEDSEQUENCESQS_H
#include <meta/igOptVisitObject.h>
namespace Meta {
struct igUnsignedShortListList;
struct igConvertTransformsToCompressedSequencesQS : igOptVisitObject {
 igUnsignedShortListList *_lists;  // 0x2C igObjectRefMetaField
 bool _shareLists;  // 0x30 igBoolMetaField
 unsigned char unknown31[3];
};
}
#endif
