// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igContextList_register (metaobject lbl_80561DFC, vtable lbl_8047410C), size 0x14.
#ifndef META_IGCONTEXTLIST_H
#define META_IGCONTEXTLIST_H
#include <meta/igNonRefCountedObjectList.h>
namespace Meta {
struct igContextList : igNonRefCountedObjectList {
};
}
#endif
