// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igController_register (metaobject lbl_80562C14), size 0x10.
#ifndef META_IGCONTROLLER_H
#define META_IGCONTROLLER_H
#include <meta/igEventProducer.h>
namespace Meta {
struct igController : igEventProducer {
 void *_buttonMap;  // 0x08 igMemoryRefMetaField
 bool _isMapped;  // 0x0C igBoolMetaField
 unsigned char unknown0D[3];
};
}
#endif
