// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80037168 (metaobject lbl_80561DE4, vtable lbl_80474230), size 0x14.
#ifndef META_IGCONTEXTEXTINFOLIST_H
#define META_IGCONTEXTEXTINFOLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igContextExtInfoList : igObjectList {
};
}
#endif
