// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8014FE78 (metaobject lbl_805644B8, vtable lbl_804A7A60), size 0x2C.
#ifndef META_IGCOLLAPSENODEFORMORPHINSTANCE_H
#define META_IGCOLLAPSENODEFORMORPHINSTANCE_H
#include <meta/igCollapseNode.h>
namespace Meta {
struct igCollapseNodeForMorphInstance : igCollapseNode {
};
}
#endif
