// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igColorChanger_register (metaobject lbl_80563804, vtable lbl_80496834), size 0x8.
#ifndef META_IGCOLORCHANGER_H
#define META_IGCOLORCHANGER_H
#include <meta/igObject.h>
namespace Meta {
struct igColorChanger : igObject {
};
}
#endif
