// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igCollapseNodeForGroup_register (metaobject lbl_805644D4, vtable lbl_804A7E88), size 0x2C.
#ifndef META_IGCOLLAPSENODEFORGROUP_H
#define META_IGCOLLAPSENODEFORGROUP_H
#include <meta/igCollapseNode.h>
namespace Meta {
struct igCollapseNodeForGroup : igCollapseNode {
};
}
#endif
