// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8014FC90 (metaobject lbl_805644B4, vtable lbl_804A79C8), size 0x2C.
#ifndef META_IGCOLLAPSENODEFORMODELVIEWMATRIXBONESELECT_H
#define META_IGCOLLAPSENODEFORMODELVIEWMATRIXBONESELECT_H
#include <meta/igCollapseNode.h>
namespace Meta {
struct igCollapseNodeForModelViewMatrixBoneSelect : igCollapseNode {
};
}
#endif
