// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800CB958 (metaobject lbl_80562C08), size 0xC.
#ifndef META_IGCONTROLLERMANAGER_H
#define META_IGCONTROLLERMANAGER_H
#include <meta/igEventProducer.h>
namespace Meta {
struct igControllerList;
struct igControllerManager : igEventProducer {
 igControllerList *_controllers;  // 0x08 igObjectRefMetaField
};
}
#endif
