// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igCollapseNodeForGeometry_register (metaobject lbl_805644C8, vtable lbl_804A7CC0), size 0x2C.
#ifndef META_IGCOLLAPSENODEFORGEOMETRY_H
#define META_IGCOLLAPSENODEFORGEOMETRY_H
#include <meta/igCollapseNode.h>
namespace Meta {
struct igCollapseNodeForGeometry : igCollapseNode {
};
}
#endif
