// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8014E9D8 (metaobject lbl_8056446C, vtable lbl_804A7530), size 0x34.
#ifndef META_IGCONVERTANIMATIONSTOCOMPRESSEDSEQUENCESQS_H
#define META_IGCONVERTANIMATIONSTOCOMPRESSEDSEQUENCESQS_H
#include <meta/igOptVisitObject.h>
namespace Meta {
struct igUnsignedShortListList;
struct igConvertAnimationsToCompressedSequencesQS : igOptVisitObject {
 igUnsignedShortListList *_lists;  // 0x2C igObjectRefMetaField
 bool _shareLists;  // 0x30 igBoolMetaField
 unsigned char unknown31[3];
};
}
#endif
