// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igCollapseNodeForNode_register (metaobject lbl_805644DC, vtable lbl_804A7FB8), size 0x2C.
#ifndef META_IGCOLLAPSENODEFORNODE_H
#define META_IGCOLLAPSENODEFORNODE_H
#include <meta/igCollapseNode.h>
namespace Meta {
struct igCollapseNodeForNode : igCollapseNode {
};
}
#endif
