// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igCompareAttrForTexture_register (metaobject lbl_8056448C, vtable lbl_804A76D8), size 0x2C.
#ifndef META_IGCOMPAREATTRFORTEXTURE_H
#define META_IGCOMPAREATTRFORTEXTURE_H
#include <meta/igCompareAttr.h>
namespace Meta {
struct igCompareAttrForTexture : igCompareAttr {
};
}
#endif
