// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80150248 (metaobject lbl_805644C0, vtable lbl_804A7B90), size 0x2C.
#ifndef META_IGCOLLAPSENODEFORLIGHTSET_H
#define META_IGCOLLAPSENODEFORLIGHTSET_H
#include <meta/igCollapseNode.h>
namespace Meta {
struct igCollapseNodeForLightSet : igCollapseNode {
};
}
#endif
