// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801C4604 (metaobject lbl_805650F4, vtable lbl_804B6FA0), size 0x24.
#ifndef META_IGCOMPILEDTRANSFORM_H
#define META_IGCOMPILEDTRANSFORM_H
#include <meta/igObject.h>
namespace Meta {
struct igStringObj;
struct igTransformSource;
struct igCompiledTransform : igObject {
 int _parentIdx;  // 0x08 igIntMetaField
 igTransformSource *_source;  // 0x0C igObjectRefMetaField
 int _moIdx;  // 0x10 igIntMetaField
 void *_invJoint;  // 0x14 igRawRefMetaField
 igStringObj *_name;  // 0x18 igObjectRefMetaField
 bool _isNode;  // 0x1C igBoolMetaField
 bool _isJointChainStart;  // 0x1D igBoolMetaField
 unsigned char unknown1E[2];
 int _boneIndex;  // 0x20 igIntMetaField
};
}
#endif
