// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igCollisionInfo_register (metaobject lbl_805660DC, vtable lbl_804CD050), size 0x18.
#ifndef META_IGCOLLISIONINFO_H
#define META_IGCOLLISIONINFO_H
#include <meta/igInfo.h>
namespace Meta {
struct igCollisionGrid;
struct igCollisionInfo : igInfo {
 igCollisionGrid *_grid;  // 0x14 igObjectRefMetaField
};
}
#endif
