// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801C276C (metaobject lbl_80564FF4, vtable lbl_804B71E8), size 0x30.
#ifndef META_IGCOMPRESSEDTRANSFORMSEQUENCE1_5DATA_H
#define META_IGCOMPRESSEDTRANSFORMSEQUENCE1_5DATA_H
#include <meta/igObject.h>
namespace Meta {
struct igUnsignedShortList;
struct igCompressedTransformSequence1_5Data : igObject {
 igUnsignedShortList *_compressedTranslationList;  // 0x08 igObjectRefMetaField
 igUnsignedShortList *_compressedQuatList;  // 0x0C igObjectRefMetaField
 igUnsignedShortList *_compressedScaleList;  // 0x10 igObjectRefMetaField
 igUnsignedShortList *_compressedTimeList;  // 0x14 igObjectRefMetaField
 float _translationBase;  // 0x18 igFloatMetaField
 float _translationRange;  // 0x1C igFloatMetaField
 float _quatBase;  // 0x20 igFloatMetaField
 float _quatRange;  // 0x24 igFloatMetaField
 float _scaleBase;  // 0x28 igFloatMetaField
 float _scaleRange;  // 0x2C igFloatMetaField
};
}
#endif
