// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8028DA84 (metaobject lbl_80566118, vtable lbl_804CCBF0), size 0x4C.
#ifndef META_IGCOLLISIONGRID_H
#define META_IGCOLLISIONGRID_H
#include <meta/igObject.h>
namespace Meta {
struct igAABox;
struct igCollisionCellList;
struct igCollisionGroupList;
struct igCollisionGrid : igObject {
 igCollisionCellList *_cells;  // 0x08 igObjectRefMetaField
 igCollisionCellList *_activeCells;  // 0x0C igObjectRefMetaField
 int _sizeX;  // 0x10 igIntMetaField
 int _sizeY;  // 0x14 igIntMetaField
 int _sizeZ;  // 0x18 igIntMetaField
 float _maxRadius;  // 0x1C igFloatMetaField
 int _maxPriority;  // 0x20 igIntMetaField
 igCollisionCellList *_processedCells;  // 0x24 igObjectRefMetaField
 igCollisionGroupList *_checkedGroups;  // 0x28 igObjectRefMetaField
 igCollisionGroupList *_dynamicCollisions;  // 0x2C igObjectRefMetaField
 igCollisionGroupList *_staticCollisions;  // 0x30 igObjectRefMetaField
 igCollisionGroupList *_lostGroups;  // 0x34 igObjectRefMetaField
 igAABox *_bound;  // 0x38 igObjectRefMetaField
 float _deltas[3];  // 0x3C igVec3fMetaField
 int _rate;  // 0x48 igIntMetaField
};
}
#endif
