// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igControllerList_register (metaobject lbl_80562BC0, vtable lbl_804807E8), size 0x14.
#ifndef META_IGCONTROLLERLIST_H
#define META_IGCONTROLLERLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igControllerList : igObjectList {
};
}
#endif
