// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80037358 (metaobject lbl_80561DE8, vtable lbl_804741D4), size 0x14.
#ifndef META_IGCONTEXTEXTINFO_H
#define META_IGCONTEXTEXTINFO_H
#include <meta/igObject.h>
namespace Meta {
struct igMetaObject;
struct igContextExtInfo : igObject {
 igMetaObject *_pMeta;  // 0x08 igObjectRefMetaField
 const char *_pName;  // 0x0C igStringMetaField
 void *_pVendorName;  // 0x10 igMemoryRefMetaField
};
}
#endif
