// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8014D3F4 (metaobject lbl_805643D8, vtable lbl_804A713C), size 0x30.
#ifndef META_IGCREATEINFOSFROMREGISTRY_H
#define META_IGCREATEINFOSFROMREGISTRY_H
#include <meta/igOptBase.h>
namespace Meta {
struct igCreateInfosFromRegistry : igOptBase {
 const char *_registryName;  // 0x28 igStringMetaField
 bool _clearInfoList;  // 0x2C igBoolMetaField
 unsigned char unknown2D[3];
};
}
#endif
