// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802AC120 (metaobject lbl_805343EC, vtable lbl_804CE744), size 0x1C.
// Note: _mwply: igStructMetaField, count from the space to the next member.
// Note: _adxt: igStructMetaField, count from the space to the next member.
// Note: _macroFunction: igStructMetaField, count from the space to the next member.
#ifndef META_IGCRIMOVIEDATA_H
#define META_IGCRIMOVIEDATA_H
#include <meta/igObject.h>
namespace Meta {
struct igCriMovieData : igObject {
 unsigned char _mwply[4];  // 0x08 igStructMetaField
 void *_cprmbuf;  // 0x0C igRawRefMetaField
 unsigned char _adxt[4];  // 0x10 igStructMetaField
 void *_adxwork;  // 0x14 igRawRefMetaField
 unsigned char _macroFunction[4];  // 0x18 igStructMetaField
};
}
#endif
