// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8014DC14 (metaobject lbl_80564404, vtable lbl_804A72E4), size 0x3C.
#ifndef META_IGCREATEACTORBOUNDS_H
#define META_IGCREATEACTORBOUNDS_H
#include <meta/igOptBase.h>
namespace Meta {
struct igActorInfoList;
struct igAnimationDatabaseList;
struct igCommonTraversal;
struct igCreateActorBounds : igOptBase {
 igCommonTraversal *_traversal;  // 0x28 igObjectRefMetaField
 igActorInfoList *_actorInfoList;  // 0x2C igObjectRefMetaField
 igAnimationDatabaseList *_animationDatabaseList;  // 0x30 igObjectRefMetaField
 float _sampleRate;  // 0x34 igFloatMetaField
 float _scaleFactor;  // 0x38 igFloatMetaField
};
}
#endif
