// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igCreateBoundingBoxes_register (metaobject lbl_805643E4, vtable lbl_804A71C4), size 0x34.
#ifndef META_IGCREATEBOUNDINGBOXES_H
#define META_IGCREATEBOUNDINGBOXES_H
#include <meta/igOptBase.h>
namespace Meta {
struct igCreateBoundingBoxes : igOptBase {
 bool _optimize;  // 0x28 igBoolMetaField
 bool _removeOldVolumes;  // 0x29 igBoolMetaField
 bool _createNewVolumes;  // 0x2A igBoolMetaField
 bool _preserveActorVolumes;  // 0x2B igBoolMetaField
 const char *_exclusionList;  // 0x2C igStringMetaField
 bool _useWholeAnimation;  // 0x30 igBoolMetaField
 unsigned char unknown31[3];
};
}
#endif
