// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800D3018 (metaobject lbl_80562FE4, vtable lbl_80493A2C), size 0x14.
#ifndef META_IGCUSTOMSTATEFIELDLIST_H
#define META_IGCUSTOMSTATEFIELDLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igCustomStateFieldList : igObjectList {
};
}
#endif
