// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igCullFaceAttr_register (metaobject lbl_80562938, vtable lbl_8047CE18), size 0x14.
#ifndef META_IGCULLFACEATTR_H
#define META_IGCULLFACEATTR_H
#include <meta/igVisualAttribute.h>
#include <meta/enums.h>
namespace Meta {
struct igCullFaceAttr : igVisualAttribute {
 bool _enabled;  // 0x0C igBoolMetaField
 unsigned char unknown0D[3];
 IG_GFX_CULL_FACE_MODE::Value _mode;  // 0x10 igEnumMetaField
};
}
#endif
