// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igCustomState_register (metaobject lbl_80563004), size 0xC.
#ifndef META_IGCUSTOMSTATE_H
#define META_IGCUSTOMSTATE_H
#include <meta/igNamedObject.h>
namespace Meta {
struct igCustomState : igNamedObject {
};
}
#endif
