// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igCustomStateField_register (metaobject lbl_80562FE8, vtable lbl_804939D0), size 0x14.
#ifndef META_IGCUSTOMSTATEFIELD_H
#define META_IGCUSTOMSTATEFIELD_H
#include <meta/igNamedObject.h>
namespace Meta {
struct igMetaField;
struct igCustomStateField : igNamedObject {
 unsigned int _stateCollectionHandle;  // 0x0C igUnsignedIntMetaField
 igMetaField *_stateField;  // 0x10 igObjectRefMetaField
};
}
#endif
