// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800D365C (metaobject lbl_80562FF8, vtable lbl_80493840), size 0x1C.
#ifndef META_IGCUSTOMSTATECOLLECTION_H
#define META_IGCUSTOMSTATECOLLECTION_H
#include <meta/igObjectList.h>
namespace Meta {
struct igCustomStateCollection : igObjectList {
 const char *_name;  // 0x14 igStringMetaField
 unsigned int _flags;  // 0x18 igUnsignedIntMetaField
};
}
#endif
