// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igCustomStateCollectionList_register (metaobject lbl_80562FF4, vtable lbl_80493908), size 0x14.
#ifndef META_IGCUSTOMSTATECOLLECTIONLIST_H
#define META_IGCUSTOMSTATECOLLECTIONLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igCustomStateCollectionList : igObjectList {
};
}
#endif
