// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800B88AC (metaobject lbl_80562934), size 0xC.
#ifndef META_IGCUSTOMSTATECOLLECTIONATTR_H
#define META_IGCUSTOMSTATECOLLECTIONATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igCustomStateCollectionAttr : igVisualAttribute {
};
}
#endif
