// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igCustomMatrixState_register (metaobject lbl_80563090, vtable lbl_80493108), size 0x4C.
#ifndef META_IGCUSTOMMATRIXSTATE_H
#define META_IGCUSTOMMATRIXSTATE_H
#include <meta/igCustomState.h>
namespace Meta {
struct igCustomMatrixState : igCustomState {
 float _value[16];  // 0x0C igMatrix44fMetaField
};
}
#endif
