// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8014D070 (metaobject lbl_805643D0, vtable lbl_804A8940), size 0x14.
#ifndef META_IGDATALISTLIST_H
#define META_IGDATALISTLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igDataListList : igObjectList {
};
}
#endif
