// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80033A14 (metaobject lbl_80561D3C, vtable lbl_80472FA0), size 0x14.
#ifndef META_IGDATALIST_H
#define META_IGDATALIST_H
#include <meta/igObject.h>
namespace Meta {
struct igDataList : igObject {
 int _count;  // 0x08 igIntMetaField
 int _capacity;  // 0x0C igIntMetaField
 void *_data;  // 0x10 igMemoryRefMetaField
};
}
#endif
