// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igDataPumpManager_register (metaobject lbl_80565AE4, vtable lbl_804BBB64), size 0xC.
#ifndef META_IGDATAPUMPMANAGER_H
#define META_IGDATAPUMPMANAGER_H
#include <meta/igObject.h>
namespace Meta {
struct igDataPumpList;
struct igDataPumpManager : igObject {
 igDataPumpList *_dataPumpList;  // 0x08 igObjectRefMetaField
};
}
#endif
