// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igDataPumpList_register (metaobject lbl_80565AEC, vtable lbl_804BBA9C), size 0x14.
#ifndef META_IGDATAPUMPLIST_H
#define META_IGDATAPUMPLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igDataPumpList : igObjectList {
};
}
#endif
