// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802194CC (metaobject lbl_80565B08, vtable lbl_804BB680), size 0x1C.
#ifndef META_IGDATAPUMP_H
#define META_IGDATAPUMP_H
#include <meta/igObject.h>
namespace Meta {
struct igDataPumpInterface;
struct igMetaField;
struct igDataPump : igObject {
 void *_destObj;  // 0x08 igObjectRefMetaField
 igMetaField *_destMeta;  // 0x0C igObjectRefMetaField
 const char *_destMetaClassName;  // 0x10 igStringMetaField
 const char *_destMetaFieldName;  // 0x14 igStringMetaField
 igDataPumpInterface *_dpi;  // 0x18 igObjectRefMetaField
};
}
#endif
