// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801132B0 (metaobject lbl_805637C8, vtable lbl_80496704), size 0x2C.
#ifndef META_IGDEFAULTASPECT_H
#define META_IGDEFAULTASPECT_H
#include <meta/igGuiComponentAspect.h>
namespace Meta {
struct igDefaultAspectElementList;
struct igDefaultAspect : igGuiComponentAspect {
 igDefaultAspectElementList *_elementList;  // 0x28 igObjectRefMetaField
};
}
#endif
