// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80033328 (metaobject lbl_80561D2C, vtable lbl_804756A4), size 0x14.
#ifndef META_IGDEPENDENCYLIST_H
#define META_IGDEPENDENCYLIST_H
#include <meta/igDataList.h>
namespace Meta {
struct igDependencyList : igDataList {
};
}
#endif
