// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800335AC (metaobject lbl_80561D34, vtable lbl_804755B0), size 0x38.
#ifndef META_IGDEPENDENCYMETAFIELD_H
#define META_IGDEPENDENCYMETAFIELD_H
#include <meta/igCompoundMetaField.h>
namespace Meta {
struct igDependencyMetaField : igCompoundMetaField {
};
}
#endif
