// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igDefaultManager_register (metaobject lbl_80564374, vtable lbl_804A6FA0), size 0x30.
#ifndef META_IGDEFAULTMANAGER_H
#define META_IGDEFAULTMANAGER_H
#include <meta/igObject.h>
namespace Meta {
struct igItemInterface;
struct igItemManager;
struct igListenerInterface;
struct igListenerManager;
struct igLockInterface;
struct igLogInterface;
struct igMessageInterface;
struct igMessageManager;
struct igOptInterface;
struct igOptManager;
struct igDefaultManager : igObject {
 igOptManager *_optManager;  // 0x08 igObjectRefMetaField
 igItemManager *_itemManager;  // 0x0C igObjectRefMetaField
 igListenerManager *_listenerManager;  // 0x10 igObjectRefMetaField
 igMessageManager *_messageManager;  // 0x14 igObjectRefMetaField
 igOptInterface *_optInterface;  // 0x18 igObjectRefMetaField
 igItemInterface *_itemInterface;  // 0x1C igObjectRefMetaField
 igListenerInterface *_listenerInterface;  // 0x20 igObjectRefMetaField
 igMessageInterface *_messageInterface;  // 0x24 igObjectRefMetaField
 igLockInterface *_lockInterface;  // 0x28 igObjectRefMetaField
 igLogInterface *_logInterface;  // 0x2C igObjectRefMetaField
};
}
#endif
