// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igDepthFunctionAttr_register (metaobject lbl_80562924, vtable lbl_8047CC70), size 0x10.
#ifndef META_IGDEPTHFUNCTIONATTR_H
#define META_IGDEPTHFUNCTIONATTR_H
#include <meta/igVisualAttribute.h>
#include <meta/enums.h>
namespace Meta {
struct igDepthFunctionAttr : igVisualAttribute {
 IG_GFX_DEPTH_TEST_FUNCTION::Value _func;  // 0x0C igEnumMetaField
};
}
#endif
