// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igDestinationAlphaStateAttr_register (metaobject lbl_805628F8, vtable lbl_8047C9E0), size 0x10.
#ifndef META_IGDESTINATIONALPHASTATEATTR_H
#define META_IGDESTINATIONALPHASTATEATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igDestinationAlphaStateAttr : igVisualAttribute {
 bool _enabled;  // 0x0C igBoolMetaField
 unsigned char unknown0D[3];
};
}
#endif
