// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800CB7D0 (metaobject lbl_80562BC4, vtable lbl_804804E8), size 0x4C.
#ifndef META_IGDEFAULTINTERFACEMANAGER_H
#define META_IGDEFAULTINTERFACEMANAGER_H
#include <meta/igInterfaceManager.h>
namespace Meta {
struct igDefaultInterfaceManager : igInterfaceManager {
 void *_mouseMotionFunction;  // 0x0C igRawRefMetaField
 void *_mouseButtonDownFunction;  // 0x10 igRawRefMetaField
 void *_mouseButtonUpFunction;  // 0x14 igRawRefMetaField
 void *_windowMoveFunction;  // 0x18 igRawRefMetaField
 void *_windowResizeFunction;  // 0x1C igRawRefMetaField
 void *_windowCloseFunction;  // 0x20 igRawRefMetaField
 void *_controllerJoystickMotionFunction;  // 0x24 igRawRefMetaField
 void *_controllerButtonDownFunction;  // 0x28 igRawRefMetaField
 void *_controllerButtonUpFunction;  // 0x2C igRawRefMetaField
 void *_controllerButtonPressureFunction;  // 0x30 igRawRefMetaField
 void *_controllerConnectionFunction;  // 0x34 igRawRefMetaField
 void *_controllerDisconnectionFunction;  // 0x38 igRawRefMetaField
 void *_controllerSliderFunction;  // 0x3C igRawRefMetaField
 void *_controllerPointOfViewFunction;  // 0x40 igRawRefMetaField
 void *_keyDownFunction;  // 0x44 igRawRefMetaField
 void *_keyUpFunction;  // 0x48 igRawRefMetaField
};
}
#endif
