// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igDirectory_register (metaobject lbl_80561CAC, vtable lbl_80472E8C), size 0x48.
#ifndef META_IGDIRECTORY_H
#define META_IGDIRECTORY_H
#include <meta/igObjectList.h>
namespace Meta {
struct igDirectoryList;
struct igInfoList;
struct igPointerList;
struct igResource;
struct igSemaphore;
struct igShortListList;
struct igDirectory : igObjectList {
 const char *_name;  // 0x14 igStringMetaField
 igDirectoryList *_externalDirectoryList;  // 0x18 igObjectRefMetaField
 igInfoList *_infoList;  // 0x1C igObjectRefMetaField
 igResource *_managingResource;  // 0x20 igObjectRefMetaField
 bool _sharingState;  // 0x24 igBoolMetaField
 bool _trackUniqueEntries;  // 0x25 igBoolMetaField
 unsigned char unknown26[2];
 igDirectory *_uniqueEntryList;  // 0x28 igObjectRefMetaField
 igPointerList *_refList;  // 0x2C igObjectRefMetaField
 bool _loadPendingState;  // 0x30 igBoolMetaField
 bool _validState;  // 0x31 igBoolMetaField
 bool _compatibleState;  // 0x32 igBoolMetaField
 unsigned char unknown33[1];
 int _loadedRefCount;  // 0x34 igIntMetaField
 bool _concreteState;  // 0x38 igBoolMetaField
 unsigned char unknown39[3];
 igShortListList *_metaFieldPerObjectIndices;  // 0x3C igObjectRefMetaField
 bool _autoWriteFilePreProcessState;  // 0x40 igBoolMetaField
 bool _useMemoryPoolAssignmentsState;  // 0x41 igBoolMetaField
 bool _forceWriteMemoryPoolInfoFromMetaState;  // 0x42 igBoolMetaField
 unsigned char unknown43[1];
 igSemaphore *_loadingSemaphore;  // 0x44 igObjectRefMetaField
};
}
#endif
