// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igDoubleList_register (metaobject lbl_80561D70, vtable lbl_80474EB8), size 0x14.
#ifndef META_IGDOUBLELIST_H
#define META_IGDOUBLELIST_H
#include <meta/igDataList.h>
namespace Meta {
struct igDoubleList : igDataList {
};
}
#endif
