// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igDOFShader_register (metaobject lbl_80564FC0, vtable lbl_804B4E20), size 0x50.
#ifndef META_IGDOFSHADER_H
#define META_IGDOFSHADER_H
#include <meta/igGroup.h>
namespace Meta {
struct igNonRefCountedAttrList;
struct igDOFShader : igGroup {
 bool _bEnabled;  // 0x20 igBoolMetaField
 unsigned char unknown21[3];
 float _fBlurriness;  // 0x24 igFloatMetaField
 float _fFocusRange;  // 0x28 igFloatMetaField
 float _fHFOV;  // 0x2C igFloatMetaField
 float _fVFOV;  // 0x30 igFloatMetaField
 float _fNearClip;  // 0x34 igFloatMetaField
 float _fFarClip;  // 0x38 igFloatMetaField
 float _fAspectRatio;  // 0x3C igFloatMetaField
 bool _bChanged;  // 0x40 igBoolMetaField
 unsigned char unknown41[3];
 float _fSmallHFOV;  // 0x44 igFloatMetaField
 float _fSmallVFOV;  // 0x48 igFloatMetaField
 igNonRefCountedAttrList *_pTmpAttrList;  // 0x4C igObjectRefMetaField
};
}
#endif
