// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igDoubleArrayMetaField_register (metaobject lbl_80561C9C, vtable lbl_80472D98), size 0x38.
#ifndef META_IGDOUBLEARRAYMETAFIELD_H
#define META_IGDOUBLEARRAYMETAFIELD_H
#include <meta/igDoubleMetaField.h>
namespace Meta {
struct igDoubleArrayMetaField : igDoubleMetaField {
 int _num;  // 0x34 igIntMetaField
};
}
#endif
