// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igDriverDatabase_register (metaobject lbl_80561C4C, vtable lbl_80472C48), size 0x38.
#ifndef META_IGDRIVERDATABASE_H
#define META_IGDRIVERDATABASE_H
#include <meta/igObject.h>
#include <meta/enums.h>
namespace Meta {
struct igFile;
struct igRegistry;
struct igStringObj;
struct igStringObjList;
struct igStringRefListList;
struct igDriverDatabase : igObject {
 igStringObjList *_currentProperties;  // 0x08 igObjectRefMetaField
 igStringRefListList *_subPropertyNames;  // 0x0C igObjectRefMetaField
 igStringRefListList *_subPropertyValues;  // 0x10 igObjectRefMetaField
 igRegistry *_overrideSource;  // 0x14 igObjectRefMetaField
 int _overrideSourceSection;  // 0x18 igIntMetaField
 SECTION_OVERRIDE_MODE::Value _overrideMode;  // 0x1C igEnumMetaField
 igFile *_databaseFile;  // 0x20 igObjectRefMetaField
 igStringObj *_databaseFileName;  // 0x24 igObjectRefMetaField
 igStringObj *_rawDatabase;  // 0x28 igObjectRefMetaField
 int _currentLine;  // 0x2C igIntMetaField
 bool _verbose;  // 0x30 igBoolMetaField
 unsigned char unknown31[3];
 void *_dbIndex;  // 0x34 igRawRefMetaField
};
}
#endif
