// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8014C170 (metaobject lbl_80564370, vtable lbl_804A6F2C), size 0x20.
#ifndef META_IGDYNAMICLOCK_H
#define META_IGDYNAMICLOCK_H
#include <meta/igInstanceLock.h>
namespace Meta {
struct igDynamicLock : igInstanceLock {
};
}
#endif
