// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801C1C2C (metaobject lbl_80564F94, vtable lbl_804B4D40), size 0xA8.
#ifndef META_IGENBAYAANIMATIONSTATE_H
#define META_IGENBAYAANIMATIONSTATE_H
#include <meta/igAnimationState.h>
namespace Meta {
struct igEnbayaAnimationState : igAnimationState {
 void *_context;  // 0xA0 igRawRefMetaField
 bool _fastCacheDecodingState;  // 0xA4 igBoolMetaField
 unsigned char unknownA5[3];
};
}
#endif
