// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igEnbayaTransformSource_register (metaobject lbl_80564F78, vtable lbl_804B4C5C), size 0x10.
#ifndef META_IGENBAYATRANSFORMSOURCE_H
#define META_IGENBAYATRANSFORMSOURCE_H
#include <meta/igTransformSource.h>
namespace Meta {
struct igEnbayaAnimationSource;
struct igEnbayaTransformSource : igTransformSource {
 int _trackId;  // 0x08 igIntMetaField
 igEnbayaAnimationSource *_enbayaAnimationSource;  // 0x0C igObjectRefMetaField
};
}
#endif
