// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igEnbayaCompressAnimations_register (metaobject lbl_80564330, vtable lbl_804A6E74), size 0x68.
#ifndef META_IGENBAYACOMPRESSANIMATIONS_H
#define META_IGENBAYACOMPRESSANIMATIONS_H
#include <meta/igOptVisitObject.h>
namespace Meta {
struct igDataTable;
struct igFloatList;
struct igIntList;
struct igStringRefList;
struct igEnbayaCompressAnimations : igOptVisitObject {
 float _quantizationError;  // 0x2C igFloatMetaField
 int _sampleRate;  // 0x30 igIntMetaField
 bool _printStatistics;  // 0x34 igBoolMetaField
 unsigned char unknown35[3];
 const char *_ignoreBones;  // 0x38 igStringMetaField
 const char *_specialCaseIniFilename;  // 0x3C igStringMetaField
 const char *_currentAnimationDatabase;  // 0x40 igStringMetaField
 igStringRefList *_ignoreBoneList;  // 0x44 igObjectRefMetaField
 igStringRefList *_specialCaseFilenames;  // 0x48 igObjectRefMetaField
 igStringRefList *_specialCaseAnimationDatabaseNames;  // 0x4C igObjectRefMetaField
 igStringRefList *_specialCaseAnimationNames;  // 0x50 igObjectRefMetaField
 igIntList *_specialCaseSampleRates;  // 0x54 igObjectRefMetaField
 igFloatList *_specialCaseQuantizationErrors;  // 0x58 igObjectRefMetaField
 igDataTable *_table;  // 0x5C igObjectRefMetaField
 const char *_separator;  // 0x60 igStringMetaField
 int _sortColumn;  // 0x64 igIntMetaField
};
}
#endif
