// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801C1938 (metaobject lbl_80564F84, vtable lbl_804B4CE4), size 0x14.
#ifndef META_IGENBAYACONTEXTPOOL_H
#define META_IGENBAYACONTEXTPOOL_H
#include <meta/igObject.h>
namespace Meta {
struct igPointerListList;
struct igUnsignedIntList;
struct igEnbayaContextPool : igObject {
 igPointerListList *_poolList;  // 0x08 igObjectRefMetaField
 igUnsignedIntList *_boneCountList;  // 0x0C igObjectRefMetaField
 igUnsignedIntList *_freeIndexList;  // 0x10 igObjectRefMetaField
};
}
#endif
