// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8003188C (metaobject lbl_80561C3C, vtable lbl_80472B24), size 0x3C.
#ifndef META_IGENUMARRAYMETAFIELD_H
#define META_IGENUMARRAYMETAFIELD_H
#include <meta/igEnumMetaField.h>
namespace Meta {
struct igEnumArrayMetaField : igEnumMetaField {
 int _num;  // 0x38 igIntMetaField
};
}
#endif
