// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80113030 (metaobject lbl_805637BC, vtable lbl_8049665C), size 0x14.
#ifndef META_IGEVENTDISPATCHER_H
#define META_IGEVENTDISPATCHER_H
#include <meta/igInterfaceManager.h>
namespace Meta {
struct igControllerManager;
struct igEventReceiverOrderedList;
struct igEventDispatcher : igInterfaceManager {
 igEventReceiverOrderedList *_receivers;  // 0x0C igObjectRefMetaField
 igControllerManager *_controllerManager;  // 0x10 igObjectRefMetaField
};
}
#endif
