// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80112DF0 (metaobject lbl_805637B8, vtable lbl_80497724), size 0x8.
#ifndef META_IGEVENTRECEIVER_H
#define META_IGEVENTRECEIVER_H
#include <meta/igObject.h>
namespace Meta {
struct igEventReceiver : igObject {
};
}
#endif
