// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800CB4AC (metaobject lbl_80562BB0), size 0x8.
#ifndef META_IGEVENTPRODUCER_H
#define META_IGEVENTPRODUCER_H
#include <meta/igObject.h>
namespace Meta {
struct igEventProducer : igObject {
};
}
#endif
