// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800CB3BC (metaobject lbl_80562BAC, vtable lbl_80480BB8), size 0x14.
#ifndef META_IGEVENTPRODUCERLIST_H
#define META_IGEVENTPRODUCERLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igEventProducerList : igObjectList {
};
}
#endif
