// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800D4AB0 (metaobject lbl_8056306C, vtable lbl_804929B4), size 0x2C.
#ifndef META_IGEXTERNALIMAGEENTRY_H
#define META_IGEXTERNALIMAGEENTRY_H
#include <meta/igExternalDirEntry.h>
namespace Meta {
struct igExternalImageEntry : igExternalDirEntry {
};
}
#endif
