// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80120DA4 (metaobject lbl_805639C8, vtable lbl_8049B200), size 0x14.
#ifndef META_IGEXTENDBYRAYFUNCTIONLIST_H
#define META_IGEXTENDBYRAYFUNCTIONLIST_H
#include <meta/igDataList.h>
namespace Meta {
struct igExtendByRayFunctionList : igDataList {
};
}
#endif
