// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igExternalIndexedEntry_register (metaobject lbl_80561B70, vtable lbl_804728F8), size 0x34.
#ifndef META_IGEXTERNALINDEXEDENTRY_H
#define META_IGEXTERNALINDEXEDENTRY_H
#include <meta/igDirEntry.h>
namespace Meta {
struct igMetaObject;
struct igExternalIndexedEntry : igDirEntry {
 int _directoryIndex;  // 0x1C igIntMetaField
 int _entryIndex;  // 0x20 igIntMetaField
 igMetaObject *_entryType;  // 0x24 igObjectRefMetaField
 int _entryTypeIndex;  // 0x28 igIntMetaField
 igMetaObject *_objectType;  // 0x2C igObjectRefMetaField
 int _objectTypeIndex;  // 0x30 igIntMetaField
};
}
#endif
