// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80120AAC (metaobject lbl_805639C0, vtable lbl_8049B380), size 0x14.
#ifndef META_IGEXTENDBYVECFUNCTIONLIST_H
#define META_IGEXTENDBYVECFUNCTIONLIST_H
#include <meta/igDataList.h>
namespace Meta {
struct igExtendByVecFunctionList : igDataList {
};
}
#endif
