// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80030A3C (metaobject lbl_80561B8C, vtable lbl_804729A4), size 0x2C.
#ifndef META_IGEXTERNALDIRENTRY_H
#define META_IGEXTERNALDIRENTRY_H
#include <meta/igDirEntry.h>
namespace Meta {
struct igExternalDirEntry : igDirEntry {
 const char *_directoryName;  // 0x1C igStringMetaField
 const char *_entryName;  // 0x20 igStringMetaField
 int _entryIndex;  // 0x24 igIntMetaField
 const char *_externalFilePath;  // 0x28 igStringMetaField
};
}
#endif
