// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igExtendByFunctionList_register (metaobject lbl_805639D4, vtable lbl_8049AFC0), size 0x14.
#ifndef META_IGEXTENDBYFUNCTIONLIST_H
#define META_IGEXTENDBYFUNCTIONLIST_H
#include <meta/igDataList.h>
namespace Meta {
struct igExtendByFunctionList : igDataList {
};
}
#endif
