// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igFileNameList_register (metaobject lbl_80534364, vtable lbl_804CE368), size 0x14.
#ifndef META_IGFILENAMELIST_H
#define META_IGFILENAMELIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igFileNameList : igObjectList {
};
}
#endif
