// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igFileImagePng_register (metaobject lbl_805630F0, vtable lbl_80491194), size 0x60.
#ifndef META_IGFILEIMAGEPNG_H
#define META_IGFILEIMAGEPNG_H
#include <meta/igFileImage.h>
namespace Meta {
struct igFile;
struct igFileImagePng : igFileImage {
 igFile *_file;  // 0x5C igObjectRefMetaField
};
}
#endif
