// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801125A8 (metaobject lbl_80563798, vtable lbl_80497424), size 0xC.
#ifndef META_IGFIELDSYNCHRONIZER_H
#define META_IGFIELDSYNCHRONIZER_H
#include <meta/igObject.h>
namespace Meta {
struct igFieldChangeViewList;
struct igFieldSynchronizer : igObject {
 igFieldChangeViewList *_views;  // 0x08 igObjectRefMetaField
};
}
#endif
