// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igFile_register (metaobject lbl_80561B3C), size 0x2C.
#ifndef META_IGFILE_H
#define META_IGFILE_H
#include <meta/igNamedObject.h>
namespace Meta {
struct igFile : igNamedObject {
 const char *_fileName;  // 0x0C igStringMetaField
 int _readMode;  // 0x10 igEnumMetaField
 int _openMode;  // 0x14 igEnumMetaField
 void *_fileHandle;  // 0x18 igRawRefMetaField
 int _optimalReadChunkSize;  // 0x1C igIntMetaField
 int _optimalWriteChunkSize;  // 0x20 igIntMetaField
 int _pageSize;  // 0x24 igIntMetaField
 const char *_completeFilename;  // 0x28 igStringMetaField
};
}
#endif
