// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igFieldUpdate_register (metaobject lbl_80564300, vtable lbl_804A6CC0), size 0x34.
#ifndef META_IGFIELDUPDATE_H
#define META_IGFIELDUPDATE_H
#include <meta/igItemBase.h>
namespace Meta {
struct igMetaField;
struct igFieldUpdate : igItemBase {
 const char *_destinationFieldName;  // 0x20 igStringMetaField
 const char *_sourceFieldName;  // 0x24 igStringMetaField
 void *_destinationObject;  // 0x28 igObjectRefMetaField
 igMetaField *_sourceField;  // 0x2C igObjectRefMetaField
 igMetaField *_destinationField;  // 0x30 igObjectRefMetaField
};
}
#endif
