// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800D2358 (metaobject lbl_80562F74), size 0x5C.
#ifndef META_IGFILEIMAGE_H
#define META_IGFILEIMAGE_H
#include <meta/igImage.h>
namespace Meta {
struct igFileImage : igImage {
};
}
#endif
