// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801127D4 (metaobject lbl_805637A0, vtable lbl_8049735C), size 0x14.
#ifndef META_IGFIELDCHANGEVIEWLIST_H
#define META_IGFIELDCHANGEVIEWLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igFieldChangeViewList : igObjectList {
};
}
#endif
