// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igFlattenNode_register (metaobject lbl_8056425C), size 0x2C.
#ifndef META_IGFLATTENNODE_H
#define META_IGFLATTENNODE_H
#include <meta/igCollapseNode.h>
namespace Meta {
struct igFlattenNode : igCollapseNode {
};
}
#endif
