// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igFlattenNodeForGroup_register (metaobject lbl_80564254, vtable lbl_804A69F4), size 0x2C.
#ifndef META_IGFLATTENNODEFORGROUP_H
#define META_IGFLATTENNODEFORGROUP_H
#include <meta/igFlattenNode.h>
namespace Meta {
struct igFlattenNodeForGroup : igFlattenNode {
};
}
#endif
