// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igFloatMetaField_register (metaobject lbl_80561B20, vtable lbl_804725BC), size 0x34.
#ifndef META_IGFLOATMETAFIELD_H
#define META_IGFLOATMETAFIELD_H
#include <meta/igMetaField.h>
namespace Meta {
struct igFloatMetaField : igMetaField {
};
}
#endif
