// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igFlushRenderer_register (metaobject lbl_80515D40, vtable lbl_804CBDE8), size 0xC.
#ifndef META_IGFLUSHRENDERER_H
#define META_IGFLUSHRENDERER_H
#include <meta/igRenderer.h>
namespace Meta {
struct igFlushRenderer : igRenderer {
};
}
#endif
