// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80034E7C (metaobject lbl_80561D7C, vtable lbl_80474D30), size 0x14.
#ifndef META_IGFLOATLIST_H
#define META_IGFLOATLIST_H
#include <meta/igDataList.h>
namespace Meta {
struct igFloatList : igDataList {
};
}
#endif
