// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igFloatObject_register (metaobject lbl_80565A90, vtable lbl_804BBDF0), size 0xC.
#ifndef META_IGFLOATOBJECT_H
#define META_IGFLOATOBJECT_H
#include <meta/igObject.h>
namespace Meta {
struct igFloatObject : igObject {
 float _value;  // 0x08 igFloatMetaField
};
}
#endif
