// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igFloatHistogram_register (metaobject lbl_80565A98, vtable lbl_804BBD38), size 0x24.
#ifndef META_IGFLOATHISTOGRAM_H
#define META_IGFLOATHISTOGRAM_H
#include <meta/igHistogramBase.h>
namespace Meta {
struct igFloatHistogram : igHistogramBase {
 unsigned char unknown0C[12];
 float _minValueIgb;  // 0x18 igFloatMetaField
 float _maxValueIgb;  // 0x1C igFloatMetaField
 float _binWidthIgb;  // 0x20 igFloatMetaField
};
}
#endif
