// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80034CC0 (metaobject lbl_80561D78, vtable lbl_80474DF0), size 0x14.
#ifndef META_IGFLOATLISTLIST_H
#define META_IGFLOATLISTLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igFloatListList : igObjectList {
};
}
#endif
