// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801489B0 (metaobject lbl_80564258, vtable lbl_804A695C), size 0x2C.
#ifndef META_IGFLATTENNODEFORATTRSET_H
#define META_IGFLATTENNODEFORATTRSET_H
#include <meta/igFlattenNode.h>
namespace Meta {
struct igFlattenNodeForAttrSet : igFlattenNode {
};
}
#endif
