// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igFloatArrayMetaField_register (metaobject lbl_80561B28, vtable lbl_804726B0), size 0x38.
#ifndef META_IGFLOATARRAYMETAFIELD_H
#define META_IGFLOATARRAYMETAFIELD_H
#include <meta/igFloatMetaField.h>
namespace Meta {
struct igFloatArrayMetaField : igFloatMetaField {
 int _num;  // 0x34 igIntMetaField
};
}
#endif
