// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8002F868 (metaobject lbl_80561B18, vtable lbl_80472550), size 0xC.
#ifndef META_IGFOLDER_H
#define META_IGFOLDER_H
#include <meta/igObject.h>
namespace Meta {
struct igFolder : igObject {
 const char *_folderName;  // 0x08 igStringMetaField
};
}
#endif
