// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80148350 (metaobject lbl_80564248, vtable lbl_804A683C), size 0x30.
#ifndef META_IGGATHERCOMPILEGRAPHS_H
#define META_IGGATHERCOMPILEGRAPHS_H
#include <meta/igOptVisitObject.h>
namespace Meta {
struct igGatherCompileGraphs : igOptVisitObject {
 const char *_compileString;  // 0x2C igStringMetaField
};
}
#endif
