// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80149B74 (metaobject lbl_805642A8, vtable lbl_804A8F78), size 0x20.
#ifndef META_IGGAUSSIANFILTERFUN_H
#define META_IGGAUSSIANFILTERFUN_H
#include <meta/igSerialFilterFun.h>
namespace Meta {
struct igGaussianFilterFun : igSerialFilterFun {
 int _constantsCount;  // 0x10 igIntMetaField
 void *_constants;  // 0x14 igMemoryRefMetaField
 double _sigma;  // 0x18 igDoubleMetaField
};
}
#endif
