// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igGamecubeVertexArray1_1_register (metaobject lbl_805633C0, vtable lbl_80491324), size 0x50.
#ifndef META_IGGAMECUBEVERTEXARRAY1_1_H
#define META_IGGAMECUBEVERTEXARRAY1_1_H
#include <meta/igVertexArray1_1.h>
namespace Meta {
struct igGamecubeVertexArray1_1 : igVertexArray1_1 {
 unsigned char unknown30[32];
};
}
#endif
