// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8003B0E0 (metaobject lbl_80562074, vtable lbl_80470110), size 0x388.
// Note: _thread: igStructMetaField, count from the space to the next member.
// Note: _alarm: igStructMetaField, count from the space to the next member.
#ifndef META_IGGAMECUBETHREAD_H
#define META_IGGAMECUBETHREAD_H
#include <meta/igThread.h>
namespace Meta {
struct igSemaphore;
struct igGamecubeThread : igThread {
 void *_result;  // 0x30 igRawRefMetaField
 bool _isDeferred;  // 0x34 igBoolMetaField
 bool _stopRequested;  // 0x35 igBoolMetaField
 bool _atStoppingPoint;  // 0x36 igBoolMetaField
 bool _isActive;  // 0x37 igBoolMetaField
 unsigned char _thread[792];  // 0x38 igStructMetaField
 void *_master;  // 0x350 igRawRefMetaField
 unsigned char unknown354[4];
 unsigned char _alarm[40];  // 0x358 igStructMetaField
 igSemaphore *_threadDoneSema;  // 0x380 igObjectRefMetaField
 unsigned char unknown384[4];
};
}
#endif
