// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igGamecubeScissorExt_register (metaobject lbl_805633E4, vtable lbl_80491580), size 0x2C.
#ifndef META_IGGAMECUBESCISSOREXT_H
#define META_IGGAMECUBESCISSOREXT_H
#include <meta/igScissorExt.h>
namespace Meta {
struct igGamecubeScissorExt : igScissorExt {
 unsigned char unknown14[24];
};
}
#endif
