// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8003B534 (metaobject lbl_805620B4, vtable lbl_804703A4), size 0x28.
#ifndef META_IGGAMECUBELONGTIMER_H
#define META_IGGAMECUBELONGTIMER_H
#include <meta/igLongTimer.h>
namespace Meta {
struct igGamecubeLongTimer : igLongTimer {
};
}
#endif
