// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800CBDE0 (metaobject lbl_80562C24, vtable lbl_80480288), size 0x30.
#ifndef META_IGGAMECUBEWINDOW_H
#define META_IGGAMECUBEWINDOW_H
#include <meta/igWindow.h>
namespace Meta {
struct igVisualContext;
struct igGamecubeWindow : igWindow {
 int _width;  // 0x08 igIntMetaField
 int _height;  // 0x0C igIntMetaField
 int _originX;  // 0x10 igIntMetaField
 int _originY;  // 0x14 igIntMetaField
 igVisualContext *_vc;  // 0x18 igObjectRefMetaField
 bool _controllerEnabled;  // 0x1C igBoolMetaField
 unsigned char unknown1D[3];
 int _videoMode;  // 0x20 igIntMetaField
 const char *_winName;  // 0x24 igStringMetaField
 int _renderDestinationHandle;  // 0x28 igIntMetaField
 bool _open;  // 0x2C igBoolMetaField
 unsigned char unknown2D[3];
};
}
#endif
