// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igGamecubeControllerManager_register (metaobject lbl_80562C50, vtable lbl_80480338), size 0xC.
#ifndef META_IGGAMECUBECONTROLLERMANAGER_H
#define META_IGGAMECUBECONTROLLERMANAGER_H
#include <meta/igControllerManager.h>
namespace Meta {
struct igGamecubeControllerManager : igControllerManager {
};
}
#endif
