// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igGamecubeIndexArray_register (metaobject lbl_80563460, vtable lbl_804914EC), size 0x1C.
#ifndef META_IGGAMECUBEINDEXARRAY_H
#define META_IGGAMECUBEINDEXARRAY_H
#include <meta/igIndexArray.h>
namespace Meta {
struct igGamecubeIndexArray : igIndexArray {
};
}
#endif
