// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igGamecubeHostFile_register (metaobject lbl_805620B8, vtable lbl_8047043C), size 0x38.
// Note: _handle: igStructMetaField, count from the space to the next member.
#ifndef META_IGGAMECUBEHOSTFILE_H
#define META_IGGAMECUBEHOSTFILE_H
#include <meta/igFile.h>
namespace Meta {
struct igGamecubeHostFile : igFile {
 int _blocksize;  // 0x2C igIntMetaField
 unsigned char _handle[4];  // 0x30 igStructMetaField
 bool _isBinary;  // 0x34 igBoolMetaField
 bool _MessageMode;  // 0x35 igBoolMetaField
 unsigned char unknown36[2];
};
}
#endif
