// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igGamecubeEnvironmentMapShader_register (metaobject lbl_805655D8, vtable lbl_804B3068), size 0x88.
#ifndef META_IGGAMECUBEENVIRONMENTMAPSHADER_H
#define META_IGGAMECUBEENVIRONMENTMAPSHADER_H
#include <meta/igEnvironmentMapShader2.h>
namespace Meta {
struct igBlendFunctionAttr;
struct igTextureAttr;
struct igTextureBindAttr;
struct igTextureFunctionAttr;
struct igGamecubeEnvironmentMapShader : igEnvironmentMapShader2 {
 igBlendFunctionAttr *_envMapBlendFunc;  // 0x70 igObjectRefMetaField
 unsigned char _reflectionScale;  // 0x74 igUnsignedCharMetaField
 unsigned char unknown75[3];
 igTextureAttr *_scaleTexture;  // 0x78 igObjectRefMetaField
 igTextureBindAttr *_scaleTextureBind;  // 0x7C igObjectRefMetaField
 igTextureFunctionAttr *_scaleTextureFunc;  // 0x80 igObjectRefMetaField
 bool _selfShadowEnabled;  // 0x84 igBoolMetaField
 unsigned char unknown85[3];
};
}
#endif
