// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8003AEF8 (metaobject lbl_80562070, vtable lbl_804700A8), size 0x10.
#ifndef META_IGGAMECUBETHREADMANAGER_H
#define META_IGGAMECUBETHREADMANAGER_H
#include <meta/igThreadManager.h>
namespace Meta {
struct igGamecubeThreadManager : igThreadManager {
};
}
#endif
