// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igGamecubeController_register (metaobject lbl_80562C54, vtable lbl_804803A0), size 0x34.
// Note: _x: igFloatArrayMetaField, count from the space to the next member.
// Note: _y: igFloatArrayMetaField, count from the space to the next member.
#ifndef META_IGGAMECUBECONTROLLER_H
#define META_IGGAMECUBECONTROLLER_H
#include <meta/igController.h>
namespace Meta {
struct igWindow;
struct igGamecubeController : igController {
 float _x[2];  // 0x10 igFloatArrayMetaField
 float _y[2];  // 0x18 igFloatArrayMetaField
 unsigned int _buttonState;  // 0x20 igUnsignedIntMetaField
 unsigned short _channel;  // 0x24 igUnsignedShortMetaField
 unsigned char unknown26[2];
 igWindow *_attachedWindow;  // 0x28 igObjectRefMetaField
 unsigned char _triggerLeftPressure;  // 0x2C igUnsignedCharMetaField
 unsigned char _triggerRightPressure;  // 0x2D igUnsignedCharMetaField
 unsigned char _buttonAPressure;  // 0x2E igUnsignedCharMetaField
 unsigned char _buttonBPressure;  // 0x2F igUnsignedCharMetaField
 bool _connected;  // 0x30 igBoolMetaField
 unsigned char unknown31[3];
};
}
#endif
