// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800D7798 (metaobject lbl_805633B8, vtable lbl_804912BC), size 0x18.
#ifndef META_IGGAMECUBEVERTEXARRAY2_H
#define META_IGGAMECUBEVERTEXARRAY2_H
#include <meta/igVertexArray2.h>
namespace Meta {
struct igGamecubeVertexArray2 : igVertexArray2 {
};
}
#endif
