// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igGamecubeSemaphore_register (metaobject lbl_805620A0, vtable lbl_80470314), size 0x24.
// Note: _sema: igStructMetaField, count from the space to the next member.
#ifndef META_IGGAMECUBESEMAPHORE_H
#define META_IGGAMECUBESEMAPHORE_H
#include <meta/igSemaphore.h>
namespace Meta {
struct igGamecubeSemaphore : igSemaphore {
 unsigned int _initCount;  // 0x0C igUnsignedIntMetaField
 unsigned int _maxCount;  // 0x10 igUnsignedIntMetaField
 bool _isActive;  // 0x14 igBoolMetaField
 unsigned char unknown15[3];
 unsigned char _sema[12];  // 0x18 igStructMetaField
};
}
#endif
