// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igGamecubeImageConvert_register (metaobject lbl_80563464, vtable lbl_8049168C), size 0x8.
#ifndef META_IGGAMECUBEIMAGECONVERT_H
#define META_IGGAMECUBEIMAGECONVERT_H
#include <meta/igImageConvert.h>
namespace Meta {
struct igGamecubeImageConvert : igImageConvert {
};
}
#endif
