// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80149510 (metaobject lbl_8056428C, vtable lbl_804A90A0), size 0x14.
#ifndef META_IGGAUSSIANSMOOTHIMAGE_H
#define META_IGGAUSSIANSMOOTHIMAGE_H
#include <meta/igSmoothImage.h>
namespace Meta {
struct igGaussianSmoothImage : igSmoothImage {
};
}
#endif
