// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igGamecubeAudioSourceList_register (metaobject lbl_80562B60, vtable lbl_8047EAF8), size 0x14.
#ifndef META_IGGAMECUBEAUDIOSOURCELIST_H
#define META_IGGAMECUBEAUDIOSOURCELIST_H
#include <meta/igDataList.h>
namespace Meta {
struct igGamecubeAudioSourceList : igDataList {
};
}
#endif
