// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igGamecubeCallStackTracer_register (metaobject lbl_805620F4, vtable lbl_804705F8), size 0x14.
#ifndef META_IGGAMECUBECALLSTACKTRACER_H
#define META_IGGAMECUBECALLSTACKTRACER_H
#include <meta/igCallStackTracer.h>
namespace Meta {
struct igGamecubeCallStackTracer : igCallStackTracer {
};
}
#endif
