// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800B6434 (metaobject lbl_80562854, vtable lbl_8047C3E8), size 0x10.
#ifndef META_IGGEOMETRYMASKATTR_H
#define META_IGGEOMETRYMASKATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igGeometryMaskAttr : igVisualAttribute {
 unsigned int _mask;  // 0x0C igUnsignedIntMetaField
};
}
#endif
