// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igGenericAttrStatisticsList_register (metaobject lbl_80563B10, vtable lbl_804AAAD4), size 0x14.
#ifndef META_IGGENERICATTRSTATISTICSLIST_H
#define META_IGGENERICATTRSTATISTICSLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igGenericAttrStatisticsList : igObjectList {
};
}
#endif
