// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igGenerateMacroTexture_register (metaobject lbl_805641F8, vtable lbl_804A6660), size 0x6C.
#ifndef META_IGGENERATEMACROTEXTURE_H
#define META_IGGENERATEMACROTEXTURE_H
#include <meta/igOptTraverseGraph.h>
namespace Meta {
struct igGeometryListList;
struct igRegistry;
struct igTextureList;
struct igGenerateMacroTexture : igOptTraverseGraph {
 unsigned int _maxHeight;  // 0x34 igUnsignedIntMetaField
 unsigned int _maxWidth;  // 0x38 igUnsignedIntMetaField
 int _generatedTextureFormat;  // 0x3C igEnumMetaField
 const char *_outputTextureName;  // 0x40 igStringMetaField
 bool _ignoreInstantiation;  // 0x44 igBoolMetaField
 bool _useRepeatMode;  // 0x45 igBoolMetaField
 unsigned char unknown46[2];
 igTextureList *_textureList;  // 0x48 igObjectRefMetaField
 igTextureList *_excludeList;  // 0x4C igObjectRefMetaField
 igTextureList *_repeatList;  // 0x50 igObjectRefMetaField
 igGeometryListList *_geometryList;  // 0x54 igObjectRefMetaField
 igRegistry *_pagesRegistry;  // 0x58 igObjectRefMetaField
 const char *_fileName;  // 0x5C igStringMetaField
 const char *_sectionName;  // 0x60 igStringMetaField
 int _section;  // 0x64 igIntMetaField
 const char *_macroTextureName;  // 0x68 igStringMetaField
};
}
#endif
