// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igGenericNodeStatisticsList_register (metaobject lbl_80563B14, vtable lbl_804AAA0C), size 0x14.
#ifndef META_IGGENERICNODESTATISTICSLIST_H
#define META_IGGENERICNODESTATISTICSLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igGenericNodeStatisticsList : igObjectList {
};
}
#endif
