// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igGetCenterFunctionList_register (metaobject lbl_805639AC, vtable lbl_8049B740), size 0x14.
#ifndef META_IGGETCENTERFUNCTIONLIST_H
#define META_IGGETCENTERFUNCTIONLIST_H
#include <meta/igDataList.h>
namespace Meta {
struct igGetCenterFunctionList : igDataList {
};
}
#endif
