// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801C0048 (metaobject lbl_80564EEC, vtable lbl_804B730C), size 0x14.
#ifndef META_IGGEOMETRYLIST_H
#define META_IGGEOMETRYLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igGeometryList : igObjectList {
};
}
#endif
