// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igGeometry_register (metaobject lbl_80564EF0, vtable lbl_804B4A60), size 0x2C.
#ifndef META_IGGEOMETRY_H
#define META_IGGEOMETRY_H
#include <meta/igAttrSet.h>
namespace Meta {
struct igRenderListAttr;
struct igGeometry : igAttrSet {
 igRenderListAttr *_renderList;  // 0x28 igObjectRefMetaField
};
}
#endif
