// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igGeometryAttr2_register (metaobject lbl_8056285C, vtable lbl_8047C468), size 0x2C.
#ifndef META_IGGEOMETRYATTR2_H
#define META_IGGEOMETRYATTR2_H
#include <meta/igVisualAttribute.h>
#include <meta/enums.h>
namespace Meta {
struct igIndexArray;
struct igPrimLengthArray;
struct igVertexArray2;
struct igGeometryAttr2 : igVisualAttribute {
 igVertexArray2 *_vertexArray;  // 0x0C igObjectRefMetaField
 igIndexArray *_indexArray;  // 0x10 igObjectRefMetaField
 igPrimLengthArray *_stripLengths;  // 0x14 igObjectRefMetaField
 IG_GFX_DRAW::Value _primType;  // 0x18 igEnumMetaField
 unsigned int _numPrims;  // 0x1C igUnsignedIntMetaField
 unsigned int _offset;  // 0x20 igUnsignedIntMetaField
 unsigned int _unitID;  // 0x24 igUnsignedIntMetaField
 bool _drawState;  // 0x28 igBoolMetaField
 unsigned char unknown29[3];
};
}
#endif
