// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800B6F98 (metaobject lbl_805628B0, vtable lbl_8047C658), size 0x8.
#ifndef META_IGGENERICATTRDEFAULTMANAGER_H
#define META_IGGENERICATTRDEFAULTMANAGER_H
#include <meta/igAttrDefaultManager.h>
namespace Meta {
struct igGenericAttrDefaultManager : igAttrDefaultManager {
};
}
#endif
