// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igGfxStateModifierList_register (metaobject lbl_80563034, vtable lbl_8049365C), size 0x14.
#ifndef META_IGGFXSTATEMODIFIERLIST_H
#define META_IGGFXSTATEMODIFIERLIST_H
#include <meta/igDataList.h>
namespace Meta {
struct igGfxStateModifierList : igDataList {
};
}
#endif
