// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igGfxShaderConstantList_register (metaobject lbl_80563008, vtable lbl_80493778), size 0x14.
#ifndef META_IGGFXSHADERCONSTANTLIST_H
#define META_IGGFXSHADERCONSTANTLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igGfxShaderConstantList : igObjectList {
};
}
#endif
