// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igGfxShaderDefine_register (metaobject lbl_80563040, vtable lbl_80493538), size 0x14.
#ifndef META_IGGFXSHADERDEFINE_H
#define META_IGGFXSHADERDEFINE_H
#include <meta/igNamedObject.h>
namespace Meta {
struct igGfxShaderDefine : igNamedObject {
 void *_value;  // 0x0C igObjectRefMetaField
 bool _enabledState;  // 0x10 igBoolMetaField
 unsigned char unknown11[3];
};
}
#endif
