// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igGroup_register (metaobject lbl_80564ED0, vtable lbl_804B49CC), size 0x20.
#ifndef META_IGGROUP_H
#define META_IGGROUP_H
#include <meta/igNode.h>
namespace Meta {
struct igNodeList;
struct igGroup : igNode {
 igNodeList *_childList;  // 0x1C igObjectRefMetaField
};
}
#endif
