// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8011189C (metaobject lbl_80563738, vtable lbl_804964A0), size 0xC.
#ifndef META_IGGUICOMPONENTCONTROLLER_H
#define META_IGGUICOMPONENTCONTROLLER_H
#include <meta/igView.h>
namespace Meta {
struct igGuiComponentController : igView {
};
}
#endif
