// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igGuiComponentList_register (metaobject lbl_8056374C, vtable lbl_80497480), size 0x14.
#ifndef META_IGGUICOMPONENTLIST_H
#define META_IGGUICOMPONENTLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igGuiComponentList : igObjectList {
};
}
#endif
