// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80110EE8 (metaobject lbl_805636E0, vtable lbl_804963B0), size 0xB8.
#ifndef META_IGGUISYSTEMMODEL_H
#define META_IGGUISYSTEMMODEL_H
#include <meta/igModel.h>
namespace Meta {
struct igGuiComponent;
struct igGuiSystemModel : igModel {
 float _windowSize[2];  // 0x0C igVec2fMetaField
 float _mousePosition[2];  // 0x14 igVec2fMetaField
 bool _mousePressed;  // 0x1C igBoolMetaField
 unsigned char unknown1D[3];
 float _viewMatrix[16];  // 0x20 igMatrix44fMetaField
 float _projectionMatrix[16];  // 0x60 igMatrix44fMetaField
 bool _active;  // 0xA0 igBoolMetaField
 unsigned char unknownA1[3];
 igGuiComponent *_rootComponent;  // 0xA4 igObjectRefMetaField
 igGuiComponent *_focusedComponent;  // 0xA8 igObjectRefMetaField
 igGuiComponent *_componentUnderMouse;  // 0xAC igObjectRefMetaField
 igGuiComponent *_pushedComponent;  // 0xB0 igObjectRefMetaField
 bool _windowCloseRequested;  // 0xB4 igBoolMetaField
 unsigned char unknownB5[3];
};
}
#endif
