// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80111EAC (metaobject lbl_80563750, vtable lbl_8049659C), size 0x24.
#ifndef META_IGGUICOMPONENT_H
#define META_IGGUICOMPONENT_H
#include <meta/igObject.h>
namespace Meta {
struct igGuiComponentAspect;
struct igGuiComponentController;
struct igGuiComponentModel;
struct igGuiComponentNode;
struct igGuiSystem;
struct igGuiComponent : igObject {
 igGuiSystem *_guiSystem;  // 0x08 igObjectRefMetaField
 igGuiComponentController *_controller;  // 0x0C igObjectRefMetaField
 igGuiComponentModel *_model;  // 0x10 igObjectRefMetaField
 igGuiComponentAspect *_aspect;  // 0x14 igObjectRefMetaField
 igGuiComponent *_parent;  // 0x18 igObjectRefMetaField
 igGuiComponentNode *_node;  // 0x1C igObjectRefMetaField
 bool _linked;  // 0x20 igBoolMetaField
 unsigned char unknown21[3];
};
}
#endif
