// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801113F8 (metaobject lbl_80563710, vtable lbl_8049640C), size 0x24.
#ifndef META_IGGUICOMPONENTNODE_H
#define META_IGGUICOMPONENTNODE_H
#include <meta/igGroup.h>
namespace Meta {
struct igGuiComponent;
struct igGuiComponentNode : igGroup {
 igGuiComponent *_component;  // 0x20 igObjectRefMetaField
};
}
#endif
