// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801BF270 (metaobject lbl_80564EBC, vtable lbl_804B817C), size 0x10.
#ifndef META_IGHEAPABLE_H
#define META_IGHEAPABLE_H
#include <meta/igObject.h>
namespace Meta {
struct igHeapable : igObject {
 float _heapKey;  // 0x08 igFloatMetaField
 unsigned int _heapPosition;  // 0x0C igUnsignedIntMetaField
};
}
#endif
