// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80216984 (metaobject lbl_805659DC, vtable lbl_804BCA64), size 0xC.
#ifndef META_IGHISTOGRAMBASE_H
#define META_IGHISTOGRAMBASE_H
#include <meta/igObject.h>
namespace Meta {
struct igIntList;
struct igHistogramBase : igObject {
 igIntList *_bins;  // 0x08 igObjectRefMetaField
};
}
#endif
