// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80147364 (metaobject lbl_805641F4, vtable lbl_804A65D8), size 0x28.
#ifndef META_IGHIDEACTORSKINGRAPHS_H
#define META_IGHIDEACTORSKINGRAPHS_H
#include <meta/igOptBase.h>
namespace Meta {
struct igHideActorSkinGraphs : igOptBase {
};
}
#endif
