// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igHotKeyBinding_register (metaobject lbl_8056365C, vtable lbl_80497600), size 0x14.
#ifndef META_IGHOTKEYBINDING_H
#define META_IGHOTKEYBINDING_H
#include <meta/igObject.h>
namespace Meta {
struct igAction;
struct igHotKeyBinding : igObject {
 int _key;  // 0x08 igEnumMetaField
 int _button;  // 0x0C igEnumMetaField
 igAction *_action;  // 0x10 igObjectRefMetaField
};
}
#endif
