// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igHotKeyBindingList_register (metaobject lbl_80563658, vtable lbl_8049765C), size 0x14.
#ifndef META_IGHOTKEYBINDINGLIST_H
#define META_IGHOTKEYBINDINGLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igHotKeyBindingList : igObjectList {
};
}
#endif
