// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800AFA64 (metaobject lbl_80562594, vtable lbl_8047E194), size 0x14.
#ifndef META_IGIMAGEMIPMAPLIST_H
#define META_IGIMAGEMIPMAPLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igImageMipMapList : igObjectList {
};
}
#endif
