// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igImageList_register (metaobject lbl_80562F6C, vtable lbl_80493CA8), size 0x14.
#ifndef META_IGIMAGELIST_H
#define META_IGIMAGELIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igImageList : igObjectList {
};
}
#endif
