// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igImage_register (metaobject lbl_80562F78), size 0x5C.
#ifndef META_IGIMAGE_H
#define META_IGIMAGE_H
#include <meta/igObject.h>
namespace Meta {
struct igImage : igObject {
 unsigned char unknown08[84];
};
}
#endif
