// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80137BE0 (metaobject lbl_80563D38, vtable lbl_804A3FAC), size 0x50.
#ifndef META_IGIMAGEHISTOGRAM_LA_H
#define META_IGIMAGEHISTOGRAM_LA_H
#include <meta/igImageHistogramBase.h>
namespace Meta {
struct igImageHistogram_LA : igImageHistogramBase {
};
}
#endif
