// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800D1F6C (metaobject lbl_80562F60), size 0x8.
#ifndef META_IGIMAGEUTILS_H
#define META_IGIMAGEUTILS_H
#include <meta/igObject.h>
namespace Meta {
struct igImageUtils : igObject {
};
}
#endif
