// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80137648 (metaobject lbl_80563D30, vtable lbl_804A3E6C), size 0x50.
#ifndef META_IGIMAGEHISTOGRAM_RGBA_H
#define META_IGIMAGEHISTOGRAM_RGBA_H
#include <meta/igImageHistogramBase.h>
namespace Meta {
struct igImageHistogram_RGBA : igImageHistogramBase {
};
}
#endif
