// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80146510 (metaobject lbl_80564178, vtable lbl_804A63C8), size 0x2C.
#ifndef META_IGINTERNALIZESHADER_H
#define META_IGINTERNALIZESHADER_H
#include <meta/igOptVisitObject.h>
namespace Meta {
struct igInternalizeShader : igOptVisitObject {
};
}
#endif
