// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80033F84 (metaobject lbl_80561D54, vtable lbl_80475358), size 0x14.
#ifndef META_IGINTLISTLIST_H
#define META_IGINTLISTLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igIntListList : igObjectList {
};
}
#endif
