// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igIntersectTraversal_register (metaobject lbl_80564E3C, vtable lbl_804B4474), size 0x40.
#ifndef META_IGINTERSECTTRAVERSAL_H
#define META_IGINTERSECTTRAVERSAL_H
#include <meta/igTraversal.h>
namespace Meta {
struct igMatrixStack;
struct igNodeList;
struct igProbe;
struct igRay;
struct igVolumeList;
struct igIntersectTraversal : igTraversal {
 igMatrixStack *_matStack;  // 0x20 igObjectRefMetaField
 igNodeList *_nodeStack;  // 0x24 igObjectRefMetaField
 igProbe *_probe;  // 0x28 igObjectRefMetaField
 int _mode;  // 0x2C igIntMetaField
 void *_hitProc;  // 0x30 igRawRefMetaField
 igVolumeList *_volumes;  // 0x34 igObjectRefMetaField
 igRay *_ray;  // 0x38 igObjectRefMetaField
 unsigned char unknown3C[4];
};
}
#endif
