// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igInterfaced_register (metaobject lbl_8056417C), size 0x20.
#ifndef META_IGINTERFACED_H
#define META_IGINTERFACED_H
#include <meta/igObject.h>
namespace Meta {
struct igItemInterface;
struct igListenerInterface;
struct igLockInterface;
struct igLogInterface;
struct igMessageInterface;
struct igOptInterface;
struct igInterfaced : igObject {
 igOptInterface *_optInterface;  // 0x08 igObjectRefMetaField
 igItemInterface *_itemInterface;  // 0x0C igObjectRefMetaField
 igListenerInterface *_listenerInterface;  // 0x10 igObjectRefMetaField
 igMessageInterface *_messageInterface;  // 0x14 igObjectRefMetaField
 igLockInterface *_lockInterface;  // 0x18 igObjectRefMetaField
 igLogInterface *_logInterface;  // 0x1C igObjectRefMetaField
};
}
#endif
