// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80121394 (metaobject lbl_805639D8, vtable lbl_8049AF00), size 0x14.
#ifndef META_IGINTERSECTIONFUNCTIONLIST_H
#define META_IGINTERSECTIONFUNCTIONLIST_H
#include <meta/igDataList.h>
namespace Meta {
struct igIntersectionFunctionList : igDataList {
};
}
#endif
