// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8002E3B8 (metaobject lbl_805619E0), size 0x34.
#ifndef META_IGINTMETAFIELD_H
#define META_IGINTMETAFIELD_H
#include <meta/igMetaField.h>
namespace Meta {
struct igIntMetaField : igMetaField {
};
}
#endif
