// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igInterpretedShaderProcessor_register (metaobject lbl_80564E6C, vtable lbl_804B473C), size 0x8.
#ifndef META_IGINTERPRETEDSHADERPROCESSOR_H
#define META_IGINTERPRETEDSHADERPROCESSOR_H
#include <meta/igShaderProcessor.h>
namespace Meta {
struct igInterpretedShaderProcessor : igShaderProcessor {
};
}
#endif
