// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801BD404 (metaobject lbl_80564E0C, vtable lbl_804B46CC), size 0xB0.
#ifndef META_IGINVERSEKINEMATICSANIMATION_H
#define META_IGINVERSEKINEMATICSANIMATION_H
#include <meta/igAnimation.h>
namespace Meta {
struct igActor;
struct igTransformRecorder;
struct igInverseKinematicsAnimation : igAnimation {
 float _goalMatrix[16];  // 0x40 igMatrix44fMetaField
 float _solverTwistValue;  // 0x80 igFloatMetaField
 void *_initialMatrixArray;  // 0x84 igMemoryRefMetaField
 void *_solutionMatrixArray;  // 0x88 igMemoryRefMetaField
 void *_resultMatrixArray;  // 0x8C igMemoryRefMetaField
 void *_skeletonBoneIndexArray;  // 0x90 igMemoryRefMetaField
 void *_skeletonParentBoneIndexArray;  // 0x94 igMemoryRefMetaField
 igActor *_actor;  // 0x98 igObjectRefMetaField
 igTransformRecorder *_recorder;  // 0x9C igObjectRefMetaField
 int _goalBoneIndex;  // 0xA0 igIntMetaField
 float _solverPoleVector[3];  // 0xA4 igVec3fMetaField
};
}
#endif
