// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igIntList_register (metaobject lbl_80561DC4, vtable lbl_80474600), size 0x14.
#ifndef META_IGINTLIST_H
#define META_IGINTLIST_H
#include <meta/igDataList.h>
namespace Meta {
struct igIntList : igDataList {
};
}
#endif
