// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801BC1F4 (metaobject lbl_80564DC8, vtable lbl_804B44E4), size 0x14.
#ifndef META_IGINVERSEKINEMATICSSOURCE_H
#define META_IGINVERSEKINEMATICSSOURCE_H
#include <meta/igAnimationSequence.h>
namespace Meta {
struct igInverseKinematicsAnimation;
struct igInverseKinematicsSource : igAnimationSequence {
 igInverseKinematicsAnimation *_inverseKinematicsAnimation;  // 0x08 igObjectRefMetaField
 unsigned int _boneIndex;  // 0x0C igUnsignedIntMetaField
 bool _evaluated;  // 0x10 igBoolMetaField
 unsigned char unknown11[3];
};
}
#endif
