// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igIniShaderFactory_register (metaobject lbl_80564E88, vtable lbl_804B4860), size 0x3C.
#ifndef META_IGINISHADERFACTORY_H
#define META_IGINISHADERFACTORY_H
#include <meta/igShaderFactory.h>
namespace Meta {
struct igInterpretedShaderData;
struct igMemoryPool;
struct igObjectStringMap;
struct igRegistry;
struct igIniShaderFactory : igShaderFactory {
 const char *_implementationName;  // 0x18 igStringMetaField
 igRegistry *_implementation;  // 0x1C igObjectRefMetaField
 igRegistry *_interface;  // 0x20 igObjectRefMetaField
 const char *_interfaceFileName;  // 0x24 igStringMetaField
 int _interfaceSection;  // 0x28 igIntMetaField
 igMemoryPool *_mp;  // 0x2C igObjectRefMetaField
 igInterpretedShaderData *_data;  // 0x30 igObjectRefMetaField
 igObjectStringMap *_cachedObjects;  // 0x34 igObjectRefMetaField
 igObjectStringMap *_fileCache;  // 0x38 igObjectRefMetaField
};
}
#endif
