// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800364EC (metaobject lbl_80561DC0, vtable lbl_804745A0), size 0x14.
#ifndef META_IGINTLISTNOCLEAN_H
#define META_IGINTLISTNOCLEAN_H
#include <meta/igIntList.h>
namespace Meta {
struct igIntListNoClean : igIntList {
};
}
#endif
