// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80286C34 (metaobject lbl_80515D30, vtable lbl_804CB3A4), size 0x1C.
#ifndef META_IGINFOMANAGERORDEREDLIST_H
#define META_IGINFOMANAGERORDEREDLIST_H
#include <meta/igDependencyOrderedList.h>
namespace Meta {
struct igInfoManagerOrderedList : igDependencyOrderedList {
};
}
#endif
