// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igInstanceChangedListener_register (metaobject lbl_805641EC, vtable lbl_804A94AC), size 0x20.
#ifndef META_IGINSTANCECHANGEDLISTENER_H
#define META_IGINSTANCECHANGEDLISTENER_H
#include <meta/igObjectChangedListener.h>
namespace Meta {
struct igInstanceChangedListener : igObjectChangedListener {
};
}
#endif
