// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igInverseKinematicsHandleList_register (metaobject lbl_80564DF4, vtable lbl_804B77DC), size 0x14.
#ifndef META_IGINVERSEKINEMATICSHANDLELIST_H
#define META_IGINVERSEKINEMATICSHANDLELIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igInverseKinematicsHandleList : igObjectList {
};
}
#endif
