// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80144CF4 (metaobject lbl_80564130, vtable lbl_804A9A0C), size 0x20.
#ifndef META_IGITEMMANAGER_H
#define META_IGITEMMANAGER_H
#include <meta/igManager.h>
namespace Meta {
struct igItemManager : igManager {
};
}
#endif
