// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igItemInterface_register (metaobject lbl_80564134, vtable lbl_804A62BC), size 0x34.
#ifndef META_IGITEMINTERFACE_H
#define META_IGITEMINTERFACE_H
#include <meta/igInterface.h>
namespace Meta {
struct igItemDataBaseList;
struct igMetaObjectList;
struct igMetaObjectListList;
struct igStringRefListList;
struct igItemInterface : igInterface {
 igItemDataBaseList *_itemDataBaseList;  // 0x20 igObjectRefMetaField
 igMetaObjectList *_metaList;  // 0x24 igObjectRefMetaField
 igMetaObjectListList *_itemList;  // 0x28 igObjectRefMetaField
 igStringRefListList *_itemNameList;  // 0x2C igObjectRefMetaField
 unsigned int _currentKnownItem;  // 0x30 igUnsignedIntMetaField
};
}
#endif
