// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80143C60 (metaobject lbl_805640D8), size 0x8.
#ifndef META_IGITERATOR_H
#define META_IGITERATOR_H
#include <meta/igObject.h>
namespace Meta {
struct igIterator : igObject {
};
}
#endif
