// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igIterateObject_register (metaobject lbl_805640DC, vtable lbl_804A9BE8), size 0x24.
#ifndef META_IGITERATEOBJECT_H
#define META_IGITERATEOBJECT_H
#include <meta/igIterator.h>
namespace Meta {
struct igIntList;
struct igItemInterface;
struct igObjectList;
struct igObjectListList;
struct igIterateObject : igIterator {
 igItemInterface *_itemInterface;  // 0x08 igObjectRefMetaField
 const char *_traversalName;  // 0x0C igStringMetaField
 bool _visitOnce;  // 0x10 igBoolMetaField
 unsigned char unknown11[3];
 igObjectList *_currentPath;  // 0x14 igObjectRefMetaField
 igIntList *_currentIndices;  // 0x18 igObjectRefMetaField
 igObjectListList *_cachedChildList;  // 0x1C igObjectRefMetaField
 igObjectList *_traversedObject;  // 0x20 igObjectRefMetaField
};
}
#endif
