// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80144564 (metaobject lbl_8056410C, vtable lbl_804A9B30), size 0x10.
#ifndef META_IGITERATEFIELD_H
#define META_IGITERATEFIELD_H
#include <meta/igIterator.h>
namespace Meta {
struct igMetaObject;
struct igIterateField : igIterator {
 igMetaObject *_iterated;  // 0x08 igObjectRefMetaField
 int _current;  // 0x0C igIntMetaField
};
}
#endif
