// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80145C0C (metaobject lbl_80564164), size 0x20.
#ifndef META_IGITEMBASE_H
#define META_IGITEMBASE_H
#include <meta/igBase.h>
namespace Meta {
struct igItemBase : igBase {
};
}
#endif
