// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80145218 (metaobject lbl_8056414C, vtable lbl_804A9954), size 0x14.
#ifndef META_IGITEMDATABASELIST_H
#define META_IGITEMDATABASELIST_H
#include <meta/igCompoundList.h>
namespace Meta {
struct igItemDataBaseList : igCompoundList {
};
}
#endif
