// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igJoint_register (metaobject lbl_80564DBC, vtable lbl_804B7A1C), size 0xB0.
#ifndef META_IGJOINT_H
#define META_IGJOINT_H
#include <meta/igTransform.h>
namespace Meta {
struct igMatrixObject;
struct igJoint : igTransform {
 float _inverseOriginalTransform[16];  // 0x6C igMatrix44fMetaField
 igMatrixObject *_blendingMatrix;  // 0xAC igObjectRefMetaField
};
}
#endif
