// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80149F18 (metaobject lbl_805642BC, vtable lbl_804A8EB0), size 0x10.
#ifndef META_IGLANCZOS3FILTERFUN_H
#define META_IGLANCZOS3FILTERFUN_H
#include <meta/igSerialFilterFun.h>
namespace Meta {
struct igLanczos3FilterFun : igSerialFilterFun {
};
}
#endif
