// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8014310C (metaobject lbl_805640AC, vtable lbl_804A9E30), size 0x20.
#ifndef META_IGLISTENERMANAGER_H
#define META_IGLISTENERMANAGER_H
#include <meta/igManager.h>
namespace Meta {
struct igListenerManager : igManager {
};
}
#endif
