// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80142F90 (metaobject lbl_805640A8), size 0x20.
#ifndef META_IGLISTENERPRODUCERBASE_H
#define META_IGLISTENERPRODUCERBASE_H
#include <meta/igBase.h>
namespace Meta {
struct igListenerProducerBase : igBase {
};
}
#endif
