// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igLightSet_register (metaobject lbl_80564DB4, vtable lbl_804B43E8), size 0x20.
#ifndef META_IGLIGHTSET_H
#define META_IGLIGHTSET_H
#include <meta/igNode.h>
namespace Meta {
struct igLightList;
struct igLightSet : igNode {
 igLightList *_lights;  // 0x1C igObjectRefMetaField
};
}
#endif
