// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801BB828 (metaobject lbl_80564DAC, vtable lbl_804B4354), size 0x24.
#ifndef META_IGLIGHTSTATESET_H
#define META_IGLIGHTSTATESET_H
#include <meta/igGroup.h>
namespace Meta {
struct igLightStateAttrList;
struct igLightStateSet : igGroup {
 igLightStateAttrList *_lightEnables;  // 0x20 igObjectRefMetaField
};
}
#endif
