// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igListenerList_register (metaobject lbl_805640C8, vtable lbl_804A9CA0), size 0x14.
#ifndef META_IGLISTENERLIST_H
#define META_IGLISTENERLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igListenerList : igObjectList {
};
}
#endif
