// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igListenerListList_register (metaobject lbl_805640C4, vtable lbl_804A9D68), size 0x14.
#ifndef META_IGLISTENERLISTLIST_H
#define META_IGLISTENERLISTLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igListenerListList : igObjectList {
};
}
#endif
