// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801438C4 (metaobject lbl_805640CC, vtable lbl_804AAED0), size 0x20.
#ifndef META_IGLISTENERBASE_H
#define META_IGLISTENERBASE_H
#include <meta/igBase.h>
namespace Meta {
struct igListenerBase : igBase {
};
}
#endif
