// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igLibraryLoader_register (metaobject lbl_805619BC), size 0x8.
#ifndef META_IGLIBRARYLOADER_H
#define META_IGLIBRARYLOADER_H
#include <meta/igObject.h>
namespace Meta {
struct igLibraryLoader : igObject {
};
}
#endif
