// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igLibrary_register (metaobject lbl_805619C4), size 0xC.
#ifndef META_IGLIBRARY_H
#define META_IGLIBRARY_H
#include <meta/igObject.h>
namespace Meta {
struct igLibrary : igObject {
 void *_registerFunction;  // 0x08 igRawRefMetaField
};
}
#endif
