// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igLongArrayMetaField_register (metaobject lbl_80561994, vtable lbl_804721F4), size 0x38.
#ifndef META_IGLONGARRAYMETAFIELD_H
#define META_IGLONGARRAYMETAFIELD_H
#include <meta/igLongMetaField.h>
namespace Meta {
struct igLongArrayMetaField : igLongMetaField {
 int _num;  // 0x34 igIntMetaField
};
}
#endif
