// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igLongStack_register (metaobject lbl_805659C4, vtable lbl_804BCDC0), size 0x14.
#ifndef META_IGLONGSTACK_H
#define META_IGLONGSTACK_H
#include <meta/igDataList.h>
namespace Meta {
struct igLongStack : igDataList {
};
}
#endif
