// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8002CD80 (metaobject lbl_80561978), size 0x28.
#ifndef META_IGLONGTIMER_H
#define META_IGLONGTIMER_H
#include <meta/igTimer.h>
namespace Meta {
struct igLongTimer : igTimer {
 long long _startTime;  // 0x08 igLongMetaField
 long long _additionalTime;  // 0x10 igLongMetaField
 long long _resetTime;  // 0x18 igLongMetaField
 bool _isStopped;  // 0x20 igBoolMetaField
 unsigned char unknown21[7];
};
}
#endif
