// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igLogInterface_register (metaobject lbl_80564088, vtable lbl_804A60D8), size 0x24.
#ifndef META_IGLOGINTERFACE_H
#define META_IGLOGINTERFACE_H
#include <meta/igInterface.h>
namespace Meta {
struct igLogInterface : igInterface {
 bool _verbose;  // 0x20 igBoolMetaField
 unsigned char unknown21[3];
};
}
#endif
