// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igLongList_register (metaobject lbl_80561DB0, vtable lbl_80474780), size 0x14.
#ifndef META_IGLONGLIST_H
#define META_IGLONGLIST_H
#include <meta/igDataList.h>
namespace Meta {
struct igLongList : igDataList {
};
}
#endif
