// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igMatrixStack_register (metaobject lbl_80565A4C, vtable lbl_804BC474), size 0x14.
#ifndef META_IGMATRIXSTACK_H
#define META_IGMATRIXSTACK_H
#include <meta/igDataList.h>
namespace Meta {
struct igMatrixStack : igDataList {
};
}
#endif
