// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801B21E4 (metaobject lbl_80564944, vtable lbl_804B8E40), size 0x20.
#ifndef META_IGMATRIXOBJECTPOOL_H
#define META_IGMATRIXOBJECTPOOL_H
#include <meta/igObjectPool.h>
namespace Meta {
struct igMatrixObjectPool : igObjectPool {
};
}
#endif
