// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800B46D8 (metaobject lbl_80562780, vtable lbl_8047BE68), size 0x10.
#ifndef META_IGMATRIXOPTSTATEATTR_H
#define META_IGMATRIXOPTSTATEATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igMatrixOptStateAttr : igVisualAttribute {
 bool _enabled;  // 0x0C igBoolMetaField
 unsigned char unknown0D[3];
};
}
#endif
