// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igMacrotextureStrip_register (metaobject lbl_80564060, vtable lbl_804A5FB8), size 0x44.
#ifndef META_IGMACROTEXTURESTRIP_H
#define META_IGMACROTEXTURESTRIP_H
#include <meta/igOptVisitObject.h>
namespace Meta {
struct igMacrotextureStrip : igOptVisitObject {
 const char *_hashString;  // 0x2C igStringMetaField
 const char *_geoString;  // 0x30 igStringMetaField
 bool _ignoreUVRepeat;  // 0x34 igBoolMetaField
 unsigned char unknown35[3];
 const char *_macroTextureName;  // 0x38 igStringMetaField
 int _magnificationFilter;  // 0x3C igEnumMetaField
 int _minificationFilter;  // 0x40 igEnumMetaField
};
}
#endif
