// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80121514 (metaobject lbl_805639E0, vtable lbl_8049AD78), size 0x14.
#ifndef META_IGMATRIX44FLIST_H
#define META_IGMATRIX44FLIST_H
#include <meta/igDataList.h>
namespace Meta {
struct igMatrix44fList : igDataList {
};
}
#endif
