// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igMatrix44dMetaField_register (metaobject lbl_8056399C, vtable lbl_8049A144), size 0x34.
#ifndef META_IGMATRIX44DMETAFIELD_H
#define META_IGMATRIX44DMETAFIELD_H
#include <meta/igMetaField.h>
namespace Meta {
struct igMatrix44dMetaField : igMetaField {
};
}
#endif
