// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igMacroOpt_register (metaobject lbl_8056407C, vtable lbl_804A6050), size 0x30.
#ifndef META_IGMACROOPT_H
#define META_IGMACROOPT_H
#include <meta/igOptBase.h>
namespace Meta {
struct igRegistry;
struct igMacroOpt : igOptBase {
 const char *_fileName;  // 0x28 igStringMetaField
 igRegistry *_fileRegistry;  // 0x2C igObjectRefMetaField
};
}
#endif
