// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8021805C (metaobject lbl_80565A5C, vtable lbl_804BC224), size 0x14.
#ifndef META_IGMATRIXOBJECTLIST_H
#define META_IGMATRIXOBJECTLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igMatrixObjectList : igObjectList {
};
}
#endif
