// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80142038 (metaobject lbl_8056405C, vtable lbl_804AA22C), size 0x20.
#ifndef META_IGMANAGER_H
#define META_IGMANAGER_H
#include <meta/igInterfaced.h>
namespace Meta {
struct igManager : igInterfaced {
};
}
#endif
