// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igMemoryRefArrayMetaField_register (metaobject lbl_80561848, vtable lbl_80471A08), size 0x54.
#ifndef META_IGMEMORYREFARRAYMETAFIELD_H
#define META_IGMEMORYREFARRAYMETAFIELD_H
#include <meta/igMemoryRefMetaField.h>
namespace Meta {
struct igMemoryRefArrayMetaField : igMemoryRefMetaField {
 int _num;  // 0x50 igIntMetaField
};
}
#endif
