// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80284D3C (metaobject lbl_80515C88, vtable lbl_804CB8C4), size 0x14.
#ifndef META_IGMESSAGERECEIVERLIST_H
#define META_IGMESSAGERECEIVERLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igMessageReceiverList : igObjectList {
};
}
#endif
