// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igMemoryDirEntry_register (metaobject lbl_80561914, vtable lbl_80471F20), size 0x38.
#ifndef META_IGMEMORYDIRENTRY_H
#define META_IGMEMORYDIRENTRY_H
#include <meta/igDirEntry.h>
namespace Meta {
struct igMetaField;
struct igMemoryDirEntry : igDirEntry {
 int _memSize;  // 0x1C igIntMetaField
 int _memTypeSize;  // 0x20 igIntMetaField
 igMetaField *_memType;  // 0x24 igObjectRefMetaField
 int _memTypeIndex;  // 0x28 igIntMetaField
 int _alignmentTypeIndex;  // 0x2C igIntMetaField
 int _memoryPoolHandle;  // 0x30 igIntMetaField
 bool _refCounted;  // 0x34 igBoolMetaField
 unsigned char unknown35[3];
};
}
#endif
