// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8002C51C (metaobject lbl_80561904, vtable lbl_80475EF8), size 0x14.
#ifndef META_IGMEMORYFILEENTRYLIST_H
#define META_IGMEMORYFILEENTRYLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igMemoryFileEntryList : igObjectList {
};
}
#endif
