// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8028570C (metaobject lbl_80515CAC), size 0x8.
#ifndef META_IGMESSAGEDISPATCHER_H
#define META_IGMESSAGEDISPATCHER_H
#include <meta/igObject.h>
namespace Meta {
struct igMessageDispatcher : igObject {
};
}
#endif
