// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80141E90 (metaobject lbl_80564054, vtable lbl_804A5F30), size 0x2C.
#ifndef META_IGMERGEIGB_H
#define META_IGMERGEIGB_H
#include <meta/igOptBase.h>
namespace Meta {
struct igMergeIGB : igOptBase {
 const char *_igbName;  // 0x28 igStringMetaField
};
}
#endif
