// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igMessageBase_register (metaobject lbl_80564050, vtable lbl_804AA878), size 0x20.
#ifndef META_IGMESSAGEBASE_H
#define META_IGMESSAGEBASE_H
#include <meta/igBase.h>
namespace Meta {
struct igMessageBase : igBase {
};
}
#endif
