// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igMessenger_register (metaobject lbl_80515C7C, vtable lbl_804CB98C), size 0xC.
#ifndef META_IGMESSENGER_H
#define META_IGMESSENGER_H
#include <meta/igObject.h>
namespace Meta {
struct igMessageDispatcher;
struct igMessenger : igObject {
 igMessageDispatcher *_dispatcher;  // 0x08 igObjectRefMetaField
};
}
#endif
