// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igMetaEnumList_register (metaobject lbl_805643CC, vtable lbl_804A8A08), size 0x14.
#ifndef META_IGMETAENUMLIST_H
#define META_IGMETAENUMLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igMetaEnumList : igObjectList {
};
}
#endif
