// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igMemoryPoolInfoList_register (metaobject lbl_80561854, vtable lbl_80475FC0), size 0x14.
#ifndef META_IGMEMORYPOOLINFOLIST_H
#define META_IGMEMORYPOOLINFOLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igMemoryPoolInfoList : igObjectList {
};
}
#endif
