// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80285220 (metaobject lbl_80515C94, vtable lbl_804CB79C), size 0x10.
#ifndef META_IGMESSAGEFILTER_H
#define META_IGMESSAGEFILTER_H
#include <meta/igObject.h>
namespace Meta {
struct igMessageReceiverList;
struct igMetaObject;
struct igMessageFilter : igObject {
 igMetaObject *_msgType;  // 0x08 igObjectRefMetaField
 igMessageReceiverList *_receivers;  // 0x0C igObjectRefMetaField
};
}
#endif
