// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800342F4 (metaobject lbl_80561D5C, vtable lbl_804751C8), size 0x14.
#ifndef META_IGMETAOBJECTLISTLIST_H
#define META_IGMETAOBJECTLISTLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igMetaObjectListList : igObjectList {
};
}
#endif
