// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igMetaEnum_register (metaobject lbl_80561808, vtable lbl_8047617C), size 0x14.
#ifndef META_IGMETAENUM_H
#define META_IGMETAENUM_H
#include <meta/igObject.h>
namespace Meta {
struct igIntList;
struct igStringRefList;
struct igMetaEnum : igObject {
 const char *_name;  // 0x08 igStringMetaField
 igStringRefList *_names;  // 0x0C igObjectRefMetaField
 igIntList *_values;  // 0x10 igObjectRefMetaField
};
}
#endif
