// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8002A0D0 (metaobject lbl_8056174C), size 0x64.
#ifndef META_IGMETAOBJECT_H
#define META_IGMETAOBJECT_H
#include <meta/igObject.h>
namespace Meta {
struct __internalNonRefCountedObjectList;
struct __internalObjectList;
struct igMetaObject : igObject {
 int _id;  // 0x08 igIntMetaField
 int _index;  // 0x0C igIntMetaField
 int _majorVersion;  // 0x10 igIntMetaField
 int _minorVersion;  // 0x14 igIntMetaField
 bool _volatile;  // 0x18 igBoolMetaField
 bool _persistent;  // 0x19 igBoolMetaField
 bool _abstractState;  // 0x1A igBoolMetaField
 unsigned char unknown1B[1];
 const char *_name;  // 0x1C igStringMetaField
 int _runTimeSize;  // 0x20 igIntMetaField
 int _validity;  // 0x24 igIntMetaField
 __internalObjectList *_metaFields;  // 0x28 igObjectRefMetaField
 int _instanceCount;  // 0x2C igIntMetaField
 __internalNonRefCountedObjectList *_instances;  // 0x30 igObjectRefMetaField
 __internalNonRefCountedObjectList *_children;  // 0x34 igObjectRefMetaField
 igMetaObject *_parent;  // 0x38 igObjectRefMetaField
 void *_abstractProxy;  // 0x3C igRawRefMetaField
 void *_writeProxy;  // 0x40 igRawRefMetaField
 void *_templateObject;  // 0x44 igObjectRefMetaField
 int _sizeofSize;  // 0x48 igIntMetaField
 void *_setupFunction;  // 0x4C igRawRefMetaField
 void *_cleanupFunction;  // 0x50 igRawRefMetaField
 void *_getMetaObjectFunction;  // 0x54 igRawRefMetaField
 unsigned short _requiredAlignment;  // 0x58 igUnsignedShortMetaField
 unsigned char unknown5A[2];
 void *_vTablePointer;  // 0x5C igRawRefMetaField
 const char *_poolName;  // 0x60 igStringMetaField
};
}
#endif
