// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igMemoryPool_register (metaobject lbl_805618B4), size 0x70.
#ifndef META_IGMEMORYPOOL_H
#define META_IGMEMORYPOOL_H
#include <meta/igObject.h>
namespace Meta {
struct igMemoryPool : igObject {
 long long _localAllocated;  // 0x08 igLongMetaField
 long long _localFreed;  // 0x10 igLongMetaField
 long long _localNetAllocated;  // 0x18 igLongMetaField
 long long _localNetAllocatedHigh;  // 0x20 igLongMetaField
 long long _localAllocatedWithOverhead;  // 0x28 igLongMetaField
 long long _localFreedWithOverhead;  // 0x30 igLongMetaField
 long long _localNetAllocatedWithOverhead;  // 0x38 igLongMetaField
 long long _localNetAllocatedWithOverheadHigh;  // 0x40 igLongMetaField
 long long _localAllocationCount;  // 0x48 igLongMetaField
 long long _localFreeCount;  // 0x50 igLongMetaField
 long long _localNetAllocationCount;  // 0x58 igLongMetaField
 long long _localNetAllocationCountHigh;  // 0x60 igLongMetaField
 bool _updateStatistics;  // 0x68 igBoolMetaField
 bool _updateGlobalStatistics;  // 0x69 igBoolMetaField
 unsigned char unknown6A[6];
};
}
#endif
