// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igMetaFieldInfo_register (metaobject lbl_805617B4, vtable lbl_804718B0), size 0x14.
#ifndef META_IGMETAFIELDINFO_H
#define META_IGMETAFIELDINFO_H
#include <meta/igInfo.h>
namespace Meta {
struct igMetaFieldInfo : igInfo {
};
}
#endif
