// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80285904 (metaobject lbl_80515CB0, vtable lbl_804CBF40), size 0x18.
// Note: _msgHandlerFunc: igStructMetaField, count from the space to the next member.
#ifndef META_IGMESSAGEDEFAULTRECEIVER_H
#define META_IGMESSAGEDEFAULTRECEIVER_H
#include <meta/igMessageReceiver.h>
namespace Meta {
struct igMessageDefaultReceiver : igMessageReceiver {
 void *_msgHandler;  // 0x08 igObjectRefMetaField
 unsigned char _msgHandlerFunc[12];  // 0x0C igStructMetaField
};
}
#endif
