// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igMessageReceiver_register (metaobject lbl_80515C8C), size 0x8.
#ifndef META_IGMESSAGERECEIVER_H
#define META_IGMESSAGERECEIVER_H
#include <meta/igObject.h>
namespace Meta {
struct igMessageReceiver : igObject {
};
}
#endif
