// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80149D9C (metaobject lbl_805642B8, vtable lbl_804A8F14), size 0x10.
#ifndef META_IGMITCHELLFILTERFUN_H
#define META_IGMITCHELLFILTERFUN_H
#include <meta/igSerialFilterFun.h>
namespace Meta {
struct igMitchellFilterFun : igSerialFilterFun {
};
}
#endif
