// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igMorphSequenceData_register (metaobject lbl_80564CF0, vtable lbl_804B7CB8), size 0x20.
#ifndef META_IGMORPHSEQUENCEDATA_H
#define META_IGMORPHSEQUENCEDATA_H
#include <meta/igObject.h>
namespace Meta {
struct igFloatList;
struct igUnsignedIntList;
struct igMorphSequenceData : igObject {
 int _keyCount;  // 0x08 igIntMetaField
 igUnsignedIntList *_timeList;  // 0x0C igObjectRefMetaField
 igFloatList *_dataList;  // 0x10 igObjectRefMetaField
 igFloatList *_interpList;  // 0x14 igObjectRefMetaField
 int _lastKey;  // 0x18 igIntMetaField
 bool _unifTime;  // 0x1C igBoolMetaField
 unsigned char unknown1D[3];
};
}
#endif
