// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802AD104 (metaobject lbl_8053446C, vtable lbl_804CE898), size 0x10.
#ifndef META_IGMOVIERENDERER_H
#define META_IGMOVIERENDERER_H
#include <meta/igRenderer.h>
namespace Meta {
struct igMovieManager;
struct igMovieRenderer : igRenderer {
 igMovieManager *_movieManager;  // 0x0C igObjectRefMetaField
};
}
#endif
