// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801B9710 (metaobject lbl_80564CEC, vtable lbl_804B7D14), size 0x14.
#ifndef META_IGMORPHSEQUENCEDATALIST_H
#define META_IGMORPHSEQUENCEDATALIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igMorphSequenceDataList : igObjectList {
};
}
#endif
