// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802AC42C (metaobject lbl_80534404, vtable lbl_804CE118), size 0x14.
#ifndef META_IGMOVIEINFOLIST_H
#define META_IGMOVIEINFOLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igMovieInfoList : igObjectList {
};
}
#endif
