// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igMovieCodec_register (metaobject lbl_805343D8, vtable lbl_804CE7D8), size 0xC.
#ifndef META_IGMOVIECODEC_H
#define META_IGMOVIECODEC_H
#include <meta/igNamedObject.h>
namespace Meta {
struct igMovieCodec : igNamedObject {
};
}
#endif
