// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igMovieManager_register (metaobject lbl_80534474, vtable lbl_804CE958), size 0x28.
#ifndef META_IGMOVIEMANAGER_H
#define META_IGMOVIEMANAGER_H
#include <meta/igInfoManager.h>
namespace Meta {
struct igAudioContext;
struct igMovieCodecList;
struct igMovieInfoList;
struct igMovieRenderer;
struct igRendererOrderedList;
struct igMovieManager : igInfoManager {
 igMovieInfoList *_movieList;  // 0x10 igObjectRefMetaField
 bool _audioDisabled;  // 0x14 igBoolMetaField
 unsigned char unknown15[3];
 igAudioContext *_audio;  // 0x18 igObjectRefMetaField
 igMovieCodecList *_codecList;  // 0x1C igObjectRefMetaField
 igMovieRenderer *_movieRenderer;  // 0x20 igObjectRefMetaField
 igRendererOrderedList *_rendererList;  // 0x24 igObjectRefMetaField
};
}
#endif
