// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igModel_register (metaobject lbl_80563638, vtable lbl_80496040), size 0xC.
#ifndef META_IGMODEL_H
#define META_IGMODEL_H
#include <meta/igObject.h>
namespace Meta {
struct igNonRefCountedViewList;
struct igModel : igObject {
 igNonRefCountedViewList *_views;  // 0x08 igObjectRefMetaField
};
}
#endif
