// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igMorphSequence_register (metaobject lbl_80564CBC, vtable lbl_804B7DDC), size 0x40.
#ifndef META_IGMORPHSEQUENCE_H
#define META_IGMORPHSEQUENCE_H
#include <meta/igObject.h>
#include <meta/enums.h>
namespace Meta {
struct igMorphSequenceDataList;
struct igUnsignedIntList;
struct igMorphSequence : igObject {
 int _keyCount;  // 0x08 igIntMetaField
 igUnsignedIntList *_timeList;  // 0x0C igObjectRefMetaField
 int _lastKey;  // 0x10 igIntMetaField
 bool _unifTime;  // 0x14 igBoolMetaField
 unsigned char unknown15[3];
 igMorphSequence_PLAY_MODE::Value _playMode;  // 0x18 igEnumMetaField
 INTERPOLATION_METHOD::Value _interpolationMethod;  // 0x1C igEnumMetaField
 int _coefCount;  // 0x20 igIntMetaField
 igMorphSequenceDataList *_coefList;  // 0x24 igObjectRefMetaField
 float _startTime;  // 0x28 igFloatMetaField
 unsigned char unknown2C[4];
 long long _keyFrameTimeOffset;  // 0x30 igLongMetaField
 unsigned int _animationDuration;  // 0x38 igUnsignedIntMetaField
 unsigned char unknown3C[4];
};
}
#endif
