// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802ABA64 (metaobject lbl_805343D4, vtable lbl_804CE240), size 0x14.
#ifndef META_IGMOVIECODECLIST_H
#define META_IGMOVIECODECLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igMovieCodecList : igObjectList {
};
}
#endif
