// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igMorphData_register (metaobject lbl_80562764), size 0x8.
#ifndef META_IGMORPHDATA_H
#define META_IGMORPHDATA_H
#include <meta/igObject.h>
namespace Meta {
struct igMorphData : igObject {
};
}
#endif
