// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801B2A2C (metaobject lbl_80564958, vtable lbl_804B8A58), size 0x20.
#ifndef META_IGMODELVIEWMATRIXATTRPOOL_H
#define META_IGMODELVIEWMATRIXATTRPOOL_H
#include <meta/igObjectPool.h>
namespace Meta {
struct igModelViewMatrixAttrPool : igObjectPool {
};
}
#endif
