// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800B409C (metaobject lbl_80562768, vtable lbl_8047DDA8), size 0x14.
#ifndef META_IGMODELVIEWMATRIXATTRLIST_H
#define META_IGMODELVIEWMATRIXATTRLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igModelViewMatrixAttrList : igObjectList {
};
}
#endif
