// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igModelViewMatrixAttr_register (metaobject lbl_8056276C, vtable lbl_8047BD64), size 0x4C.
#ifndef META_IGMODELVIEWMATRIXATTR_H
#define META_IGMODELVIEWMATRIXATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igModelViewMatrixAttr : igVisualAttribute {
 float _m[16];  // 0x0C igMatrix44fMetaField
};
}
#endif
