// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801B9084 (metaobject lbl_80564C88, vtable lbl_804B4158), size 0x50.
// Note: _weightingPolicy: igFloatArrayMetaField, count from the space to the next member.
#ifndef META_IGMULTIRESOLUTIONMESHCORE_H
#define META_IGMULTIRESOLUTIONMESHCORE_H
#include <meta/igObject.h>
namespace Meta {
struct igIndexArray;
struct igUnsignedShortList;
struct igVertexArray;
struct igMultiResolutionMeshCore : igObject {
 igVertexArray *_vertexArray;  // 0x08 igObjectRefMetaField
 igIndexArray *_indexArray;  // 0x0C igObjectRefMetaField
 igUnsignedShortList *_proxyArray;  // 0x10 igObjectRefMetaField
 igUnsignedShortList *_folderArray;  // 0x14 igObjectRefMetaField
 unsigned int _minimumPolygonCount;  // 0x18 igUnsignedIntMetaField
 unsigned int _maximumPolygonCount;  // 0x1C igUnsignedIntMetaField
 unsigned short _minimumVertexCount;  // 0x20 igUnsignedShortMetaField
 unsigned short _maximumVertexCount;  // 0x22 igUnsignedShortMetaField
 int _placementPolicy;  // 0x24 igEnumMetaField
 float _weightingPolicy[10];  // 0x28 igFloatArrayMetaField
};
}
#endif
