// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800B3338 (metaobject lbl_80562720, vtable lbl_8047BBEC), size 0x10.
#ifndef META_IGMULTIPASSSTATEATTR_H
#define META_IGMULTIPASSSTATEATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igMultiPassStateAttr : igVisualAttribute {
 int _numPasses;  // 0x0C igIntMetaField
};
}
#endif
