// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80029B6C (metaobject lbl_80561740, vtable lbl_80476234), size 0x14.
#ifndef META_IGNAMEDOBJECTLIST_H
#define META_IGNAMEDOBJECTLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igNamedObjectList : igObjectList {
};
}
#endif
