// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igNodeUsageObjectDefinitionList_register (metaobject lbl_80563AE4, vtable lbl_804AABF8), size 0x14.
#ifndef META_IGNODEUSAGEOBJECTDEFINITIONLIST_H
#define META_IGNODEUSAGEOBJECTDEFINITIONLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igNodeUsageObjectDefinitionList : igObjectList {
};
}
#endif
