// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igNonRefCountedMatrixObjectList_register (metaobject lbl_80565A58, vtable lbl_804BC2EC), size 0x14.
#ifndef META_IGNONREFCOUNTEDMATRIXOBJECTLIST_H
#define META_IGNONREFCOUNTEDMATRIXOBJECTLIST_H
#include <meta/igNonRefCountedObjectList.h>
namespace Meta {
struct igNonRefCountedMatrixObjectList : igNonRefCountedObjectList {
};
}
#endif
