// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80408708 (metaobject lbl_8055CAB0, vtable lbl_804F1880), size 0x30.
#ifndef META_IGNORMALSRENDERER_H
#define META_IGNORMALSRENDERER_H
#include <meta/igRenderer.h>
namespace Meta {
struct igAttrList;
struct igColorAttr;
struct igGeometryAttrList;
struct igGraphPath;
struct igModelViewMatrixAttr;
struct igViewerParameters;
struct igNormalsRenderer : igRenderer {
 igViewerParameters *_parameters;  // 0x0C igObjectRefMetaField
 igAttrList *_attrList;  // 0x10 igObjectRefMetaField
 igAttrList *_defaultAttrList;  // 0x14 igObjectRefMetaField
 igModelViewMatrixAttr *_modelViewAttr;  // 0x18 igObjectRefMetaField
 igColorAttr *_colorAttr;  // 0x1C igObjectRefMetaField
 igGeometryAttrList *_normals;  // 0x20 igObjectRefMetaField
 bool _invalidStoredNormals;  // 0x24 igBoolMetaField
 unsigned char unknown25[3];
 igGraphPath *_path;  // 0x28 igObjectRefMetaField
 bool _draw;  // 0x2C igBoolMetaField
 unsigned char unknown2D[3];
};
}
#endif
