// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igNonRefCountedViewList_register (metaobject lbl_80563574, vtable lbl_80498064), size 0x14.
#ifndef META_IGNONREFCOUNTEDVIEWLIST_H
#define META_IGNONREFCOUNTEDVIEWLIST_H
#include <meta/igNonRefCountedObjectList.h>
namespace Meta {
struct igNonRefCountedViewList : igNonRefCountedObjectList {
};
}
#endif
