// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igNonRefCountedObjectList_register (metaobject lbl_80561730, vtable lbl_80476DA8), size 0x14.
#ifndef META_IGNONREFCOUNTEDOBJECTLIST_H
#define META_IGNONREFCOUNTEDOBJECTLIST_H
#include <meta/igDataList.h>
namespace Meta {
struct igNonRefCountedObjectList : igDataList {
};
}
#endif
