// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igNodeListList_register (metaobject lbl_80564BB8, vtable lbl_804B8368), size 0x14.
#ifndef META_IGNODELISTLIST_H
#define META_IGNODELISTLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igNodeListList : igObjectList {
};
}
#endif
