// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igNonRefCountedNodeList_register (metaobject lbl_80564BB4, vtable lbl_804B83CC), size 0x14.
#ifndef META_IGNONREFCOUNTEDNODELIST_H
#define META_IGNONREFCOUNTEDNODELIST_H
#include <meta/igNonRefCountedObjectList.h>
namespace Meta {
struct igNonRefCountedNodeList : igNonRefCountedObjectList {
};
}
#endif
