// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801AC0E8 (metaobject lbl_80564704, vtable lbl_804B9ECC), size 0x14.
#ifndef META_IGNONREFCOUNTEDTRANSFORMLIST_H
#define META_IGNONREFCOUNTEDTRANSFORMLIST_H
#include <meta/igNonRefCountedObjectList.h>
namespace Meta {
struct igNonRefCountedTransformList : igNonRefCountedObjectList {
};
}
#endif
