// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801C7CE4 (metaobject lbl_80565300, vtable lbl_804B6B98), size 0x14.
#ifndef META_IGNONREFCOUNTEDATTRSTACKMANAGERLIST_H
#define META_IGNONREFCOUNTEDATTRSTACKMANAGERLIST_H
#include <meta/igNonRefCountedObjectList.h>
namespace Meta {
struct igNonRefCountedAttrStackManagerList : igNonRefCountedObjectList {
};
}
#endif
