// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igNormalizeNormalsStateAttr_register (metaobject lbl_80562718, vtable lbl_8047BB6C), size 0x10.
#ifndef META_IGNORMALIZENORMALSSTATEATTR_H
#define META_IGNORMALIZENORMALSSTATEATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igNormalizeNormalsStateAttr : igVisualAttribute {
 bool _enabled;  // 0x0C igBoolMetaField
 unsigned char unknown0D[3];
};
}
#endif
