// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igObjectPropertyForLightSet_register (metaobject lbl_80563F9C, vtable lbl_804A57DC), size 0x2C.
#ifndef META_IGOBJECTPROPERTYFORLIGHTSET_H
#define META_IGOBJECTPROPERTYFORLIGHTSET_H
#include <meta/igObjectPropertyForNode.h>
namespace Meta {
struct igObjectPropertyForLightSet : igObjectPropertyForNode {
};
}
#endif
