// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igObjectPropertyForTransform_register (metaobject lbl_80563FCC, vtable lbl_804A5AC0), size 0x2C.
#ifndef META_IGOBJECTPROPERTYFORTRANSFORM_H
#define META_IGOBJECTPROPERTYFORTRANSFORM_H
#include <meta/igObjectPropertyForNode.h>
namespace Meta {
struct igObjectPropertyForTransform : igObjectPropertyForNode {
};
}
#endif
