// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8013F03C (metaobject lbl_80563F8C, vtable lbl_804A56B4), size 0x2C.
#ifndef META_IGOBJECTPROPERTYFORSEGMENT_H
#define META_IGOBJECTPROPERTYFORSEGMENT_H
#include <meta/igObjectPropertyForNode.h>
namespace Meta {
struct igObjectPropertyForSegment : igObjectPropertyForNode {
};
}
#endif
