// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8002865C (metaobject lbl_805616DC, vtable lbl_804763F0), size 0x10.
#ifndef META_IGOBJECTSTRINGMAP_H
#define META_IGOBJECTSTRINGMAP_H
#include <meta/igObject.h>
namespace Meta {
struct igNamedObjectList;
struct igObjectList;
struct igObjectStringMap : igObject {
 igNamedObjectList *_names;  // 0x08 igObjectRefMetaField
 igObjectList *_data;  // 0x0C igObjectRefMetaField
};
}
#endif
