// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8013BC38 (metaobject lbl_80563EDC, vtable lbl_804A4A8C), size 0x2C.
#ifndef META_IGOBJECTTRAVERSAL_H
#define META_IGOBJECTTRAVERSAL_H
#include <meta/igItemBase.h>
namespace Meta {
struct igObjectList;
struct igObjectTraversal : igItemBase {
 void *_container;  // 0x20 igObjectRefMetaField
 igObjectList *_childList;  // 0x24 igObjectRefMetaField
 igObjectList *_parentList;  // 0x28 igObjectRefMetaField
};
}
#endif
