// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igObjectPropertyForTimeTransform_register (metaobject lbl_80563F6C, vtable lbl_804A54F8), size 0x2C.
#ifndef META_IGOBJECTPROPERTYFORTIMETRANSFORM_H
#define META_IGOBJECTPROPERTYFORTIMETRANSFORM_H
#include <meta/igObjectPropertyForNode.h>
namespace Meta {
struct igObjectPropertyForTimeTransform : igObjectPropertyForNode {
};
}
#endif
