// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80066B08 (metaobject lbl_805622A4), size 0x8.
#ifndef META_IGOBJECT_H
#define META_IGOBJECT_H
namespace Meta {
struct igObject {
 void *__vtable;  // 0x00
 unsigned char unknown04[4];
};
}
#endif
