// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8013CDAC (metaobject lbl_80563F1C, vtable lbl_804A4F30), size 0x2C.
#ifndef META_IGOBJECTPROPERTYFORBILLBOARD_H
#define META_IGOBJECTPROPERTYFORBILLBOARD_H
#include <meta/igObjectPropertyForNode.h>
namespace Meta {
struct igObjectPropertyForBillboard : igObjectPropertyForNode {
};
}
#endif
