// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igObjectPropertyForUserInfo_register (metaobject lbl_80563F7C, vtable lbl_804A558C), size 0x2C.
#ifndef META_IGOBJECTPROPERTYFORUSERINFO_H
#define META_IGOBJECTPROPERTYFORUSERINFO_H
#include <meta/igObjectPropertyForNode.h>
namespace Meta {
struct igObjectPropertyForUserInfo : igObjectPropertyForNode {
};
}
#endif
