// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80140AB8 (metaobject lbl_80564000, vtable lbl_804AAE58), size 0x20.
#ifndef META_IGOBJECTCHANGEDLISTENER_H
#define META_IGOBJECTCHANGEDLISTENER_H
#include <meta/igListenerBase.h>
namespace Meta {
struct igObjectChangedListener : igListenerBase {
};
}
#endif
