// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igObjectPropertyForModelViewMatrixBoneSelect_register (metaobject lbl_80563F24, vtable lbl_804A4FC4), size 0x2C.
#ifndef META_IGOBJECTPROPERTYFORMODELVIEWMATRIXBONESELECT_H
#define META_IGOBJECTPROPERTYFORMODELVIEWMATRIXBONESELECT_H
#include <meta/igObjectPropertyForNode.h>
namespace Meta {
struct igObjectPropertyForModelViewMatrixBoneSelect : igObjectPropertyForNode {
};
}
#endif
