// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80028A20 (metaobject lbl_805616E8), size 0x44.
#ifndef META_IGOBJECTREFMETAFIELD_H
#define META_IGOBJECTREFMETAFIELD_H
#include <meta/igRefMetaField.h>
namespace Meta {
struct igMetaObject;
struct igObjectRefMetaField : igRefMetaField {
 igMetaObject *_metaObject;  // 0x38 igObjectRefMetaField
 bool _refCounted;  // 0x3C igBoolMetaField
 unsigned char unknown3D[3];
 const char *_poolName;  // 0x40 igStringMetaField
};
}
#endif
