// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801408E4 (metaobject lbl_80563FF8), size 0x24.
#ifndef META_IGOBJECTPROPERTY_H
#define META_IGOBJECTPROPERTY_H
#include <meta/igItemBase.h>
namespace Meta {
struct igObjectProperty : igItemBase {
 void *_object;  // 0x20 igObjectRefMetaField
};
}
#endif
