// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8013BED4 (metaobject lbl_80563EEC, vtable lbl_804A4BB8), size 0x2C.
#ifndef META_IGOBJECTPROPERTYFORCAMERA_H
#define META_IGOBJECTPROPERTYFORCAMERA_H
#include <meta/igObjectPropertyForNode.h>
namespace Meta {
struct igObjectPropertyForCamera : igObjectPropertyForNode {
};
}
#endif
