// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80140184 (metaobject lbl_80563FC4, vtable lbl_804A5B54), size 0x2C.
#ifndef META_IGOBJECTPROPERTYFORGROUP_H
#define META_IGOBJECTPROPERTYFORGROUP_H
#include <meta/igObjectPropertyForNode.h>
namespace Meta {
struct igObjectPropertyForGroup : igObjectPropertyForNode {
};
}
#endif
