// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igObjectPropertyForEnvironmentMapShader_register (metaobject lbl_80563F34, vtable lbl_804A50EC), size 0x2C.
#ifndef META_IGOBJECTPROPERTYFORENVIRONMENTMAPSHADER_H
#define META_IGOBJECTPROPERTYFORENVIRONMENTMAPSHADER_H
#include <meta/igObjectPropertyForNode.h>
namespace Meta {
struct igObjectPropertyForEnvironmentMapShader : igObjectPropertyForNode {
};
}
#endif
