// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igObjectPropertyForSwitch_register (metaobject lbl_80563FBC, vtable lbl_804A5998), size 0x2C.
#ifndef META_IGOBJECTPROPERTYFORSWITCH_H
#define META_IGOBJECTPROPERTYFORSWITCH_H
#include <meta/igObjectPropertyForNode.h>
namespace Meta {
struct igObjectPropertyForSwitch : igObjectPropertyForNode {
};
}
#endif
