// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igOnOffValueObserver_register (metaobject lbl_805635EC, vtable lbl_80495E2C), size 0x10.
#ifndef META_IGONOFFVALUEOBSERVER_H
#define META_IGONOFFVALUEOBSERVER_H
#include <meta/igView.h>
namespace Meta {
struct igRadioGroup;
struct igOnOffValueObserver : igView {
 igRadioGroup *_group;  // 0x0C igObjectRefMetaField
};
}
#endif
