// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igOnOffValueObserverList_register (metaobject lbl_805635E8, vtable lbl_804979F8), size 0x14.
#ifndef META_IGONOFFVALUEOBSERVERLIST_H
#define META_IGONOFFVALUEOBSERVERLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igOnOffValueObserverList : igObjectList {
};
}
#endif
