// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8010EFFC (metaobject lbl_80563628, vtable lbl_80497940), size 0x28.
#ifndef META_IGONOFFMODEL_H
#define META_IGONOFFMODEL_H
#include <meta/igGuiComponentModel.h>
namespace Meta {
struct igOnOffModel : igGuiComponentModel {
 bool _value;  // 0x24 igBoolMetaField
 unsigned char unknown25[3];
};
}
#endif
