// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801139AC (metaobject lbl_805637F4, vtable lbl_80496774), size 0x58.
#ifndef META_IGONOFFCOLORCHANGER_H
#define META_IGONOFFCOLORCHANGER_H
#include <meta/igBasicColorChanger.h>
namespace Meta {
struct igOnOffColorChanger : igBasicColorChanger {
};
}
#endif
