// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8013B890 (metaobject lbl_80563ECC, vtable lbl_804AA160), size 0x8.
#ifndef META_IGOPTCONFIGURATION_H
#define META_IGOPTCONFIGURATION_H
#include <meta/igObject.h>
namespace Meta {
struct igOptConfiguration : igObject {
};
}
#endif
