// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igOptVisitObject_register (metaobject lbl_80563E54), size 0x2C.
#ifndef META_IGOPTVISITOBJECT_H
#define META_IGOPTVISITOBJECT_H
#include <meta/igOptBase.h>
namespace Meta {
struct igMetaObject;
struct igOptVisitObject : igOptBase {
 igMetaObject *_visitedMetaObject;  // 0x28 igObjectRefMetaField
};
}
#endif
