// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igOptimizeActorSkinsInScenes_register (metaobject lbl_80563E18, vtable lbl_804A448C), size 0x30.
#ifndef META_IGOPTIMIZEACTORSKINSINSCENES_H
#define META_IGOPTIMIZEACTORSKINSINSCENES_H
#include <meta/igMacroOpt.h>
namespace Meta {
struct igOptimizeActorSkinsInScenes : igMacroOpt {
};
}
#endif
