// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8013AF60 (metaobject lbl_80563E88), size 0x34.
#ifndef META_IGOPTREPLACENODE_H
#define META_IGOPTREPLACENODE_H
#include <meta/igOptTraverseGraph.h>
namespace Meta {
struct igOptReplaceNode : igOptTraverseGraph {
};
}
#endif
