// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igOptBase_register (metaobject lbl_80563ED0), size 0x28.
#ifndef META_IGOPTBASE_H
#define META_IGOPTBASE_H
#include <meta/igBase.h>
namespace Meta {
struct igOptConfiguration;
struct igRegistry;
struct igOptBase : igBase {
 igRegistry *_registry;  // 0x20 igObjectRefMetaField
 igOptConfiguration *_configuration;  // 0x24 igObjectRefMetaField
};
}
#endif
