// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8013B5E8 (metaobject lbl_80563EB8, vtable lbl_804A4980), size 0x30.
#ifndef META_IGOPTINTERFACE_H
#define META_IGOPTINTERFACE_H
#include <meta/igInterface.h>
namespace Meta {
struct igFileInfo;
struct igInfoList;
struct igMetaObjectList;
struct igOptInterface : igInterface {
 igMetaObjectList *_optimizationList;  // 0x20 igObjectRefMetaField
 const char *_filePath;  // 0x24 igStringMetaField
 igFileInfo *_file;  // 0x28 igObjectRefMetaField
 igInfoList *_disabledInfos;  // 0x2C igObjectRefMetaField
};
}
#endif
