// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8013A404 (metaobject lbl_80563E28, vtable lbl_804A459C), size 0x40.
#ifndef META_IGOPTIMIZEACTORKEYFRAMES_H
#define META_IGOPTIMIZEACTORKEYFRAMES_H
#include <meta/igOptBase.h>
namespace Meta {
struct igOptimizeActorKeyframes : igOptBase {
 float _maximumTranslation;  // 0x28 igFloatMetaField
 unsigned char unknown2C[4];
 double _maximumAngleChange;  // 0x30 igDoubleMetaField
 bool _convertZeroBaseKeyframeTime;  // 0x38 igBoolMetaField
 bool _removeScaleChannel;  // 0x39 igBoolMetaField
 unsigned char unknown3A[6];
};
}
#endif
