// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igOverrideAttrSet_register (metaobject lbl_80564B94, vtable lbl_804B85BC), size 0x28.
#ifndef META_IGOVERRIDEATTRSET_H
#define META_IGOVERRIDEATTRSET_H
#include <meta/igAttrSet.h>
namespace Meta {
struct igOverrideAttrSet : igAttrSet {
};
}
#endif
