// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80138F98 (metaobject lbl_80563DD0), size 0xC.
#ifndef META_IGPARAMETERSETCONSTRAINT_H
#define META_IGPARAMETERSETCONSTRAINT_H
#include <meta/igObject.h>
namespace Meta {
struct igParameterSetConstraint : igObject {
 const char *_errorMessage;  // 0x08 igStringMetaField
};
}
#endif
