// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igParticleFormat_register (metaobject lbl_80562EFC, vtable lbl_80493E34), size 0x30.
#ifndef META_IGPARTICLEFORMAT_H
#define META_IGPARTICLEFORMAT_H
#include <meta/igObject.h>
namespace Meta {
struct igParticleFormat : igObject {
 unsigned char unknown08[40];
};
}
#endif
