// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igParticleArray_register (metaobject lbl_80562E9C, vtable lbl_80492640), size 0x5C.
#ifndef META_IGPARTICLEARRAY_H
#define META_IGPARTICLEARRAY_H
#include <meta/igObject.h>
namespace Meta {
struct igParticleArray : igObject {
 unsigned char unknown08[84];
};
}
#endif
