// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igParticleAttr_register (metaobject lbl_805626F8, vtable lbl_8047BAE4), size 0x30.
#ifndef META_IGPARTICLEATTR_H
#define META_IGPARTICLEATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igParticleArray;
struct igParticleAttr : igVisualAttribute {
 bool _bUseCurrentTime;  // 0x0C igBoolMetaField
 unsigned char unknown0D[3];
 igParticleArray *_particleArray;  // 0x10 igObjectRefMetaField
 unsigned int _particleNum;  // 0x14 igUnsignedIntMetaField
 unsigned int _particleOffset;  // 0x18 igUnsignedIntMetaField
 unsigned char unknown1C[4];
 long long _startTime;  // 0x20 igLongMetaField
 float _time;  // 0x28 igFloatMetaField
 float _offset;  // 0x2C igFloatMetaField
};
}
#endif
