// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80139C9C (metaobject lbl_80563E08, vtable lbl_804A4428), size 0x18.
#ifndef META_IGPARAMETEREXIST_H
#define META_IGPARAMETEREXIST_H
#include <meta/igParameterSetConstraint.h>
namespace Meta {
struct igMetaObject;
struct igParameterExist : igParameterSetConstraint {
 const char *_fieldName;  // 0x0C igStringMetaField
 igMetaObject *_fieldType;  // 0x10 igObjectRefMetaField
 igMetaObject *_referenceType;  // 0x14 igObjectRefMetaField
};
}
#endif
