// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igParameterMatch_register (metaobject lbl_80563DFC, vtable lbl_804A43C4), size 0x14.
#ifndef META_IGPARAMETERMATCH_H
#define META_IGPARAMETERMATCH_H
#include <meta/igParameterSetConstraint.h>
namespace Meta {
struct igParameterMatch : igParameterSetConstraint {
 const char *_fieldOneName;  // 0x0C igStringMetaField
 const char *_fieldTwoName;  // 0x10 igStringMetaField
};
}
#endif
