// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igParameterSet_register (metaobject lbl_80563DDC, vtable lbl_804A4304), size 0x1C.
#ifndef META_IGPARAMETERSET_H
#define META_IGPARAMETERSET_H
#include <meta/igObject.h>
namespace Meta {
struct igMetaObject;
struct igParameterSetList;
struct igStringRefList;
struct igParameterSet : igObject {
 igMetaObject *_dynamicMeta;  // 0x08 igObjectRefMetaField
 void *_data;  // 0x0C igRawRefMetaField
 igParameterSetList *_parameterSetList;  // 0x10 igObjectRefMetaField
 igStringRefList *_fieldNameList;  // 0x14 igObjectRefMetaField
 igStringRefList *_sourceNameList;  // 0x18 igObjectRefMetaField
};
}
#endif
