// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igParticleAttrList_register (metaobject lbl_805626F4, vtable lbl_8047E0CC), size 0x14.
#ifndef META_IGPARTICLEATTRLIST_H
#define META_IGPARTICLEATTRLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igParticleAttrList : igObjectList {
};
}
#endif
