// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80138EA8 (metaobject lbl_80563DCC, vtable lbl_804AA3C4), size 0x14.
#ifndef META_IGPARAMETERSETCONSTRAINTLIST_H
#define META_IGPARAMETERSETCONSTRAINTLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igParameterSetConstraintList : igObjectList {
};
}
#endif
