// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800B2564 (metaobject lbl_805626B8, vtable lbl_8047B964), size 0x10.
#ifndef META_IGPIXELSHADERBINDATTR_H
#define META_IGPIXELSHADERBINDATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igPixelShaderAttr;
struct igPixelShaderBindAttr : igVisualAttribute {
 igPixelShaderAttr *_pixelShader;  // 0x0C igObjectRefMetaField
};
}
#endif
