// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igPixelPipelineModeAttr_register (metaobject lbl_805626EC, vtable lbl_8047BA64), size 0x10.
#ifndef META_IGPIXELPIPELINEMODEATTR_H
#define META_IGPIXELPIPELINEMODEATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igPixelPipelineModeAttr : igVisualAttribute {
 int _pipelineMode;  // 0x0C igEnumMetaField
};
}
#endif
