// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igPickMode_register (metaobject lbl_8055C9A4, vtable lbl_804F1DE8), size 0xBC.
#ifndef META_IGPICKMODE_H
#define META_IGPICKMODE_H
#include <meta/igViewMode.h>
namespace Meta {
struct igGraphPath;
struct igGuiSystem;
struct igIntersectTraversal;
struct igMouseCursor;
struct igRay;
struct igViewerParameters;
struct igPickMode : igViewMode {
 igViewerParameters *_parameters;  // 0x4C igObjectRefMetaField
 igGuiSystem *_guiSystem;  // 0x50 igObjectRefMetaField
 igMouseCursor *_cursor;  // 0x54 igObjectRefMetaField
 igMouseCursor *_savedCursor;  // 0x58 igObjectRefMetaField
 bool _savedCursorState;  // 0x5C igBoolMetaField
 unsigned char unknown5D[3];
 igIntersectTraversal *_intersectTraversal;  // 0x60 igObjectRefMetaField
 igRay *_ray;  // 0x64 igObjectRefMetaField
 float _impactLength;  // 0x68 igFloatMetaField
 bool _hit;  // 0x6C igBoolMetaField
 unsigned char unknown6D[3];
 igGraphPath *_hitPath;  // 0x70 igObjectRefMetaField
 float _inverseProjectionMatrix[16];  // 0x74 igMatrix44fMetaField
 float _joystickT[2];  // 0xB4 igVec2fMetaField
};
}
#endif
