// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igPixelShaderAttr_register (metaobject lbl_805626C0, vtable lbl_8047B9E4), size 0x34.
#ifndef META_IGPIXELSHADERATTR_H
#define META_IGPIXELSHADERATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igGfxShaderConstantList;
struct igGfxShaderDefineList;
struct igTextureSamplerSourceList;
struct igVisualContext;
struct igPixelShaderAttr : igVisualAttribute {
 int _iHandle;  // 0x0C igIntMetaField
 void *_pData;  // 0x10 igRawRefMetaField
 int _iBytes;  // 0x14 igIntMetaField
 igVisualContext *_visualContext;  // 0x18 igObjectRefMetaField
 const char *_textDefinition;  // 0x1C igStringMetaField
 const char *_entryPoint;  // 0x20 igStringMetaField
 const char *_profile;  // 0x24 igStringMetaField
 igTextureSamplerSourceList *_samplerList;  // 0x28 igObjectRefMetaField
 igGfxShaderConstantList *_stateList;  // 0x2C igObjectRefMetaField
 igGfxShaderDefineList *_defineList;  // 0x30 igObjectRefMetaField
};
}
#endif
