// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800283DC (metaobject lbl_805616CC, vtable lbl_804764B0), size 0x14.
#ifndef META_IGPLUGINREPOSITORY_H
#define META_IGPLUGINREPOSITORY_H
#include <meta/igNamedObject.h>
namespace Meta {
struct igPluginRepository : igNamedObject {
 const char *_location;  // 0x0C igStringMetaField
 int _locationType;  // 0x10 igEnumMetaField
};
}
#endif
