// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igPlanarShadowProcessor_register (metaobject lbl_80564B74, vtable lbl_804B3F6C), size 0x40.
#ifndef META_IGPLANARSHADOWPROCESSOR_H
#define META_IGPLANARSHADOWPROCESSOR_H
#include <meta/igShaderProcessor.h>
namespace Meta {
struct igLightAttr;
struct igModelViewMatrixAttr;
struct igProjectionMatrixAttr;
struct igPlanarShadowProcessor : igShaderProcessor {
 igModelViewMatrixAttr *_modelViewMatrix;  // 0x08 igObjectRefMetaField
 igProjectionMatrixAttr *_projectionMatrix;  // 0x0C igObjectRefMetaField
 float _shadowPlane[4];  // 0x10 igVec4fMetaField
 float _lightPosition[3];  // 0x20 igVec3fMetaField
 float _lightDirection[3];  // 0x2C igVec3fMetaField
 bool _isPerspective;  // 0x38 igBoolMetaField
 unsigned char unknown39[3];
 igLightAttr *_light;  // 0x3C igObjectRefMetaField
};
}
#endif
