// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80034664 (metaobject lbl_80561D64, vtable lbl_80475038), size 0x14.
#ifndef META_IGPOINTERLISTLIST_H
#define META_IGPOINTERLISTLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igPointerListList : igObjectList {
};
}
#endif
