// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80034820 (metaobject lbl_80561D68, vtable lbl_80474F78), size 0x14.
#ifndef META_IGPOINTERLIST_H
#define META_IGPOINTERLIST_H
#include <meta/igDataList.h>
namespace Meta {
struct igPointerList : igDataList {
};
}
#endif
