// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80138948 (metaobject lbl_80563DAC, vtable lbl_804A41D0), size 0x34.
#ifndef META_IGPROMOTEALLATTRS_H
#define META_IGPROMOTEALLATTRS_H
#include <meta/igOptVisitObject.h>
namespace Meta {
struct igPromoteAllAttrs : igOptVisitObject {
 const char *_newAttrSetName;  // 0x2C igStringMetaField
 const char *_attrsToIgnore;  // 0x30 igStringMetaField
};
}
#endif
