// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igPropertyValue_register (metaobject lbl_80564A34), size 0x8.
#ifndef META_IGPROPERTYVALUE_H
#define META_IGPROPERTYVALUE_H
#include <meta/igObject.h>
namespace Meta {
struct igPropertyValue : igObject {
};
}
#endif
