// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igProjectiveShadowShader_register (metaobject lbl_80564A78), size 0xF0.
#ifndef META_IGPROJECTIVESHADOWSHADER_H
#define META_IGPROJECTIVESHADOWSHADER_H
#include <meta/igGroup.h>
namespace Meta {
struct igColorAttr;
struct igCopyRenderDestinationAttr;
struct igGeometry;
struct igGeometryAttr;
struct igImage;
struct igLightAttr;
struct igModelViewMatrixAttr;
struct igNodeList;
struct igNonRefCountedAttrList;
struct igProjectionMatrixAttr;
struct igRenderDestinationAttr;
struct igSetRenderDestinationAttr;
struct igTextureAttr;
struct igTextureBindAttr;
struct igTextureMatrixAttr;
struct igTextureUnloadAttr;
struct igViewportAttr;
struct igProjectiveShadowShader : igGroup {
 float _lightPos[3];  // 0x20 igVec3fMetaField
 float _lightDir[3];  // 0x2C igVec3fMetaField
 float _cutoff;  // 0x38 igFloatMetaField
 igNodeList *_shadowCasters;  // 0x3C igObjectRefMetaField
 igNodeList *_shadowReceivers;  // 0x40 igObjectRefMetaField
 float _shadowFactor;  // 0x44 igFloatMetaField
 int _shadowTexW;  // 0x48 igIntMetaField
 int _shadowTexH;  // 0x4C igIntMetaField
 float _shadowLightness;  // 0x50 igFloatMetaField
 igNonRefCountedAttrList *_viewToProjectedLightTextureMatrixpAttrList;  // 0x54 igObjectRefMetaField
 igModelViewMatrixAttr *_lightMVMAttr;  // 0x58 igObjectRefMetaField
 igProjectionMatrixAttr *_lightProjAttr;  // 0x5C igObjectRefMetaField
 igModelViewMatrixAttr *_blurMVMAttr;  // 0x60 igObjectRefMetaField
 igProjectionMatrixAttr *_blurProjAttr;  // 0x64 igObjectRefMetaField
 int _inited;  // 0x68 igIntMetaField
 igGeometry *_quadsGeom;  // 0x6C igObjectRefMetaField
 igGeometryAttr *_unused;  // 0x70 igObjectRefMetaField
 igColorAttr *_shadowColor;  // 0x74 igObjectRefMetaField
 bool _blurState;  // 0x78 igBoolMetaField
 unsigned char unknown79[3];
 float _zNear;  // 0x7C igFloatMetaField
 float _zFar;  // 0x80 igFloatMetaField
 float _upVector[3];  // 0x84 igVec3fMetaField
 igTextureMatrixAttr *_viewToProjectedLightTextureMatrix;  // 0x90 igObjectRefMetaField
 bool _drawReceiver;  // 0x94 igBoolMetaField
 bool _updateShadowMap;  // 0x95 igBoolMetaField
 unsigned char unknown96[2];
 igRenderDestinationAttr *_pShadowTexRD;  // 0x98 igObjectRefMetaField
 igSetRenderDestinationAttr *_pSetShadowTexRD;  // 0x9C igObjectRefMetaField
 igTextureAttr *_pShadowTex;  // 0xA0 igObjectRefMetaField
 igTextureBindAttr *_pShadowTexBind;  // 0xA4 igObjectRefMetaField
 igRenderDestinationAttr *_pBlurTexRD;  // 0xA8 igObjectRefMetaField
 igSetRenderDestinationAttr *_pSetBlurTexRD;  // 0xAC igObjectRefMetaField
 igTextureAttr *_pBlurTex;  // 0xB0 igObjectRefMetaField
 igTextureBindAttr *_pBlurTexBind;  // 0xB4 igObjectRefMetaField
 igCopyRenderDestinationAttr *_shadowCopyBack;  // 0xB8 igObjectRefMetaField
 igImage *_shadowCopyBackImage;  // 0xBC igObjectRefMetaField
 igViewportAttr *_shadowViewport;  // 0xC0 igObjectRefMetaField
 igViewportAttr *_shadowInnerViewport;  // 0xC4 igObjectRefMetaField
 igLightAttr *_light;  // 0xC8 igObjectRefMetaField
 igTextureBindAttr *_pShadowTexBind1;  // 0xCC igObjectRefMetaField
 bool _useOrthographic;  // 0xD0 igBoolMetaField
 unsigned char unknownD1[3];
 float _top;  // 0xD4 igFloatMetaField
 float _bottom;  // 0xD8 igFloatMetaField
 float _right;  // 0xDC igFloatMetaField
 float _left;  // 0xE0 igFloatMetaField
 igTextureUnloadAttr *_unloadShadowTexRD;  // 0xE4 igObjectRefMetaField
 igTextureUnloadAttr *_unloadBlurTexRD;  // 0xE8 igObjectRefMetaField
 bool _releaseRenderDestinationAfterDraw;  // 0xEC igBoolMetaField
 bool _useShadowFactor;  // 0xED igBoolMetaField
 unsigned char unknownEE[2];
};
}
#endif
