// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igProjectionMatrixAttrPool_register (metaobject lbl_80564950, vtable lbl_804B8BE8), size 0x20.
#ifndef META_IGPROJECTIONMATRIXATTRPOOL_H
#define META_IGPROJECTIONMATRIXATTRPOOL_H
#include <meta/igObjectPool.h>
namespace Meta {
struct igProjectionMatrixAttrPool : igObjectPool {
};
}
#endif
