// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801BDD40 (metaobject lbl_80564E5C, vtable lbl_804B7684), size 0x14.
#ifndef META_IGPROBE_H
#define META_IGPROBE_H
#include <meta/igObject.h>
namespace Meta {
struct igIntList;
struct igRayList;
struct igVolume;
struct igProbe : igObject {
 igVolume *_volume;  // 0x08 igObjectRefMetaField
 igRayList *_rays;  // 0x0C igObjectRefMetaField
 igIntList *_intersectFaceType;  // 0x10 igObjectRefMetaField
};
}
#endif
