// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801B4708 (metaobject lbl_80564A3C, vtable lbl_804B86B4), size 0x14.
#ifndef META_IGPROPERTYLIST_H
#define META_IGPROPERTYLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igPropertyList : igObjectList {
};
}
#endif
