// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80121790 (metaobject lbl_805639EC, vtable lbl_8049ABF0), size 0x14.
#ifndef META_IGQUATERNIONFLIST_H
#define META_IGQUATERNIONFLIST_H
#include <meta/igDataList.h>
namespace Meta {
struct igQuaternionfList : igDataList {
};
}
#endif
