// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igQuantizeImage_register (metaobject lbl_80563D1C, vtable lbl_804A3E10), size 0x18.
#ifndef META_IGQUANTIZEIMAGE_H
#define META_IGQUANTIZEIMAGE_H
#include <meta/igObject.h>
#include <meta/enums.h>
namespace Meta {
struct igCBBoxList;
struct igImageHistogramBase;
struct igQuantizeImage : igObject {
 igCBBoxList *_bboxList;  // 0x08 igObjectRefMetaField
 igImageHistogramBase *_histogram;  // 0x0C igObjectRefMetaField
 igQuantizeImagePhaseEnum::Value _phase;  // 0x10 igEnumMetaField
 void *_errorLimit;  // 0x14 igMemoryRefMetaField
};
}
#endif
