// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8010EB14 (metaobject lbl_805635FC, vtable lbl_80495EF4), size 0x20.
#ifndef META_IGRADIOGROUP_H
#define META_IGRADIOGROUP_H
#include <meta/igObject.h>
namespace Meta {
struct igOnOffValueObserverList;
struct igRadioGroupModel;
struct igRadioGroupSelectedObserver;
struct igRadioGroup : igObject {
 igRadioGroupModel *_model;  // 0x08 igObjectRefMetaField
 igRadioGroupSelectedObserver *_selectedObserver;  // 0x0C igObjectRefMetaField
 igOnOffValueObserverList *_observerList;  // 0x10 igObjectRefMetaField
 bool _alwaysSelected;  // 0x14 igBoolMetaField
 unsigned char unknown15[3];
 int _lastSelected;  // 0x18 igIntMetaField
 int _defaultSelected;  // 0x1C igIntMetaField
};
}
#endif
