// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igRawRefMetaField_register (metaobject lbl_80561694), size 0x38.
#ifndef META_IGRAWREFMETAFIELD_H
#define META_IGRAWREFMETAFIELD_H
#include <meta/igRefMetaField.h>
namespace Meta {
struct igRawRefMetaField : igRefMetaField {
};
}
#endif
