// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8011F87C (metaobject lbl_80563968, vtable lbl_8049B8B8), size 0x14.
#ifndef META_IGRAYLIST_H
#define META_IGRAYLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igRayList : igObjectList {
};
}
#endif
