// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80216B40 (metaobject lbl_805659E4), size 0x8.
#ifndef META_IGRANDOMNUMBER_H
#define META_IGRANDOMNUMBER_H
#include <meta/igObject.h>
namespace Meta {
struct igRandomNumber : igObject {
};
}
#endif
