// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igRefVertexBlendMatrixAttr_register (metaobject lbl_80562694, vtable lbl_8047B754), size 0x14.
#ifndef META_IGREFVERTEXBLENDMATRIXATTR_H
#define META_IGREFVERTEXBLENDMATRIXATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igMatrixObject;
struct igRefVertexBlendMatrixAttr : igVisualAttribute {
 igMatrixObject *_m;  // 0x0C igObjectRefMetaField
 unsigned short _blendMatID;  // 0x10 igUnsignedShortMetaField
 unsigned char unknown12[2];
};
}
#endif
