// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80026FB4 (metaobject lbl_80561670, vtable lbl_80476780), size 0x14.
#ifndef META_IGREGISTRYVALUELIST_H
#define META_IGREGISTRYVALUELIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igRegistryValueList : igObjectList {
};
}
#endif
