// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80135724 (metaobject lbl_80563C88, vtable lbl_804A3880), size 0x2C.
#ifndef META_IGREPLACEATTRFORNODE_H
#define META_IGREPLACEATTRFORNODE_H
#include <meta/igReplaceAttr.h>
namespace Meta {
struct igReplaceAttrForNode : igReplaceAttr {
};
}
#endif
