// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80134BEC (metaobject lbl_80563C54, vtable lbl_804A36B4), size 0x2C.
#ifndef META_IGREPLACECHILDFORNODE_H
#define META_IGREPLACECHILDFORNODE_H
#include <meta/igReplaceChild.h>
namespace Meta {
struct igReplaceChildForNode : igReplaceChild {
};
}
#endif
