// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801AF310 (metaobject lbl_80564864, vtable lbl_804B9590), size 0x20.
#ifndef META_IGRENDERPACKAGE_H
#define META_IGRENDERPACKAGE_H
#include <meta/igObject.h>
namespace Meta {
struct igNonRefCountedAttrList;
struct igRenderPackageList;
struct igRenderPackage : igObject {
 igNonRefCountedAttrList *_stateAttrs;  // 0x08 igObjectRefMetaField
 igNonRefCountedAttrList *_cachedStateAttrs;  // 0x0C igObjectRefMetaField
 igNonRefCountedAttrList *_geomAttrs;  // 0x10 igObjectRefMetaField
 void *_sortingCache;  // 0x14 igRawRefMetaField
 float _distance;  // 0x18 igFloatMetaField
 igRenderPackageList *_theMass;  // 0x1C igObjectRefMetaField
};
}
#endif
