// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igRenderPackagePool_register (metaobject lbl_80564860, vtable lbl_804B95EC), size 0x20.
#ifndef META_IGRENDERPACKAGEPOOL_H
#define META_IGRENDERPACKAGEPOOL_H
#include <meta/igObjectPool.h>
namespace Meta {
struct igRenderPackagePool : igObjectPool {
};
}
#endif
