// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80134040 (metaobject lbl_80563C04, vtable lbl_804A34EC), size 0x2C.
#ifndef META_IGRESORTTRANSPARENCY_H
#define META_IGRESORTTRANSPARENCY_H
#include <meta/igOptVisitObject.h>
namespace Meta {
struct igResortTransparency : igOptVisitObject {
};
}
#endif
