// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801348D4 (metaobject lbl_80563C40, vtable lbl_804A361C), size 0x30.
#ifndef META_IGREPLACEOBJECT_H
#define META_IGREPLACEOBJECT_H
#include <meta/igItemBase.h>
namespace Meta {
struct igParameterSet;
struct igReplaceObject : igItemBase {
 const char *_traversalName;  // 0x20 igStringMetaField
 void *_oldObject;  // 0x24 igObjectRefMetaField
 void *_newObject;  // 0x28 igObjectRefMetaField
 igParameterSet *_returned;  // 0x2C igObjectRefMetaField
};
}
#endif
