// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igRemoveDynamic_register (metaobject lbl_80563CB4, vtable lbl_804A3AC0), size 0x34.
#ifndef META_IGREMOVEDYNAMIC_H
#define META_IGREMOVEDYNAMIC_H
#include <meta/igOptVisitObject.h>
namespace Meta {
struct igRemoveDynamic : igOptVisitObject {
 const char *_nodeString;  // 0x2C igStringMetaField
 bool _removeDynamicWithSingleChild;  // 0x30 igBoolMetaField
 unsigned char unknown31[3];
};
}
#endif
