// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8013501C (metaobject lbl_80563C64, vtable lbl_804AA6A4), size 0x2C.
#ifndef META_IGREPLACEDCHILDEVENT_H
#define META_IGREPLACEDCHILDEVENT_H
#include <meta/igHierarchyChangedEvent.h>
namespace Meta {
struct igReplacedChildEvent : igHierarchyChangedEvent {
 void *_object;  // 0x20 igObjectRefMetaField
 void *_newChild;  // 0x24 igObjectRefMetaField
 void *_oldChild;  // 0x28 igObjectRefMetaField
};
}
#endif
