// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igRepairHierarchy_register (metaobject lbl_80563CA0, vtable lbl_804A39B0), size 0x30.
#ifndef META_IGREPAIRHIERARCHY_H
#define META_IGREPAIRHIERARCHY_H
#include <meta/igOptBase.h>
namespace Meta {
struct igNonRefCountedNodeList;
struct igRepairHierarchy : igOptBase {
 igNonRefCountedNodeList *_nodeList;  // 0x28 igObjectRefMetaField
 bool _disableRepair;  // 0x2C igBoolMetaField
 bool _createParentList;  // 0x2D igBoolMetaField
 unsigned char unknown2E[2];
};
}
#endif
