// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igReduceWeights_register (metaobject lbl_80563CF0, vtable lbl_804A3D00), size 0x44.
#ifndef META_IGREDUCEWEIGHTS_H
#define META_IGREDUCEWEIGHTS_H
#include <meta/igOptBase.h>
#include <meta/enums.h>
namespace Meta {
struct igFloatList;
struct igReduceWeights : igOptBase {
 igFloatList *_lodRangeList;  // 0x28 igObjectRefMetaField
 bool _printOnly;  // 0x2C igBoolMetaField
 unsigned char unknown2D[3];
 unsigned int _maxWeightCount;  // 0x30 igUnsignedIntMetaField
 float _threshold;  // 0x34 igFloatMetaField
 REDUCE_WEIGHT_OPT_TYPE::Value _weightOptType;  // 0x38 igEnumMetaField
 REDUCE_WEIGHT_CREATE_LOD::Value _createLod;  // 0x3C igEnumMetaField
 const char *_lodRangeListString;  // 0x40 igStringMetaField
};
}
#endif
