// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igRebindActors_register (metaobject lbl_80563D10, vtable lbl_804A3D88), size 0x2C.
#ifndef META_IGREBINDACTORS_H
#define META_IGREBINDACTORS_H
#include <meta/igOptBase.h>
namespace Meta {
struct igRebindActors : igOptBase {
 bool _useReflected;  // 0x28 igBoolMetaField
 unsigned char unknown29[3];
};
}
#endif
