// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80027360 (metaobject lbl_80561684), size 0x38.
#ifndef META_IGREFMETAFIELD_H
#define META_IGREFMETAFIELD_H
#include <meta/igMetaField.h>
namespace Meta {
struct igRefMetaField : igMetaField {
 bool _construct;  // 0x34 igBoolMetaField
 bool _destruct;  // 0x35 igBoolMetaField
 unsigned char unknown36[2];
};
}
#endif
