// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8010D944 (metaobject lbl_805635AC, vtable lbl_80497D64), size 0x3C.
#ifndef META_IGSCROLLLISTCOMPONENTMODEL_H
#define META_IGSCROLLLISTCOMPONENTMODEL_H
#include <meta/igBoxModel.h>
namespace Meta {
struct igGuiComponent;
struct igGuiComponentList;
struct igScrollListComponentModel : igBoxModel {
 igGuiComponent *_upArrow;  // 0x28 igObjectRefMetaField
 igGuiComponent *_downArrow;  // 0x2C igObjectRefMetaField
 igGuiComponentList *_items;  // 0x30 igObjectRefMetaField
 int _displayFirst;  // 0x34 igIntMetaField
 int _displayCount;  // 0x38 igIntMetaField
};
}
#endif
