// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igScaleActors_register (metaobject lbl_80563BF8, vtable lbl_804A3464), size 0x30.
#ifndef META_IGSCALEACTORS_H
#define META_IGSCALEACTORS_H
#include <meta/igOptBase.h>
namespace Meta {
struct igGeometryList;
struct igScaleActors : igOptBase {
 float _scale;  // 0x28 igFloatMetaField
 igGeometryList *_skinGeometryList;  // 0x2C igObjectRefMetaField
};
}
#endif
