// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80133B48 (metaobject lbl_80563BF4, vtable lbl_804A33CC), size 0x2C.
#ifndef META_IGSCALEPS2TEXTURE_H
#define META_IGSCALEPS2TEXTURE_H
#include <meta/igOptVisitObject.h>
namespace Meta {
struct igScalePs2Texture : igOptVisitObject {
};
}
#endif
