// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igScalerModel_register (metaobject lbl_805635C8, vtable lbl_80497D08), size 0x40.
#ifndef META_IGSCALERMODEL_H
#define META_IGSCALERMODEL_H
#include <meta/igSimpleChildHolderModel.h>
namespace Meta {
struct igScalerModel : igSimpleChildHolderModel {
 float _scale[3];  // 0x34 igVec3fMetaField
};
}
#endif
