// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igScissorExt_register (metaobject lbl_80562E14), size 0x14.
#ifndef META_IGSCISSOREXT_H
#define META_IGSCISSOREXT_H
#include <meta/igContextExt.h>
namespace Meta {
struct igScissorExt : igContextExt {
};
}
#endif
