// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igSceneInfo_register (metaobject lbl_80564A14, vtable lbl_804B3D68), size 0x40.
#ifndef META_IGSCENEINFO_H
#define META_IGSCENEINFO_H
#include <meta/igInfo.h>
namespace Meta {
struct igGraphPathList;
struct igNode;
struct igNodeList;
struct igTextureList;
struct igSceneInfo : igInfo {
 igNode *_sceneGraph;  // 0x14 igObjectRefMetaField
 igTextureList *_textures;  // 0x18 igObjectRefMetaField
 igGraphPathList *_cameras;  // 0x1C igObjectRefMetaField
 long long _animationBegin;  // 0x20 igLongMetaField
 long long _animationEnd;  // 0x28 igLongMetaField
 float _upVector[3];  // 0x30 igVec3fMetaField
 igNodeList *_sceneGraphList;  // 0x3C igObjectRefMetaField
};
}
#endif
