// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800B12BC (metaobject lbl_8056263C, vtable lbl_8047B5CC), size 0x1C.
#ifndef META_IGSCENEAMBIENTCOLORATTR_H
#define META_IGSCENEAMBIENTCOLORATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igSceneAmbientColorAttr : igVisualAttribute {
 float _color[4];  // 0x0C igVec4fMetaField
};
}
#endif
