// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igScissorAttr_register (metaobject lbl_80562624, vtable lbl_8047B548), size 0x20.
#ifndef META_IGSCISSORATTR_H
#define META_IGSCISSORATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igScissorAttr : igVisualAttribute {
 bool _enb;  // 0x0C igBoolMetaField
 unsigned char unknown0D[3];
 int _x;  // 0x10 igIntMetaField
 int _y;  // 0x14 igIntMetaField
 int _w;  // 0x18 igIntMetaField
 int _h;  // 0x1C igIntMetaField
};
}
#endif
