// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8014A738 (metaobject lbl_805642D4), size 0x10.
#ifndef META_IGSERIALFILTERFUN_H
#define META_IGSERIALFILTERFUN_H
#include <meta/igFilterFun.h>
namespace Meta {
struct igSerialFilterFun : igFilterFun {
 double _hWidth;  // 0x08 igDoubleMetaField
};
}
#endif
