// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igSelfShadowShader_register (metaobject lbl_80564968, vtable lbl_804B3CD4), size 0xE8.
#ifndef META_IGSELFSHADOWSHADER_H
#define META_IGSELFSHADOWSHADER_H
#include <meta/igGroup.h>
namespace Meta {
struct igAttr;
struct igColorAttr;
struct igCopyRenderDestinationAttr;
struct igImage;
struct igLightAttr;
struct igModelViewMatrixAttr;
struct igNodeList;
struct igProjectionMatrixAttr;
struct igRenderDestinationAttr;
struct igSetRenderDestinationAttr;
struct igTexGenMatrixAttr;
struct igTextureAttr;
struct igTextureBindAttr;
struct igTextureMatrixAttr;
struct igVectorConstantAttr;
struct igViewportAttr;
struct igSelfShadowShader : igGroup {
 bool _inited;  // 0x20 igBoolMetaField
 unsigned char unknown21[3];
 float _lightPosition[3];  // 0x24 igVec3fMetaField
 float _lightDirection[3];  // 0x30 igVec3fMetaField
 float _cutoffAngle;  // 0x3C igFloatMetaField
 float _zNear;  // 0x40 igFloatMetaField
 float _zFar;  // 0x44 igFloatMetaField
 float _upVector[3];  // 0x48 igVec3fMetaField
 igNodeList *_shadowCasters;  // 0x54 igObjectRefMetaField
 igNodeList *_shadowReceivers;  // 0x58 igObjectRefMetaField
 igModelViewMatrixAttr *_lightMVMAttr;  // 0x5C igObjectRefMetaField
 igProjectionMatrixAttr *_lightProjAttr;  // 0x60 igObjectRefMetaField
 igTextureMatrixAttr *_viewToProjectedLightTextureMatrix;  // 0x64 igObjectRefMetaField
 igTextureMatrixAttr *_depthTextureMatrix;  // 0x68 igObjectRefMetaField
 float _zBias;  // 0x6C igFloatMetaField
 float _shadowColor[4];  // 0x70 igVec4fMetaField
 int _shadowTexW;  // 0x80 igIntMetaField
 int _shadowTexH;  // 0x84 igIntMetaField
 int _depthIndex;  // 0x88 igIntMetaField
 bool _updateDepthMap;  // 0x8C igBoolMetaField
 unsigned char unknown8D[3];
 igRenderDestinationAttr *_pShadowTexRD;  // 0x90 igObjectRefMetaField
 igSetRenderDestinationAttr *_pSetShadowTexRD;  // 0x94 igObjectRefMetaField
 igTextureAttr *_pShadowTex;  // 0x98 igObjectRefMetaField
 igTextureBindAttr *_pShadowTexBind0;  // 0x9C igObjectRefMetaField
 igTextureBindAttr *_pShadowTexBind1;  // 0xA0 igObjectRefMetaField
 igTextureBindAttr *_pShadowTexBind2;  // 0xA4 igObjectRefMetaField
 igCopyRenderDestinationAttr *_shadowCopyBack;  // 0xA8 igObjectRefMetaField
 igImage *_shadowCopyBackImage;  // 0xAC igObjectRefMetaField
 igViewportAttr *_shadowViewport;  // 0xB0 igObjectRefMetaField
 igVectorConstantAttr *_shadowColorPixelConstant;  // 0xB4 igObjectRefMetaField
 igTextureBindAttr *_rampTexBind1;  // 0xB8 igObjectRefMetaField
 igAttr *_shadowEnvironmentColor;  // 0xBC igObjectRefMetaField
 igLightAttr *_light;  // 0xC0 igObjectRefMetaField
 igTexGenMatrixAttr *_depthToAlphaMatrix;  // 0xC4 igObjectRefMetaField
 igTexGenMatrixAttr *_depthToAlphaMatrixBiased;  // 0xC8 igObjectRefMetaField
 igColorAttr *_shadowColorAttr;  // 0xCC igObjectRefMetaField
 bool _useOrthographic;  // 0xD0 igBoolMetaField
 unsigned char unknownD1[3];
 float _top;  // 0xD4 igFloatMetaField
 float _bottom;  // 0xD8 igFloatMetaField
 float _right;  // 0xDC igFloatMetaField
 float _left;  // 0xE0 igFloatMetaField
 igViewportAttr *_shadowInnerViewport;  // 0xE4 igObjectRefMetaField
};
}
#endif
