// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802846AC (metaobject lbl_80515C70, vtable lbl_804CC018), size 0x10.
#ifndef META_IGSERIALSCHEDULER_H
#define META_IGSERIALSCHEDULER_H
#include <meta/igInsightScheduler.h>
namespace Meta {
struct igInfoManagerList;
struct igInfoManagerOrderedList;
struct igSerialScheduler : igInsightScheduler {
 igInfoManagerOrderedList *_managerList;  // 0x08 igObjectRefMetaField
 igInfoManagerList *_cachedManagerList;  // 0x0C igObjectRefMetaField
};
}
#endif
