// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80133914 (metaobject lbl_80563BF0, vtable lbl_804A3358), size 0x20.
#ifndef META_IGSEGMENTLOCK_H
#define META_IGSEGMENTLOCK_H
#include <meta/igTypeLock.h>
namespace Meta {
struct igSegmentLock : igTypeLock {
};
}
#endif
