// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igShadeModelAttr_register (metaobject lbl_8056260C, vtable lbl_8047B3C4), size 0x10.
#ifndef META_IGSHADEMODELATTR_H
#define META_IGSHADEMODELATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igShadeModelAttr : igVisualAttribute {
 int _mode;  // 0x0C igEnumMetaField
};
}
#endif
