// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igShortListList_register (metaobject lbl_80561D8C, vtable lbl_80474BA8), size 0x14.
#ifndef META_IGSHORTLISTLIST_H
#define META_IGSHORTLISTLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igShortListList : igObjectList {
};
}
#endif
