// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igShaderFactory_register (metaobject lbl_805648E8, vtable lbl_804B3AB8), size 0x18.
#ifndef META_IGSHADERFACTORY_H
#define META_IGSHADERFACTORY_H
#include <meta/igNamedObject.h>
#include <meta/enums.h>
namespace Meta {
struct igNamedObjectList;
struct igShaderFactory : igNamedObject {
 igNamedObjectList *_attrNames;  // 0x0C igObjectRefMetaField
 igNamedObjectList *_attrTypes;  // 0x10 igObjectRefMetaField
 FILE_CACHING_MODE::Value _fileCachingMode;  // 0x14 igEnumMetaField
};
}
#endif
