// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igShaderFunction_register (metaobject lbl_805648DC), size 0x8.
#ifndef META_IGSHADERFUNCTION_H
#define META_IGSHADERFUNCTION_H
#include <meta/igObject.h>
namespace Meta {
struct igShaderFunction : igObject {
};
}
#endif
