// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igShaderInfo_register (metaobject lbl_805648D4, vtable lbl_804B3A54), size 0x18.
#ifndef META_IGSHADERINFO_H
#define META_IGSHADERINFO_H
#include <meta/igInfo.h>
namespace Meta {
struct igShaderFactoryList;
struct igShaderInfo : igInfo {
 igShaderFactoryList *_factoryList;  // 0x14 igObjectRefMetaField
};
}
#endif
