// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igShaderFactoryList_register (metaobject lbl_805648E0, vtable lbl_804B9098), size 0x14.
#ifndef META_IGSHADERFACTORYLIST_H
#define META_IGSHADERFACTORYLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igShaderFactoryList : igObjectList {
};
}
#endif
