// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801B073C (metaobject lbl_805648BC, vtable lbl_804B3930), size 0x34.
#ifndef META_IGSIMPLESHADER_H
#define META_IGSIMPLESHADER_H
#include <meta/igShader2.h>
namespace Meta {
struct igBitMask;
struct igDataPumpManager;
struct igShaderData;
struct igShaderProcessor;
struct igSimpleShader : igShader2 {
 igShaderData *_shaderData;  // 0x24 igObjectRefMetaField
 igShaderProcessor *_processor;  // 0x28 igObjectRefMetaField
 igBitMask *_passMask;  // 0x2C igObjectRefMetaField
 igDataPumpManager *_dataPumpManager;  // 0x30 igObjectRefMetaField
};
}
#endif
