// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801AFC10 (metaobject lbl_80564894, vtable lbl_804B3810), size 0x1C.
#ifndef META_IGSKELETON_H
#define META_IGSKELETON_H
#include <meta/igAnimationHierarchy.h>
namespace Meta {
struct igSkeletonBoneInfoList;
struct igSkeleton : igAnimationHierarchy {
 igSkeletonBoneInfoList *_boneInfoList;  // 0x10 igObjectRefMetaField
 void *_invJointArray;  // 0x14 igMemoryRefMetaField
 int _jointCount;  // 0x18 igIntMetaField
};
}
#endif
