// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801AFE74 (metaobject lbl_805648A4, vtable lbl_804B925C), size 0x14.
#ifndef META_IGSKELETONBONEINFOLIST_H
#define META_IGSKELETONBONEINFOLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igSkeletonBoneInfoList : igObjectList {
};
}
#endif
