// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igSkeletonBoneInfo_register (metaobject lbl_805648A8, vtable lbl_804B9200), size 0x18.
#ifndef META_IGSKELETONBONEINFO_H
#define META_IGSKELETONBONEINFO_H
#include <meta/igNamedObject.h>
namespace Meta {
struct igSkeletonBoneInfo : igNamedObject {
 int _parentIdx;  // 0x0C igIntMetaField
 int _bmIdx;  // 0x10 igIntMetaField
 int _flags;  // 0x14 igIntMetaField
};
}
#endif
