// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igSkinList_register (metaobject lbl_80564880, vtable lbl_804B94C8), size 0x14.
#ifndef META_IGSKINLIST_H
#define META_IGSKINLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igSkinList : igObjectList {
};
}
#endif
