// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80133064 (metaobject lbl_80563BB4, vtable lbl_804A31A0), size 0x3C.
#ifndef META_IGSMARTCOMPILEGRAPH_H
#define META_IGSMARTCOMPILEGRAPH_H
#include <meta/igOptVisitObject.h>
namespace Meta {
struct igMetaObjectList;
struct igNodeList;
struct igSmartCompileGraph : igOptVisitObject {
 int _priorStateUsage;  // 0x2C igIntMetaField
 const char *_metaListString;  // 0x30 igStringMetaField
 igMetaObjectList *_allowedMetas;  // 0x34 igObjectRefMetaField
 igNodeList *_nodeList;  // 0x38 igObjectRefMetaField
};
}
#endif
