// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80149604 (metaobject lbl_80564290), size 0x14.
#ifndef META_IGSMOOTHIMAGE_H
#define META_IGSMOOTHIMAGE_H
#include <meta/igFilterImage.h>
namespace Meta {
struct igSmoothImage : igFilterImage {
};
}
#endif
