// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801AE998 (metaobject lbl_805647C8, vtable lbl_804B37AC), size 0x84.
#ifndef META_IGSORTER_H
#define META_IGSORTER_H
#include <meta/igObject.h>
namespace Meta {
struct igCullFaceAttr;
struct igDepthWriteStateAttr;
struct igDisplayListAttr;
struct igGeometry;
struct igIntList;
struct igNonRefCountedAttrList;
struct igRenderPackage;
struct igRenderPackageList;
struct igRenderPackagePool;
struct igSorter : igObject {
 igDisplayListAttr *_dlist;  // 0x08 igObjectRefMetaField
 int _mode;  // 0x0C igIntMetaField
 igRenderPackagePool *_renderPackagePool;  // 0x10 igObjectRefMetaField
 igNonRefCountedAttrList *_tmpAttrs;  // 0x14 igObjectRefMetaField
 igRenderPackageList *_transpPackages;  // 0x18 igObjectRefMetaField
 igRenderPackageList *_opaquePackages;  // 0x1C igObjectRefMetaField
 igRenderPackageList *_firstPackages;  // 0x20 igObjectRefMetaField
 igDisplayListAttr *_lightAttrs;  // 0x24 igObjectRefMetaField
 igDisplayListAttr *_firstAttrs;  // 0x28 igObjectRefMetaField
 igDisplayListAttr *_transpAttrs;  // 0x2C igObjectRefMetaField
 igDisplayListAttr *_opaqueAttrs;  // 0x30 igObjectRefMetaField
 igIntList *_firstPackageIndices;  // 0x34 igObjectRefMetaField
 igIntList *_transpPackageIndices;  // 0x38 igObjectRefMetaField
 igIntList *_opaquePackageIndices;  // 0x3C igObjectRefMetaField
 igDepthWriteStateAttr *_depthWriteDisable;  // 0x40 igObjectRefMetaField
 igCullFaceAttr *_cullFaceFront;  // 0x44 igObjectRefMetaField
 igCullFaceAttr *_cullFaceBack;  // 0x48 igObjectRefMetaField
 int _transparencyDrawMode;  // 0x4C igIntMetaField
 igRenderPackage *_emptyRenderPackage;  // 0x50 igObjectRefMetaField
 igRenderPackageList *_emptyRenderPackageList;  // 0x54 igObjectRefMetaField
 igIntList *_emptyRenderPackageIndices;  // 0x58 igObjectRefMetaField
 igDisplayListAttr *_lastEmptyRenderPackageAttrs;  // 0x5C igObjectRefMetaField
 igDisplayListAttr *_firstEmptyRenderPackageAttrs;  // 0x60 igObjectRefMetaField
 igGeometry *_emptyGeometry;  // 0x64 igObjectRefMetaField
 igIntList *_curList;  // 0x68 igObjectRefMetaField
 igIntList *_prevList;  // 0x6C igObjectRefMetaField
 bool _isCompoundPackageOpen;  // 0x70 igBoolMetaField
 bool _isCompoundPackageTransparent;  // 0x71 igBoolMetaField
 bool _isCompoundPackageFirst;  // 0x72 igBoolMetaField
 unsigned char unknown73[1];
 igRenderPackage *_compoundPackage;  // 0x74 igObjectRefMetaField
 int _compoundPackageNestCount;  // 0x78 igIntMetaField
 igRenderPackage *_cachedPackage;  // 0x7C igObjectRefMetaField
 bool _outputCreated;  // 0x80 igBoolMetaField
 bool _useZSort;  // 0x81 igBoolMetaField
 bool _forceNoSeparate;  // 0x82 igBoolMetaField
 bool _printOutputState;  // 0x83 igBoolMetaField
};
}
#endif
