// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8011F60C (metaobject lbl_8056395C, vtable lbl_8049B980), size 0x18.
#ifndef META_IGSPHERE_H
#define META_IGSPHERE_H
#include <meta/igVolume.h>
namespace Meta {
struct igSphere : igVolume {
 float _center[3];  // 0x08 igVec3fMetaField
 float _radius;  // 0x14 igFloatMetaField
};
}
#endif
