// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igStringRefList_register (metaobject lbl_8056158C, vtable lbl_80470F5C), size 0x14.
#ifndef META_IGSTRINGREFLIST_H
#define META_IGSTRINGREFLIST_H
#include <meta/igDataList.h>
namespace Meta {
struct igStringRefList : igDataList {
};
}
#endif
