// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igStringKey_register (metaobject lbl_805647C0, vtable lbl_804B3748), size 0xC.
#ifndef META_IGSTRINGKEY_H
#define META_IGSTRINGKEY_H
#include <meta/igPropertyKey.h>
namespace Meta {
struct igStringKey : igPropertyKey {
 const char *_value;  // 0x08 igStringMetaField
};
}
#endif
