// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igStringValue_register (metaobject lbl_805647B8, vtable lbl_804B97E0), size 0xC.
#ifndef META_IGSTRINGVALUE_H
#define META_IGSTRINGVALUE_H
#include <meta/igPropertyValue.h>
namespace Meta {
struct igStringValue : igPropertyValue {
 const char *_value;  // 0x08 igStringMetaField
};
}
#endif
