// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80130840 (metaobject lbl_80563ACC, vtable lbl_804A2D64), size 0x30.
#ifndef META_IGSTRIPTRIANGLES_H
#define META_IGSTRIPTRIANGLES_H
#include <meta/igOptBase.h>
namespace Meta {
struct igStripTriangles : igOptBase {
 unsigned int _minNumberOfTriangle;  // 0x28 igUnsignedIntMetaField
 bool _stitch;  // 0x2C igBoolMetaField
 bool _index;  // 0x2D igBoolMetaField
 unsigned char unknown2E[2];
};
}
#endif
