// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igStatistics_register (metaobject lbl_80563B44, vtable lbl_804A2F64), size 0x34.
#ifndef META_IGSTATISTICS_H
#define META_IGSTATISTICS_H
#include <meta/igOptBase.h>
#include <meta/enums.h>
namespace Meta {
struct igAllAttrStatistics;
struct igAllNodeStatistics;
struct igStatistics : igOptBase {
 igAllNodeStatistics *_nodeStatistics;  // 0x28 igObjectRefMetaField
 igAllAttrStatistics *_attrStatistics;  // 0x2C igObjectRefMetaField
 STATISTICS_VERBOSE::Value _level;  // 0x30 igEnumMetaField
};
}
#endif
