// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igStringRefListList_register (metaobject lbl_80561D4C, vtable lbl_804754E8), size 0x14.
#ifndef META_IGSTRINGREFLISTLIST_H
#define META_IGSTRINGREFLISTLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igStringRefListList : igObjectList {
};
}
#endif
