// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igStandardQueue_register (metaobject lbl_80562048, vtable lbl_8046F87C), size 0x2C.
#ifndef META_IGSTANDARDQUEUE_H
#define META_IGSTANDARDQUEUE_H
#include <meta/igQueue.h>
namespace Meta {
struct igSemaphore;
struct igStandardQueue : igQueue {
 igSemaphore *_insertLock;  // 0x0C igObjectRefMetaField
 igSemaphore *_removeLock;  // 0x10 igObjectRefMetaField
 igSemaphore *_queueSema;  // 0x14 igObjectRefMetaField
 unsigned int _capacity;  // 0x18 igUnsignedIntMetaField
 unsigned int _insertElement;  // 0x1C igUnsignedIntMetaField
 unsigned int _removeElement;  // 0x20 igUnsignedIntMetaField
 void *_data;  // 0x24 igMemoryRefMetaField
 unsigned int _maxCapacity;  // 0x28 igUnsignedIntMetaField
};
}
#endif
