// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igStdFilterFun_register (metaobject lbl_805642D0, vtable lbl_804A8CBC), size 0x10.
#ifndef META_IGSTDFILTERFUN_H
#define META_IGSTDFILTERFUN_H
#include <meta/igSerialFilterFun.h>
namespace Meta {
struct igStdFilterFun : igSerialFilterFun {
};
}
#endif
