// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igStatisticsItemList_register (metaobject lbl_8055C740, vtable lbl_804F1680), size 0x14.
#ifndef META_IGSTATISTICSITEMLIST_H
#define META_IGSTATISTICSITEMLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igStatisticsItemList : igObjectList {
};
}
#endif
