// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igStatisticsNodeUsage_register (metaobject lbl_80563ADC, vtable lbl_804A2E04), size 0x48.
#ifndef META_IGSTATISTICSNODEUSAGE_H
#define META_IGSTATISTICSNODEUSAGE_H
#include <meta/igOptStatistics.h>
namespace Meta {
struct igMetaObject;
struct igStatisticsNodeUsage : igOptStatistics {
 igMetaObject *_nodeType;  // 0x44 igObjectRefMetaField
};
}
#endif
