// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igSwitch_register (metaobject lbl_805647B0, vtable lbl_804B36B4), size 0x24.
#ifndef META_IGSWITCH_H
#define META_IGSWITCH_H
#include <meta/igGroup.h>
namespace Meta {
struct igBitMask;
struct igSwitch : igGroup {
 igBitMask *_childMask;  // 0x20 igObjectRefMetaField
};
}
#endif
