// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igSymbolTable_register (metaobject lbl_80561538, vtable lbl_80470D7C), size 0x2C.
#ifndef META_IGSYMBOLTABLE_H
#define META_IGSYMBOLTABLE_H
#include <meta/igObject.h>
namespace Meta {
struct igIntListNoClean;
struct igStringTable;
struct igUnsignedIntListNoClean;
struct igSymbolTable : igObject {
 int _capacity;  // 0x08 igIntMetaField
 int _hashCapacity;  // 0x0C igIntMetaField
 unsigned int _lowAddress;  // 0x10 igUnsignedIntMetaField
 unsigned int _highAddress;  // 0x14 igUnsignedIntMetaField
 unsigned int _hashIncrement;  // 0x18 igUnsignedIntMetaField
 igUnsignedIntListNoClean *_symbols;  // 0x1C igObjectRefMetaField
 igIntListNoClean *_hashIndex;  // 0x20 igObjectRefMetaField
 igStringTable *_symbolNames;  // 0x24 igObjectRefMetaField
 igStringTable *_sourceFileNames;  // 0x28 igObjectRefMetaField
};
}
#endif
