// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igTextureAttr_register (metaobject lbl_80562554, vtable lbl_8047AFF4), size 0x48.
#ifndef META_IGTEXTUREATTR_H
#define META_IGTEXTUREATTR_H
#include <meta/igVisualAttribute.h>
#include <meta/enums.h>
namespace Meta {
struct igImage;
struct igImageMipMapList;
struct igTextureUnloadAttr;
struct igVisualContext;
struct igTextureAttr : igVisualAttribute {
 igVisualContext *_vc;  // 0x0C igObjectRefMetaField
 unsigned int _bColor;  // 0x10 igUnsignedIntMetaField
 IG_GFX_TEXTURE_FILTER::Value _magFilter;  // 0x14 igEnumMetaField
 IG_GFX_TEXTURE_FILTER::Value _minFilter;  // 0x18 igEnumMetaField
 IG_GFX_TEXTURE_WRAP::Value _wrapS;  // 0x1C igEnumMetaField
 IG_GFX_TEXTURE_WRAP::Value _wrapT;  // 0x20 igEnumMetaField
 int _texId;  // 0x24 igIntMetaField
 IG_GFX_TEXTURE_MODE::Value _mipmapMode;  // 0x28 igEnumMetaField
 IG_GFX_TEXTURE_SOURCE::Value _source;  // 0x2C igEnumMetaField
 igImage *_image;  // 0x30 igObjectRefMetaField
 bool _paging;  // 0x34 igBoolMetaField
 unsigned char unknown35[3];
 igTextureUnloadAttr *_tu;  // 0x38 igObjectRefMetaField
 int _imageCount;  // 0x3C igIntMetaField
 igImageMipMapList *_imageMipMaps;  // 0x40 igObjectRefMetaField
 void *_videoBuffer;  // 0x44 igRawRefMetaField
};
}
#endif
