// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800AE114 (metaobject lbl_805624E4, vtable lbl_8047E2B8), size 0x14.
#ifndef META_IGTEXTUREMATRIXATTRLIST_H
#define META_IGTEXTUREMATRIXATTRLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igTextureMatrixAttrList : igObjectList {
};
}
#endif
