// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igTextureStageConstantColorSelectAttr_register (metaobject lbl_80562AAC, vtable lbl_8047A41C), size 0x14.
#ifndef META_IGTEXTURESTAGECONSTANTCOLORSELECTATTR_H
#define META_IGTEXTURESTAGECONSTANTCOLORSELECTATTR_H
#include <meta/igVisualAttribute.h>
#include <meta/enums.h>
namespace Meta {
struct igTextureStageConstantColorSelectAttr : igVisualAttribute {
 IG_GFX_TEXTURE_CONSTANT_COLOR_SELECTION::Value _constantSelect;  // 0x0C igEnumMetaField
 short _unitID;  // 0x10 igShortMetaField
 unsigned char unknown12[2];
};
}
#endif
