// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igTextureTransformMovieProcessor_register (metaobject lbl_8056475C, vtable lbl_804B3644), size 0x50.
#ifndef META_IGTEXTURETRANSFORMMOVIEPROCESSOR_H
#define META_IGTEXTURETRANSFORMMOVIEPROCESSOR_H
#include <meta/igShaderProcessor.h>
namespace Meta {
struct igTextureMatrixAttr;
struct igVectorConstantAttr;
struct igTextureTransformMovieProcessor : igShaderProcessor {
 float _framesPerSecond;  // 0x08 igFloatMetaField
 int _cellCountX;  // 0x0C igIntMetaField
 int _cellCountY;  // 0x10 igIntMetaField
 int _totalCellCount;  // 0x14 igIntMetaField
 igTextureMatrixAttr *_currentTextureMatrix;  // 0x18 igObjectRefMetaField
 igTextureMatrixAttr *_nextTextureMatrix;  // 0x1C igObjectRefMetaField
 bool _interpolateFrames;  // 0x20 igBoolMetaField
 unsigned char unknown21[3];
 igVectorConstantAttr *_blendFactor;  // 0x24 igObjectRefMetaField
 float _secondsPerFrame;  // 0x28 igFloatMetaField
 float _secondsPerCycle;  // 0x2C igFloatMetaField
 float _scaleX;  // 0x30 igFloatMetaField
 float _scaleY;  // 0x34 igFloatMetaField
 float _previousCycleTime;  // 0x38 igFloatMetaField
 unsigned char unknown3C[4];
 long long _previousFrameTime;  // 0x40 igLongMetaField
 int _previousCell;  // 0x48 igIntMetaField
 float _previousBlendFactor;  // 0x4C igFloatMetaField
};
}
#endif
