// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800AF31C (metaobject lbl_80562548, vtable lbl_8047AF6C), size 0x14.
#ifndef META_IGTEXTUREBINDATTR_H
#define META_IGTEXTUREBINDATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igTextureAttr;
struct igTextureBindAttr : igVisualAttribute {
 igTextureAttr *_texture;  // 0x0C igObjectRefMetaField
 int _unitID;  // 0x10 igIntMetaField
};
}
#endif
