// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800BC4F8 (metaobject lbl_80562AB8, vtable lbl_8047A49C), size 0x14.
#ifndef META_IGTEXTURESTAGECONSTANTALPHASELECTATTR_H
#define META_IGTEXTURESTAGECONSTANTALPHASELECTATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igTextureStageConstantAlphaSelectAttr : igVisualAttribute {
 int _constantSelect;  // 0x0C igEnumMetaField
 short _unitID;  // 0x10 igShortMetaField
 unsigned char unknown12[2];
};
}
#endif
