// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igTextureBindAttrList_register (metaobject lbl_80534408, vtable lbl_804CDFF0), size 0x14.
#ifndef META_IGTEXTUREBINDATTRLIST_H
#define META_IGTEXTUREBINDATTRLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igTextureBindAttrList : igObjectList {
};
}
#endif
