// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igTextureCubeAttr_register (metaobject lbl_80562528, vtable lbl_8047AE48), size 0x68.
// Note: _cubeImage: igObjectRefArrayMetaField, count from the space to the next member.
#ifndef META_IGTEXTURECUBEATTR_H
#define META_IGTEXTURECUBEATTR_H
#include <meta/igTextureAttr.h>
#include <meta/enums.h>
namespace Meta {
struct igTextureCubeAttr : igTextureAttr {
 void * _cubeImage[6];  // 0x48 igObjectRefArrayMetaField
 ApplyType::Value _applyType;  // 0x60 igEnumMetaField
 int _unused;  // 0x64 igIntMetaField
};
}
#endif
