// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igTextureMatrixStateAttr_register (metaobject lbl_805624D8, vtable lbl_8047AC48), size 0x14.
#ifndef META_IGTEXTUREMATRIXSTATEATTR_H
#define META_IGTEXTUREMATRIXSTATEATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igTextureMatrixStateAttr : igVisualAttribute {
 bool _enabled;  // 0x0C igBoolMetaField
 unsigned char unknown0D[3];
 int _unitID;  // 0x10 igIntMetaField
};
}
#endif
