// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igTexGenMatrixAttr_register (metaobject lbl_805625A4, vtable lbl_8047B114), size 0x50.
#ifndef META_IGTEXGENMATRIXATTR_H
#define META_IGTEXGENMATRIXATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igTexGenMatrixAttr : igVisualAttribute {
 float m[16];  // 0x0C igMatrix44fMetaField
 int _unitID;  // 0x4C igIntMetaField
};
}
#endif
