// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800AE88C (metaobject lbl_80562504, vtable lbl_8047ADB8), size 0x28.
#ifndef META_IGTEXTUREFUNCTIONATTR_H
#define META_IGTEXTUREFUNCTIONATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igTextureFunctionAttr : igVisualAttribute {
 int _mode;  // 0x0C igEnumMetaField
 int _unitID;  // 0x10 igIntMetaField
 int _arg0;  // 0x14 igEnumMetaField
 int _arg1;  // 0x18 igEnumMetaField
 int _type;  // 0x1C igEnumMetaField
 unsigned char _call_state;  // 0x20 igUnsignedCharMetaField
 unsigned char unknown21[3];
 int _functionType;  // 0x24 igEnumMetaField
};
}
#endif
