// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800AE640 (metaobject lbl_805624FC, vtable lbl_8047AD50), size 0x18.
#ifndef META_IGTEXTUREINFO_H
#define META_IGTEXTUREINFO_H
#include <meta/igInfo.h>
namespace Meta {
struct igTextureList;
struct igTextureInfo : igInfo {
 igTextureList *_textureList;  // 0x14 igObjectRefMetaField
};
}
#endif
