// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800BC720 (metaobject lbl_80562AC4, vtable lbl_8047A51C), size 0x14.
#ifndef META_IGTEXTUREENVIRONMENTCOLORATTR_H
#define META_IGTEXTUREENVIRONMENTCOLORATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igTextureEnvironmentColorAttr : igVisualAttribute {
 unsigned int _environmentColor;  // 0x0C igUnsignedIntMetaField
 short _unitID;  // 0x10 igShortMetaField
 unsigned char unknown12[2];
};
}
#endif
