// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800ADD2C (metaobject lbl_805624CC, vtable lbl_8047ABC4), size 0x14.
#ifndef META_IGTEXTURESTATEATTR_H
#define META_IGTEXTURESTATEATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igTextureStateAttr : igVisualAttribute {
 bool _enabled;  // 0x0C igBoolMetaField
 unsigned char unknown0D[3];
 int _unitID;  // 0x10 igIntMetaField
};
}
#endif
