// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800D44D8 (metaobject lbl_8056304C, vtable lbl_80493470), size 0x14.
#ifndef META_IGTEXTURESAMPLERSOURCELIST_H
#define META_IGTEXTURESAMPLERSOURCELIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igTextureSamplerSourceList : igObjectList {
};
}
#endif
