// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800ADAC8 (metaobject lbl_805624C0, vtable lbl_8047AB40), size 0x14.
#ifndef META_IGTEXTUREUNLOADATTR_H
#define META_IGTEXTUREUNLOADATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igTextureAttr;
struct igTextureUnloadAttr : igVisualAttribute {
 igTextureAttr *_texture;  // 0x0C igObjectRefMetaField
 int _unitID;  // 0x10 igIntMetaField
};
}
#endif
