// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igThreadManager_register (metaobject lbl_805614E8), size 0x10.
#ifndef META_IGTHREADMANAGER_H
#define META_IGTHREADMANAGER_H
#include <meta/igObject.h>
namespace Meta {
struct igNonRefCountedThreadList;
struct igSemaphore;
struct igThreadManager : igObject {
 igNonRefCountedThreadList *_threadList;  // 0x08 igObjectRefMetaField
 igSemaphore *_sema;  // 0x0C igObjectRefMetaField
};
}
#endif
