// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800240F4 (metaobject lbl_80561534, vtable lbl_80476BB4), size 0x14.
#ifndef META_IGTHREADLIST_H
#define META_IGTHREADLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igThreadList : igObjectList {
};
}
#endif
