// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80023748 (metaobject lbl_805614E4), size 0x8.
#ifndef META_IGTIMER_H
#define META_IGTIMER_H
#include <meta/igObject.h>
namespace Meta {
struct igTimer : igObject {
};
}
#endif
