// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igTimeSwitch_register (metaobject lbl_80564744, vtable lbl_804B9A1C), size 0x38.
#ifndef META_IGTIMESWITCH_H
#define META_IGTIMESWITCH_H
#include <meta/igGroup.h>
namespace Meta {
struct igSpecialDoubleList;
struct igTimeSwitch : igGroup {
 igSpecialDoubleList *_timeList;  // 0x20 igObjectRefMetaField
 unsigned char unknown24[4];
 double _startTime;  // 0x28 igDoubleMetaField
 int _playMode;  // 0x30 igEnumMetaField
 unsigned char unknown34[4];
};
}
#endif
