// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801ACE44 (metaobject lbl_80564734), size 0x30.
#ifndef META_IGTIMETRANSFORM_H
#define META_IGTIMETRANSFORM_H
#include <meta/igGroup.h>
namespace Meta {
struct igTimeTransform : igGroup {
 double _scale;  // 0x20 igDoubleMetaField
 double _bias;  // 0x28 igDoubleMetaField
};
}
#endif
