// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800D27DC (metaobject lbl_80562FD0, vtable lbl_80493BE8), size 0x14.
#ifndef META_IGTRACKEDELEMENTLIST_H
#define META_IGTRACKEDELEMENTLIST_H
#include <meta/igDataList.h>
namespace Meta {
struct igTrackedElementList : igDataList {
};
}
#endif
