// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igTrackedElementMetaField_register (metaobject lbl_80562FDC, vtable lbl_80493AF4), size 0x38.
#ifndef META_IGTRACKEDELEMENTMETAFIELD_H
#define META_IGTRACKEDELEMENTMETAFIELD_H
#include <meta/igCompoundMetaField.h>
namespace Meta {
struct igTrackedElementMetaField : igCompoundMetaField {
};
}
#endif
