// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801B2ED4 (metaobject lbl_80564964, vtable lbl_804B8810), size 0x14.
#ifndef META_IGTRAVERSALFUNCTIONLIST_H
#define META_IGTRAVERSALFUNCTIONLIST_H
#include <meta/igDataList.h>
namespace Meta {
struct igTraversalFunctionList : igDataList {
};
}
#endif
