// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igTransformFunctionList_register (metaobject lbl_805639B8, vtable lbl_8049B500), size 0x14.
#ifndef META_IGTRANSFORMFUNCTIONLIST_H
#define META_IGTRANSFORMFUNCTIONLIST_H
#include <meta/igDataList.h>
namespace Meta {
struct igTransformFunctionList : igDataList {
};
}
#endif
