// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801AB230 (metaobject lbl_80564694), size 0x8.
#ifndef META_IGTRANSFORMSOURCEPARAMETERS_H
#define META_IGTRANSFORMSOURCEPARAMETERS_H
#include <meta/igObject.h>
namespace Meta {
struct igTransformSourceParameters : igObject {
};
}
#endif
