// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801AB354 (metaobject lbl_80564698), size 0x8.
#ifndef META_IGTRANSFORMSOURCE_H
#define META_IGTRANSFORMSOURCE_H
#include <meta/igObject.h>
namespace Meta {
struct igTransformSource : igObject {
};
}
#endif
