// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igTransientShaderData_register (metaobject lbl_80564680, vtable lbl_804BA1D8), size 0x18.
#ifndef META_IGTRANSIENTSHADERDATA_H
#define META_IGTRANSIENTSHADERDATA_H
#include <meta/igShaderData.h>
namespace Meta {
struct igTransientShaderData : igShaderData {
};
}
#endif
