// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igTransformSequence1_5_register (metaobject lbl_8056469C, vtable lbl_804B32DC), size 0x68.
// Note: _interpolationMethod: igUnsignedCharArrayMetaField, count from the space to the next member.
#ifndef META_IGTRANSFORMSEQUENCE1_5_H
#define META_IGTRANSFORMSEQUENCE1_5_H
#include <meta/igTransformSequence.h>
namespace Meta {
struct igCompressedTransformSequence1_5Data;
struct igLongList;
struct igVec3fList;
struct igTransformSequence1_5 : igTransformSequence {
 igLongList *_timeListLong;  // 0x38 igObjectRefMetaField
 igVec3fList *_interpolationDataTranslation;  // 0x3C igObjectRefMetaField
 igVec3fList *_interpolationDataRotation;  // 0x40 igObjectRefMetaField
 igVec3fList *_interpolationDataScale;  // 0x44 igObjectRefMetaField
 unsigned char _drivenChannels;  // 0x48 igUnsignedCharMetaField
 unsigned char _interpolationMethod[7];  // 0x49 igUnsignedCharArrayMetaField
 long long _keyframeTimeOffset;  // 0x50 igLongMetaField
 long long _animationDuration;  // 0x58 igLongMetaField
 igCompressedTransformSequence1_5Data *_compressedDataObject;  // 0x60 igObjectRefMetaField
 unsigned char unknown64[4];
};
}
#endif
