// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igTransformList_register (metaobject lbl_8056470C, vtable lbl_804B9CD8), size 0x14.
#ifndef META_IGTRANSFORMLIST_H
#define META_IGTRANSFORMLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igTransformList : igObjectList {
};
}
#endif
