// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igTransformSequence_register (metaobject lbl_805646D0), size 0x38.
#ifndef META_IGTRANSFORMSEQUENCE_H
#define META_IGTRANSFORMSEQUENCE_H
#include <meta/igTransformSource.h>
namespace Meta {
struct igDoubleList;
struct igQuaternionfList;
struct igVec3fList;
struct igTransformSequence : igTransformSource {
 igVec3fList *_xlateList;  // 0x08 igObjectRefMetaField
 igQuaternionfList *_quatList;  // 0x0C igObjectRefMetaField
 igVec3fList *_scaleList;  // 0x10 igObjectRefMetaField
 igDoubleList *_timeList;  // 0x14 igObjectRefMetaField
 double _startTime;  // 0x18 igDoubleMetaField
 bool _uniformTimeEnabled;  // 0x20 igBoolMetaField
 unsigned char unknown21[3];
 int _playMode;  // 0x24 igEnumMetaField
 int _lastTime;  // 0x28 igIntMetaField
 float _centerOfRotation[3];  // 0x2C igVec3fMetaField
};
}
#endif
