// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80130140 (metaobject lbl_80563AA8, vtable lbl_804AADE0), size 0x24.
#ifndef META_IGTYPECHANGEDLISTENER_H
#define META_IGTYPECHANGEDLISTENER_H
#include <meta/igObjectChangedListener.h>
namespace Meta {
struct igMetaObject;
struct igTypeChangedListener : igObjectChangedListener {
 igMetaObject *_objectType;  // 0x20 igObjectRefMetaField
};
}
#endif
