// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igUnsignedIntArrayMetaField_register (metaobject lbl_805614C4, vtable lbl_80470950), size 0x38.
#ifndef META_IGUNSIGNEDINTARRAYMETAFIELD_H
#define META_IGUNSIGNEDINTARRAYMETAFIELD_H
#include <meta/igUnsignedIntMetaField.h>
namespace Meta {
struct igUnsignedIntArrayMetaField : igUnsignedIntMetaField {
 int _num;  // 0x34 igIntMetaField
};
}
#endif
