// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800228E0 (metaobject lbl_805614B0, vtable lbl_8047085C), size 0x38.
#ifndef META_IGUNSIGNEDLONGARRAYMETAFIELD_H
#define META_IGUNSIGNEDLONGARRAYMETAFIELD_H
#include <meta/igUnsignedLongMetaField.h>
namespace Meta {
struct igUnsignedLongArrayMetaField : igUnsignedLongMetaField {
 int _num;  // 0x34 igIntMetaField
};
}
#endif
