// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80035DA8 (metaobject lbl_80561DA8, vtable lbl_804748A0), size 0x14.
#ifndef META_IGUNSIGNEDINTLIST_H
#define META_IGUNSIGNEDINTLIST_H
#include <meta/igDataList.h>
namespace Meta {
struct igUnsignedIntList : igDataList {
};
}
#endif
