// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80216F7C (metaobject lbl_80565A04, vtable lbl_804BC880), size 0x14.
#ifndef META_IGUNRESOLVEDSYMBOLLIST_H
#define META_IGUNRESOLVEDSYMBOLLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igUnresolvedSymbolList : igObjectList {
};
}
#endif
