// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802171BC (metaobject lbl_80565A08, vtable lbl_804BC7C8), size 0x18.
#ifndef META_IGUNRESOLVEDSYMBOL_H
#define META_IGUNRESOLVEDSYMBOL_H
#include <meta/igNamedObject.h>
namespace Meta {
struct igObjectRefMetaField;
struct igUnresolvedSymbol : igNamedObject {
 igObjectRefMetaField *_field;  // 0x0C igObjectRefMetaField
 int _index;  // 0x10 igIntMetaField
 void *_object;  // 0x14 igObjectRefMetaField
};
}
#endif
