// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8002201C (metaobject lbl_80561494), size 0x34.
#ifndef META_IGUNSIGNEDSHORTMETAFIELD_H
#define META_IGUNSIGNEDSHORTMETAFIELD_H
#include <meta/igMetaField.h>
namespace Meta {
struct igUnsignedShortMetaField : igMetaField {
};
}
#endif
