// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igUnsignedLongList_register (metaobject lbl_80561DB8, vtable lbl_804746C0), size 0x14.
#ifndef META_IGUNSIGNEDLONGLIST_H
#define META_IGUNSIGNEDLONGLIST_H
#include <meta/igDataList.h>
namespace Meta {
struct igUnsignedLongList : igDataList {
};
}
#endif
