// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8014B044 (metaobject lbl_805642F8, vtable lbl_804A6C54), size 0x28.
#ifndef META_IGUPDATEDFIELDEVENT_H
#define META_IGUPDATEDFIELDEVENT_H
#include <meta/igObjectChangedEvent.h>
namespace Meta {
struct igMetaField;
struct igUpdatedFieldEvent : igObjectChangedEvent {
 igMetaField *_field;  // 0x24 igObjectRefMetaField
};
}
#endif
