// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801AA950 (metaobject lbl_80564660), size 0x24.
#ifndef META_IGUSERINFO_H
#define META_IGUSERINFO_H
#include <meta/igGroup.h>
namespace Meta {
struct igPropertyList;
struct igUserInfo : igGroup {
 igPropertyList *_propertyList;  // 0x20 igObjectRefMetaField
};
}
#endif
