// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igVertexStream_register (metaobject lbl_80562D9C, vtable lbl_804922CC), size 0x24.
#ifndef META_IGVERTEXSTREAM_H
#define META_IGVERTEXSTREAM_H
#include <meta/igNamedObject.h>
#include <meta/enums.h>
namespace Meta {
struct igVertexDataList;
struct igVertexStream : igNamedObject {
 void *_stream;  // 0x0C igRawRefMetaField
 bool _isConfigured;  // 0x10 igBoolMetaField
 unsigned char unknown11[3];
 igVertexDataList *_vertexDataList;  // 0x14 igObjectRefMetaField
 IG_VERTEX_ACCESS_MODE::Value _accessMode;  // 0x18 igEnumMetaField
 IG_GFX_DRAW::Value _primitive;  // 0x1C igEnumMetaField
 IG_VERTEX_STREAM_COMPILE_MODE::Value _streamMode;  // 0x20 igEnumMetaField
};
}
#endif
