// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8011DD34 (metaobject lbl_805638D0, vtable lbl_8049BA94), size 0x8.
#ifndef META_IGVECTORMORPHING_H
#define META_IGVECTORMORPHING_H
#include <meta/igObject.h>
namespace Meta {
struct igVectorMorphing : igObject {
};
}
#endif
