// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80122438 (metaobject lbl_80563A20, vtable lbl_8049A5D8), size 0x14.
#ifndef META_IGVEC2FLIST_H
#define META_IGVEC2FLIST_H
#include <meta/igDataList.h>
namespace Meta {
struct igVec2fList : igDataList {
};
}
#endif
