// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igVertexBlendMatrixAttrList_register (metaobject lbl_8056249C, vtable lbl_8047E380), size 0x14.
#ifndef META_IGVERTEXBLENDMATRIXATTRLIST_H
#define META_IGVERTEXBLENDMATRIXATTRLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igVertexBlendMatrixAttrList : igObjectList {
};
}
#endif
