// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801221F8 (metaobject lbl_80563A14, vtable lbl_8047DF98), size 0x14.
#ifndef META_IGVEC3FLIST_H
#define META_IGVEC3FLIST_H
#include <meta/igDataList.h>
namespace Meta {
struct igVec3fList : igDataList {
};
}
#endif
