// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igVertexShaderBindAttr_register (metaobject lbl_80562430, vtable lbl_8047A704), size 0x10.
#ifndef META_IGVERTEXSHADERBINDATTR_H
#define META_IGVERTEXSHADERBINDATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igVertexShaderAttr;
struct igVertexShaderBindAttr : igVisualAttribute {
 igVertexShaderAttr *_vertexShader;  // 0x0C igObjectRefMetaField
};
}
#endif
