// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800CFC68 (metaobject lbl_80562DDC), size 0x30.
// Note: _vertexFormat: igStructMetaField, count from the space to the next member.
#ifndef META_IGVERTEXARRAY1_1_H
#define META_IGVERTEXARRAY1_1_H
#include <meta/igVertexArray.h>
namespace Meta {
struct igMemoryPool;
struct igVertexArray1_1 : igVertexArray {
 igMemoryPool *_memPool;  // 0x18 igObjectRefMetaField
 unsigned char _vertexFormat[4];  // 0x1C igStructMetaField
 void *_blendWeights;  // 0x20 igMemoryRefMetaField
 void *_blendIndices;  // 0x24 igMemoryRefMetaField
 unsigned int _blendIndex;  // 0x28 igUnsignedIntMetaField
 void *_pointSpriteSize;  // 0x2C igMemoryRefMetaField
};
}
#endif
