// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igVec4fMetaField_register (metaobject lbl_805638E8, vtable lbl_80499204), size 0x34.
#ifndef META_IGVEC4FMETAFIELD_H
#define META_IGVEC4FMETAFIELD_H
#include <meta/igMetaField.h>
namespace Meta {
struct igVec4fMetaField : igMetaField {
};
}
#endif
