// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800ACBEC (metaobject lbl_8056246C, vtable lbl_8047A804), size 0x10.
#ifndef META_IGVERTEXPIPELINEMODEATTR_H
#define META_IGVERTEXPIPELINEMODEATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igVertexPipelineModeAttr : igVisualAttribute {
 int _mode;  // 0x0C igEnumMetaField
};
}
#endif
