// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801B238C (metaobject lbl_80564948, vtable lbl_804B8D78), size 0x20.
#ifndef META_IGVERTEXBLENDMATRIXLISTATTRPOOL_H
#define META_IGVERTEXBLENDMATRIXLISTATTRPOOL_H
#include <meta/igObjectPool.h>
namespace Meta {
struct igVertexBlendMatrixListAttrPool : igObjectPool {
};
}
#endif
