// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igVec3dMetaField_register (metaobject lbl_8056392C, vtable lbl_804999A4), size 0x34.
#ifndef META_IGVEC3DMETAFIELD_H
#define META_IGVEC3DMETAFIELD_H
#include <meta/igMetaField.h>
namespace Meta {
struct igVec3dMetaField : igMetaField {
};
}
#endif
