// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8011E530 (metaobject lbl_805638F0, vtable lbl_804992F8), size 0x38.
#ifndef META_IGVEC4FARRAYMETAFIELD_H
#define META_IGVEC4FARRAYMETAFIELD_H
#include <meta/igVec4fMetaField.h>
namespace Meta {
struct igVec4fArrayMetaField : igVec4fMetaField {
 int _num;  // 0x34 igIntMetaField
};
}
#endif
