// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800AD014 (metaobject lbl_8056247C, vtable lbl_8047A908), size 0x9C.
#ifndef META_IGVERTEXBLENDMATRIXLISTATTR_H
#define META_IGVERTEXBLENDMATRIXLISTATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igMatrixObjectList;
struct igVertexBlendMatrixListAttr : igVisualAttribute {
 bool _isSkeletonTransformIdentity;  // 0x0C igBoolMetaField
 bool _isSkeletonTransformSet;  // 0x0D igBoolMetaField
 unsigned char unknown0E[2];
 void *_matrixCache;  // 0x10 igRawRefMetaField
 int _currentMatrixCount;  // 0x14 igIntMetaField
 igMatrixObjectList *_matrixList;  // 0x18 igObjectRefMetaField
 float _skeletonTransform[16];  // 0x1C igMatrix44fMetaField
 float _skeletonInverseTransform[16];  // 0x5C igMatrix44fMetaField
};
}
#endif
