// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igVector3MorphData_register (metaobject lbl_80562734, vtable lbl_8047BC70), size 0x2C.
#ifndef META_IGVECTOR3MORPHDATA_H
#define META_IGVECTOR3MORPHDATA_H
#include <meta/igMorphData.h>
#include <meta/enums.h>
namespace Meta {
struct igFloatList;
struct igPointerList;
struct igVec3fAlignedList;
struct igVec3fListList;
struct igVector3MorphData : igMorphData {
 igVec3fAlignedList *_base;  // 0x08 igObjectRefMetaField
 igVec3fListList *_targets;  // 0x0C igObjectRefMetaField
 int _targetCount;  // 0x10 igIntMetaField
 int _vertexCount;  // 0x14 igIntMetaField
 igPointerList *_activeTargets;  // 0x18 igObjectRefMetaField
 igFloatList *_activeCoeff;  // 0x1C igObjectRefMetaField
 int _activeCount;  // 0x20 igIntMetaField
 IG_GFX_VERTEX_COMPONENT::Value _component;  // 0x24 igEnumMetaField
 bool _dirty;  // 0x28 igBoolMetaField
 unsigned char unknown29[3];
};
}
#endif
