// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igVec4fList_register (metaobject lbl_80563A00, vtable lbl_8049A9A8), size 0x14.
#ifndef META_IGVEC4FLIST_H
#define META_IGVEC4FLIST_H
#include <meta/igDataList.h>
namespace Meta {
struct igVec4fList : igDataList {
};
}
#endif
