// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igVertexArrayList_register (metaobject lbl_80562DF8, vtable lbl_80493F64), size 0x14.
#ifndef META_IGVERTEXARRAYLIST_H
#define META_IGVERTEXARRAYLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igVertexArrayList : igObjectList {
};
}
#endif
