// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igVertexArrayHelper_register (metaobject lbl_8056465C, vtable lbl_804B31B0), size 0x8.
#ifndef META_IGVERTEXARRAYHELPER_H
#define META_IGVERTEXARRAYHELPER_H
#include <meta/igObject.h>
namespace Meta {
struct igVertexArrayHelper : igObject {
};
}
#endif
