// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igVec3fListList_register (metaobject lbl_80563A08, vtable lbl_8049A8E0), size 0x14.
#ifndef META_IGVEC3FLISTLIST_H
#define META_IGVEC3FLISTLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igVec3fListList : igObjectList {
};
}
#endif
