// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8011F394 (metaobject lbl_8056394C, vtable lbl_80499D74), size 0x34.
#ifndef META_IGVEC2DMETAFIELD_H
#define META_IGVEC2DMETAFIELD_H
#include <meta/igMetaField.h>
namespace Meta {
struct igVec2dMetaField : igMetaField {
};
}
#endif
