// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800AD678 (metaobject lbl_805624AC, vtable lbl_8047AA0C), size 0x20.
#ifndef META_IGVECTORCONSTANTATTR_H
#define META_IGVECTORCONSTANTATTR_H
#include <meta/igCustomStateCollectionAttr.h>
namespace Meta {
struct igVectorConstantAttr : igCustomStateCollectionAttr {
 float _value[4];  // 0x0C igVec4fMetaField
 int _unitID;  // 0x1C igIntMetaField
};
}
#endif
