// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igVertexArray2Helper_register (metaobject lbl_80562D78, vtable lbl_804921D4), size 0x10.
#ifndef META_IGVERTEXARRAY2HELPER_H
#define META_IGVERTEXARRAY2HELPER_H
#include <meta/igNamedObject.h>
namespace Meta {
struct igVertexArray2;
struct igVertexArray2Helper : igNamedObject {
 igVertexArray2 *_vertexArray;  // 0x0C igObjectRefMetaField
};
}
#endif
