// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800CF0E4 (metaobject lbl_80562D84, vtable lbl_8049233C), size 0x18.
#ifndef META_IGVERTEXARRAY2_H
#define META_IGVERTEXARRAY2_H
#include <meta/igNamedObject.h>
namespace Meta {
struct igObjectList;
struct igVertexStream;
struct igVertexArray2 : igNamedObject {
 void *_internalBuffer;  // 0x0C igObjectRefMetaField
 igObjectList *_objList;  // 0x10 igObjectRefMetaField
 igVertexStream *_vertexStream;  // 0x14 igObjectRefMetaField
};
}
#endif
