// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igVectorBlending_register (metaobject lbl_805638D4, vtable lbl_8049BA38), size 0x8.
#ifndef META_IGVECTORBLENDING_H
#define META_IGVECTORBLENDING_H
#include <meta/igObject.h>
namespace Meta {
struct igVectorBlending : igObject {
};
}
#endif
