// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igVisualContext_register (metaobject lbl_80562D00), size 0x140.
// Note: _vertexArray2: igObjectRefArrayMetaField, count from the space to the next member.
#ifndef META_IGVISUALCONTEXT_H
#define META_IGVISUALCONTEXT_H
#include <meta/igContext.h>
#include <meta/enums.h>
namespace Meta {
struct igCustomStateCollectionList;
struct igCustomStateFieldList;
struct igMemoryPool;
struct igTimer;
struct igVisualContext : igContext {
 int _contextIndex;  // 0x14 igIntMetaField
 igMemoryPool *_driverDataMemoryPool;  // 0x18 igObjectRefMetaField
 igMemoryPool *_vertexMemoryPool;  // 0x1C igObjectRefMetaField
 igMemoryPool *_internalMemoryPool;  // 0x20 igObjectRefMetaField
 igMemoryPool *_temporaryMemoryPool;  // 0x24 igObjectRefMetaField
 igMemoryPool *_imageMemoryPool;  // 0x28 igObjectRefMetaField
 igMemoryPool *_textureMemoryPool;  // 0x2C igObjectRefMetaField
 igMemoryPool *_statisticsMemoryPool;  // 0x30 igObjectRefMetaField
 igMemoryPool *_listMemoryPool;  // 0x34 igObjectRefMetaField
 igTimer *_timer;  // 0x38 igObjectRefMetaField
 bool _showFrameRate;  // 0x3C igBoolMetaField
 bool _commandLineFrameRate;  // 0x3D igBoolMetaField
 unsigned char unknown3E[2];
 int _primitiveCount;  // 0x40 igIntMetaField
 float _frameStartTime;  // 0x44 igFloatMetaField
 int _blendMatricesCount;  // 0x48 igIntMetaField
 unsigned int _blendIndex;  // 0x4C igUnsignedIntMetaField
 void *_inverseTranspose;  // 0x50 igMemoryRefMetaField
 void *_blendMatrices;  // 0x54 igRawRefMetaField
 unsigned int _inverseTransposeCount;  // 0x58 igUnsignedIntMetaField
 unsigned char unknown5C[4];
 long long _renderingTime;  // 0x60 igLongMetaField
 IG_GFX_SCISSOR_TYPE::Value _scissorType;  // 0x68 igEnumMetaField
 float _viewMatrixHint[16];  // 0x6C igMatrix44fMetaField
 float _viewMatrixInverse[16];  // 0xAC igMatrix44fMetaField
 bool _viewMatrixDirty;  // 0xEC igBoolMetaField
 unsigned char unknownED[3];
 void * _vertexArray2[16];  // 0xF0 igObjectRefArrayMetaField
 igCustomStateCollectionList *_customStates;  // 0x130 igObjectRefMetaField
 igCustomStateFieldList *_customFields;  // 0x134 igObjectRefMetaField
 bool _ditherState;  // 0x138 igBoolMetaField
 unsigned char unknown139[7];
};
}
#endif
