// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igViewModel_register (metaobject lbl_8055CA78, vtable lbl_804F1174), size 0xB0.
#ifndef META_IGVIEWMODEL_H
#define META_IGVIEWMODEL_H
#include <meta/igModel.h>
namespace Meta {
struct igViewModel : igModel {
 float _viewMatrix[16];  // 0x0C igMatrix44fMetaField
 float _ratio;  // 0x4C igFloatMetaField
 float _hfov;  // 0x50 igFloatMetaField
 float _nearPlane;  // 0x54 igFloatMetaField
 float _farPlane;  // 0x58 igFloatMetaField
 float _position[3];  // 0x5C igVec3fMetaField
 float _direction[3];  // 0x68 igVec3fMetaField
 float _viewUpVector[3];  // 0x74 igVec3fMetaField
 float _viewLeftVector[3];  // 0x80 igVec3fMetaField
 float _sceneUpVector[3];  // 0x8C igVec3fMetaField
 long long _drawTime;  // 0x98 igLongMetaField
 float _selectedCenter[3];  // 0xA0 igVec3fMetaField
 float _selectedLength;  // 0xAC igFloatMetaField
};
}
#endif
