// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igViewerAction_register (metaobject lbl_8055C778, vtable lbl_804F1AE0), size 0x18.
// Note: _function: igStructMetaField, count from the space to the next member.
#ifndef META_IGVIEWERACTION_H
#define META_IGVIEWERACTION_H
#include <meta/igAction.h>
namespace Meta {
struct igViewerSceneInfoManager;
struct igViewerAction : igAction {
 igViewerSceneInfoManager *_ref;  // 0x08 igObjectRefMetaField
 unsigned char _function[12];  // 0x0C igStructMetaField
};
}
#endif
