// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_800AC200 (metaobject lbl_80562410, vtable lbl_8047A680), size 0x28.
#ifndef META_IGVIEWPORTATTR_H
#define META_IGVIEWPORTATTR_H
#include <meta/igVisualAttribute.h>
namespace Meta {
struct igScissorExt;
struct igViewportAttr : igVisualAttribute {
 int _x;  // 0x0C igIntMetaField
 int _y;  // 0x10 igIntMetaField
 int _w;  // 0x14 igIntMetaField
 int _h;  // 0x18 igIntMetaField
 igScissorExt *_scissorExt;  // 0x1C igObjectRefMetaField
 float _nearZ;  // 0x20 igFloatMetaField
 float _farZ;  // 0x24 igFloatMetaField
};
}
#endif
