// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igVisualContextCapabilityManager_register (metaobject lbl_80562CF4, vtable lbl_80491D28), size 0xC.
#ifndef META_IGVISUALCONTEXTCAPABILITYMANAGER_H
#define META_IGVISUALCONTEXTCAPABILITYMANAGER_H
#include <meta/igCapabilityManager.h>
namespace Meta {
struct igVisualContext;
struct igVisualContextCapabilityManager : igCapabilityManager {
 igVisualContext *_visualContext;  // 0x08 igObjectRefMetaField
};
}
#endif
