// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igViewerStatisticsManager_register (metaobject lbl_8055C700, vtable lbl_804F1C80), size 0x48.
#ifndef META_IGVIEWERSTATISTICSMANAGER_H
#define META_IGVIEWERSTATISTICSMANAGER_H
#include <meta/igObject.h>
namespace Meta {
struct igBoxComponent;
struct igMetaFieldList;
struct igMetaObjectList;
struct igStatisticsItemList;
struct igStringObj;
struct igViewerGuiFactory;
struct igVisualContext;
struct igViewerStatisticsManager : igObject {
 igStatisticsItemList *_items;  // 0x08 igObjectRefMetaField
 igVisualContext *_visualContext;  // 0x0C igObjectRefMetaField
 igViewerGuiFactory *_guiFactory;  // 0x10 igObjectRefMetaField
 igBoxComponent *_menu;  // 0x14 igObjectRefMetaField
 igBoxComponent *_boxComponent;  // 0x18 igObjectRefMetaField
 igStringObj *_string;  // 0x1C igObjectRefMetaField
 bool _recordStatisticMaximum;  // 0x20 igBoolMetaField
 unsigned char unknown21[3];
 igMetaObjectList *_attrMetaObjects;  // 0x24 igObjectRefMetaField
 igMetaFieldList *_extraSgStatistics;  // 0x28 igObjectRefMetaField
 float _attrCount;  // 0x2C igFloatMetaField
 float _displayListAttrCount;  // 0x30 igFloatMetaField
 float _textureAttrCount;  // 0x34 igFloatMetaField
 float _geometryAttrCount;  // 0x38 igFloatMetaField
 float _geometrySetAttrCount;  // 0x3C igFloatMetaField
 float _mvmAttrCount;  // 0x40 igFloatMetaField
 unsigned char unknown44[4];
};
}
#endif
