// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igViewerDataPumpManager_register (metaobject lbl_8055C998, vtable lbl_804F18F0), size 0x14.
#ifndef META_IGVIEWERDATAPUMPMANAGER_H
#define META_IGVIEWERDATAPUMPMANAGER_H
#include <meta/igInfoManager.h>
namespace Meta {
struct igDataPumpManager;
struct igViewerDataPumpManager : igInfoManager {
 igDataPumpManager *_dataPumpManager;  // 0x10 igObjectRefMetaField
};
}
#endif
