// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igViewerSceneInfoManager_register (metaobject lbl_8055C788), size 0xC8.
#ifndef META_IGVIEWERSCENEINFOMANAGER_H
#define META_IGVIEWERSCENEINFOMANAGER_H
#include <meta/igInfoManager.h>
namespace Meta {
struct igBoundingBoxRenderer;
struct igBoxComponent;
struct igFlushRenderer;
struct igGuiComponent;
struct igGuiComponentList;
struct igGuiSystem;
struct igHotKeyEventReceiver;
struct igNormalsRenderer;
struct igObjectList;
struct igRadioGroup;
struct igStatisticsItem;
struct igTextureList;
struct igViewManager;
struct igViewerGuiFactory;
struct igViewerModeChangeMessage;
struct igViewerParameters;
struct igViewerRenderer;
struct igViewerSceneInfoManagerController;
struct igViewerStatisticsManager;
struct igViewerSceneInfoManager : igInfoManager {
 igViewerSceneInfoManagerController *_applicationController;  // 0x10 igObjectRefMetaField
 igViewerParameters *_parameters;  // 0x14 igObjectRefMetaField
 igViewerRenderer *_viewerRenderer;  // 0x18 igObjectRefMetaField
 igBoundingBoxRenderer *_bboxRenderer;  // 0x1C igObjectRefMetaField
 igNormalsRenderer *_normalsRenderer;  // 0x20 igObjectRefMetaField
 igFlushRenderer *_flushRenderer;  // 0x24 igObjectRefMetaField
 int _clippingCheckFrame;  // 0x28 igIntMetaField
 igGuiSystem *_gui;  // 0x2C igObjectRefMetaField
 igViewerGuiFactory *_guiFactory;  // 0x30 igObjectRefMetaField
 igBoxComponent *_rootComponent;  // 0x34 igObjectRefMetaField
 igGuiComponent *_menuHolder;  // 0x38 igObjectRefMetaField
 igGuiComponent *_operationBoxHolder;  // 0x3C igObjectRefMetaField
 igBoxComponent *_operationBox;  // 0x40 igObjectRefMetaField
 igGuiComponent *_timeBoxHolder;  // 0x44 igObjectRefMetaField
 igBoxComponent *_timeBox;  // 0x48 igObjectRefMetaField
 igBoxComponent *_menuBar;  // 0x4C igObjectRefMetaField
 igBoxComponent *_viewMenu;  // 0x50 igObjectRefMetaField
 igBoxComponent *_viewportMenu;  // 0x54 igObjectRefMetaField
 igBoxComponent *_cameraMenu;  // 0x58 igObjectRefMetaField
 igGuiComponent *_cameraMenuActiver;  // 0x5C igObjectRefMetaField
 igBoxComponent *_optionMenu;  // 0x60 igObjectRefMetaField
 igBoxComponent *_disableMenu;  // 0x64 igObjectRefMetaField
 igBoxComponent *_statMenu;  // 0x68 igObjectRefMetaField
 igBoxComponent *_timeMenu;  // 0x6C igObjectRefMetaField
 igBoxComponent *_alchemyMenu;  // 0x70 igObjectRefMetaField
 igStatisticsItem *_timeStatistic;  // 0x74 igObjectRefMetaField
 igStatisticsItem *_speedStatistic;  // 0x78 igObjectRefMetaField
 igStatisticsItem *_nearPlaneStatistic;  // 0x7C igObjectRefMetaField
 igStatisticsItem *_farPlaneStatistic;  // 0x80 igObjectRefMetaField
 igHotKeyEventReceiver *_hotKeyReceiver;  // 0x84 igObjectRefMetaField
 igViewManager *_viewManager;  // 0x88 igObjectRefMetaField
 igViewerStatisticsManager *_statManager;  // 0x8C igObjectRefMetaField
 igGuiComponentList *_disableComponents;  // 0x90 igObjectRefMetaField
 igObjectList *_disableViews;  // 0x94 igObjectRefMetaField
 igRadioGroup *_operationModeGroup;  // 0x98 igObjectRefMetaField
 igObjectList *_references;  // 0x9C igObjectRefMetaField
 int _frames;  // 0xA0 igIntMetaField
 unsigned char unknownA4[4];
 long long _lastStatTime;  // 0xA8 igLongMetaField
 int _guiVisibility;  // 0xB0 igEnumMetaField
 igTextureList *_textureList;  // 0xB4 igObjectRefMetaField
 igViewerModeChangeMessage *_modeChange;  // 0xB8 igObjectRefMetaField
 bool _isCapturingBudget;  // 0xBC igBoolMetaField
 unsigned char unknownBD[3];
 igGuiComponent *_hideAllStatisticsMenuItem;  // 0xC0 igObjectRefMetaField
 unsigned char unknownC4[4];
};
}
#endif
