// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igVolume_register (metaobject lbl_805638C8), size 0x8.
#ifndef META_IGVOLUME_H
#define META_IGVOLUME_H
#include <meta/igObject.h>
namespace Meta {
struct igVolume : igObject {
};
}
#endif
