// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_8011DC04 (metaobject lbl_805638CC, vtable lbl_8049BAF0), size 0x14.
#ifndef META_IGVOLUMELIST_H
#define META_IGVOLUMELIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igVolumeList : igObjectList {
};
}
#endif
