// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80110C30 (metaobject lbl_805636DC, vtable lbl_8049634C), size 0xC.
#ifndef META_IGWINDOWSIZEOBSERVER_H
#define META_IGWINDOWSIZEOBSERVER_H
#include <meta/igView.h>
namespace Meta {
struct igWindowSizeObserver : igView {
};
}
#endif
