// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igWindow_register (metaobject lbl_80562B74), size 0x8.
#ifndef META_IGWINDOW_H
#define META_IGWINDOW_H
#include <meta/igEventProducer.h>
namespace Meta {
struct igWindow : igEventProducer {
};
}
#endif
