// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igZFilterWeightListList_register (metaobject lbl_80564274, vtable lbl_804A9284), size 0x14.
#ifndef META_IGZFILTERWEIGHTLISTLIST_H
#define META_IGZFILTERWEIGHTLISTLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igZFilterWeightListList : igObjectList {
};
}
#endif
