// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_80149288 (metaobject lbl_80564280, vtable lbl_804A9160), size 0x18.
#ifndef META_IGZFILTERWEIGHT_H
#define META_IGZFILTERWEIGHT_H
#include <meta/igObject.h>
namespace Meta {
struct igZFilterWeight : igObject {
 int _pixel;  // 0x08 igIntMetaField
 unsigned char unknown0C[4];
 double _weight;  // 0x10 igDoubleMetaField
};
}
#endif
