// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_801490B0 (metaobject lbl_80564278, vtable lbl_804A91BC), size 0x18.
#ifndef META_IGZFILTERWEIGHTLIST_H
#define META_IGZFILTERWEIGHTLIST_H
#include <meta/igObjectList.h>
namespace Meta {
struct igZFilterWeightList : igObjectList {
 int _n;  // 0x14 igIntMetaField
};
}
#endif
