// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by igZoomImage_register (metaobject lbl_80564294, vtable lbl_804A903C), size 0x14.
#ifndef META_IGZOOMIMAGE_H
#define META_IGZOOMIMAGE_H
#include <meta/igFilterImage.h>
namespace Meta {
struct igZoomImage : igFilterImage {
};
}
#endif
