// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by libBecRuntimePlugin_register (metaobject lbl_80534498), size 0xA4.
#ifndef META_LIBBECRUNTIMEPLUGIN_H
#define META_LIBBECRUNTIMEPLUGIN_H
#include <meta/igInsightPlugin.h>
namespace Meta {
struct be;
struct beAction2;
struct beActionStarter;
struct beBkColor;
struct beCameraCtrl;
struct beChangePosTransform;
struct beCri;
struct beDBManager;
struct beDemoManager;
struct beFileListInfoManager;
struct beFont;
struct beGenerater;
struct beHitLandDeliv;
struct beHitLandModel;
struct beLayerCtl;
struct beLightCtrl;
struct beLua;
struct beMatCtrl;
struct beMemory;
struct beMessenger;
struct beMeterCtrl;
struct beMovie;
struct beNumberCtrl;
struct bePadManager;
struct beParticleCtrl2;
struct bePoint01;
struct beSaveUtil;
struct beSeCtl;
struct beSelectCtrl;
struct beShadow01;
struct beSound;
struct beStaticInfoCtl;
struct beSwitchCtrl;
struct beSystem;
struct beTargetObj;
struct beTextureCtrl;
struct beTimer;
struct beWaterPlain;
struct beWeapon;
struct libBecRuntimePlugin : igInsightPlugin {
 beParticleCtrl2 *_particleCtrl2;  // 0x08 igObjectRefMetaField
 beLua *_luaManager;  // 0x0C igObjectRefMetaField
 beMatCtrl *_matCtrl;  // 0x10 igObjectRefMetaField
 beSelectCtrl *_selectCtrl;  // 0x14 igObjectRefMetaField
 beWaterPlain *_waterPlain;  // 0x18 igObjectRefMetaField
 beAction2 *_action2;  // 0x1C igObjectRefMetaField
 beMeterCtrl *_meterCtrl;  // 0x20 igObjectRefMetaField
 beTargetObj *_targetObj;  // 0x24 igObjectRefMetaField
 beWeapon *_weapon;  // 0x28 igObjectRefMetaField
 beCameraCtrl *_cameraCtrl;  // 0x2C igObjectRefMetaField
 bePoint01 *_point01;  // 0x30 igObjectRefMetaField
 beBkColor *_bkColor;  // 0x34 igObjectRefMetaField
 beChangePosTransform *_cpTransform;  // 0x38 igObjectRefMetaField
 beShadow01 *_shadow01;  // 0x3C igObjectRefMetaField
 beGenerater *_generater;  // 0x40 igObjectRefMetaField
 beHitLandModel *_hitLandModel;  // 0x44 igObjectRefMetaField
 beHitLandDeliv *_hitLandDeliv;  // 0x48 igObjectRefMetaField
 beSound *_sound;  // 0x4C igObjectRefMetaField
 beSeCtl *_seCtl;  // 0x50 igObjectRefMetaField
 beActionStarter *_actionStarter;  // 0x54 igObjectRefMetaField
 beLayerCtl *_layerCtl;  // 0x58 igObjectRefMetaField
 beFont *_font;  // 0x5C igObjectRefMetaField
 beSwitchCtrl *_switchCtrl;  // 0x60 igObjectRefMetaField
 beLightCtrl *_lightCtrl;  // 0x64 igObjectRefMetaField
 beNumberCtrl *_numberCtrl;  // 0x68 igObjectRefMetaField
 beStaticInfoCtl *_staticInfoCtl;  // 0x6C igObjectRefMetaField
 beMovie *_movie;  // 0x70 igObjectRefMetaField
 beDBManager *_dbManager;  // 0x74 igObjectRefMetaField
 beSaveUtil *_saveUtil;  // 0x78 igObjectRefMetaField
 beTextureCtrl *_textureCtrl;  // 0x7C igObjectRefMetaField
 beSystem *_system;  // 0x80 igObjectRefMetaField
 beMessenger *_messenger;  // 0x84 igObjectRefMetaField
 beFileListInfoManager *_fileList;  // 0x88 igObjectRefMetaField
 bePadManager *_padManager;  // 0x8C igObjectRefMetaField
 beCri *_cri;  // 0x90 igObjectRefMetaField
 be *_luaInterface;  // 0x94 igObjectRefMetaField
 beDemoManager *_demoManager;  // 0x98 igObjectRefMetaField
 beTimer *_timer;  // 0x9C igObjectRefMetaField
 beMemory *_memory;  // 0xA0 igObjectRefMetaField
};
}
#endif
