// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by libNdmwRuntimePlugin_register (metaobject lbl_80535C20, vtable lbl_804E6DB0), size 0x5C.
#ifndef META_LIBNDMWRUNTIMEPLUGIN_H
#define META_LIBNDMWRUNTIMEPLUGIN_H
#include <meta/igInsightPlugin.h>
namespace Meta {
struct beNDMWAfsSetup;
struct beNDMWGameRam;
struct beNDMWLoadCtrl2;
struct beNDMWLoadIntf2;
struct beNDMWLogo;
struct beNDMWMdlEBullet;
struct beNDMWMdlEffect;
struct beNDMWMdlEnemy;
struct beNDMWMdlItem;
struct beNDMWMdlMapBase;
struct beNDMWMdlMapCursor;
struct beNDMWMdlObject;
struct beNDMWMdlPBullet;
struct beNDMWMdlPlayer;
struct beNDMWMdlPlayer2;
struct beNDMWPanelWaza;
struct beNDMWSaveCtrl;
struct beNDMWSaveIntf;
struct beNDMWStageCtl;
struct beNDMWStatus;
struct beNDMWTitle2;
struct libNdmwRuntimePlugin : igInsightPlugin {
 beNDMWAfsSetup *_afsSetup;  // 0x08 igObjectRefMetaField
 beNDMWStageCtl *_stageCtl;  // 0x0C igObjectRefMetaField
 beNDMWPanelWaza *_panelWaza;  // 0x10 igObjectRefMetaField
 beNDMWLogo *_logo;  // 0x14 igObjectRefMetaField
 beNDMWTitle2 *_title2;  // 0x18 igObjectRefMetaField
 beNDMWLoadCtrl2 *_loadCtrl2;  // 0x1C igObjectRefMetaField
 beNDMWLoadIntf2 *_loadIntf2;  // 0x20 igObjectRefMetaField
 beNDMWSaveCtrl *_saveCtrl;  // 0x24 igObjectRefMetaField
 beNDMWSaveIntf *_saveIntf;  // 0x28 igObjectRefMetaField
 beNDMWGameRam *_gameRam;  // 0x2C igObjectRefMetaField
 beNDMWStatus *_status;  // 0x30 igObjectRefMetaField
 beNDMWMdlPlayer *_mdlPlayer;  // 0x34 igObjectRefMetaField
 beNDMWMdlPlayer2 *_mdlPlayer2;  // 0x38 igObjectRefMetaField
 beNDMWMdlPBullet *_mdlPBullet;  // 0x3C igObjectRefMetaField
 beNDMWMdlEnemy *_mdlEnemy;  // 0x40 igObjectRefMetaField
 beNDMWMdlEBullet *_mdlEBullet;  // 0x44 igObjectRefMetaField
 beNDMWMdlObject *_mdlObject;  // 0x48 igObjectRefMetaField
 beNDMWMdlItem *_mdlItem;  // 0x4C igObjectRefMetaField
 beNDMWMdlEffect *_mdlEffect;  // 0x50 igObjectRefMetaField
 beNDMWMdlMapBase *_mdlMapBase;  // 0x54 igObjectRefMetaField
 beNDMWMdlMapCursor *_mdlMapCursor;  // 0x58 igObjectRefMetaField
};
}
#endif
