// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by ParticleInfo_register (metaobject lbl_80535888, vtable lbl_804D351C), size 0x400.
// Note: _points: igFloatArrayMetaField, count from the space to the next member.
// Note: _numControls: igIntArrayMetaField, count from the space to the next member.
#ifndef META_PARTICLEINFO_H
#define META_PARTICLEINFO_H
#include <meta/igSceneInfo.h>
#include <meta/enums.h>
namespace Meta {
struct igGeometry;
struct igImage;
struct ParticleInfo : igSceneInfo {
 float _points[192];  // 0x40 igFloatArrayMetaField
 int _numControls[32];  // 0x340 igIntArrayMetaField
 float _lifetime;  // 0x3C0 igFloatMetaField
 int _count;  // 0x3C4 igIntMetaField
 igImage *_texture;  // 0x3C8 igObjectRefMetaField
 IG_PARTICLE_ALPHA_TYPE::Value _alphaType;  // 0x3CC igEnumMetaField
 IG_PARTICLE_ALPHA_FUNCTION::Value _alphaFunction;  // 0x3D0 igEnumMetaField
 bool _sizeLock;  // 0x3D4 igBoolMetaField
 bool _sizeWorld;  // 0x3D5 igBoolMetaField
 unsigned char unknown3D6[2];
 IG_PARTICLE_TIME_TYPE::Value _timeType;  // 0x3D8 igEnumMetaField
 bool _particleScene;  // 0x3DC igBoolMetaField
 unsigned char unknown3DD[3];
 IG_PARTICLE_EMITTER_TYPE::Value _shape;  // 0x3E0 igEnumMetaField
 bool _maximize;  // 0x3E4 igBoolMetaField
 unsigned char unknown3E5[3];
 int _xImageCount;  // 0x3E8 igIntMetaField
 int _yImageCount;  // 0x3EC igIntMetaField
 bool _resizeCurves;  // 0x3F0 igBoolMetaField
 unsigned char unknown3F1[3];
 float _startOffset;  // 0x3F4 igFloatMetaField
 igGeometry *_geometry;  // 0x3F8 igObjectRefMetaField
 unsigned char unknown3FC[4];
};
}
#endif
