// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by fn_802E8004 (metaobject lbl_80535868, vtable lbl_804E0044), size 0x40.
#ifndef META_PARTICLETIMER_H
#define META_PARTICLETIMER_H
#include <meta/igGeometry.h>
namespace Meta {
struct ParticleTimer : igGeometry {
 bool _timeRunning;  // 0x2C igBoolMetaField
 unsigned char unknown2D[3];
 long long _timeBias;  // 0x30 igLongMetaField
 long long _time;  // 0x38 igLongMetaField
};
}
#endif
