// Generated by tools/alchemymeta/headers.py from the class registration in the original DOL; do not edit.
// Registered by ParticleArray_register (metaobject lbl_80535838, vtable lbl_804DFEB0), size 0x7C.
#ifndef META_PARTICLEARRAY_H
#define META_PARTICLEARRAY_H
#include <meta/igParticleArray.h>
namespace Meta {
struct igVertexArray;
struct ParticleArray : igParticleArray {
 float _xImageCount;  // 0x5C igFloatMetaField
 float _yImageCount;  // 0x60 igFloatMetaField
 bool _loopTime;  // 0x64 igBoolMetaField
 bool _continuousTime;  // 0x65 igBoolMetaField
 unsigned char unknown66[2];
 float _startOffset;  // 0x68 igFloatMetaField
 bool _hasTextureCoordinates;  // 0x6C igBoolMetaField
 unsigned char unknown6D[3];
 igVertexArray *_vertexArray1;  // 0x70 igObjectRefMetaField
 igVertexArray *_vertexArray2;  // 0x74 igObjectRefMetaField
 bool _whichVertexArray;  // 0x78 igBoolMetaField
 bool _setConstant1;  // 0x79 igBoolMetaField
 bool _setConstant2;  // 0x7A igBoolMetaField
 unsigned char unknown7B[1];
};
}
#endif
