#include <unknownGen.h>
#pragma push
#pragma auto_inline off
extern "C" {
extern void *kSuccess__3Gap;
}
class UnknownGenV8004F2DC_0 {
public:
 virtual void s08();
 virtual void s0C();
 virtual void s10();
 virtual void s14();
 virtual void s18();
 virtual void s1C();
 virtual void s20();
 virtual void s24();
 virtual void s28();
 virtual void s2C();
 virtual void s30();
 virtual void s34();
 virtual void s38();
 virtual void s3C();
 virtual void s40();
 virtual void s44();
 virtual void s48();
 virtual void s4C();
 virtual void s50();
 virtual void s54();
 virtual void s58();
 virtual void s5C();
 virtual void s60();
 virtual void s64();
 virtual void s68();
 virtual void s6C();
 virtual void s70();
 virtual void s74();
 virtual void s78();
 virtual void s7C();
 virtual void s80();
 virtual void s84();
 virtual void s88();
 virtual void s8C();
 virtual void s90();
 virtual void s94();
 virtual void s98();
 virtual void s9C();
 virtual void sA0();
 virtual void sA4();
 virtual void sA8();
 virtual void sAC();
 virtual void sB0();
 virtual void sB4();
 virtual void sB8();
 virtual void sBC();
 virtual void sC0();
 virtual void sC4();
 virtual void sC8();
 virtual void sCC();
 virtual void sD0();
 virtual void sD4();
 virtual void sD8();
 virtual void sDC();
 virtual void sE0();
 virtual void sE4();
 virtual void sE8();
 virtual void sEC();
 virtual void sF0();
 virtual void sF4();
 virtual void sF8();
 virtual void sFC();
 virtual void s100();
 virtual void s104();
 virtual void s108(void *);
};
class UnknownGenV8004F2DC_1 {
public:
 virtual void s08();
 virtual void s0C();
 virtual void s10();
 virtual void s14();
 virtual void s18();
 virtual void s1C();
 virtual void s20();
 virtual void s24();
 virtual void s28();
 virtual void s2C();
 virtual void s30();
 virtual void s34();
 virtual void s38();
 virtual void s3C();
 virtual void s40();
 virtual void s44();
 virtual void s48();
 virtual void s4C();
 virtual void s50();
 virtual void s54();
 virtual void s58();
 virtual void s5C();
 virtual void s60();
 virtual void s64();
 virtual void s68();
 virtual void s6C();
 virtual void s70();
 virtual void s74();
 virtual void s78();
 virtual void s7C();
 virtual void s80();
 virtual void s84();
 virtual void s88();
 virtual void s8C();
 virtual void s90();
 virtual void s94();
 virtual void s98();
 virtual void s9C();
 virtual void sA0();
 virtual void sA4();
 virtual void sA8();
 virtual void sAC();
 virtual void sB0();
 virtual void sB4();
 virtual void sB8();
 virtual void sBC();
 virtual void sC0();
 virtual void sC4();
 virtual void sC8();
 virtual void sCC();
 virtual void sD0();
 virtual void sD4();
 virtual void sD8();
 virtual void sDC();
 virtual void sE0();
 virtual void sE4();
 virtual void sE8();
 virtual void sEC();
 virtual void sF0();
 virtual void sF4();
 virtual void sF8();
 virtual void sFC();
 virtual void s100();
 virtual void s104();
 virtual void s108(void *);
};
class UnknownGenV8004F2DC_2 {
public:
 virtual void s08();
 virtual void s0C();
 virtual void s10();
 virtual void s14();
 virtual void s18();
 virtual void s1C();
 virtual void s20();
 virtual void s24();
 virtual void s28();
 virtual void s2C();
 virtual void s30();
 virtual void s34();
 virtual void s38();
 virtual void s3C();
 virtual void s40();
 virtual void s44();
 virtual void s48();
 virtual void s4C();
 virtual void s50();
 virtual void s54();
 virtual void s58();
 virtual void s5C();
 virtual void s60();
 virtual void s64();
 virtual void s68();
 virtual void s6C();
 virtual void s70();
 virtual void s74();
 virtual void s78();
 virtual void s7C();
 virtual void s80();
 virtual void s84();
 virtual void s88();
 virtual void s8C();
 virtual void s90();
 virtual void s94();
 virtual void s98();
 virtual void s9C();
 virtual void sA0();
 virtual void sA4();
 virtual void sA8();
 virtual void sAC();
 virtual void sB0();
 virtual void sB4();
 virtual void sB8();
 virtual void sBC();
 virtual void sC0();
 virtual void sC4();
 virtual void sC8();
 virtual void sCC();
 virtual void sD0();
 virtual void sD4();
 virtual void sD8();
 virtual void sDC();
 virtual void sE0();
 virtual void sE4();
 virtual void sE8();
 virtual void sEC();
 virtual void sF0();
 virtual void sF4();
 virtual void sF8();
 virtual void sFC();
 virtual void s100();
 virtual void s104();
 virtual void s108(void *);
};
class UnknownGenV8004F2DC_3 {
public:
 virtual void s08();
 virtual void s0C();
 virtual void s10();
 virtual void s14();
 virtual void s18();
 virtual void s1C();
 virtual void s20();
 virtual void s24();
 virtual void s28();
 virtual void s2C();
 virtual void s30();
 virtual void s34();
 virtual void s38();
 virtual void s3C();
 virtual void s40();
 virtual void s44();
 virtual void s48();
 virtual void s4C();
 virtual void s50();
 virtual void s54();
 virtual void s58();
 virtual void s5C();
 virtual void s60();
 virtual void s64();
 virtual void s68();
 virtual void s6C();
 virtual void s70();
 virtual void s74();
 virtual void s78();
 virtual void s7C();
 virtual void s80();
 virtual void s84();
 virtual void s88();
 virtual void s8C();
 virtual void s90();
 virtual void s94();
 virtual void s98();
 virtual void s9C();
 virtual void sA0();
 virtual void sA4();
 virtual void sA8();
 virtual void sAC();
 virtual void sB0();
 virtual void sB4();
 virtual void sB8();
 virtual void sBC();
 virtual void sC0();
 virtual void sC4();
 virtual void sC8();
 virtual void sCC();
 virtual void sD0();
 virtual void sD4();
 virtual void sD8();
 virtual void sDC();
 virtual void sE0();
 virtual void sE4();
 virtual void sE8();
 virtual void sEC();
 virtual void sF0();
 virtual void sF4();
 virtual void sF8();
 virtual void sFC();
 virtual void s100();
 virtual void s104();
 virtual void s108(void *);
};
class UnknownGenV8004F2DC_4 {
public:
 virtual void s08();
 virtual void s0C();
 virtual void s10();
 virtual void s14();
 virtual void s18();
 virtual void s1C();
 virtual void s20();
 virtual void s24();
 virtual void s28();
 virtual void s2C();
 virtual void s30();
 virtual void s34();
 virtual void s38();
 virtual void s3C();
 virtual void s40();
 virtual void s44();
 virtual void s48();
 virtual void s4C();
 virtual void s50();
 virtual void s54();
 virtual void s58();
 virtual void s5C();
 virtual void s60();
 virtual void s64();
 virtual void s68();
 virtual void s6C();
 virtual void s70();
 virtual void s74();
 virtual void s78();
 virtual void s7C();
 virtual void s80();
 virtual void s84();
 virtual void s88();
 virtual void s8C();
 virtual void s90();
 virtual void s94();
 virtual void s98();
 virtual void s9C();
 virtual void sA0();
 virtual void sA4();
 virtual void sA8();
 virtual void sAC();
 virtual void sB0();
 virtual void sB4();
 virtual void sB8();
 virtual void sBC();
 virtual void sC0();
 virtual void sC4();
 virtual void sC8();
 virtual void sCC();
 virtual void sD0();
 virtual void sD4();
 virtual void sD8();
 virtual void sDC();
 virtual void sE0();
 virtual void sE4();
 virtual void sE8();
 virtual void sEC();
 virtual void sF0();
 virtual void sF4();
 virtual void sF8();
 virtual void sFC();
 virtual void s100();
 virtual void s104();
 virtual void s108(void *);
};
class UnknownGenV8004F2DC_5 {
public:
 virtual void s08();
 virtual void s0C();
 virtual void s10();
 virtual void s14();
 virtual void s18();
 virtual void s1C();
 virtual void s20();
 virtual void s24();
 virtual void s28();
 virtual void s2C();
 virtual void s30();
 virtual void s34();
 virtual void s38();
 virtual void s3C();
 virtual void s40();
 virtual void s44();
 virtual void s48();
 virtual void s4C();
 virtual void s50();
 virtual void s54();
 virtual void s58();
 virtual void s5C();
 virtual void s60();
 virtual void s64();
 virtual void s68();
 virtual void s6C();
 virtual void s70();
 virtual void s74();
 virtual void s78();
 virtual void s7C();
 virtual void s80();
 virtual void s84();
 virtual void s88();
 virtual void s8C();
 virtual void s90();
 virtual void s94();
 virtual void s98();
 virtual void s9C();
 virtual void sA0();
 virtual void sA4();
 virtual void sA8();
 virtual void sAC();
 virtual void sB0();
 virtual void sB4();
 virtual void sB8();
 virtual void sBC();
 virtual void sC0();
 virtual void sC4();
 virtual void sC8();
 virtual void sCC();
 virtual void sD0();
 virtual void sD4();
 virtual void sD8();
 virtual void sDC();
 virtual void sE0();
 virtual void sE4();
 virtual void sE8();
 virtual void sEC();
 virtual void sF0();
 virtual void sF4();
 virtual void sF8();
 virtual void sFC();
 virtual void s100();
 virtual void s104();
 virtual void s108(void *);
};
class UnknownGenV8004F2DC_6 {
public:
 virtual void s08();
 virtual void s0C();
 virtual void s10();
 virtual void s14();
 virtual void s18();
 virtual void s1C();
 virtual void s20();
 virtual void s24();
 virtual void s28();
 virtual void s2C();
 virtual void s30();
 virtual void s34();
 virtual void s38();
 virtual void s3C();
 virtual void s40();
 virtual void s44();
 virtual void s48();
 virtual void s4C();
 virtual void s50();
 virtual void s54();
 virtual void s58();
 virtual void s5C();
 virtual void s60();
 virtual void s64();
 virtual void s68();
 virtual void s6C();
 virtual void s70();
 virtual void s74();
 virtual void s78();
 virtual void s7C();
 virtual void s80();
 virtual void s84();
 virtual void s88();
 virtual void s8C();
 virtual void s90();
 virtual void s94();
 virtual void s98();
 virtual void s9C();
 virtual void sA0();
 virtual void sA4();
 virtual void sA8();
 virtual void sAC();
 virtual void sB0();
 virtual void sB4();
 virtual void sB8();
 virtual void sBC();
 virtual void sC0();
 virtual void sC4();
 virtual void sC8();
 virtual void sCC();
 virtual void sD0();
 virtual void sD4();
 virtual void sD8();
 virtual void sDC();
 virtual void sE0();
 virtual void sE4();
 virtual void sE8();
 virtual void sEC();
 virtual void sF0();
 virtual void sF4();
 virtual void sF8();
 virtual void sFC();
 virtual void s100();
 virtual void s104();
 virtual void s108(void *);
};
extern "C" {
void fn_8004F2DC(int p0,int p1){
 void *value0;
 void *value1;
 reinterpret_cast<UnknownGenV8004F2DC_0 *>(*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p1)+280))->s108(*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p1)+172));
 *reinterpret_cast<void * *>(reinterpret_cast<char *>((void *)p1)+172)=(void *)0;
 reinterpret_cast<UnknownGenV8004F2DC_1 *>(*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p1)+280))->s108(*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p1)+176));
 *reinterpret_cast<void * *>(reinterpret_cast<char *>((void *)p1)+176)=(void *)0;
 reinterpret_cast<UnknownGenV8004F2DC_2 *>(*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p1)+280))->s108(*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p1)+180));
 *reinterpret_cast<void * *>(reinterpret_cast<char *>((void *)p1)+180)=(void *)0;
 reinterpret_cast<UnknownGenV8004F2DC_3 *>(*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p1)+280))->s108(*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p1)+184));
 *reinterpret_cast<void * *>(reinterpret_cast<char *>((void *)p1)+184)=(void *)0;
 reinterpret_cast<UnknownGenV8004F2DC_4 *>(*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p1)+280))->s108(*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p1)+236));
 *reinterpret_cast<void * *>(reinterpret_cast<char *>((void *)p1)+236)=(void *)0;
 if(*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p1)+120)){
  reinterpret_cast<UnknownGenV8004F2DC_5 *>(*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p1)+280))->s108(*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p1)+120));
 }
 *reinterpret_cast<void * *>(reinterpret_cast<char *>((void *)p1)+296)=(void *)0;
 if(*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p1)+300)){
  reinterpret_cast<UnknownGenV8004F2DC_6 *>(*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p1)+280))->s108(*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p1)+300));
  *reinterpret_cast<void * *>(reinterpret_cast<char *>((void *)p1)+300)=(void *)0;
 }
 value0=*reinterpret_cast<void **>(reinterpret_cast<char *>((void *)p1)+304);
 if(value0){
  value1=*reinterpret_cast<void **>(reinterpret_cast<char *>(value0)+4);
  *reinterpret_cast<void * *>(reinterpret_cast<char *>(value0)+4)=(reinterpret_cast<char *>(value1)+-1);
  if(!((unsigned int)(int)*reinterpret_cast<void **>(reinterpret_cast<char *>(value0)+4)&0x7FFFFF)){
   fn_80066E1C(value0);
  }
 }
 *reinterpret_cast<void * *>(reinterpret_cast<char *>((void *)p1)+304)=(void *)0;
 *reinterpret_cast<void * *>(reinterpret_cast<char *>((void *)p0)+0)=kSuccess__3Gap;
}
}
#pragma pop
