"""Attribute functions to Alchemy classes from the extracted metadata (tools/alchemymeta/extract.py).

Roles, each checked against the code before it is recorded:
  register    calls the metaobject registration (fn_80066204) for the class
  getMeta     loads the class's metaobject, registering it first if needed (called by the r7 callback)
  getMetaCall the r7 callback, which only calls getMeta
  parentMeta  the r6 callback, which only reads the parent's metaobject
  vtableRead  the r10 callback, which constructs a temporary instance and reads its vtable
  fieldInit   appends and describes the class's reflected fields (fn_80065924/fn_800659C0)
  virtual+XX  the function at byte offset XX of the class's own vtable, where it differs from the
              parent's own vtable (an override or a new virtual function)
A function claimed by more than one class (shared code) is not attributed.

Writes config/GDJEB2/alchemy_class_functions.txt: address, class, role and the name tools/alchemymeta/rename.py
gives the function (<class>_<role>, virtual+XX as virtualXX; a later copy of a twice-registered class
adds _2), one per line.
usage: /opt/homebrew/bin/python3 tools/alchemymeta/attribute.py"""
import collections,json,re,struct,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]/'unknowngen'))
import callshape
from paths import BUILD,CONFIG,RELINDEX

classes=json.load(open(BUILD/'analysis'/'meta'/'classes.json'))
idx=json.load(open(RELINDEX))
sym={};size={};fn_at={}
for l in open(CONFIG/'symbols.txt'):
  m=re.match(r'(\S+) = (\.\w+):0x([0-9A-F]+); // type:(\w+)(?: size:0x([0-9A-F]+))?',l)
  if not m: continue
  sym[m[1]]=int(m[3],16);size[m[1]]=int(m[5] or '0',16)
  if m[4]=='function': fn_at[int(m[3],16)]=m[1]
def refs(fn): return [(t,ty) for o,ty,t,a in idx.get(fn,{}).get('rel',[])]
def vtable(lbl):
  """Function slots of a vtable object (two leading words, then function pointers)."""
  n=size.get(lbl,0)//4;ws=struct.unpack('>%dI'%n,callshape.rd(sym[lbl],4*n)) if n else ()
  return {4*k:fn_at[w] for k,w in enumerate(ws) if k>=2 and w in fn_at}

claims=collections.defaultdict(set)
def claim(fn,cls,role):
  if fn: claims[fn].add((cls,role))
for k,c in classes.items():
  cls=k.split('@')[0]+('_2' if '@' in k else '');cb=c['callbacks'];p=classes.get(c['parent'])
  claim(c['register'],cls,'register')
  if c['fieldinit']: claim(c['fieldinit'],cls,'fieldInit')
  if cb.get('r6') and p and {t for t,ty in refs(cb['r6'])}=={p['meta']}: claim(cb['r6'],cls,'parentMeta')
  if cb.get('r7'):
    calls=[t for t,ty in refs(cb['r7']) if ty==10]
    if len(calls)==1 and c['meta'] in {t for t,ty in refs(calls[0])}:
      claim(cb['r7'],cls,'getMetaCall');claim(calls[0],cls,'getMeta')
  if c['vtables']:
    claim(cb.get('r10'),cls,'vtableRead')
    mine=vtable(c['vtables'][-1]);base=vtable(p['vtables'][-1]) if p and p['vtables'] else {}
    for off,fn in mine.items():
      if base.get(off)!=fn: claim(fn,cls,'virtual+%02X'%off)

lines=[];shared=0;names={};taken=set(sym)
for fn in sorted(claims,key=lambda f:sym.get(f,0)):
  cs=claims[fn]
  if len({c for c,r in cs})!=1: shared+=1;continue
  # One name per function: its first role in this order.
  c,r=min(cs,key=lambda x:(['register','getMeta','getMetaCall','parentMeta','vtableRead','fieldInit'].index(x[1]) if '+' not in x[1] else 9,x[1]))
  nm='%s_%s'%(c,r.replace('+',''))
  if nm in names.values() or (nm in taken and nm!=fn): raise SystemExit('name collision '+nm)
  names[fn]=nm
  lines.append('%08X\t%s\t%s\t%s'%(sym[fn],c,','.join(sorted(r_ for c_,r_ in cs)),nm))
out=CONFIG/'alchemy_class_functions.txt'
out.write_text('# Generated by tools/alchemymeta/attribute.py: address, Alchemy class, roles (see the tool), name.\n'+'\n'.join(lines)+'\n')
fns=set(names)
print('attributed functions',len(fns),'bytes',sum(idx[f]['size'] for f in fns if f in idx),'shared (skipped)',shared)
print(collections.Counter(r.split('+')[0] for l in lines for r in l.split('\t')[2].split(',')))
